export interface GpMappingData {
  id: number;
  block: string;
  gpName: string;
  taggedUlb: string;
  taggedMrf: string;
}

export const gpMappingData: GpMappingData[] = [
  // Basudevpur Block (Rows 1-36)
  { id: 1, block: 'Basudevpur', gpName: 'ADHUAN', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 2, block: 'Basudevpur', gpName: 'ANDOLA', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 3, block: 'Basudevpur', gpName: 'ARANDUA', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 4, block: 'Basudevpur', gpName: 'ARTUNG', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 5, block: 'Basudevpur', gpName: 'ARUHA', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 6, block: 'Basudevpur', gpName: 'BALIMEDA', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 7, block: 'Basudevpur', gpName: 'BALIMUNDA', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 8, block: 'Basudevpur', gpName: 'BARANDUA', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 9, block: 'Basudevpur', gpName: 'BIDDEIPUR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 10, block: 'Basudevpur', gpName: 'BINOBHA NAGAR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 11, block: 'Basudevpur', gpName: 'BIRAS', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 12, block: 'Basudevpur', gpName: 'BRAHMANIGAON', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 13, block: 'Basudevpur', gpName: 'CHUDAMANI', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 14, block: 'Basudevpur', gpName: 'ERAM', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 15, block: 'Basudevpur', gpName: 'ERTAL', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 16, block: 'Basudevpur', gpName: 'GOBINDAPUR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 17, block: 'Basudevpur', gpName: 'GOPABANDHU NAGAR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 18, block: 'Basudevpur', gpName: 'GUAGADIA', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 19, block: 'Basudevpur', gpName: 'JAGANNATHPRASAD', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 20, block: 'Basudevpur', gpName: 'JAGANNATHPUR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 21, block: 'Basudevpur', gpName: 'K.BINAYAKPUR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 22, block: 'Basudevpur', gpName: 'KARANJADIA', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 23, block: 'Basudevpur', gpName: 'KISMAT KRUSHANAPUR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 24, block: 'Basudevpur', gpName: 'KUMARPUR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 25, block: 'Basudevpur', gpName: 'LAXMIDASPUR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 26, block: 'Basudevpur', gpName: 'LUNGA', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 27, block: 'Basudevpur', gpName: 'NAIKANIDIHI', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 28, block: 'Basudevpur', gpName: 'NARASINGHPUR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 29, block: 'Basudevpur', gpName: 'NUAGAN', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 30, block: 'Basudevpur', gpName: 'PADHUAN', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 31, block: 'Basudevpur', gpName: 'PADMAPUR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 32, block: 'Basudevpur', gpName: 'RAJGHAROPOKHARI', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 33, block: 'Basudevpur', gpName: 'SANAKRUSHANNPUR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 34, block: 'Basudevpur', gpName: 'SASUBHUASUNI', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 35, block: 'Basudevpur', gpName: 'SUDARSANPUR', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },
  { id: 36, block: 'Basudevpur', gpName: 'SUGO', taggedUlb: 'Basudevpur Municipality', taggedMrf: 'Basudevpur' },

  // Bhadrak Block (Rows 37-72)
  { id: 37, block: 'Bhadrak', gpName: 'AMBOROLI', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 38, block: 'Bhadrak', gpName: 'ANDHAIPALLY', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 39, block: 'Bhadrak', gpName: 'ARNNAPAL', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 40, block: 'Bhadrak', gpName: 'BISHNUPURBINDHA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 41, block: 'Bhadrak', gpName: 'BANDHAGAON', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 42, block: 'Bhadrak', gpName: 'BANIA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 43, block: 'Bhadrak', gpName: 'BANITIA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 44, block: 'Bhadrak', gpName: 'BARAHAMPUR', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 45, block: 'Bhadrak', gpName: 'BAUDPUR', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 46, block: 'Bhadrak', gpName: 'BENTAL', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 47, block: 'Bhadrak', gpName: 'BETARA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 48, block: 'Bhadrak', gpName: 'BOHUDARADA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 49, block: 'Bhadrak', gpName: 'CHANDIGAON', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 50, block: 'Bhadrak', gpName: 'CHARAMPA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 51, block: 'Bhadrak', gpName: 'DAISING', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 52, block: 'Bhadrak', gpName: 'ERADA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 53, block: 'Bhadrak', gpName: 'EREIN', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 54, block: 'Bhadrak', gpName: 'GELPUR', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 55, block: 'Bhadrak', gpName: 'GELTUA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 56, block: 'Bhadrak', gpName: 'GORAMATI', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 57, block: 'Bhadrak', gpName: 'GUJIDARADA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 58, block: 'Bhadrak', gpName: 'HARIPUR', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 59, block: 'Bhadrak', gpName: 'JAGADALPUR', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 60, block: 'Bhadrak', gpName: 'KALEI', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 61, block: 'Bhadrak', gpName: 'KAUPUR', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 62, block: 'Bhadrak', gpName: 'KEDARPUR', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 63, block: 'Bhadrak', gpName: 'KHANDATADA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 64, block: 'Bhadrak', gpName: 'KODABARUAN', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 65, block: 'Bhadrak', gpName: 'KORKARA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 66, block: 'Bhadrak', gpName: 'OLANGA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 67, block: 'Bhadrak', gpName: 'PARASINGA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 68, block: 'Bhadrak', gpName: 'RAHANJA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 69, block: 'Bhadrak', gpName: 'RAMBHILA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 70, block: 'Bhadrak', gpName: 'RANDIA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 71, block: 'Bhadrak', gpName: 'SABARANGA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },
  { id: 72, block: 'Bhadrak', gpName: 'SAHADA', taggedUlb: 'Bhadrak Municipality', taggedMrf: 'Bidanga & Mirzapur' },

  // Chandbali Block (Rows 73-108)
  { id: 73, block: 'Chandabali', gpName: 'Aradi', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 74, block: 'Chandabali', gpName: 'Badaostia', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 75, block: 'Chandabali', gpName: 'Bajarapur', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 76, block: 'Chandabali', gpName: 'Bhatapada', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 77, block: 'Chandabali', gpName: 'Bhuinbruti', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 78, block: 'Chandabali', gpName: 'Bansada', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 79, block: 'Chandabali', gpName: 'Bijayanagar', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 80, block: 'Chandabali', gpName: 'Chardia', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 81, block: 'Chandabali', gpName: 'Dhamara', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 82, block: 'Chandabali', gpName: 'Dosinga', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 83, block: 'Chandabali', gpName: 'Ghatapur', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 84, block: 'Chandabali', gpName: 'Gopinathapur', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 85, block: 'Chandabali', gpName: 'Jagula', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 86, block: 'Chandabali', gpName: 'Jaleswarpur', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 87, block: 'Chandabali', gpName: 'Jashipur', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 88, block: 'Chandabali', gpName: 'Kaithkhola', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 89, block: 'Chandabali', gpName: 'Kandagaradi', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 90, block: 'Chandabali', gpName: 'Karanjamal', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 91, block: 'Chandabali', gpName: 'Karanpalli', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 92, block: 'Chandabali', gpName: 'Khadalpokhari', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 93, block: 'Chandabali', gpName: 'Kheranga', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 94, block: 'Chandabali', gpName: 'Madhapur', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 95, block: 'Chandabali', gpName: 'Mahulia', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 96, block: 'Chandabali', gpName: 'Mousudha', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 97, block: 'Chandabali', gpName: 'Motto', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 98, block: 'Chandabali', gpName: 'Nalagohira', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 99, block: 'Chandabali', gpName: 'Nalgunda', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 100, block: 'Chandabali', gpName: 'Nandapur', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 101, block: 'Chandabali', gpName: 'Nuagaon', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 102, block: 'Chandabali', gpName: 'Olaga', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 103, block: 'Chandabali', gpName: 'Orasahi', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 104, block: 'Chandabali', gpName: 'Panchutikiri', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 105, block: 'Chandabali', gpName: 'Sundarpur', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 106, block: 'Chandabali', gpName: 'Tentulidihi', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 107, block: 'Chandabali', gpName: 'Totapada', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },
  { id: 108, block: 'Chandabali', gpName: 'Uttukuda', taggedUlb: 'Chandbali NAC', taggedMrf: 'Kunjakalika MRF1' },

  // Dhamnagar Block (Rows 109-139)
  { id: 109, block: 'Dhamnagar', gpName: 'Anandapur', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 110, block: 'Dhamnagar', gpName: 'Arjunpur', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 111, block: 'Dhamnagar', gpName: 'Asurali', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 112, block: 'Dhamnagar', gpName: 'Bamkura', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 113, block: 'Dhamnagar', gpName: 'Bayangdihi', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 114, block: 'Dhamnagar', gpName: 'Bhagabanpur', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 115, block: 'Dhamnagar', gpName: 'Bhatasahi', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 116, block: 'Dhamnagar', gpName: 'Sarei Chudakuti', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 117, block: 'Dhamnagar', gpName: 'Daipur', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 118, block: 'Dhamnagar', gpName: 'Dalanga', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 119, block: 'Dhamnagar', gpName: 'Dhusuri', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 120, block: 'Dhamnagar', gpName: 'Dobal', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 121, block: 'Dhamnagar', gpName: 'Fatepur', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 122, block: 'Dhamnagar', gpName: 'Gadhiali', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 123, block: 'Dhamnagar', gpName: 'Gobindpur', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 124, block: 'Dhamnagar', gpName: 'Hasnabad', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 125, block: 'Dhamnagar', gpName: 'Kalyani', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 126, block: 'Dhamnagar', gpName: 'Karada', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 127, block: 'Dhamnagar', gpName: 'Kasimpur', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 128, block: 'Dhamnagar', gpName: 'Katasahi', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 129, block: 'Dhamnagar', gpName: 'Khadipada', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 130, block: 'Dhamnagar', gpName: 'Khaparpada', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 131, block: 'Dhamnagar', gpName: 'Kothar', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 132, block: 'Dhamnagar', gpName: 'Mustafapur', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 133, block: 'Dhamnagar', gpName: 'Nadigaon', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 134, block: 'Dhamnagar', gpName: 'Padhani', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 135, block: 'Dhamnagar', gpName: 'Palasahi', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 136, block: 'Dhamnagar', gpName: 'Radhaballavpur', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 137, block: 'Dhamnagar', gpName: 'Raipur', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 138, block: 'Dhamnagar', gpName: 'Sahaspur', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' },
  { id: 139, block: 'Dhamnagar', gpName: 'Sohada', taggedUlb: 'Dhamnagar NAC', taggedMrf: 'Wealth Center Rahapita' }
];
