export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
  routeId: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // ANANDAPUR Block (1-18)
  { id: 1, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 01 (SALAPADA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'PANCHUPALLY', wasteGeneratedKg: 2.2, gpNodalPerson: 'Pujashree Priyadarsani Rout', gpNodalContact: '9348618629', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABBDJHKP-01' },
  { id: 2, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 01 (SALAPADA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'BAILO', wasteGeneratedKg: 3.7, gpNodalPerson: 'Sunanda Rout', gpNodalContact: '7681883651', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABBDJHKP-01' },
  { id: 3, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 01 (SALAPADA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'BELABAHALI', wasteGeneratedKg: 2.7, gpNodalPerson: 'Kumudini Jena', gpNodalContact: '9438240703', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABBDJHKP-01' },
  { id: 4, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 01 (SALAPADA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'HARIDAPAL', wasteGeneratedKg: 2.0, gpNodalPerson: 'Kalpana Muduli', gpNodalContact: '7749046858', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABBDJHKP-01' },
  { id: 5, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 01 (SALAPADA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'JALASUAN', wasteGeneratedKg: 1.2, gpNodalPerson: 'Pujashree Priyadarsani Rout', gpNodalContact: '9348618629', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABBDJHKP-01' },
  { id: 6, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 01 (SALAPADA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'DHAKOTHA', wasteGeneratedKg: 3.4, gpNodalPerson: 'Harada Prasana Barik', gpNodalContact: '7008760114', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABBDJHKP-01' },
  { id: 7, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 01 (SALAPADA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'KOLIMATI', wasteGeneratedKg: 3.0, gpNodalPerson: 'Harada Prasana Barik', gpNodalContact: '7008760114', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABBDJHKP-01' },
  { id: 8, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 02 (PADAMPUR)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'SALABANI', wasteGeneratedKg: 2.7, gpNodalPerson: 'Rosalin Biswal(PEO)', gpNodalContact: '7735905425', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABKKMST-02' },
  { id: 9, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 02 (PADAMPUR)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'MOCHINDA', wasteGeneratedKg: 2.4, gpNodalPerson: 'Elina Parida (PEO)', gpNodalContact: '9861363939', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABKKMST-02' },
  { id: 10, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 02 (PADAMPUR)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'TARATARA', wasteGeneratedKg: 3.1, gpNodalPerson: 'Purnima Parida (PEO)', gpNodalContact: '9438454060', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABKKMST-02' },
  { id: 11, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 02 (PADAMPUR)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'KATHAKATA', wasteGeneratedKg: 1.7, gpNodalPerson: 'Purnima Parida (PEO)', gpNodalContact: '9438454060', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABKKMST-02' },
  { id: 12, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 02 (PADAMPUR)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'KANTIPAL', wasteGeneratedKg: 3.5, gpNodalPerson: 'Sushree Sangita Nayak (PEO)', gpNodalContact: '8018686966', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABKKMST-02' },
  { id: 13, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 02 (PADAMPUR)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'BAUNSAGARH', wasteGeneratedKg: 3.5, gpNodalPerson: 'Sushree Sangita Nayak (PEO)', gpNodalContact: '8018686966', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABKKMST-02' },
  { id: 14, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 02 (PADAMPUR)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'KODAPADA', wasteGeneratedKg: 2.5, gpNodalPerson: 'Amiya Kumar Rout (PEO)', gpNodalContact: '9437722249', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABGKMP-03' },
  { id: 15, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 02 (PADAMPUR)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'BUDHIKUDA', wasteGeneratedKg: 1.0, gpNodalPerson: 'Sarada Prasana Sahu (PEO)', gpNodalContact: '8763372751', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABGKMP-03' },
  { id: 16, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 02 (PADAMPUR)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'GAYALMUNDA', wasteGeneratedKg: 3.2, gpNodalPerson: 'Sarada Prasana Sahu (PEO)', gpNodalContact: '8763372751', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABGKMP-03' },
  { id: 17, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 02 (PADAMPUR)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'PANASADIHA', wasteGeneratedKg: 2.5, gpNodalPerson: 'Ananda Dash (PEO)', gpNodalContact: '7605939818', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABGKMP-03' },
  { id: 18, block: 'Anandapur', ulb: 'Anandapur Municipality', mrf: 'MRF - 02 (PADAMPUR)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'MANOHARPUR', wasteGeneratedKg: 1.6, gpNodalPerson: 'Ananda Dash (PEO)', gpNodalContact: '7605939818', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9777119786', routeId: 'KANABGKMP-03' },

  // CHAMPUA Block (19-40)
  { id: 19, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'Rajia', wasteGeneratedKg: 4.5, gpNodalPerson: 'Ranjulata Giri (PEO)', gpNodalContact: '7008589558', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABKPRR-01' },
  { id: 20, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'Kalikaprasad', wasteGeneratedKg: 2.0, gpNodalPerson: 'Lalita Prasad Jena', gpNodalContact: '9658417070', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABKPRR-01' },
  { id: 21, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'Badanai', wasteGeneratedKg: 3.9, gpNodalPerson: 'Jully Sardar (PEO)', gpNodalContact: '8895722926', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABKPRR-01' },
  { id: 22, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'Parsala', wasteGeneratedKg: 1.5, gpNodalPerson: 'Sachidananda Barik (PEO)', gpNodalContact: '9776350580', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABKPRR-01' },
  { id: 23, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'Rimuli', wasteGeneratedKg: 2.6, gpNodalPerson: 'Dibyaranjan Mohanta (PEO)', gpNodalContact: '8489130948', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABKPRR-01' },
  { id: 24, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'SUNAPOSI', wasteGeneratedKg: 2.8, gpNodalPerson: 'Rachayita Senapati (PEO)', gpNodalContact: '6371624521', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHAJKKS-02' },
  { id: 25, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'JAMUDALAK', wasteGeneratedKg: 3.3, gpNodalPerson: 'Rina Pradhan (PEO)', gpNodalContact: '7008589559', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHAJKKS-02' },
  { id: 26, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'KUTARIPOSI', wasteGeneratedKg: 1.0, gpNodalPerson: 'Bijan Kumar Munda (PEO)', gpNodalContact: '8763679544', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHAJKKS-02' },
  { id: 27, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'KODAGADIA', wasteGeneratedKg: 2.3, gpNodalPerson: 'Rina Pradhan (PEO)', gpNodalContact: '7008589559', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHAJKKS-02' },
  { id: 28, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'SAREI', wasteGeneratedKg: 2.7, gpNodalPerson: 'Ranjulata Giri (PEO)', gpNodalContact: '7008589558', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHACKKPSU-03' },
  { id: 29, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'KARANJIA', wasteGeneratedKg: 2.2, gpNodalPerson: 'Kabitarani Majhi (PEO)', gpNodalContact: '9861109380', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHACKKPSU-03' },
  { id: 30, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'CHANDRASEKHARPUR', wasteGeneratedKg: 1.8, gpNodalPerson: 'Smrutiranjan Sethi (PEO)', gpNodalContact: '9337387392', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHACKKPSU-03' },
  { id: 31, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'KASHIPAL', wasteGeneratedKg: 1.0, gpNodalPerson: 'Purnachandra Mohanta (PEO)', gpNodalContact: '7653068538', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHACKKPSU-03' },
  { id: 32, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'PADUA', wasteGeneratedKg: 1.9, gpNodalPerson: 'Ganeswar Pradhan (PEO)', gpNodalContact: '7008391389', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHACKKPSU-03' },
  { id: 33, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'UCHABALI', wasteGeneratedKg: 1.8, gpNodalPerson: 'Swagatika Prusti (PEO)', gpNodalContact: '9777789396', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHACKKPSU-03' },
  { id: 34, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'JYOTIPUR', wasteGeneratedKg: 1.4, gpNodalPerson: 'Sanjaya Kumar Modi (PEO)', gpNodalContact: '9777571763', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABBJJJSR-04' },
  { id: 35, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'BHUINPUR', wasteGeneratedKg: 1.5, gpNodalPerson: 'Anil Kumar Mohanta (PEO)', gpNodalContact: '9439387423', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABBJJJSR-04' },
  { id: 36, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'JALLY', wasteGeneratedKg: 1.5, gpNodalPerson: 'Swagatika Prusti (PEO)', gpNodalContact: '9777789396', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABBJJJSR-04' },
  { id: 37, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'SADANGI', wasteGeneratedKg: 1.9, gpNodalPerson: 'Lokanath Naik (PEO)', gpNodalContact: '6370210878', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABBJJJSR-04' },
  { id: 38, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'JAJAPOSI', wasteGeneratedKg: 2.2, gpNodalPerson: 'Anil Kumar Mohanta (PEO)', gpNodalContact: '9439387423', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABBJJJSR-04' },
  { id: 39, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'BHANDA', wasteGeneratedKg: 1.9, gpNodalPerson: 'Jully Sardar (PEO)', gpNodalContact: '8895722926', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABBJJJSR-04' },
  { id: 40, block: 'Champua', ulb: 'Champua NAC', mrf: 'MRF - 01 (KANTIA-RAJIA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'RANGAMATIA', wasteGeneratedKg: 2.4, gpNodalPerson: 'Purnachandra Mohanta (PEO)', gpNodalContact: '7653068538', ulbNodalPerson: 'SK Sahabaz (SE)', ulbNodalContact: '9439921087', routeId: 'KCHABBJJJSR-04' },

  // JODA Block (41-59)
  { id: 41, block: 'Joda', ulb: 'Barbil Municipality', mrf: 'MRF - 01 (KARA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'KARAKHENDRA', wasteGeneratedKg: 0.2, gpNodalPerson: 'Purusottam Sahoo(PEO)', gpNodalContact: '9437386122', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBBKS-01' },
  { id: 42, block: 'Joda', ulb: 'Barbil Municipality', mrf: 'MRF - 01 (KARA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'BALAGODA', wasteGeneratedKg: 0.2, gpNodalPerson: 'Radhakanta Behera (PEO)', gpNodalContact: '9437354992', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBBKS-01' },
  { id: 43, block: 'Joda', ulb: 'Barbil Municipality', mrf: 'MRF - 01 (KARA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'SERENDA', wasteGeneratedKg: 1.5, gpNodalPerson: 'Purusottam Sahoo(PEO)', gpNodalContact: '9437386122', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBBKS-01' },
  { id: 44, block: 'Joda', ulb: 'Barbil Municipality', mrf: 'MRF - 01 (KARA)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'BOLANI', wasteGeneratedKg: 1.5, gpNodalPerson: 'Phula Oram (PEO)', gpNodalContact: '9827858383', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBBKS-01' },
  { id: 45, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'JAJANGA', wasteGeneratedKg: 1.5, gpNodalPerson: 'Utkala Keshari Das (PEO)', gpNodalContact: '7077254293', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBBJJJP-02' },
  { id: 46, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'JALAHARI', wasteGeneratedKg: 0.7, gpNodalPerson: 'Utkala Keshari Das (PEO)', gpNodalContact: '7077254293', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBBJJJP-02' },
  { id: 47, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'JURUDI', wasteGeneratedKg: 0.1, gpNodalPerson: 'Duryadhan Mohanta (PEO)', gpNodalContact: '9668676068', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBBJJJP-02' },
  { id: 48, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'PALASA', wasteGeneratedKg: 0.6, gpNodalPerson: 'Duryadhan Mohanta (PEO)', gpNodalContact: '9668676068', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBBJJJP-02' },
  { id: 49, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'BALADA', wasteGeneratedKg: 0.3, gpNodalPerson: 'Rohan Singh (PEO)', gpNodalContact: '9861154363', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBBJJJP-02' },
  { id: 50, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'BADAKALIMATI', wasteGeneratedKg: 1.1, gpNodalPerson: 'Prasanta Oram (PEO)', gpNodalContact: '7008267040', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBBJJJP-02' },
  { id: 51, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'BHADRASAHI', wasteGeneratedKg: 1.8, gpNodalPerson: 'Manmath Mahakud (PEO)', gpNodalContact: '8763087690', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODABBCDK-03' },
  { id: 52, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'BIRIKALA', wasteGeneratedKg: 1.0, gpNodalPerson: 'Krishna Acharya (PEO)', gpNodalContact: '7735132317', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODABBCDK-03' },
  { id: 53, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'DEOJHAR', wasteGeneratedKg: 2.1, gpNodalPerson: 'Kunjabihari Mohanta (PEO)', gpNodalContact: '8327751634', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODABBCDK-03' },
  { id: 54, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'KANDRA', wasteGeneratedKg: 2.3, gpNodalPerson: 'Krishna Acharya (PEO)', gpNodalContact: '7735132317', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODABBCDK-03' },
  { id: 55, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'ASENIKALA', wasteGeneratedKg: 2.7, gpNodalPerson: 'Subhash Nayak (PEO)', gpNodalContact: '6370136138', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODABBCDK-03' },
  { id: 56, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'CHAMAKPUR', wasteGeneratedKg: 1.2, gpNodalPerson: 'Subhash Nayak (PEO)', gpNodalContact: '6370136138', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODABBCDK-03' },
  { id: 57, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'GUALI', wasteGeneratedKg: 1.7, gpNodalPerson: 'Jagyanasini Behera (PEO)', gpNodalContact: '7854924851', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBGL-04' },
  { id: 58, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'LOIDAPADA', wasteGeneratedKg: 1.7, gpNodalPerson: 'Jagyanasini Behera (PEO)', gpNodalContact: '7854924851', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBGL-04' },
  { id: 59, block: 'Joda', ulb: 'Joda Municipality', mrf: 'MRF - 01 (BACHU HONTING)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'BHUINROIDA', wasteGeneratedKg: 0.7, gpNodalPerson: 'Bidyadhar Patra (PEO)', gpNodalContact: '9437149913', ulbNodalPerson: 'Somendra Sethi (SE)', ulbNodalContact: '7008847065', routeId: 'KJODBGL-04' },

  // KENDUJHAR SADAR Block (60-84)
  { id: 60, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 01 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'Janardanpur', wasteGeneratedKg: 1.7, gpNodalPerson: 'Prakash Kumar Jena(PEO)', gpNodalContact: '6370529866', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBGJMR-01' },
  { id: 61, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 01 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'Raisuan', wasteGeneratedKg: 2.1, gpNodalPerson: 'Tilottoma Mahakud(PEO)', gpNodalContact: '7608881582', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBGJMR-01' },
  { id: 62, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 01 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'Gopinathpur', wasteGeneratedKg: 1.7, gpNodalPerson: 'Tilottoma Mahakud(PEO)', gpNodalContact: '7608881582', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBGJMR-01' },
  { id: 63, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 01 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'Mahadeijoda', wasteGeneratedKg: 2.4, gpNodalPerson: 'Sophia Begum(PEO)', gpNodalContact: '9437664852', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBGJMR-01' },
  { id: 64, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 01 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD MONDAY OF EVERY MONTH', gpName: 'Baradapal', wasteGeneratedKg: 1.3, gpNodalPerson: 'Suresh Chandra Brahma(PEO)', gpNodalContact: '9437214610', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBGJMR-01' },
  { id: 65, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 01 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'Nuagaon', wasteGeneratedKg: 3.4, gpNodalPerson: 'Khetrabasi Jena(PEO)', gpNodalContact: '7008389227', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENKNPPP-02' },
  { id: 66, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 01 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'Parjanpur', wasteGeneratedKg: 2.1, gpNodalPerson: 'Ranjit Kumar Mohanta(PEO)', gpNodalContact: '7008469634', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENKNPPP-02' },
  { id: 67, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 01 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'Kandaraposi', wasteGeneratedKg: 3.0, gpNodalPerson: 'Sanjaya Kumar Mohanta(PEO)', gpNodalContact: '6372565510', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENKNPPP-02' },
  { id: 68, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 01 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'Palasapanga', wasteGeneratedKg: 2.1, gpNodalPerson: 'Ganeswar Mohanta(PEO)', gpNodalContact: '9777799996', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENKNPPP-02' },
  { id: 69, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 01 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH MONDAY OF EVERY MONTH', gpName: 'Padampur', wasteGeneratedKg: 2.6, gpNodalPerson: 'Suraj Dash(PEO)', gpNodalContact: '7008437669', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENKNPPP-02' },
  { id: 70, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'Gobardhan', wasteGeneratedKg: 2.3, gpNodalPerson: 'Ganeswar Mohanta(PEO)', gpNodalContact: '9777799996', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBBGHKRS-03' },
  { id: 71, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'Kaunrikala', wasteGeneratedKg: 1.9, gpNodalPerson: 'Ramesh Chandra Nayak(PEO)', gpNodalContact: '7008928185', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBBGHKRS-03' },
  { id: 72, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'Sankiri', wasteGeneratedKg: 1.6, gpNodalPerson: 'Santosh Kumar Nayak (PEO)', gpNodalContact: '9668853158', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBBGHKRS-03' },
  { id: 73, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'Handibhanga', wasteGeneratedKg: 2.8, gpNodalPerson: 'Binod Bihari Sahoo(PEO)', gpNodalContact: '7008248030', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBBGHKRS-03' },
  { id: 74, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'Raikala', wasteGeneratedKg: 2.5, gpNodalPerson: 'Binod Bihari Sahoo(PEO)', gpNodalContact: '7008248030', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBBGHKRS-03' },
  { id: 75, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'Bauripada', wasteGeneratedKg: 3.2, gpNodalPerson: 'Tusharjyoti Soren (PEO)', gpNodalContact: '7846816353', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBBGHKRS-03' },
  { id: 76, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1ST & 3RD WEDNESDAY OF EVERY MONTH', gpName: 'Bodapalasa', wasteGeneratedKg: 2.3, gpNodalPerson: 'Ranjit Kumar Mohanta(PEO)', gpNodalContact: '7008469634', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENBBGHKRS-03' },
  { id: 77, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'Sirispal', wasteGeneratedKg: 3.5, gpNodalPerson: 'Malati Majhi (PEO)', gpNodalContact: '7653066144', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENDKMMNNRS-04' },
  { id: 78, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'Naranpur', wasteGeneratedKg: 4.3, gpNodalPerson: 'Suresh Chandra Brahma(PEO)', gpNodalContact: '9437214610', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENDKMMNNRS-04' },
  { id: 79, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'Raghunathpur', wasteGeneratedKg: 3.3, gpNodalPerson: 'Sanjaya Kumar Mohanta(PEO)', gpNodalContact: '6372565510', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENDKMMNNRS-04' },
  { id: 80, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'Kathabari', wasteGeneratedKg: 1.7, gpNodalPerson: 'Suryakanta Bagsingh(PEO)', gpNodalContact: '7846856028', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENDKMMNNRS-04' },
  { id: 81, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'Maidankel', wasteGeneratedKg: 2.6, gpNodalPerson: 'Khetrabasi Jena(PEO)', gpNodalContact: '7008389227', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENDKMMNNRS-04' },
  { id: 82, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'Dimbo', wasteGeneratedKg: 3.1, gpNodalPerson: 'Suresh Chandra Brahma(PEO)', gpNodalContact: '9437214610', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENDKMMNNRS-04' },
  { id: 83, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'Nelung', wasteGeneratedKg: 2.2, gpNodalPerson: 'Hemalata Mohanta (PEO)', gpNodalContact: '9438029533', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENDKMMNNRS-04' },
  { id: 84, block: 'Kendujhar Sadar', ulb: 'Kendujhargarh Municipality', mrf: 'MRF - 02 (BRAHMANIGAON)', vehicleType: 'TRACTOR', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '2ND & 4TH WEDNESDAY OF EVERY MONTH', gpName: 'Mandua', wasteGeneratedKg: 2.4, gpNodalPerson: 'Holika Dehuri (PEO)', gpNodalContact: '9090423837', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9439921087', routeId: 'KKENDKMMNNRS-04' }
];
