export interface GpMappingData {
  id: number;
  block: string;
  gpName: string;
  taggedUlb: string;
  taggedMrf: string;
}

export const gpMappingData: GpMappingData[] = [
  // Anandapur Municipality - Anandapur Block
  { id: 1, block: 'Anandapur', gpName: 'BAILO', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Salapada' },
  { id: 2, block: 'Anandapur', gpName: 'BELABAHALI', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Salapada' },
  { id: 3, block: 'Anandapur', gpName: 'HARIDAPAL', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Salapada' },
  { id: 4, block: 'Anandapur', gpName: 'PANCHUPALLY', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Salapada' },
  { id: 5, block: 'Anandapur', gpName: 'JALASUAN', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Salapada' },
  { id: 6, block: 'Anandapur', gpName: 'DHAKOTHA', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Salapada' },
  { id: 7, block: 'Anandapur', gpName: 'KOLIMATI', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Salapada' },
  { id: 8, block: 'Anandapur', gpName: 'TARATARA', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Padampur' },
  { id: 9, block: 'Anandapur', gpName: 'KATHAKATA', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Padampur' },
  { id: 10, block: 'Anandapur', gpName: 'KANTIPAL', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Padampur' },
  { id: 11, block: 'Anandapur', gpName: 'MOCHINDA', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Padampur' },
  { id: 12, block: 'Anandapur', gpName: 'SALABANI', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Padampur' },
  { id: 13, block: 'Anandapur', gpName: 'BAUNSAGARH', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Padampur' },
  { id: 14, block: 'Anandapur', gpName: 'KODAPADA', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Padampur' },
  { id: 15, block: 'Anandapur', gpName: 'BUDHIKUDA', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Padampur' },
  { id: 16, block: 'Anandapur', gpName: 'GAYALMUNDA', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Padampur' },
  { id: 17, block: 'Anandapur', gpName: 'PANASADIHA', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Padampur' },
  { id: 18, block: 'Anandapur', gpName: 'MANOHARPUR', taggedUlb: 'Anandapur Municipality', taggedMrf: 'Padampur' },

  // Champua NAC - Champua Block
  { id: 19, block: 'Champua', gpName: 'Rajia', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 20, block: 'Champua', gpName: 'Kalikaprasad', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 21, block: 'Champua', gpName: 'Badanai', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 22, block: 'Champua', gpName: 'Parsala', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 23, block: 'Champua', gpName: 'Rimuli', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 24, block: 'Champua', gpName: 'Sunaposi', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 25, block: 'Champua', gpName: 'Jamudalak', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 26, block: 'Champua', gpName: 'Kutariposi', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 27, block: 'Champua', gpName: 'Kodagadia', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 28, block: 'Champua', gpName: 'Sarei', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 29, block: 'Champua', gpName: 'Karanjia', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 30, block: 'Champua', gpName: 'Chandrasekharpur', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 31, block: 'Champua', gpName: 'Kashipal', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 32, block: 'Champua', gpName: 'Padua', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 33, block: 'Champua', gpName: 'Uchabali', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 34, block: 'Champua', gpName: 'Jyotipur', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 35, block: 'Champua', gpName: 'Bhuinpur', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 36, block: 'Champua', gpName: 'Jally', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 37, block: 'Champua', gpName: 'Sadangi', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 38, block: 'Champua', gpName: 'Jajaposi', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 39, block: 'Champua', gpName: 'Bhanda', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },
  { id: 40, block: 'Champua', gpName: 'Rangamatia', taggedUlb: 'Champua NAC', taggedMrf: 'Kainta of Rajia GP' },

  // Joda Block
  { id: 41, block: 'Joda', gpName: 'BOLANI', taggedUlb: 'Barbil Municipality', taggedMrf: 'Darbi Chack' },
  { id: 42, block: 'Joda', gpName: 'BALAGODA', taggedUlb: 'Barbil Municipality', taggedMrf: 'Santbahal hoting' },
  { id: 43, block: 'Joda', gpName: 'KARAKHENDRA', taggedUlb: 'Barbil Municipality', taggedMrf: 'Kara' },
  { id: 44, block: 'Joda', gpName: 'SERENDA', taggedUlb: 'Barbil Municipality', taggedMrf: 'Kara' },
  { id: 45, block: 'Joda', gpName: 'JAJANGA', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 46, block: 'Joda', gpName: 'JALAHARI', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 47, block: 'Joda', gpName: 'JURUDI', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 48, block: 'Joda', gpName: 'PALASA', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 49, block: 'Joda', gpName: 'BALADA', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 50, block: 'Joda', gpName: 'BADAKALIMATI', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 51, block: 'Joda', gpName: 'BHADRASAHI', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 52, block: 'Joda', gpName: 'BIRIKALA', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 53, block: 'Joda', gpName: 'DEOJHAR', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 54, block: 'Joda', gpName: 'KANDRA', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 55, block: 'Joda', gpName: 'ASENIKALA', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 56, block: 'Joda', gpName: 'CHAMAKPUR', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 57, block: 'Joda', gpName: 'GUALI', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 58, block: 'Joda', gpName: 'LOIDAPADA', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },
  { id: 59, block: 'Joda', gpName: 'BHUINROIDA', taggedUlb: 'Joda Municipality', taggedMrf: 'Bachu hoting' },

  // Kendujhar Sadar Block
  { id: 60, block: 'Kendujhar Sadar', gpName: 'Janardanpur', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 61, block: 'Kendujhar Sadar', gpName: 'Raisuan', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 62, block: 'Kendujhar Sadar', gpName: 'Gopinathpur', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 63, block: 'Kendujhar Sadar', gpName: 'Mahadeijoda', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 64, block: 'Kendujhar Sadar', gpName: 'Baradapal', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 65, block: 'Kendujhar Sadar', gpName: 'Nuagaon', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 66, block: 'Kendujhar Sadar', gpName: 'Parjanpur', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 67, block: 'Kendujhar Sadar', gpName: 'Kandaraposi', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 68, block: 'Kendujhar Sadar', gpName: 'Palasapanga', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 69, block: 'Kendujhar Sadar', gpName: 'Padampur', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 70, block: 'Kendujhar Sadar', gpName: 'Gobardhan', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 71, block: 'Kendujhar Sadar', gpName: 'Kaunrikala', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 72, block: 'Kendujhar Sadar', gpName: 'Sankiri', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 73, block: 'Kendujhar Sadar', gpName: 'Handibhanga', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 74, block: 'Kendujhar Sadar', gpName: 'Raikala', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 75, block: 'Kendujhar Sadar', gpName: 'Bauripada', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 76, block: 'Kendujhar Sadar', gpName: 'Bodapalasa', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 77, block: 'Kendujhar Sadar', gpName: 'Sirispal', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 78, block: 'Kendujhar Sadar', gpName: 'Naranpur', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 79, block: 'Kendujhar Sadar', gpName: 'Raghunathpur', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 80, block: 'Kendujhar Sadar', gpName: 'Kathabari', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 81, block: 'Kendujhar Sadar', gpName: 'Maidankel', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 82, block: 'Kendujhar Sadar', gpName: 'Dimbo', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 83, block: 'Kendujhar Sadar', gpName: 'Nelung', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
  { id: 84, block: 'Kendujhar Sadar', gpName: 'Mandua', taggedUlb: 'Kendujhargarh Municipality', taggedMrf: 'Brahmanigaon' },
];
