
export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // GOP BLOCK - KONARK MRF
  { id: 1, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'SIMILI', wasteGeneratedKg: 231.0, gpNodalPerson: 'MANDEEP SATAPATHY', gpNodalContact: '9583111126', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 2, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'BAULANGA', wasteGeneratedKg: 112.1, gpNodalPerson: 'MANASWINI MOHAPATRA', gpNodalContact: '8455976763', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 3, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'ISANPUR', wasteGeneratedKg: 48.2, gpNodalPerson: 'SISIR KUMAR MALLICK', gpNodalContact: '7008681814', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 4, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'DESTHALI', wasteGeneratedKg: 67.7, gpNodalPerson: 'SISIR KUMAR MALLICK', gpNodalContact: '7008681814', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 5, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'SORAVA', wasteGeneratedKg: 64.9, gpNodalPerson: 'SUDHANSHU PANDA', gpNodalContact: '6370280902', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 6, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'JANGALBORI', wasteGeneratedKg: 83.6, gpNodalPerson: 'SAROJ KUMAR MUDULI', gpNodalContact: '8016724407', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 7, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'DHUMALA', wasteGeneratedKg: 74.6, gpNodalPerson: 'PRASANNA KUMAR NAYAK', gpNodalContact: '9937503589', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 8, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'BANAKHANDI', wasteGeneratedKg: 232.3, gpNodalPerson: 'MANDEEP SATAPATHY', gpNodalContact: '9583111126', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 9, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'BADATARA', wasteGeneratedKg: 75.1, gpNodalPerson: 'SOUMYA RANJAN CHINARA', gpNodalContact: '7735484733', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 10, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'BEDAPUR', wasteGeneratedKg: 35.3, gpNodalPerson: 'MANAS RANJAN DASH', gpNodalContact: '9438621026', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 11, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'MAHALPADA', wasteGeneratedKg: 70.8, gpNodalPerson: 'SOUBHAGYAJIT BISWAL', gpNodalContact: '7815042712', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 12, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'ERABANGA', wasteGeneratedKg: 75.1, gpNodalPerson: 'DEBASISH PANDA', gpNodalContact: '7008952564', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 13, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'BIRITUNGA', wasteGeneratedKg: 71.2, gpNodalPerson: 'ARATI ROUT', gpNodalContact: '7894272295', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 14, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'GOP', wasteGeneratedKg: 56.0, gpNodalPerson: 'JAGANMOHAN MANSINGH', gpNodalContact: '9583249319', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 15, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'GANESWARPUR', wasteGeneratedKg: 98.6, gpNodalPerson: 'MURALIDHARA BISWAL', gpNodalContact: '9438181420', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 16, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'NAGAPUR', wasteGeneratedKg: 387.7, gpNodalPerson: 'SARBESWAR SWAIN', gpNodalContact: '9861991146', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 17, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'ACHYUTPUR', wasteGeneratedKg: 163.3, gpNodalPerson: 'RABINDRA KUMAR PRADHAN', gpNodalContact: '9938939805', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 18, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'KUANPADA', wasteGeneratedKg: 229.5, gpNodalPerson: 'RAMESH CHANDRA BEHERA', gpNodalContact: '8917255472', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 19, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'BANIASAHI', wasteGeneratedKg: 157.2, gpNodalPerson: 'RAMESH CHANDRA BEHERA', gpNodalContact: '8917255472', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 20, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'BANTALIGAON', wasteGeneratedKg: 256.6, gpNodalPerson: 'JAGANMOHAN MANSINGH', gpNodalContact: '9583249319', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 21, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'PAYARA', wasteGeneratedKg: 163.3, gpNodalPerson: 'SARBESWAR SWAIN', gpNodalContact: '9861991146', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 22, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'DAVARA', wasteGeneratedKg: 150.8, gpNodalPerson: 'ARATI ROUT', gpNodalContact: '9937503589', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 23, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'RAHANGORADA', wasteGeneratedKg: 145.6, gpNodalPerson: 'KSHITISH KUMAR PRUSTY', gpNodalContact: '6371762276', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 24, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'NUAKHOLAMARA', wasteGeneratedKg: 157.1, gpNodalPerson: 'KSHITISH KUMAR PRUSTY', gpNodalContact: '6371762276', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 25, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'ANDHRA ICHHAPUR', wasteGeneratedKg: 160.8, gpNodalPerson: 'SARBESWAR SWAIN', gpNodalContact: '9861991146', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 26, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'ITIBHUAN', wasteGeneratedKg: 115.5, gpNodalPerson: 'RABINDRA KUMAR PRADHAN', gpNodalContact: '9938939805', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 27, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'CHAITANA', wasteGeneratedKg: 177.6, gpNodalPerson: 'SHYAMASUNDAR PRADHAN', gpNodalContact: '9861810073', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 28, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'GADAVENGURA', wasteGeneratedKg: 119.6, gpNodalPerson: 'SUSANT NAIK', gpNodalContact: '7377430486', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 29, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'BADAGAON', wasteGeneratedKg: 214.3, gpNodalPerson: 'SAROJ KUMAR MUDULI', gpNodalContact: '8018724407', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 30, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'SUTAN', wasteGeneratedKg: 171.5, gpNodalPerson: 'RANJITA PRADHAN', gpNodalContact: '7735708330', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },
  { id: 31, block: 'GOP', ulb: 'KONARK NAC', mrf: 'KONARK MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'TARAKOR', wasteGeneratedKg: 98.1, gpNodalPerson: 'RANJITA PRADHAN', gpNodalContact: '7735708330', ulbNodalPerson: 'Abhisekh Swain', ulbNodalContact: '9040183894' },

  // NIMAPADA BLOCK - NIMAPADA MRF
  { id: 32, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'ARISANDHA', wasteGeneratedKg: 180.9, gpNodalPerson: 'Bharati Sethi', gpNodalContact: '9778918823', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 33, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'SALANGA', wasteGeneratedKg: 177.6, gpNodalPerson: 'Anam Ch Sahoo', gpNodalContact: '9658827564', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 34, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'BAMANALA', wasteGeneratedKg: 275.8, gpNodalPerson: 'Anam Ch Sahoo', gpNodalContact: '9658827564', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 35, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'NUASANTH', wasteGeneratedKg: 97.2, gpNodalPerson: 'Surendra Ku Pradhan', gpNodalContact: '9668340275', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 36, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'UCHHUPUR', wasteGeneratedKg: 250.2, gpNodalPerson: 'Surendra Ku Pradhan', gpNodalContact: '9668340275', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 37, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'ANTUAR', wasteGeneratedKg: 175.4, gpNodalPerson: 'Gunanidhi Mishra', gpNodalContact: '8763333025', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 38, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'DHALESWAR', wasteGeneratedKg: 165.1, gpNodalPerson: 'Somanath Nayak', gpNodalContact: '9937247235', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 39, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'BADASIRIVILA', wasteGeneratedKg: 152.4, gpNodalPerson: 'Jitendra Muthamajhi', gpNodalContact: '7205125842', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 40, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'KOTAKOSANG', wasteGeneratedKg: 221.4, gpNodalPerson: 'Tarun Ku Sngh', gpNodalContact: '6370286626', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 41, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'BALANGA', wasteGeneratedKg: 205.7, gpNodalPerson: 'Tarun Ku Sngh', gpNodalContact: '6370286626', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 42, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'GOPINATHAPUR', wasteGeneratedKg: 149.4, gpNodalPerson: 'Bijaya Kumar Nayak', gpNodalContact: '6370547295', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 43, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'DHANUA', wasteGeneratedKg: 244.8, gpNodalPerson: 'Surath Ch Pradhan', gpNodalContact: '9938139170', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 44, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'SAINSASASAN', wasteGeneratedKg: 244.1, gpNodalPerson: 'Arabinda Behera', gpNodalContact: '9937150785', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 45, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'RENCHSASAN', wasteGeneratedKg: 201.8, gpNodalPerson: 'Bhagaban Mohapatra', gpNodalContact: '9437269464', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 46, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'GADAPADANPUR', wasteGeneratedKg: 167.6, gpNodalPerson: 'Jitendra Muthamajhi', gpNodalContact: '7205125842', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 47, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'HARIPUR', wasteGeneratedKg: 145.5, gpNodalPerson: 'Bhagaban Mohapatra', gpNodalContact: '9437269464', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 48, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'DENUA', wasteGeneratedKg: 225.7, gpNodalPerson: 'Banalata Chinara', gpNodalContact: '7789877991', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 49, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'CHANARPADA', wasteGeneratedKg: 265.1, gpNodalPerson: 'Arabinda Behera', gpNodalContact: '9937150785', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 50, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'RATILO', wasteGeneratedKg: 118.1, gpNodalPerson: 'Manasi tudu', gpNodalContact: '6372815170', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 51, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'SAGADA', wasteGeneratedKg: 196.4, gpNodalPerson: 'Susanta Ku Behera', gpNodalContact: '8637205521', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 52, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'BADAMACHHAPUR', wasteGeneratedKg: 153.8, gpNodalPerson: 'Susanta Ku Behera', gpNodalContact: '8637205521', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 53, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'ALANDA', wasteGeneratedKg: 181.3, gpNodalPerson: 'Debendra Ku Swain', gpNodalContact: '9938492557', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 54, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'TERUNDIA', wasteGeneratedKg: 279.1, gpNodalPerson: 'Sarangadhar Swain', gpNodalContact: '9777609159', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 55, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'BHOGASALADA', wasteGeneratedKg: 147.3, gpNodalPerson: 'Pradesh Ku Sahoo', gpNodalContact: '8847844395', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 56, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'BHILIGRAM', wasteGeneratedKg: 245.6, gpNodalPerson: 'Kabiraj Kandi', gpNodalContact: '7978812696', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 57, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'MITEIPUR', wasteGeneratedKg: 182.7, gpNodalPerson: 'Kabiraj Kandi', gpNodalContact: '7978812696', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 58, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'KALAPANCHAN', wasteGeneratedKg: 251.2, gpNodalPerson: 'Sarangadhar Swain', gpNodalContact: '9777609159', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 59, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Saturday', gpName: 'BHODAR', wasteGeneratedKg: 210.7, gpNodalPerson: 'Debendra Ku Swain', gpNodalContact: '9938492557', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 60, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Saturday', gpName: 'TULASIPUR', wasteGeneratedKg: 371.0, gpNodalPerson: 'Pushpakanta Das', gpNodalContact: '7978839450', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 61, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Saturday', gpName: 'BAHARANA', wasteGeneratedKg: 283.5, gpNodalPerson: 'Priyanka P. Singh', gpNodalContact: '8249717805', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 62, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Saturday', gpName: 'CHHANIJANGA', wasteGeneratedKg: 267.9, gpNodalPerson: 'Kalandi Ch Nayak', gpNodalContact: '7978325564', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },
  { id: 63, block: 'NIMAPADA', ulb: 'NIMAPADA NAC', mrf: 'NIMAPADA MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Saturday', gpName: 'TAMPALO', wasteGeneratedKg: 148.1, gpNodalPerson: 'Pooja Mallick', gpNodalContact: '8328962281', ulbNodalPerson: 'Sunil Swain', ulbNodalContact: '8249464899' },

  // PIPILI BLOCK - PIPILI MRF
  { id: 64, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'POPORANGA', wasteGeneratedKg: 148.8, gpNodalPerson: 'Biswajit Patra', gpNodalContact: '9531855973', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 65, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'GOBINDPUR', wasteGeneratedKg: 343.1, gpNodalPerson: 'Priyadarsini Mohapatra', gpNodalContact: '7537919414', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 66, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'PAMASARA', wasteGeneratedKg: 123.2, gpNodalPerson: 'Manini Pradhan', gpNodalContact: '6371963675', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 67, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'LAXMINARAYANPUR', wasteGeneratedKg: 323.8, gpNodalPerson: 'Srikanta Sahoo', gpNodalContact: '7682936358', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 68, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'PUBASASAN', wasteGeneratedKg: 274.0, gpNodalPerson: 'Diptimayee Sethi', gpNodalContact: '8895251149', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 69, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'ORAKAL', wasteGeneratedKg: 137.1, gpNodalPerson: 'Subhasmita Sahoo', gpNodalContact: '7008840931', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 70, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'JAGANNATHPUR', wasteGeneratedKg: 110.7, gpNodalPerson: 'Mangaraj Jena', gpNodalContact: '6370274288', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 71, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'NUASASAN', wasteGeneratedKg: 177.7, gpNodalPerson: 'Padma Bhusan Paltasingh', gpNodalContact: '9861016021', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 72, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'SAMPUR', wasteGeneratedKg: 173.9, gpNodalPerson: 'Padma Bhusan Paltasingh', gpNodalContact: '9861016021', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 73, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'HATASAHI', wasteGeneratedKg: 370.1, gpNodalPerson: 'Padma Bhusan Paltasingh', gpNodalContact: '9861016021', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 74, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'BHARATIPUR', wasteGeneratedKg: 133.0, gpNodalPerson: 'Diptirekha Mallick', gpNodalContact: '8917538525', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 75, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'PANIDOLA', wasteGeneratedKg: 181.9, gpNodalPerson: 'Sahera Jahan', gpNodalContact: '8249544231', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 76, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'KANTI', wasteGeneratedKg: 300.8, gpNodalPerson: 'Bharat Baliarsingh', gpNodalContact: '9778120425', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 77, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'DANDAMAKUNDAPUR', wasteGeneratedKg: 223.0, gpNodalPerson: 'Bhagaban Rath', gpNodalContact: '8144752512', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 78, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'MANGALPUR', wasteGeneratedKg: 323.8, gpNodalPerson: 'Bhagaban Rath', gpNodalContact: '8144752512', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 79, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'KULASEKHARAPATANA', wasteGeneratedKg: 137.2, gpNodalPerson: 'Suresh Chandra Sahu', gpNodalContact: '7008686652', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 80, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'DURGADASPUR', wasteGeneratedKg: 235.3, gpNodalPerson: 'Biswajita Das', gpNodalContact: '6370674019', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 81, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Thursday', gpName: 'CHANDRADEIPUR', wasteGeneratedKg: 110.6, gpNodalPerson: 'Suresh Chandra Sahu', gpNodalContact: '7008686652', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 82, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'JASUAPUR', wasteGeneratedKg: 269.5, gpNodalPerson: 'Suresh Chandra Dash', gpNodalContact: '7077175822', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 83, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'RATHAPURUSOTAMPUR', wasteGeneratedKg: 151.7, gpNodalPerson: 'Suresh Chandra Dash', gpNodalContact: '7077175822', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 84, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'SARASWATIPUR', wasteGeneratedKg: 178.0, gpNodalPerson: 'Subhakanta Mohanty', gpNodalContact: '8249084374', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 85, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'RUPADEIPUR', wasteGeneratedKg: 353.2, gpNodalPerson: 'Subhakanta Mohanty', gpNodalContact: '8249084374', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 86, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Saturday', gpName: 'TEISIPUR', wasteGeneratedKg: 308.6, gpNodalPerson: 'Kalandi Charan Bhoi', gpNodalContact: '9861810073', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 87, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Saturday', gpName: 'SAHAJPUR', wasteGeneratedKg: 118.7, gpNodalPerson: 'Suraj Mahapatra', gpNodalContact: '9886377832', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },
  { id: 88, block: 'PIPILI', ulb: 'PIPILI NAC', mrf: 'PIPILI MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Saturday', gpName: 'BIRAPURUSOTAMPUR', wasteGeneratedKg: 172.3, gpNodalPerson: 'Salma Begum', gpNodalContact: '7735802306', ulbNodalPerson: 'Diptiranjan Behera', ulbNodalContact: '9861289584' },

  // PURI SADAR BLOCK
  { id: 89, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'SASANDAMADORPUR', wasteGeneratedKg: 208.6, gpNodalPerson: 'Radhakanta Hati', gpNodalContact: '8249518040', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 90, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'BASUDEBAPUR', wasteGeneratedKg: 97.2, gpNodalPerson: 'Radhakanta Hati', gpNodalContact: '8249518040', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 91, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'KERANDIPUR', wasteGeneratedKg: 201.6, gpNodalPerson: 'Nayani Pradhan', gpNodalContact: '8895151430', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 92, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'BIRABALABHADRAPUR', wasteGeneratedKg: 99.6, gpNodalPerson: 'Soumya Mishra', gpNodalContact: '7978337452', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 93, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'HANTUKA', wasteGeneratedKg: 112.8, gpNodalPerson: 'Keshab Chandra Pradhan', gpNodalContact: '9861453363', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 94, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Monday', gpName: 'MALATIPATPUR', wasteGeneratedKg: 154.2, gpNodalPerson: 'Sunil Kumar Hembram', gpNodalContact: '9348771663', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 95, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'TALAJANGA', wasteGeneratedKg: 84.1, gpNodalPerson: 'Sarmistha Sethy', gpNodalContact: '6371598854', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 96, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'BIRAPRATAPPUR', wasteGeneratedKg: 122.8, gpNodalPerson: 'Pranay Das', gpNodalContact: '9937183770', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 97, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'CHANDANPUR', wasteGeneratedKg: 74.8, gpNodalPerson: 'Sarmistha Sethy', gpNodalContact: '6371598854', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 98, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'CHALISIBATIA', wasteGeneratedKg: 323.7, gpNodalPerson: 'Radhanath Soren', gpNodalContact: '7008078921', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 99, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'GANGANARAYANPUR', wasteGeneratedKg: 77.2, gpNodalPerson: 'Sunil Kumar Hembram', gpNodalContact: '9348771663', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 100, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Baliapanda MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Tuesday', gpName: 'BALIPADA', wasteGeneratedKg: 149.1, gpNodalPerson: 'Radhanath Soren', gpNodalContact: '7008078921', ulbNodalPerson: 'Soubagyalaxmi Jena', ulbNodalContact: '7787922159' },
  { id: 101, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Masanichandi MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'BHAILIPUR', wasteGeneratedKg: 150.3, gpNodalPerson: 'Soumya Mishra', gpNodalContact: '7978337452', ulbNodalPerson: 'Keshab Chandra Sahoo', ulbNodalContact: '8249781508' },
  { id: 102, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Masanichandi MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'BIJAYARAMACHANDRAPUR', wasteGeneratedKg: 80.6, gpNodalPerson: 'Nirmalya Nayak', gpNodalContact: '7008635643', ulbNodalPerson: 'Keshab Chandra Sahoo', ulbNodalContact: '8249781508' },
  { id: 103, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Masanichandi MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'BIRANARSINGHPUR', wasteGeneratedKg: 193.1, gpNodalPerson: 'Pratyush Ranjan Pradhan', gpNodalContact: '8249627874', ulbNodalPerson: 'Keshab Chandra Sahoo', ulbNodalContact: '8249781508' },
  { id: 104, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Masanichandi MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'GAUDAKERA', wasteGeneratedKg: 116.4, gpNodalPerson: 'Arabinda Nayak', gpNodalContact: '8249388345', ulbNodalPerson: 'Keshab Chandra Sahoo', ulbNodalContact: '8249781508' },
  { id: 105, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Masanichandi MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'KAHNEIBIDYADHARPUR', wasteGeneratedKg: 166.3, gpNodalPerson: 'Lokanath Nayak', gpNodalContact: '7978049549', ulbNodalPerson: 'Keshab Chandra Sahoo', ulbNodalContact: '8249781508' },
  { id: 106, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Masanichandi MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'PRATAPPURUSHOTTAMPUR', wasteGeneratedKg: 140.4, gpNodalPerson: 'Keshab Chandra Pradhan', gpNodalContact: '9861453363', ulbNodalPerson: 'Keshab Chandra Sahoo', ulbNodalContact: '8249781508' },
  { id: 107, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Masanichandi MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Wednesday', gpName: 'PRATAPRAMACHANDRAPUR', wasteGeneratedKg: 234.3, gpNodalPerson: 'Pranay Das', gpNodalContact: '9937183770', ulbNodalPerson: 'Keshab Chandra Sahoo', ulbNodalContact: '8249781508' },
  { id: 108, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Talabania MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'BALIPUT', wasteGeneratedKg: 245.9, gpNodalPerson: 'Ashish Mishra', gpNodalContact: '8249934431', ulbNodalPerson: 'Risav Dash', ulbNodalContact: '8908890107' },
  { id: 109, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Talabania MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'BELADALA', wasteGeneratedKg: 81.2, gpNodalPerson: 'Rajashree Das', gpNodalContact: '6370615239', ulbNodalPerson: 'Risav Dash', ulbNodalContact: '8908890107' },
  { id: 110, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Talabania MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'GADAMRUGASIRA', wasteGeneratedKg: 198.9, gpNodalPerson: 'Sulamani Jani', gpNodalContact: '9692042758', ulbNodalPerson: 'Risav Dash', ulbNodalContact: '8908890107' },
  { id: 111, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Talabania MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'JAMARSUAN', wasteGeneratedKg: 103.8, gpNodalPerson: 'Sulamani Jani', gpNodalContact: '9692042758', ulbNodalPerson: 'Risav Dash', ulbNodalContact: '8908890107' },
  { id: 112, block: 'PURI SADAR', ulb: 'PURI MUNICIPAL CORPORATION', mrf: 'Talabania MRF', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 kg', driverName: '-', driverContact: '-', collectionSchedule: 'Every Friday', gpName: 'RAIGORADA', wasteGeneratedKg: 90.3, gpNodalPerson: 'Ashish Mishra', gpNodalContact: '8249934431', ulbNodalPerson: 'Risav Dash', ulbNodalContact: '8908890107' },
];

    