export interface GpMappingData {
  id: number;
  block: string;
  gpName: string;
  taggedUlb: string;
  taggedMrf: string;
}

export const gpMappingData: GpMappingData[] = [
  // Block: GOP (Konark MRF)
  { id: 1, block: 'GOP', gpName: 'ACHUTAPUR', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 2, block: 'GOP', gpName: 'ANDHRA ICHHAPUR', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 3, block: 'GOP', gpName: 'BADAGAON', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 4, block: 'GOP', gpName: 'BADATARA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 5, block: 'GOP', gpName: 'BANAKHANDI', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 6, block: 'GOP', gpName: 'BANIASAHI', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 7, block: 'GOP', gpName: 'BANTALIGRAM', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 8, block: 'GOP', gpName: 'BEDAPUR', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 9, block: 'GOP', gpName: 'BIRTUNG', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 10, block: 'GOP', gpName: 'BOULANGA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 11, block: 'GOP', gpName: 'CHHAITANA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 12, block: 'GOP', gpName: 'DAVARA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 13, block: 'GOP', gpName: 'DESTHALI', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 14, block: 'GOP', gpName: 'DHUMALA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 15, block: 'GOP', gpName: 'ERABANGA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 16, block: 'GOP', gpName: 'GADABHINGURA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 17, block: 'GOP', gpName: 'GANESWARPUR', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 18, block: 'GOP', gpName: 'GOP', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 19, block: 'GOP', gpName: 'ISHANPUR', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 20, block: 'GOP', gpName: 'ITIBHUAN', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 21, block: 'GOP', gpName: 'JANGALBORI', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 22, block: 'GOP', gpName: 'KUANPADA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 23, block: 'GOP', gpName: 'MAHALAPADA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 24, block: 'GOP', gpName: 'NAGAPUR', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 25, block: 'GOP', gpName: 'NUAKHOLAMARA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 26, block: 'GOP', gpName: 'PAYARA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 27, block: 'GOP', gpName: 'RAHANGORADA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 28, block: 'GOP', gpName: 'SIMILI', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 29, block: 'GOP', gpName: 'SORAVA', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 30, block: 'GOP', gpName: 'SUTAN', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },
  { id: 31, block: 'GOP', gpName: 'TARAKOR', taggedUlb: 'KONARK NAC', taggedMrf: 'Konark MRF' },

  // Block: NIMAPADA (Nimapada MRF)
  { id: 32, block: 'NIMAPADA', gpName: 'AERISANDHA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 33, block: 'NIMAPADA', gpName: 'ALANDA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 34, block: 'NIMAPADA', gpName: 'ANTUARA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 35, block: 'NIMAPADA', gpName: 'BADAMACHHAPUR', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 36, block: 'NIMAPADA', gpName: 'BADASIRIVILA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 37, block: 'NIMAPADA', gpName: 'BAHARANA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 38, block: 'NIMAPADA', gpName: 'BALANGA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 39, block: 'NIMAPADA', gpName: 'BAMANALA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 40, block: 'NIMAPADA', gpName: 'BHILIGRAM', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 41, block: 'NIMAPADA', gpName: 'BHODAR', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 42, block: 'NIMAPADA', gpName: 'BHOGASALADA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 43, block: 'NIMAPADA', gpName: 'CHANRAPADA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 44, block: 'NIMAPADA', gpName: 'CHHANIJANGA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 45, block: 'NIMAPADA', gpName: 'DENUA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 46, block: 'NIMAPADA', gpName: 'DHALESWAR', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 47, block: 'NIMAPADA', gpName: 'DHANUA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 48, block: 'NIMAPADA', gpName: 'GADAPADANPUR', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 49, block: 'NIMAPADA', gpName: 'GOPINATHAPUR', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 50, block: 'NIMAPADA', gpName: 'HARIPUR', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 51, block: 'NIMAPADA', gpName: 'KALAPANCHANA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 52, block: 'NIMAPADA', gpName: 'KOTAKOSANG', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 53, block: 'NIMAPADA', gpName: 'MITEIPUR', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 54, block: 'NIMAPADA', gpName: 'NUASANTHA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 55, block: 'NIMAPADA', gpName: 'RATILO', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 56, block: 'NIMAPADA', gpName: 'RENCHSASAN', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 57, block: 'NIMAPADA', gpName: 'SAGADA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 58, block: 'NIMAPADA', gpName: 'SAINSASASAN', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 59, block: 'NIMAPADA', gpName: 'SALANGA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 60, block: 'NIMAPADA', gpName: 'TAMPALO', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 61, block: 'NIMAPADA', gpName: 'TERUNDIA', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 62, block: 'NIMAPADA', gpName: 'TULASIPUR', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },
  { id: 63, block: 'NIMAPADA', gpName: 'UCHHUPUR', taggedUlb: 'NIMAPADA NAC', taggedMrf: 'Nimapada MRF' },

  // Block: PIPILI (Pipili MRF)
  { id: 64, block: 'PIPILI', gpName: 'BHARATIPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 65, block: 'PIPILI', gpName: 'BIRAPURUSOTAMPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 66, block: 'PIPILI', gpName: 'CHANDRADEIPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 67, block: 'PIPILI', gpName: 'DHANDAMAKUNDAPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 68, block: 'PIPILI', gpName: 'DURGADASPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 69, block: 'PIPILI', gpName: 'GOBINDAPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 70, block: 'PIPILI', gpName: 'HATASAHI', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 71, block: 'PIPILI', gpName: 'JAGANNATHPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 72, block: 'PIPILI', gpName: 'JASUAPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 73, block: 'PIPILI', gpName: 'KANTI', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 74, block: 'PIPILI', gpName: 'KULASEKHARAPATANA', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 75, block: 'PIPILI', gpName: 'LAXMINARAYANPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 76, block: 'PIPILI', gpName: 'MANGALPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 77, block: 'PIPILI', gpName: 'NUASASAN', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 78, block: 'PIPILI', gpName: 'ORKAL', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 79, block: 'PIPILI', gpName: 'PAMASARA', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 80, block: 'PIPILI', gpName: 'PANIDOLA', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 81, block: 'PIPILI', gpName: 'POPORANGA', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 82, block: 'PIPILI', gpName: 'PUBASASAN', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 83, block: 'PIPILI', gpName: 'RATHAPURUSOTAMPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 84, block: 'PIPILI', gpName: 'RUPADEIPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 85, block: 'PIPILI', gpName: 'SAHAJPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 86, block: 'PIPILI', gpName: 'SAMPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 87, block: 'PIPILI', gpName: 'SARASWATIPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },
  { id: 88, block: 'PIPILI', gpName: 'TEISIPUR', taggedUlb: 'PIPILI NAC', taggedMrf: 'Pipili MRF' },

  // Block: PURI SADAR (Puri Municipality MRFs)
  { id: 89, block: 'PURI SADAR', gpName: 'BALIPADA', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 90, block: 'PURI SADAR', gpName: 'BASUDEVPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 91, block: 'PURI SADAR', gpName: 'BIRABALABHADRAPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 92, block: 'PURI SADAR', gpName: 'BIRAPRATAPPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 93, block: 'PURI SADAR', gpName: 'CHALISIBATIA', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 94, block: 'PURI SADAR', gpName: 'CHANDANPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 95, block: 'PURI SADAR', gpName: 'GANGANARAYANPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 96, block: 'PURI SADAR', gpName: 'HANTUKA', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 97, block: 'PURI SADAR', gpName: 'KERANDIPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 98, block: 'PURI SADAR', gpName: 'MALATIPATPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 99, block: 'PURI SADAR', gpName: 'SASANDAMODRARPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 100, block: 'PURI SADAR', gpName: 'TALAJANGA', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Baliapanda MRF' },
  { id: 101, block: 'PURI SADAR', gpName: 'BHAILIPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Masanichandi MRF' },
  { id: 102, block: 'PURI SADAR', gpName: 'BIJAYRAMACHANDRAPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Masanichandi MRF' },
  { id: 103, block: 'PURI SADAR', gpName: 'BIRANARSINGHPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Masanichandi MRF' },
  { id: 104, block: 'PURI SADAR', gpName: 'GOUDAKERA', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Masanichandi MRF' },
  { id: 105, block: 'PURI SADAR', gpName: 'KANHEIBIDYADHARPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Masanichandi MRF' },
  { id: 106, block: 'PURI SADAR', gpName: 'PRATAPPUROSOTTAMPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Masanichandi MRF' },
  { id: 107, block: 'PURI SADAR', gpName: 'PRATAPRAMACHANDRAPUR', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Masanichandi MRF' },
  { id: 108, block: 'PURI SADAR', gpName: 'BALIPUT', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Tlabania MRF' },
  { id: 109, block: 'PURI SADAR', gpName: 'BELADAL', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Tlabania MRF' },
  { id: 110, block: 'PURI SADAR', gpName: 'GARHMURGASIRA', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Tlabania MRF' },
  { id: 111, block: 'PURI SADAR', gpName: 'JAMARSUAN', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Tlabania MRF' },
  { id: 112, block: 'PURI SADAR', gpName: 'RAIGORADA', taggedUlb: 'PURI MUNICIPALITY', taggedMrf: 'Tlabania MRF' },
];
