
export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // GUDARI Block
  { id: 1, block: 'GUDARI', ulb: 'GUDARI NAC', mrf: 'NA', vehicleType: 'NA', vehicleNo: 'NA', vehicleCapacity: 'NA', driverName: 'NA', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'ASADA', wasteGeneratedKg: 0, gpNodalPerson: 'Sri Ghanashyam Tadingi', gpNodalContact: '8895860476', ulbNodalPerson: 'Arun Lima (Sanitation Expert)', ulbNodalContact: '8249566192' },
  { id: 2, block: 'GUDARI', ulb: 'GUDARI NAC', mrf: 'NA', vehicleType: 'NA', vehicleNo: 'NA', vehicleCapacity: 'NA', driverName: 'NA', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KARLAGHATI', wasteGeneratedKg: 0, gpNodalPerson: 'Sri Gopal Krushna Gantayat', gpNodalContact: '9437459350', ulbNodalPerson: 'Arun Lima (Sanitation Expert)', ulbNodalContact: '8249566193' },
  { id: 3, block: 'GUDARI', ulb: 'GUDARI NAC', mrf: 'NA', vehicleType: 'NA', vehicleNo: 'NA', vehicleCapacity: 'NA', driverName: 'NA', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KHARIGUDA', wasteGeneratedKg: 0, gpNodalPerson: 'Sri Kishor Chanadra Sahu', gpNodalContact: '9437747315', ulbNodalPerson: 'Arun Lima (Sanitation Expert)', ulbNodalContact: '8249566194' },
  { id: 4, block: 'GUDARI', ulb: 'GUDARI NAC', mrf: 'NA', vehicleType: 'NA', vehicleNo: 'NA', vehicleCapacity: 'NA', driverName: 'NA', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KODAMA', wasteGeneratedKg: 0, gpNodalPerson: 'Sri Krushna Ch. Behera', gpNodalContact: '7735917659', ulbNodalPerson: 'Arun Lima (Sanitation Expert)', ulbNodalContact: '8249566195' },
  { id: 5, block: 'GUDARI', ulb: 'GUDARI NAC', mrf: 'NA', vehicleType: 'NA', vehicleNo: 'NA', vehicleCapacity: 'NA', driverName: 'NA', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'M.K.RAI', wasteGeneratedKg: 0, gpNodalPerson: 'Sri Krushna Ch. Behera', gpNodalContact: '7735917659', ulbNodalPerson: 'Arun Lima (Sanitation Expert)', ulbNodalContact: '8249566196' },
  { id: 6, block: 'GUDARI', ulb: 'GUDARI NAC', mrf: 'NA', vehicleType: 'NA', vehicleNo: 'NA', vehicleCapacity: 'NA', driverName: 'NA', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MADHUBAN', wasteGeneratedKg: 0, gpNodalPerson: 'Sri Dilip Kumar Paika', gpNodalContact: '9583882552', ulbNodalPerson: 'Arun Lima (Sanitation Expert)', ulbNodalContact: '8249566197' },
  { id: 7, block: 'GUDARI', ulb: 'GUDARI NAC', mrf: 'NA', vehicleType: 'NA', vehicleNo: 'NA', vehicleCapacity: 'NA', driverName: 'NA', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'PENDILI', wasteGeneratedKg: 0, gpNodalPerson: 'Sri Gopal Krushna Gantayat', gpNodalContact: '9437459350', ulbNodalPerson: 'Arun Lima (Sanitation Expert)', ulbNodalContact: '8249566198' },
  { id: 8, block: 'GUDARI', ulb: 'GUDARI NAC', mrf: 'NA', vehicleType: 'NA', vehicleNo: 'NA', vehicleCapacity: 'NA', driverName: 'NA', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SANAHUMA', wasteGeneratedKg: 0, gpNodalPerson: 'Sri Dilip Kumar Paika', gpNodalContact: '9583882552', ulbNodalPerson: 'Arun Lima (Sanitation Expert)', ulbNodalContact: '8249566199' },
  { id: 9, block: 'GUDARI', ulb: 'GUDARI NAC', mrf: 'NA', vehicleType: 'NA', vehicleNo: 'NA', vehicleCapacity: 'NA', driverName: 'NA', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SIRIGUDA', wasteGeneratedKg: 0, gpNodalPerson: 'Sri Ghanashyam Tadingi', gpNodalContact: '8895860476', ulbNodalPerson: 'Arun Lima (Sanitation Expert)', ulbNodalContact: '8249566200' },

  // RAYAGADA Block
  { id: 10, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Badaalubadi', wasteGeneratedKg: 0, gpNodalPerson: 'Surendra nayak', gpNodalContact: '933702118', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 11, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Badaerukubadi', wasteGeneratedKg: 0, gpNodalPerson: 'Surendra nayak', gpNodalContact: '933702118', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 12, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Bairagihalua', wasteGeneratedKg: 0, gpNodalPerson: 'sibananada satapathy', gpNodalContact: '8328823141', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 13, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Baising', wasteGeneratedKg: 0, gpNodalPerson: 'sunil brama', gpNodalContact: '7008763736', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 14, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Chandili', wasteGeneratedKg: 0, gpNodalPerson: 'sibananada satapathy', gpNodalContact: '832882341', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 15, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Dangalodi', wasteGeneratedKg: 0, gpNodalPerson: 'saty narayan swain', gpNodalContact: '6372295699', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 16, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Durgapadu', wasteGeneratedKg: 0, gpNodalPerson: 'bijay nayal', gpNodalContact: '9437719815', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 17, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Gajigaon', wasteGeneratedKg: 0, gpNodalPerson: 'sunil brama', gpNodalContact: '7008763736', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 18, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Gumma', wasteGeneratedKg: 0, gpNodalPerson: 'BIJYA NAYAK', gpNodalContact: '9437719815', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 19, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Halua', wasteGeneratedKg: 0, gpNodalPerson: 'Palabhi polei', gpNodalContact: '9348089084', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 20, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Hatseshkhal', wasteGeneratedKg: 0, gpNodalPerson: 'Babula sabar', gpNodalContact: '9337929808', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 21, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Jhimidipeta', wasteGeneratedKg: 0, gpNodalPerson: 'Tejasmita Pidika', gpNodalContact: '9337527740', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 22, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Kampa Maligan', wasteGeneratedKg: 0, gpNodalPerson: 'Arun Panigrahy', gpNodalContact: '9438769271', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 23, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Karlakona', wasteGeneratedKg: 0, gpNodalPerson: 'Arun Panigrahy', gpNodalContact: '9438769271', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 24, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Karubai', wasteGeneratedKg: 0, gpNodalPerson: 'bijya nayak', gpNodalContact: '9437719815', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 25, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Kereda', wasteGeneratedKg: 0, gpNodalPerson: 'ravi charan behera', gpNodalContact: '9337909198', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 26, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Kotapeta', wasteGeneratedKg: 0, gpNodalPerson: 'Bijay laxmi Kuhar', gpNodalContact: '9348401415', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 27, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Kuli', wasteGeneratedKg: 0, gpNodalPerson: 'Sunil Brama', gpNodalContact: '7008763736', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 28, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Kumatalpeta', wasteGeneratedKg: 0, gpNodalPerson: 'susmita maharana', gpNodalContact: '9583167033', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 29, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Kumbhikota', wasteGeneratedKg: 0, gpNodalPerson: 'Rup Rekha Naik', gpNodalContact: '9937660100', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 30, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Kutuli', wasteGeneratedKg: 0, gpNodalPerson: 'Monaj Jilakara', gpNodalContact: '7008975608', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 31, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Matikona', wasteGeneratedKg: 0, gpNodalPerson: 'Monaj Jilakara', gpNodalContact: '7008975608', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 32, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Mirabali', wasteGeneratedKg: 0, gpNodalPerson: 'Chitarsen Dolei', gpNodalContact: '7848019588', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 33, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Nakiti', wasteGeneratedKg: 0, gpNodalPerson: 'Chitarsen Dolei', gpNodalContact: '7848019588', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 34, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Penta', wasteGeneratedKg: 0, gpNodalPerson: 'Rabi charan behera', gpNodalContact: '9337909198', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 35, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Pipalguda', wasteGeneratedKg: 0, gpNodalPerson: 'M K sahu', gpNodalContact: '9778182146', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 36, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Pitamahal', wasteGeneratedKg: 0, gpNodalPerson: 'M K Sahu', gpNodalContact: '9778182146', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },
  { id: 37, block: 'RAYAGADA SDAR', ulb: 'ANTARIGUDA', mrf: 'ANTARIGUDA', vehicleType: 'Not Available', vehicleNo: 'Not Available', vehicleCapacity: 'Not Available', driverName: 'Not Available', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'Tadama', wasteGeneratedKg: 0, gpNodalPerson: 'saty narayan swain', gpNodalContact: '6372295699', ulbNodalPerson: 'binayak parichya', ulbNodalContact: '9437452536' },

  // Gunupur Block
  { id: 38, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'ABADA', wasteGeneratedKg: 0, gpNodalPerson: 'BALARAM NAYAK', gpNodalContact: '9439511845', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 39, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BAGASALA', wasteGeneratedKg: 0, gpNodalPerson: 'SIBA BRATA ACHARYA', gpNodalContact: '9437783827', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 40, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BHIMPUR', wasteGeneratedKg: 0, gpNodalPerson: 'NIRUPAMA PANDA', gpNodalContact: '8249210443', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 41, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'CHALAKAMBA', wasteGeneratedKg: 0, gpNodalPerson: 'ASWINO SABAR', gpNodalContact: '7608839507', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 42, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'DOMBASORA', wasteGeneratedKg: 0, gpNodalPerson: 'BALARAM NAYAK', gpNodalContact: '9439511845', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 43, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GADIAKHALA', wasteGeneratedKg: 0, gpNodalPerson: 'BIJAYA LAXMI SABORO', gpNodalContact: '7008434839', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 44, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GHANANTRI', wasteGeneratedKg: 0, gpNodalPerson: 'SIBA BRATA ACHARYA', gpNodalContact: '9437783827', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 45, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GOTHALAPADAR', wasteGeneratedKg: 0, gpNodalPerson: 'PRABHAKAR NALLA', gpNodalContact: '8249812454', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 46, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'JAGANNATHPUR', wasteGeneratedKg: 0, gpNodalPerson: 'MADANA SUNDAR PRADHAN', gpNodalContact: '9437388460', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 47, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'JALTAR', wasteGeneratedKg: 0, gpNodalPerson: 'ESWARA SABAR', gpNodalContact: '7855816474', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 48, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KULUSING', wasteGeneratedKg: 0, gpNodalPerson: 'SHIVAPRASAD RATH', gpNodalContact: '7735014711', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 49, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MORAMA', wasteGeneratedKg: 0, gpNodalPerson: 'PRABHAKAR NALLA', gpNodalContact: '8249812454', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 50, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'PUTTASING', wasteGeneratedKg: 0, gpNodalPerson: 'DAYA SABAR', gpNodalContact: '8480107519', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 51, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'REGEDA', wasteGeneratedKg: 0, gpNodalPerson: 'MADANA SUNDAR PRADHAN', gpNodalContact: '9437388460', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 52, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SAGADA', wasteGeneratedKg: 0, gpNodalPerson: 'DAYA SABAR', gpNodalContact: '8480107519', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 53, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'CHINASARI', wasteGeneratedKg: 0, gpNodalPerson: 'SHIVAPRASAD RATH', gpNodalContact: '7735014711', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 54, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SIRIJHOLLI', wasteGeneratedKg: 0, gpNodalPerson: 'ASWINO SABAR', gpNodalContact: '7608839507', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 55, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'TOLONA', wasteGeneratedKg: 0, gpNodalPerson: 'ESWARA SABAR', gpNodalContact: '7855816474', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' },
  { id: 56, block: 'Gunupur', ulb: 'Kothaluguda', mrf: 'Kothaluguda', vehicleType: 'NOT AVAILABLE', vehicleNo: 'NOT AVAILABLE', vehicleCapacity: 'NOT AVAILABLE', driverName: 'NOT AVAILABLE', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'TITIMIRI', wasteGeneratedKg: 0, gpNodalPerson: 'BALARAM NAYAK', gpNodalContact: '9439511845', ulbNodalPerson: 'Ramaniranjan Padhi', ulbNodalContact: '7207321699' }
];
