export interface RoutePlanData {
  id: number;
  routeId: string;
  routeName: string;
  routeAbbreviation: string;
  startingGp: string;
  intermediateGps: string[];
  finalGp: string;
  destination: string;
  totalDistance: number;
  workers: {
    name: string;
    contact: string;
  }[];
  scheduledOn: string;
}

export const routePlanData: RoutePlanData[] = [
  // Block RAYAGADA (ULB ANTARIGUDA)
  {
    id: 1,
    routeId: 'RRAYB02',
    routeName: 'RRAYBK',
    routeAbbreviation: 'RRAYBK',
    startingGp: 'Badaalubadi',
    intermediateGps: ['Badaalubadi'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 10,
    workers: [{ name: 'HAIM JILAKARA', contact: '8926000295' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 2,
    routeId: 'RRAYB04',
    routeName: 'RRAYBG',
    routeAbbreviation: 'RRAYBG',
    startingGp: 'Badaerukubadi',
    intermediateGps: ['Badaerukubadi'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 12,
    workers: [{ name: 'ARAMA MINIKA', contact: '6390350872' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 3,
    routeId: 'RRAYB4',
    routeName: 'RRAYBJ',
    routeAbbreviation: 'RRAYBJ',
    startingGp: 'Bairagihalua',
    intermediateGps: ['Bairagihalua'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 15,
    workers: [{ name: 'CHANCHA KILAKA', contact: '-' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 4,
    routeId: 'RRAYB3',
    routeName: 'RRAYBK',
    routeAbbreviation: 'RRAYBK',
    startingGp: 'Baising',
    intermediateGps: ['Baising'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 8,
    workers: [{ name: 'REETA MANDINGI', contact: '9827311372' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 5,
    routeId: 'RRAYC01',
    routeName: 'RRAYCK',
    routeAbbreviation: 'RRAYCK',
    startingGp: 'Chandili',
    intermediateGps: ['Chandili'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 11,
    workers: [],
    scheduledOn: 'Scheduled'
  },
  {
    id: 6,
    routeId: 'RRAYD03',
    routeName: 'RRAYDK',
    routeAbbreviation: 'RRAYDK',
    startingGp: 'Dangalodi',
    intermediateGps: ['Dangalodi'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 10,
    workers: [{ name: 'KRUPARI PUALA', contact: '9861100233' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 7,
    routeId: 'RRAYD03',
    routeName: 'RRAYDM',
    routeAbbreviation: 'RRAYDM',
    startingGp: 'Durgapadu',
    intermediateGps: ['Durgapadu'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 20,
    workers: [{ name: 'SARSHE TOIKA', contact: '8093169104' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 8,
    routeId: 'RRAYG4',
    routeName: 'RRAYGB',
    routeAbbreviation: 'RRAYGB',
    startingGp: 'Gajigaon',
    intermediateGps: ['Gajigaon'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 12,
    workers: [],
    scheduledOn: 'Scheduled'
  },
  {
    id: 9,
    routeId: 'RRAYG5',
    routeName: 'RRAYGH',
    routeAbbreviation: 'RRAYGH',
    startingGp: 'Gumma',
    intermediateGps: ['Gumma'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 17,
    workers: [{ name: 'SHANTI MANDINGI', contact: '8249396363' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 10,
    routeId: 'RRAYH05',
    routeName: 'RRAYHT',
    routeAbbreviation: 'RRAYHT',
    startingGp: 'Halua',
    intermediateGps: ['Halua'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 6,
    workers: [{ name: 'MADHANATI SUNA', contact: '-' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 11,
    routeId: 'RRAYH04',
    routeName: 'RRAYHK',
    routeAbbreviation: 'RRAYHK',
    startingGp: 'Hatseshkhal',
    intermediateGps: ['Hatseshkhal'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 10,
    workers: [],
    scheduledOn: 'Scheduled'
  },
  {
    id: 12,
    routeId: 'RRAYJ04',
    routeName: 'RRAYJB',
    routeAbbreviation: 'RRAYJB',
    startingGp: 'Jhimidipeta',
    intermediateGps: ['Jhimidipeta'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 15,
    workers: [{ name: 'MAMATA PIDIKA', contact: '7846914778' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 13,
    routeId: 'RRAYK02',
    routeName: 'RRAYKK',
    routeAbbreviation: 'RRAYKK',
    startingGp: 'Kampa Maligan',
    intermediateGps: ['Kampa Maligan'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 6,
    workers: [],
    scheduledOn: 'Scheduled'
  },
  {
    id: 14,
    routeId: 'RRAYK01',
    routeName: 'RRAYKC',
    routeAbbreviation: 'RRAYKC',
    startingGp: 'Karlakona',
    intermediateGps: ['Karlakona'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 15,
    workers: [{ name: 'BANGARI PEDENTI', contact: '-' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 15,
    routeId: 'RRAYK03',
    routeName: 'RRAYKB',
    routeAbbreviation: 'RRAYKB',
    startingGp: 'Karubai',
    intermediateGps: ['Karubai'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 10,
    workers: [{ name: 'BINADINI SARAKA', contact: '-' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 16,
    routeId: 'RRAYK04',
    routeName: 'RRAYKJ',
    routeAbbreviation: 'RRAYKJ',
    startingGp: 'Kereda',
    intermediateGps: ['Kereda'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 21,
    workers: [],
    scheduledOn: 'Scheduled'
  },
  {
    id: 17,
    routeId: 'RRAYK01',
    routeName: 'RRAYKB',
    routeAbbreviation: 'RRAYKB',
    startingGp: 'Kotapeta',
    intermediateGps: ['Kotapeta'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 6,
    workers: [{ name: 'K SARATI', contact: '6372079702' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 18,
    routeId: 'RRAYK02',
    routeName: 'RRAYKC',
    routeAbbreviation: 'RRAYKC',
    startingGp: 'Kuli',
    intermediateGps: ['Kuli'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 8,
    workers: [],
    scheduledOn: 'Scheduled'
  },
  {
    id: 19,
    routeId: 'RRAYK01',
    routeName: 'RRAYKK',
    routeAbbreviation: 'RRAYKK',
    startingGp: 'Kumatalpeta',
    intermediateGps: ['Kumatalpeta'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 6,
    workers: [{ name: 'KASTURI KILAKA', contact: '8249574614' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 20,
    routeId: 'RRAYJK05',
    routeName: 'RRAYKK',
    routeAbbreviation: 'RRAYKK',
    startingGp: 'Kumbhikota',
    intermediateGps: ['Kumbhikota'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 26,
    workers: [{ name: 'NIMALU JALMUTE', contact: '6370350872' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 21,
    routeId: 'RRAYK5',
    routeName: 'RRAYKK',
    routeAbbreviation: 'RRAYKK',
    startingGp: 'Kutuli',
    intermediateGps: ['Kutuli'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 30,
    workers: [{ name: 'SABITRI MAJHI', contact: '91399467' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 22,
    routeId: 'RRAYM02',
    routeName: 'RRAYMK',
    routeAbbreviation: 'RRAYMK',
    startingGp: 'Matikona',
    intermediateGps: ['Matikona'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 15,
    workers: [{ name: 'AMBIKA HIMIRIKA', contact: '-' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 23,
    routeId: 'RRAYM03',
    routeName: 'RRAYMD',
    routeAbbreviation: 'RRAYMD',
    startingGp: 'Mirabali',
    intermediateGps: ['Mirabali'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 25,
    workers: [{ name: 'MUNI PRASKA', contact: '9692063018' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 24,
    routeId: 'RRAYN05',
    routeName: 'RRAYNK',
    routeAbbreviation: 'RRAYNK',
    startingGp: 'Nakiti',
    intermediateGps: ['Nakiti'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 35,
    workers: [{ name: 'LAXMI BIDIKA', contact: '-' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 25,
    routeId: 'RRAYP01',
    routeName: 'RRAYPC',
    routeAbbreviation: 'RRAYPC',
    startingGp: 'Penta',
    intermediateGps: ['Penta'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 12,
    workers: [{ name: 'PULAKA HEMALATA', contact: '940207635' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 26,
    routeId: 'RRAYP01',
    routeName: 'RRAYPD',
    routeAbbreviation: 'RRAYPD',
    startingGp: 'Pipalguda',
    intermediateGps: ['Pipalguda'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 15,
    workers: [{ name: 'ARATI HIMIRIKA', contact: '8480831926' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 27,
    routeId: 'RRAYP04',
    routeName: 'RRAYPT',
    routeAbbreviation: 'RRAYPT',
    startingGp: 'Pitamahal',
    intermediateGps: ['Pitamahal'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 6,
    workers: [],
    scheduledOn: 'Scheduled'
  },
  {
    id: 28,
    routeId: 'RRAYT05',
    routeName: 'RRAYTH',
    routeAbbreviation: 'RRAYTH',
    startingGp: 'Tadama',
    intermediateGps: ['Tadama'],
    finalGp: 'TADAMA',
    destination: 'ANTARIGUDA',
    totalDistance: 7,
    workers: [{ name: 'SWAPANA GANTA', contact: '9861797914' }],
    scheduledOn: 'Scheduled'
  },

  // Block Gunupur (ULB Kothaluguda)
  {
    id: 29,
    routeId: 'RGUNT01',
    routeName: 'RGUNJTA',
    routeAbbreviation: 'RGUNJTA',
    startingGp: 'JALTAR',
    intermediateGps: ['TOLONA'],
    finalGp: 'ABADA',
    destination: 'Kothaluguda',
    totalDistance: 10,
    workers: [{ name: 'Meri Sabar', contact: '7606987791' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 30,
    routeId: 'RGUNP01',
    routeName: 'RGUNJPA',
    routeAbbreviation: 'RGUNJPA',
    startingGp: 'JALTAR',
    intermediateGps: ['PUTTASING'],
    finalGp: 'ABADA',
    destination: 'Kothaluguda',
    totalDistance: 7,
    workers: [{ name: 'Nanuma Pal', contact: '7978359352' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 31,
    routeId: 'RGUNS01',
    routeName: 'RGUNJSA',
    routeAbbreviation: 'RGUNJSA',
    startingGp: 'JALTAR',
    intermediateGps: ['SAGADA'],
    finalGp: 'ABADA',
    destination: 'Kothaluguda',
    totalDistance: 12,
    workers: [{ name: 'Abeni Karjee', contact: '7653921088' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 32,
    routeId: 'RGUNA01',
    routeName: 'RGUNJAA',
    routeAbbreviation: 'RGUNJAA',
    startingGp: 'JALTAR',
    intermediateGps: ['ABADA'],
    finalGp: 'ABADA',
    destination: 'Kothaluguda',
    totalDistance: 18,
    workers: [{ name: 'Sarajini Sabar', contact: '9348052416' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 33,
    routeId: 'RGUNJ01',
    routeName: 'RGUNJJA',
    routeAbbreviation: 'RGUNJJA',
    startingGp: 'JALTAR',
    intermediateGps: ['JALTAR'],
    finalGp: 'ABADA',
    destination: 'Kothaluguda',
    totalDistance: 14,
    workers: [{ name: 'Archana Lima', contact: '8249179724' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 34,
    routeId: 'RGUNC02',
    routeName: 'RGUNCDB',
    routeAbbreviation: 'RGUNCDB',
    startingGp: 'CHALAKAMBA',
    intermediateGps: ['DOMBASORA'],
    finalGp: 'BAGASALA',
    destination: 'Kothaluguda',
    totalDistance: 8,
    workers: [{ name: 'Phulabati Sabar', contact: '6370838341' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 35,
    routeId: 'RGUND02',
    routeName: 'RGUNCGB',
    routeAbbreviation: 'RGUNCGB',
    startingGp: 'CHALAKAMBA',
    intermediateGps: ['GHANANTRI'],
    finalGp: 'BAGASALA',
    destination: 'Kothaluguda',
    totalDistance: 7,
    workers: [{ name: 'Susila Bebarta', contact: '7681821312' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 36,
    routeId: 'RGUNG02',
    routeName: 'RGUNCBB',
    routeAbbreviation: 'RGUNCBB',
    startingGp: 'CHALAKAMBA',
    intermediateGps: ['BAGASALA'],
    finalGp: 'BAGASALA',
    destination: 'Kothaluguda',
    totalDistance: 12,
    workers: [{ name: 'Tilitama Sabar', contact: '6371877983' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 37,
    routeId: 'RGUNG02',
    routeName: 'RGUNCCB',
    routeAbbreviation: 'RGUNCCB',
    startingGp: 'CHALAKAMBA',
    intermediateGps: ['CHALAKAMBA'],
    finalGp: 'BAGASALA',
    destination: 'Kothaluguda',
    totalDistance: 11,
    workers: [{ name: 'Sarojinipani', contact: '8897566003' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 38,
    routeId: 'RGUNB03',
    routeName: 'RGUNBTT',
    routeAbbreviation: 'RGUNBTT',
    startingGp: 'BHIMPUR',
    intermediateGps: ['TITIMIRI'],
    finalGp: 'TITIMIRI',
    destination: 'Kothaluguda',
    totalDistance: 6,
    workers: [{ name: 'Josada Sabar', contact: '9827163390' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 39,
    routeId: 'RGUNT03',
    routeName: 'RGUNBBB',
    routeAbbreviation: 'RGUNBBB',
    startingGp: 'BHIMPUR',
    intermediateGps: ['BHIMPUR'],
    finalGp: 'BHIMPUR',
    destination: 'Kothaluguda',
    totalDistance: 4,
    workers: [{ name: 'Nista Lima', contact: '8249680903' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 40,
    routeId: 'RGUNG04',
    routeName: 'RGUNGR',
    routeAbbreviation: 'RGUNGR',
    startingGp: 'GADIAKHALA',
    intermediateGps: ['REGEDA'],
    finalGp: 'REGEDA',
    destination: 'Kothaluguda',
    totalDistance: 5,
    workers: [{ name: 'Pramila sabar', contact: '6370619829' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 41,
    routeId: 'RGUNR04',
    routeName: 'RGUNGR',
    routeAbbreviation: 'RGUNGR',
    startingGp: 'GADIAKHALA',
    intermediateGps: ['GADIAKHALA'],
    finalGp: 'GADIAKHALA',
    destination: 'Kothaluguda',
    totalDistance: 5,
    workers: [{ name: 'Lopinti Budama', contact: '8658155674' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 42,
    routeId: 'RGUNK05',
    routeName: 'RGUNCK',
    routeAbbreviation: 'RGUNCK',
    startingGp: 'CHINASARI',
    intermediateGps: ['KULUSING'],
    finalGp: 'KULUSING',
    destination: 'Kothaluguda',
    totalDistance: 15,
    workers: [{ name: 'Santi Sabar', contact: '7657080631' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 43,
    routeId: 'RGUNC05',
    routeName: 'RGUN',
    routeAbbreviation: 'RGUN',
    startingGp: 'CHINASARI',
    intermediateGps: ['CHINASARI'],
    finalGp: 'KULUSING',
    destination: 'Kothaluguda',
    totalDistance: 5,
    workers: [{ name: 'Sunita sabar', contact: '8480494451' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 44,
    routeId: 'RGUNJ06',
    routeName: 'RGUN',
    routeAbbreviation: 'RGUN',
    startingGp: 'SIRIJHOLLI',
    intermediateGps: ['JAGANNATHPUR'],
    finalGp: 'MORAMA',
    destination: 'Kothaluguda',
    totalDistance: 10,
    workers: [{ name: 'Santoshi Gomango', contact: '7854816993' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 45,
    routeId: 'RGUNG06',
    routeName: 'RGUN',
    routeAbbreviation: 'RGUN',
    startingGp: 'SIRIJHOLLI',
    intermediateGps: ['GOTHALAPADAR'],
    finalGp: 'MORAMA',
    destination: 'Kothaluguda',
    totalDistance: 14,
    workers: [{ name: 'Sudheshna Adhikari', contact: '9348004102' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 46,
    routeId: 'RGUNM06',
    routeName: 'RGUN',
    routeAbbreviation: 'RGUN',
    startingGp: 'SIRIJHOLLI',
    intermediateGps: ['MORAMA'],
    finalGp: 'MORAMA',
    destination: 'Kothaluguda',
    totalDistance: 18,
    workers: [{ name: 'Chitra Patika', contact: '8297746996' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 47,
    routeId: 'RGUNS06',
    routeName: 'RGUN',
    routeAbbreviation: 'RGUN',
    startingGp: 'SIRIJHOLLI',
    intermediateGps: ['SIRIJHOLI'],
    finalGp: 'MORAMA',
    destination: 'Kothaluguda',
    totalDistance: 4,
    workers: [{ name: 'Nirupama Choudhury', contact: '9438686062' }],
    scheduledOn: 'Scheduled'
  },

  // Block GUDARI (ULB GUDARI NAC)
  {
    id: 48,
    routeId: 'RGUDASK01',
    routeName: 'RGUDAASK01',
    routeAbbreviation: 'RGUDAASK01',
    startingGp: 'ASADA',
    intermediateGps: ['SIRIGUDA'],
    finalGp: 'KODAMA',
    destination: 'GUDARI NAC',
    totalDistance: 21,
    workers: [{ name: 'ANNAPURNA NISAL', contact: '9040070919' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 49,
    routeId: 'RGUDAMS01',
    routeName: 'RGUDAAMS01',
    routeAbbreviation: 'RGUDAAMS01',
    startingGp: 'ASADA',
    intermediateGps: ['M.K.RAI'],
    finalGp: 'SANAHUMA',
    destination: 'GUDARI NAC',
    totalDistance: 11,
    workers: [{ name: 'ANNAPURNA NISAL', contact: '9040070919' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 50,
    routeId: 'RGUDAMM01',
    routeName: 'RGUDAAMM01',
    routeAbbreviation: 'RGUDAAMM01',
    startingGp: 'ASADA',
    intermediateGps: ['M.K.RAI'],
    finalGp: 'M.K.RAI',
    destination: 'GUDARI NAC',
    totalDistance: 10,
    workers: [{ name: 'ANNAPURNA NISAL', contact: '9040070919' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 51,
    routeId: 'RGUDAMPK02',
    routeName: 'RGUDAMKP02',
    routeAbbreviation: 'RGUDAMKP02',
    startingGp: 'MADHUBAN',
    intermediateGps: ['KHARIGUDA'],
    finalGp: 'PENDILI',
    destination: 'GUDARI NAC',
    totalDistance: 28,
    workers: [{ name: 'KAMALA SABAR', contact: '7855853168' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 52,
    routeId: 'RGUDAMPK02',
    routeName: 'RGUDAMKP02',
    routeAbbreviation: 'RGUDAMKP02',
    startingGp: 'MADHUBAN',
    intermediateGps: ['PENDILI'],
    finalGp: 'KARLAGHATI',
    destination: 'GUDARI NAC',
    totalDistance: 50,
    workers: [{ name: 'KAMALA SABAR', contact: '7855853168' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 53,
    routeId: 'RGUDAMSS03',
    routeName: 'RGUDAMSS03',
    routeAbbreviation: 'RGUDAMSS03',
    startingGp: 'M.K.RAI',
    intermediateGps: ['SANAHUMA'],
    finalGp: 'SANAHUMA',
    destination: 'GUDARI NAC',
    totalDistance: 12,
    workers: [{ name: 'HELENA PALAKA', contact: '8637291054' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 54,
    routeId: 'RGUDASKM04',
    routeName: 'RGUDASKM04',
    routeAbbreviation: 'RGUDASKM04',
    startingGp: 'SIRIGUDA',
    intermediateGps: ['KODAMA'],
    finalGp: 'M.K.RAI',
    destination: 'GUDARI NAC',
    totalDistance: 18,
    workers: [{ name: 'UDHABARI KANDAGARI', contact: '9827685159' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 55,
    routeId: 'RGUDASMM05',
    routeName: 'RGUDASMM05',
    routeAbbreviation: 'RGUDASMM05',
    startingGp: 'SANAHUMA',
    intermediateGps: ['M.K.RAI'],
    finalGp: 'MADHUBAN',
    destination: 'GUDARI NAC',
    totalDistance: 16,
    workers: [{ name: 'RAMADEI SABAR', contact: '7854874775' }],
    scheduledOn: 'Scheduled'
  },
  {
    id: 56,
    routeId: 'RGUDAKPM06',
    routeName: 'RGUDAKPM06',
    routeAbbreviation: 'RGUDAKPM06',
    startingGp: 'KHARIGUDA',
    intermediateGps: ['PENDILI'],
    finalGp: 'MADHUBAN',
    destination: 'GUDARI NAC',
    totalDistance: 23,
    workers: [{ name: 'MALI SABAR', contact: '9861070632' }],
    scheduledOn: 'Scheduled'
  }
];
