export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // Jajpur Block (Jajpur Municipality) - Kodandapur MRF
  { id: 1, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'PANASA', wasteGeneratedKg: 202.82, gpNodalPerson: 'Sidheswar Maharana', gpNodalContact: '9437385986', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 2, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'CHAINIPUR', wasteGeneratedKg: 84.32, gpNodalPerson: 'Rama Chandra Rana', gpNodalContact: '9439948854', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 3, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'MALANDAPUR', wasteGeneratedKg: 269.88, gpNodalPerson: 'Rama Chandra Rana', gpNodalContact: '9439948854', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 4, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'NATHASAHI', wasteGeneratedKg: 181.58, gpNodalPerson: 'Manoj Kumar Malik', gpNodalContact: '9937781378', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 5, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'BHUBANESWARPUR', wasteGeneratedKg: 132.23, gpNodalPerson: 'Chandrasekhar Jena', gpNodalContact: '9853867340', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 6, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'JAFARPUR', wasteGeneratedKg: 150.26, gpNodalPerson: 'Bijay Kumar Mallk', gpNodalContact: '7008708485', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 7, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'SIMILIA', wasteGeneratedKg: 252.17, gpNodalPerson: 'Gobinda Gopal Gadadhar Mohanty', gpNodalContact: '9337340150', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 8, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'BERUDA', wasteGeneratedKg: 153.69, gpNodalPerson: 'Amulya Kumar Sahoo', gpNodalContact: '9090050366', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 9, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'BHUINPUR', wasteGeneratedKg: 158.89, gpNodalPerson: 'Chandrasekhar Jena', gpNodalContact: '9853867340', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 10, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'KHAIRABAD', wasteGeneratedKg: 146.72, gpNodalPerson: 'Gobinda Gopal Gadadhar Mohanty', gpNodalContact: '9337340150', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 11, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Shyamadaspur', wasteGeneratedKg: 104.23, gpNodalPerson: 'Sunil Kumar Behera', gpNodalContact: '9090186510', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 12, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'ERBANK', wasteGeneratedKg: 129.68, gpNodalPerson: 'Sidheswar Maharana', gpNodalContact: '9437385986', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 13, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'SUJANPUR', wasteGeneratedKg: 204.37, gpNodalPerson: 'Sudhir Ku Mohanty', gpNodalContact: '7978026421', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 14, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'SAHASPUR', wasteGeneratedKg: 171.84, gpNodalPerson: 'Sudhir Ku Mohanty', gpNodalContact: '7978026421', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 15, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Kodandapur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'CHHATISDEVIL', wasteGeneratedKg: 177.37, gpNodalPerson: 'Abhay Kumar Dash', gpNodalContact: '7008027431', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },

  // Jajpur Block (Jajpur Municipality) - Jageswarpur MRF
  { id: 16, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Jageswarpur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'BICHITRAPUR', wasteGeneratedKg: 209.79, gpNodalPerson: 'Sasmita Panda', gpNodalContact: '7978386914', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 17, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Jageswarpur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'JAHANPUR', wasteGeneratedKg: 167.19, gpNodalPerson: 'Anjana Giri', gpNodalContact: '6370671667', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 18, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Jageswarpur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'BASUDEVPUR', wasteGeneratedKg: 152.25, gpNodalPerson: 'Abhay Kumar Dash', gpNodalContact: '7008027431', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 19, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Jageswarpur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'MARKANDAPUR', wasteGeneratedKg: 184.79, gpNodalPerson: 'Bijay Kumar Mallk', gpNodalContact: '7008708485', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 20, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Jageswarpur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Sanasuar', wasteGeneratedKg: 181.13, gpNodalPerson: 'Sitarani Soren', gpNodalContact: '8763038087', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 21, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Jageswarpur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'BADASUAR', wasteGeneratedKg: 129.02, gpNodalPerson: 'Chandramani Deogam', gpNodalContact: '8637241471', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 22, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Jageswarpur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'MAHESWARPUR', wasteGeneratedKg: 214.11, gpNodalPerson: 'Laxmaikanta Jena', gpNodalContact: '9778578513', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 23, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Jageswarpur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'UPARBARUHAN', wasteGeneratedKg: 151.04, gpNodalPerson: 'Laxmaikanta Jena', gpNodalContact: '9778578513', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 24, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Jageswarpur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'JAMDHAR', wasteGeneratedKg: 169.18, gpNodalPerson: 'Manorama Sahoo', gpNodalContact: '7735118599', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 25, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Jageswarpur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'JHALPADA', wasteGeneratedKg: 177.26, gpNodalPerson: 'Jaylaxmi Swain', gpNodalContact: '7978879723', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },
  { id: 26, block: 'Jajpur', ulb: 'Jajpur Municipality', mrf: 'Jageswarpur', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'RUDRAPUR', wasteGeneratedKg: 99.70, gpNodalPerson: 'Jaylaxmi Swain', gpNodalContact: '7978879723', ulbNodalPerson: 'Debasish Bhuyan', ulbNodalContact: '8018696757' },

  // Korei Block (Vysanagar Municipality) - Jodabara MRF
  { id: 27, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'MULAPAL', wasteGeneratedKg: 135.55, gpNodalPerson: 'Sri Satya Narayan Jena', gpNodalContact: '8249444949', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 28, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KARADA', wasteGeneratedKg: 181.13, gpNodalPerson: 'Sri Prasanta Kumar Mohapatra', gpNodalContact: '6371879562', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 29, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'PATHARAPADA', wasteGeneratedKg: 132.67, gpNodalPerson: 'Miss Swapna Sahoo', gpNodalContact: '7735961209', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 30, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'PANIKOILI', wasteGeneratedKg: 129.68, gpNodalPerson: 'Miss Rasmirekha Sahoo', gpNodalContact: '9776241350', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 31, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'GOLEIPUR', wasteGeneratedKg: 154.14, gpNodalPerson: 'Sri Manmohan Sahoo', gpNodalContact: '7978836682', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 32, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'AMRUTIA', wasteGeneratedKg: 125.15, gpNodalPerson: 'Sri Satya Ranjan Behuria', gpNodalContact: '9040552992', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 33, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'BANDALO', wasteGeneratedKg: 141.85, gpNodalPerson: 'Sri Sudarsan Sahoo', gpNodalContact: '6372088598', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 34, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'MAKANDAPUR', wasteGeneratedKg: 134.22, gpNodalPerson: 'Sri Santosh Kumar Mishra', gpNodalContact: '9078021771', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 35, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'BARUNDEI', wasteGeneratedKg: 89.74, gpNodalPerson: 'Sri Sudarsan Sahoo', gpNodalContact: '6372088598', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 36, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'TARAKOT', wasteGeneratedKg: 78.45, gpNodalPerson: 'Sri Adityanarayan Nayak', gpNodalContact: '7008697914', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 37, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'GOURAPUR', wasteGeneratedKg: 143.51, gpNodalPerson: 'Sri Kalpanath Dhir', gpNodalContact: '8895544207', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 38, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'RANAPUR', wasteGeneratedKg: 70.26, gpNodalPerson: 'Sri Debashis Moharana', gpNodalContact: '9437596673', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 39, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'ASANJHAR', wasteGeneratedKg: 81.77, gpNodalPerson: 'Smt. Snigdha Sahoo', gpNodalContact: '7978050342', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 40, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'KACHARASAHI', wasteGeneratedKg: 89.07, gpNodalPerson: 'Sri Prafulla Kumar Nath', gpNodalContact: '9861222374', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 41, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'PACHHIKOTE', wasteGeneratedKg: 182.90, gpNodalPerson: 'Sri Rabindranath Rout', gpNodalContact: '7008922260', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 42, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'JANHA', wasteGeneratedKg: 199.72, gpNodalPerson: 'Sri Padmanava Majhi', gpNodalContact: '8249563760', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 43, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'KHAMAN', wasteGeneratedKg: 139.20, gpNodalPerson: 'Sri Nirmala Chandra Panda', gpNodalContact: '9937728685', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 44, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'TANDARA', wasteGeneratedKg: 48.58, gpNodalPerson: 'Sri Debashis Moharana', gpNodalContact: '9437596673', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 45, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Jodabara', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'BADABIRUHAN', wasteGeneratedKg: 129.13, gpNodalPerson: 'Sri Ramesh Chandra Rana', gpNodalContact: '9938629217', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },

  // Korei Block (Vysanagar Municipality) - Chandama MRF
  { id: 46, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Chandama', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'DHANESWAR', wasteGeneratedKg: 221.85, gpNodalPerson: 'Sri Padmanava Majhi', gpNodalContact: '8249563760', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 47, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Chandama', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'SADAKPUR', wasteGeneratedKg: 203.49, gpNodalPerson: 'Sri Ramesh Chandra Rana', gpNodalContact: '9938629217', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 48, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Chandama', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'HALADIGADIA', wasteGeneratedKg: 25.34, gpNodalPerson: 'Sri Nirmala Chandra Panda', gpNodalContact: '9937728685', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 49, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Chandama', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'TULATI', wasteGeneratedKg: 132.34, gpNodalPerson: 'Miss Rasmirekha Sahoo', gpNodalContact: '9776241350', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 50, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Chandama', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'KANTORE', wasteGeneratedKg: 125.92, gpNodalPerson: 'Sri Satya Narayan Jena', gpNodalContact: '8249444949', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 51, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Chandama', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20th of each Month', gpName: 'TAHARPUR', wasteGeneratedKg: 163.76, gpNodalPerson: 'Sri Manoranjan Samal', gpNodalContact: '9438581723', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 52, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Chandama', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20th of each Month', gpName: 'TALAGARH', wasteGeneratedKg: 116.74, gpNodalPerson: 'Sri Manmohan Sahoo', gpNodalContact: '7978836682', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 53, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Chandama', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20th of each Month', gpName: 'PATARANGA', wasteGeneratedKg: 97.70, gpNodalPerson: 'Sri Satya Narayan Jena', gpNodalContact: '8249444949', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
  { id: 54, block: 'Korei', ulb: 'Vysanagar Municipality', mrf: 'Chandama', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20th of each Month', gpName: 'ANDHARI', wasteGeneratedKg: 102.35, gpNodalPerson: 'Sri Santosh Kumar Mishra', gpNodalContact: '9078021771', ulbNodalPerson: 'Ruchismita Puhan', ulbNodalContact: '7008694460' },
];
