export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // Dhenkanal Sadar Block
  { id: 1, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF1 Kathagada', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'BALADIABANDHA', wasteGeneratedKg: 144.53, gpNodalPerson: 'Stiti Sethy', gpNodalContact: '7978848553', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 2, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF1 Kathagada', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'GOBINDPUR', wasteGeneratedKg: 121.90, gpNodalPerson: 'Shyam Sundar Marandi', gpNodalContact: '8260559847', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 3, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF1 Kathagada', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'MANIPUR', wasteGeneratedKg: 86.09, gpNodalPerson: 'Narottam Sahoo', gpNodalContact: '8249177712', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 4, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF1 Kathagada', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'NADIALI', wasteGeneratedKg: 121.70, gpNodalPerson: 'Bishnu Priya Jena', gpNodalContact: '6371613883', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 5, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF1 Kathagada', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'TALABARKOTE', wasteGeneratedKg: 195.12, gpNodalPerson: 'Anil Kumar Sahoo', gpNodalContact: '8328842871', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 6, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Barada', wasteGeneratedKg: 139.40, gpNodalPerson: 'Trinath Sethy', gpNodalContact: '9938493144', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 7, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Gengutia', wasteGeneratedKg: 149.76, gpNodalPerson: 'Stiti Sethy', gpNodalContact: '7978848553', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 8, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Sankulei', wasteGeneratedKg: 125.32, gpNodalPerson: 'Anuradha Nahak', gpNodalContact: '7978294028', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 9, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Tarava', wasteGeneratedKg: 99.27, gpNodalPerson: 'Gayatri Pany', gpNodalContact: '7735169759', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 10, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Banasing', wasteGeneratedKg: 256.27, gpNodalPerson: 'Samir Ranjan Dehury', gpNodalContact: '7978106781', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 11, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Chaulia', wasteGeneratedKg: 144.33, gpNodalPerson: 'Sasadhar Samal', gpNodalContact: '7978015822', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 12, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Sogarpasi', wasteGeneratedKg: 150.76, gpNodalPerson: 'Sasadhar Samal', gpNodalContact: '7978015822', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 13, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Radhadeipur', wasteGeneratedKg: 53.91, gpNodalPerson: 'Samir Ranjan Dehury', gpNodalContact: '7978106781', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 14, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Nuagaon', wasteGeneratedKg: 78.45, gpNodalPerson: 'Gayachand Dash', gpNodalContact: '9777593749', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 15, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'Kankadpal', wasteGeneratedKg: 131.35, gpNodalPerson: 'Manas Ranjan Dwibedy', gpNodalContact: '9437852791', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 16, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: ' Suakhaikateni', wasteGeneratedKg: 135.38, gpNodalPerson: 'Dhaneswar Khamari', gpNodalContact: '9777222092', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 17, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'Kaimati', wasteGeneratedKg: 133.97, gpNodalPerson: 'Swarnaprava Sahoo', gpNodalContact: '6370127471', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 18, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'Beltikiri', wasteGeneratedKg: 182.04, gpNodalPerson: 'Hemalata Nayak', gpNodalContact: '8328842871', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 19, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF4 Alasuahata caltex', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'Nagiapasi', wasteGeneratedKg: 149.66, gpNodalPerson: 'Shyam Sundar Marandi', gpNodalContact: '8260559847', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 20, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF2 Mahisapat', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20th of each Month', gpName: 'Kankadahad', wasteGeneratedKg: 372.95, gpNodalPerson: 'Narottam Sahoo', gpNodalContact: '8249177712', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 21, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF2 Mahisapat', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20th of each Month', gpName: 'Mangalpur', wasteGeneratedKg: 105.91, gpNodalPerson: 'Anuradha Nahak', gpNodalContact: '7978294028', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 22, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF2 Mahisapat', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20th of each Month', gpName: 'BB Kateni', wasteGeneratedKg: 515.97, gpNodalPerson: 'Anil Kumar Sahoo', gpNodalContact: '9937643183', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 23, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF2 Mahisapat', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20th of each Month', gpName: 'Kakudibhag', wasteGeneratedKg: 133.26, gpNodalPerson: 'Ranjan Sahoo', gpNodalContact: '7008193912', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 24, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF2 Mahisapat', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20th of each Month', gpName: 'Madhu Sahu patna', wasteGeneratedKg: 147.34, gpNodalPerson: 'Dhaneswar Khamari', gpNodalContact: '9777222092', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 25, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF2 Mahisapat', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'Bhapur', wasteGeneratedKg: 246.82, gpNodalPerson: 'Sandip Sahoo', gpNodalContact: '8455945088', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 26, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF2 Mahisapat', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'C S Prasad', wasteGeneratedKg: 144.73, gpNodalPerson: 'Dhaneswar Khamari', gpNodalContact: '9777222092', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 27, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF2 Mahisapat', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'Baliamba', wasteGeneratedKg: 100.07, gpNodalPerson: 'Dilip Dehury', gpNodalContact: '8249690067', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 28, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF2 Mahisapat', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'Dhirapatna', wasteGeneratedKg: 101.08, gpNodalPerson: 'Dilip Dehury', gpNodalContact: '8249690067', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 29, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF2 Mahisapat', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'Sankarpur', wasteGeneratedKg: 432.39, gpNodalPerson: 'Sandip Sahoo', gpNodalContact: '8455945088', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  { id: 30, block: 'Dhenkanal Sadar', ulb: 'DHENKANAL MUNICIPALITY', mrf: 'MRF2 Mahisapat', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'Saptasajya', wasteGeneratedKg: 142.32, gpNodalPerson: 'Gayatri Pany', gpNodalContact: '7735169759', ulbNodalPerson: 'Soubhagya Ranjan Mallick & Sasmita Ojha', ulbNodalContact: '8018462560, 8249353630' },
  // Bhuban Block
  { id: 31, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Balibo', wasteGeneratedKg: 192.51, gpNodalPerson: 'Asutosh Nayak', gpNodalContact: '7873912018', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 32, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Ektali', wasteGeneratedKg: 156.10, gpNodalPerson: 'Raja Behera', gpNodalContact: '8658986761', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 33, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Mahulpal', wasteGeneratedKg: 160.12, gpNodalPerson: 'Krushna Chandra Sahoo', gpNodalContact: '9439140200', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 34, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Mrudanga', wasteGeneratedKg: 100.78, gpNodalPerson: 'Krushna Chandra Sahoo', gpNodalContact: '9439140200', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 35, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Bhusal', wasteGeneratedKg: 222.18, gpNodalPerson: 'Chinmaya Kumar Behera', gpNodalContact: '8280305564', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 36, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Kuninda', wasteGeneratedKg: 990.71, gpNodalPerson: 'Raja Behera', gpNodalContact: '8658986761', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 37, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Dhalapada', wasteGeneratedKg: 106.21, gpNodalPerson: 'Malha Tudu', gpNodalContact: '7735709443', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 38, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Baruan', wasteGeneratedKg: 154.39, gpNodalPerson: 'Urmila Behera', gpNodalContact: '8018614644', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 39, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Odisha', wasteGeneratedKg: 899.18, gpNodalPerson: 'PankajLochan Mahalik', gpNodalContact: '6370069070', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 40, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'GN Prasad', wasteGeneratedKg: 130.04, gpNodalPerson: 'Saraswati Behera', gpNodalContact: '7750840877', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 41, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Dayanabilli', wasteGeneratedKg: 923.32, gpNodalPerson: 'Binod Kumar Behera', gpNodalContact: '7326823097', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 42, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Surapratappur', wasteGeneratedKg: 219.66, gpNodalPerson: 'Barsha Marandi', gpNodalContact: '9178787540', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 43, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Jamunakote', wasteGeneratedKg: 880.07, gpNodalPerson: 'PankajLochan Mahalik', gpNodalContact: '6370069070', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 44, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Marthapur', wasteGeneratedKg: 228.71, gpNodalPerson: 'Pritesh Moharana', gpNodalContact: '8249617121', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 45, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Dighi', wasteGeneratedKg: 142.92, gpNodalPerson: 'Madan Mohan Mohanty', gpNodalContact: '-', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 46, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Jiral', wasteGeneratedKg: 125.42, gpNodalPerson: 'Madan Mohan Mohanty', gpNodalContact: '9078832239', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 47, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Arakhapal', wasteGeneratedKg: 119.69, gpNodalPerson: 'Pritam Kumar roul', gpNodalContact: '7749872656', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  { id: 48, block: 'Bhuban', ulb: 'BHUBAN NAC', mrf: 'MRF1KOLHASAHI', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Mathakaragola', wasteGeneratedKg: 162.73, gpNodalPerson: 'Binod Kumar Behera', gpNodalContact: '7326823097', ulbNodalPerson: 'Jyoti Ranjan Behera', ulbNodalContact: '8144276732' },
  // Hindol Block
  { id: 49, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Nuabaga', wasteGeneratedKg: 141.31, gpNodalPerson: 'Subhranshu Jena', gpNodalContact: '8144390626', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 50, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Madhapur', wasteGeneratedKg: 875.04, gpNodalPerson: 'Swayandipta Sahoo', gpNodalContact: '7978618567', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 51, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Rasol', wasteGeneratedKg: 258.59, gpNodalPerson: 'Chandrasekhar Mohanty ', gpNodalContact: '9438439461', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 52, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Jarada', wasteGeneratedKg: 125.52, gpNodalPerson: 'Manoj Bhoi', gpNodalContact: '8249288466', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 53, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Kalinga', wasteGeneratedKg: 694.00, gpNodalPerson: 'Chandrasekhar Mohanty ', gpNodalContact: '9438439461', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 54, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Chitalpur', wasteGeneratedKg: 109.73, gpNodalPerson: 'Laxmi Naik', gpNodalContact: '9437656670', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 55, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Dudurkote', wasteGeneratedKg: 197.84, gpNodalPerson: 'Benudhar Pattnayak', gpNodalContact: '8249264646', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 56, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Gulehi', wasteGeneratedKg: 106.81, gpNodalPerson: 'Biswabhusan Nayak', gpNodalContact: '8763026263', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 57, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Mahalunda', wasteGeneratedKg: 322.56, gpNodalPerson: 'Sourabha Ranjan Panda', gpNodalContact: '7683815946', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 58, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Hatura', wasteGeneratedKg: 480.37, gpNodalPerson: 'Benudhar Pattnayak', gpNodalContact: '8249264646', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 59, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Patala', wasteGeneratedKg: 392.26, gpNodalPerson: 'Ranjan Sethy', gpNodalContact: '7751954111', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 60, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Asarada', wasteGeneratedKg: 796.59, gpNodalPerson: 'Babuli ch Rout', gpNodalContact: '9938893240', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 61, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Ranjagola', wasteGeneratedKg: 798.60, gpNodalPerson: 'Sudarshan Behera', gpNodalContact: '9937178884', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 62, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Kukuta', wasteGeneratedKg: 731.21, gpNodalPerson: 'Laxmi Naik', gpNodalContact: '9437656670', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 63, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Thokar', wasteGeneratedKg: 975.62, gpNodalPerson: 'Sudarshan Behera', gpNodalContact: '9937178884', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 64, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Kantimili', wasteGeneratedKg: 144.93, gpNodalPerson: 'Sourabha Ranjan Panda', gpNodalContact: '7683815946', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 65, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Kadala', wasteGeneratedKg: 701.04, gpNodalPerson: 'Biswabhusan Nayak', gpNodalContact: '8763026263', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 66, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'Karanda', wasteGeneratedKg: 157.70, gpNodalPerson: 'Sujit Naik', gpNodalContact: '7008782091', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 67, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'Babandha', wasteGeneratedKg: 174.80, gpNodalPerson: 'Annada Prasad Mishra', gpNodalContact: '9861989798', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 68, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF2', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'Giridharprasad', wasteGeneratedKg: 179.93, gpNodalPerson: 'Ranjan Sethy', gpNodalContact: '7751954111', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 69, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'Bampa', wasteGeneratedKg: 996.74, gpNodalPerson: 'Sujit Naik', gpNodalContact: '7008782091', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 70, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '5th & 19th of each Month', gpName: 'Kutunia', wasteGeneratedKg: 819.72, gpNodalPerson: 'Annada Prasad Mishra', gpNodalContact: '9861989798', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 71, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20st of each Month', gpName: 'Nuagaon', wasteGeneratedKg: 109.43, gpNodalPerson: 'Pritam Kumar  Dhir', gpNodalContact: '9827694988', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 72, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20st of each Month', gpName: 'Paikapurunakote', wasteGeneratedKg: 775.47, gpNodalPerson: 'Bikash  Chandra Samal', gpNodalContact: '7684867733', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 73, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20st of each Month', gpName: 'Sanjapada', wasteGeneratedKg: 110.93, gpNodalPerson: 'Pritam Kumar  Dhir', gpNodalContact: '9827694988', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 74, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20st of each Month', gpName: 'Galapada', wasteGeneratedKg: 193.91, gpNodalPerson: 'Bikash chandar Samal ', gpNodalContact: '7684867733', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 75, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20st of each Month', gpName: 'Kansara', wasteGeneratedKg: 976.63, gpNodalPerson: 'Kedar Mallik', gpNodalContact: '7894862148', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 76, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20st of each Month', gpName: 'Kantamila', wasteGeneratedKg: 111.44, gpNodalPerson: 'Antaryami Gochhayat', gpNodalContact: '9348240389', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 77, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '6th & 20st of each Month', gpName: 'Baunsapokhari', wasteGeneratedKg: 118.48, gpNodalPerson: 'Anita Swain', gpNodalContact: '7008094936', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 78, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'Kunua', wasteGeneratedKg: 972.60, gpNodalPerson: 'Dinabandhu Behera', gpNodalContact: '9853701816', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 79, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'Buhalipal', wasteGeneratedKg: 105.30, gpNodalPerson: 'Dinabandhu Behera', gpNodalContact: '9853701816', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 80, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'Gandanali', wasteGeneratedKg: 104.50, gpNodalPerson: 'Santosh Sethy', gpNodalContact: '9777503900', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 81, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'Khaliborei', wasteGeneratedKg: 771.44, gpNodalPerson: 'Santosh Sethy', gpNodalContact: '9777503900', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 82, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'Nabakishorepur', wasteGeneratedKg: 889.12, gpNodalPerson: 'Akhila ku Sahoo', gpNodalContact: '9437729706', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  { id: 83, block: 'HINDOL', ulb: 'HINDOL NAC', mrf: 'MRF1', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '7th & 21st of each Month', gpName: 'Dandiri', wasteGeneratedKg: 849.90, gpNodalPerson: 'Swayandipta Sahoo', gpNodalContact: '7978618567', ulbNodalPerson: 'Rashmiranjan Biswal', ulbNodalContact: '7008513297' },
  // Kamakhyanagar Block
  { id: 84, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Baisinga', wasteGeneratedKg: 120.09, gpNodalPerson: 'Swarnaprava Biswal', gpNodalContact: '6371742884', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 85, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Baligorad', wasteGeneratedKg: 171.28, gpNodalPerson: 'Mukesh Kumar sardar', gpNodalContact: '8763876005', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 86, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Badasuanlo', wasteGeneratedKg: 163.41, gpNodalPerson: 'Ranjan Kumar Dehury', gpNodalContact: '8917505894', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 87, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Jagannathpur', wasteGeneratedKg: 123.91, gpNodalPerson: 'Amarendra Bhoi', gpNodalContact: '9348743015', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 88, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Bankual', wasteGeneratedKg: 143.82, gpNodalPerson: 'Amarendra Bhoi', gpNodalContact: '9348743015', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 89, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Budhibilli', wasteGeneratedKg: 174.10, gpNodalPerson: 'Gobardhan Sahoo', gpNodalContact: '9776883198', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 90, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Bhairpur', wasteGeneratedKg: 166.66, gpNodalPerson: 'Satyanarayan Pradhan', gpNodalContact: '9437300540', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 91, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '2nd & 16th of each Month', gpName: 'Saruali', wasteGeneratedKg: 128.84, gpNodalPerson: 'Pritisagar Nayak', gpNodalContact: '9938000309', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 92, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Kanpura', wasteGeneratedKg: 771.44, gpNodalPerson: 'Gitanjali Soren', gpNodalContact: '9438009242', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 93, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Baunsapal', wasteGeneratedKg: 108.22, gpNodalPerson: 'Mukesh Kumar sardar', gpNodalContact: '8763876005', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 94, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Kadua', wasteGeneratedKg: 750.32, gpNodalPerson: 'Prajyojit Biswal', gpNodalContact: '7606949104', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 95, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Mahulpala', wasteGeneratedKg: 145.63, gpNodalPerson: 'Abhilas Mohanty', gpNodalContact: '9078315097', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 96, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Anlabereni', wasteGeneratedKg: 202.16, gpNodalPerson: 'Deepak Singh', gpNodalContact: '9556173133', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 97, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Kusumjodi', wasteGeneratedKg: 137.19, gpNodalPerson: 'Bikash Behera', gpNodalContact: '8456848744', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 98, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'Kotagara', wasteGeneratedKg: 130.35, gpNodalPerson: 'susant kumar Swain', gpNodalContact: '9439186671', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 99, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '3rd & 17th of each Month', gpName: 'R N Pur', wasteGeneratedKg: 133.87, gpNodalPerson: 'susant kumar Swain', gpNodalContact: '9439186671', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 100, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Tumusinga', wasteGeneratedKg: 127.93, gpNodalPerson: 'Madhab Chandra pradhan', gpNodalContact: '9937680924', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 101, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Kantapal', wasteGeneratedKg: 793.37, gpNodalPerson: 'Aniruddha Rout', gpNodalContact: '9556214585', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 102, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Kantio Kateni', wasteGeneratedKg: 953.49, gpNodalPerson: 'Prajna Pranjali Panda', gpNodalContact: '8598823177', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 103, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: ' Kantioputa sahi', wasteGeneratedKg: 892.14, gpNodalPerson: 'Prafulla Kumar Senapati', gpNodalContact: '8917215679', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 104, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Sogar', wasteGeneratedKg: 217.65, gpNodalPerson: 'Pritisagar Nayak', gpNodalContact: '9938000309', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' },
  { id: 105, block: 'KAMAKHYANAGAR', ulb: 'KAMAKHYANAGAR NAC', mrf: 'MRF', vehicleType: 'Tata ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '4th & 18th of each Month', gpName: 'Baruan', wasteGeneratedKg: 111.11, gpNodalPerson: 'Gobardhan Sahoo', gpNodalContact: '9776883198', ulbNodalPerson: 'Amar jyotisilakkumar Aich', ulbNodalContact: '8456828305' }
];
