export interface GpMappingData {
  id: number;
  block: string;
  gpName: string;
  taggedUlb: string;
  taggedMrf: string;
}

export const gpMappingData: GpMappingData[] = [
  // Block Dhenkanal Sadar
  { id: 1, block: 'Dhenkanal Sadar', gpName: 'BALADIABANDHA', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF1 Kathagada' },
  { id: 2, block: 'Dhenkanal Sadar', gpName: 'GOBINDPUR', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF1 Kathagada' },
  { id: 3, block: 'Dhenkanal Sadar', gpName: 'MANIPUR', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF1 Kathagada' },
  { id: 4, block: 'Dhenkanal Sadar', gpName: 'NADIALI', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF1 Kathagada' },
  { id: 5, block: 'Dhenkanal Sadar', gpName: 'TALABARKOTE', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF1 Kathagada' },
  { id: 6, block: 'Dhenkanal Sadar', gpName: 'BALIAMBA', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF2 Mahisapat' },
  { id: 7, block: 'Dhenkanal Sadar', gpName: 'C.S.PRASAD', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF2 Mahisapat' },
  { id: 8, block: 'Dhenkanal Sadar', gpName: 'DHIRAPATANA', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF2 Mahisapat' },
  { id: 9, block: 'Dhenkanal Sadar', gpName: 'KAKUDIBHAGA', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF2 Mahisapat' },
  { id: 10, block: 'Dhenkanal Sadar', gpName: 'KANKADAHAD', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF2 Mahisapat' },
  { id: 11, block: 'Dhenkanal Sadar', gpName: 'MADHUSAHUPATANA', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF2 Mahisapat' },
  { id: 12, block: 'Dhenkanal Sadar', gpName: 'MANGALPUR', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF2 Mahisapat' },
  { id: 13, block: 'Dhenkanal Sadar', gpName: 'SANKARPUR', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF2 Mahisapat' },
  { id: 14, block: 'Dhenkanal Sadar', gpName: 'SAPTASAJYA', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF2 Mahisapat' },
  { id: 15, block: 'Dhenkanal Sadar', gpName: 'SUAKHAIKATENI', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF2 Mahisapat' },
  { id: 16, block: 'Dhenkanal Sadar', gpName: 'BANASINGH', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 17, block: 'Dhenkanal Sadar', gpName: 'BARADA', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 18, block: 'Dhenkanal Sadar', gpName: 'BELTIKIRI', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 19, block: 'Dhenkanal Sadar', gpName: 'BHALIABOLAKATENI', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 20, block: 'Dhenkanal Sadar', gpName: 'BHAPUR', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 21, block: 'Dhenkanal Sadar', gpName: 'CHAULIA', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 22, block: 'Dhenkanal Sadar', gpName: 'GENGUTIA', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 23, block: 'Dhenkanal Sadar', gpName: 'KAIMATI', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 24, block: 'Dhenkanal Sadar', gpName: 'KANKADAPAL', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 25, block: 'Dhenkanal Sadar', gpName: 'NAGIAPASI', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 26, block: 'Dhenkanal Sadar', gpName: 'NUAGAON', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 27, block: 'Dhenkanal Sadar', gpName: 'RADHADEIPUR', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 28, block: 'Dhenkanal Sadar', gpName: 'SANKULEI', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 29, block: 'Dhenkanal Sadar', gpName: 'SOGARPASI', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },
  { id: 30, block: 'Dhenkanal Sadar', gpName: 'TARAVA', taggedUlb: 'DHENKANAL MUNICIPALITY', taggedMrf: 'MRF4 Alasuahata caltex' },

  // Block Bhuban
  { id: 31, block: 'Bhuban', gpName: 'BHUSAL', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 32, block: 'Bhuban', gpName: 'KUNINDA', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 33, block: 'Bhuban', gpName: 'GN PRASAD', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 34, block: 'Bhuban', gpName: 'BARUAN', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 35, block: 'Bhuban', gpName: 'DAYANABILI', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 36, block: 'Bhuban', gpName: 'SURAPRATAPPUR', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 37, block: 'Bhuban', gpName: 'ODASHA', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 38, block: 'Bhuban', gpName: 'JAMUNAKOTA', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 39, block: 'Bhuban', gpName: 'DHALAPADA', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 40, block: 'Bhuban', gpName: 'BALIBO', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 41, block: 'Bhuban', gpName: 'EKTALI', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 42, block: 'Bhuban', gpName: 'KANAPAL (Mahualpal)', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 43, block: 'Bhuban', gpName: 'MRUDANGA', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 44, block: 'Bhuban', gpName: 'ARAKHAPAL', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 45, block: 'Bhuban', gpName: 'MATHAKARGOLLA', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 46, block: 'Bhuban', gpName: 'JIRAL', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 47, block: 'Bhuban', gpName: 'DIGHI', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1KOLHASAHI' },
  { id: 48, block: 'Bhuban', gpName: 'MATRTHAPUR', taggedUlb: 'BHUBAN NAC', taggedMrf: 'MRF1' },

  // Block HINDOL
  { id: 49, block: 'HINDOL', gpName: 'ASARADA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 50, block: 'HINDOL', gpName: 'BABANDHA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 51, block: 'HINDOL', gpName: 'BAMPA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 52, block: 'HINDOL', gpName: 'BAUNSA POKHARI', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 53, block: 'HINDOL', gpName: 'Buhalipal', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 54, block: 'HINDOL', gpName: 'CHITALPUR', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 55, block: 'HINDOL', gpName: 'DANDIRI', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 56, block: 'HINDOL', gpName: 'Dudurukote', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 57, block: 'HINDOL', gpName: 'GALAPADA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 58, block: 'HINDOL', gpName: 'GANDANALI', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 59, block: 'HINDOL', gpName: 'Giridhar Prasad', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 60, block: 'HINDOL', gpName: 'GULEHI', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 61, block: 'HINDOL', gpName: 'HATURA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 62, block: 'HINDOL', gpName: 'JARADA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 63, block: 'HINDOL', gpName: 'KADALA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 64, block: 'HINDOL', gpName: 'KALINGA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 65, block: 'HINDOL', gpName: 'KANSARA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 66, block: 'HINDOL', gpName: 'KANTAMILA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 67, block: 'HINDOL', gpName: 'KANTIMILI', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 68, block: 'HINDOL', gpName: 'KARANDA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF2' },
  { id: 69, block: 'HINDOL', gpName: 'Khaliborei', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 70, block: 'HINDOL', gpName: 'KUKUTA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 71, block: 'HINDOL', gpName: 'KUNUA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 72, block: 'HINDOL', gpName: 'KUTUNIA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 73, block: 'HINDOL', gpName: 'MADHAPUR', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 74, block: 'HINDOL', gpName: 'MAHALUNDA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 75, block: 'HINDOL', gpName: 'Nabakishorepur', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 76, block: 'HINDOL', gpName: 'Nuabag', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 77, block: 'HINDOL', gpName: 'Nuagan', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 78, block: 'HINDOL', gpName: 'Paika Purunakot', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 79, block: 'HINDOL', gpName: 'PATALA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 80, block: 'HINDOL', gpName: 'Ranjagol', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 81, block: 'HINDOL', gpName: 'RASOL', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 82, block: 'HINDOL', gpName: 'SANJAPADA', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },
  { id: 83, block: 'HINDOL', gpName: 'THOKAR', taggedUlb: 'HINDOL NAC', taggedMrf: 'MRF1' },

  // Block KAMAKHYANAGAR
  { id: 84, block: 'KAMAKHYANAGAR', gpName: 'ANALABERENI', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 85, block: 'KAMAKHYANAGAR', gpName: 'BADASUANLO', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 86, block: 'KAMAKHYANAGAR', gpName: 'BAISINGA', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 87, block: 'KAMAKHYANAGAR', gpName: 'BALIGORADA', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 88, block: 'KAMAKHYANAGAR', gpName: 'BANKUALA', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 89, block: 'KAMAKHYANAGAR', gpName: 'BARUAN(K)', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 90, block: 'KAMAKHYANAGAR', gpName: 'BAUNSAPAL', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 91, block: 'KAMAKHYANAGAR', gpName: 'BHAIRPUR', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 92, block: 'KAMAKHYANAGAR', gpName: 'BUDHIBILI', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 93, block: 'KAMAKHYANAGAR', gpName: 'JAGANNATHPUR', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 94, block: 'KAMAKHYANAGAR', gpName: 'KADUA', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 95, block: 'KAMAKHYANAGAR', gpName: 'KANAPURA', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 96, block: 'KAMAKHYANAGAR', gpName: 'KANTAPAL', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 97, block: 'KAMAKHYANAGAR', gpName: 'KANTIOKATNEI', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 98, block: 'KAMAKHYANAGAR', gpName: 'KANTIOPUTASAHI', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 99, block: 'KAMAKHYANAGAR', gpName: 'KOTAGARA', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 100, block: 'KAMAKHYANAGAR', gpName: 'KUSUMJODI', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 101, block: 'KAMAKHYANAGAR', gpName: 'MAHULPAL', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 102, block: 'KAMAKHYANAGAR', gpName: 'Rai Narasinghpur', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 103, block: 'KAMAKHYANAGAR', gpName: 'SARUALI', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 104, block: 'KAMAKHYANAGAR', gpName: 'SOGAR', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
  { id: 105, block: 'KAMAKHYANAGAR', gpName: 'TUMUSINGA', taggedUlb: 'KAMAKHYANAGAR NAC', taggedMrf: 'MRF' },
];
