export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // Khariar Block - Khariar NAC (Route 1)
  { id: 1, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'AREDA', wasteGeneratedKg: 34.5, gpNodalPerson: 'SANJAY KUMAR PRADHAN', gpNodalContact: '9668740177', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 2, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'BADDOHEL', wasteGeneratedKg: 22.3, gpNodalPerson: 'BANITA NAIK', gpNodalContact: '9439586865', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 3, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'BADI', wasteGeneratedKg: 44.2, gpNodalPerson: 'TIHARU NIAL', gpNodalContact: '9937783864', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 4, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'BARGAON', wasteGeneratedKg: 38.5, gpNodalPerson: 'TAPASWANI BHOI', gpNodalContact: '7377534203', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 5, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'BHOJPUR', wasteGeneratedKg: 28.1, gpNodalPerson: 'NETARAM MAJHI', gpNodalContact: '7326021042', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 6, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'BHULIASIKUAN', wasteGeneratedKg: 45.6, gpNodalPerson: 'HAREKRUSHNA BARIK', gpNodalContact: '9938005224', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 7, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'GARDAMUNDA', wasteGeneratedKg: 46.4, gpNodalPerson: 'TRINATH BARIK', gpNodalContact: '9078860440', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 8, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'CHANABEDA', wasteGeneratedKg: 20.5, gpNodalPerson: 'NARAHARI JAGAT', gpNodalContact: '9777770392', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 9, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'CHINDAGUDA', wasteGeneratedKg: 24.4, gpNodalPerson: 'DIPA BAG', gpNodalContact: '8658454010', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 10, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'KENDUPATI', wasteGeneratedKg: 18.3, gpNodalPerson: 'KHIRODARA MEHER', gpNodalContact: '9777131106', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 11, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'LANJI', wasteGeneratedKg: 26.6, gpNodalPerson: 'SASMITA BEHERA', gpNodalContact: '7325870507', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 12, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'SANMAHESWAR', wasteGeneratedKg: 25.8, gpNodalPerson: 'NARAHARI JAGAT', gpNodalContact: '9777770392', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 13, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'TUKLA', wasteGeneratedKg: 65.6, gpNodalPerson: 'HAREKRUSHNA BARIK', gpNodalContact: '9938005224', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },

  // Khariar Block - Khariar NAC (Route 2)
  { id: 14, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'BIRIGHAT', wasteGeneratedKg: 22.7, gpNodalPerson: 'SUSRUTA KUMAR MEHER', gpNodalContact: '9821293157', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 15, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KHASBAHAL', wasteGeneratedKg: 24.5, gpNodalPerson: 'TIHARU NIAL', gpNodalContact: '9937783864', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 16, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KHUDPEJ', wasteGeneratedKg: 18.4, gpNodalPerson: 'KHIRODARA MEHER', gpNodalContact: '9777131106', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 17, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KIRIKITA', wasteGeneratedKg: 27.3, gpNodalPerson: 'DIPA BAG', gpNodalContact: '8658454010', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 18, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'DUAJHAR', wasteGeneratedKg: 58.6, gpNodalPerson: 'SANJAY KUMAR PRADHAN', gpNodalContact: '9668740177', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 19, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'MANDOSIL', wasteGeneratedKg: 18.2, gpNodalPerson: 'MANISH KUMAR SAHU', gpNodalContact: '8455841717', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 20, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'NEHENA', wasteGeneratedKg: 36.7, gpNodalPerson: 'DINGER HARIJAN', gpNodalContact: '9178954405', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 21, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'RANIMUNDA', wasteGeneratedKg: 22.4, gpNodalPerson: 'HAREKRUSHNA BARIK', gpNodalContact: '9938005224', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 22, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'RISIGAON', wasteGeneratedKg: 20.3, gpNodalPerson: 'KAMINI BAG', gpNodalContact: '7978545326', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 23, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'DOHELPADA', wasteGeneratedKg: 14.1, gpNodalPerson: 'BANITA NAIK', gpNodalContact: '9439586865', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 24, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'SARDHAPUR', wasteGeneratedKg: 23.8, gpNodalPerson: 'SANJAY KUMAR PRADHAN', gpNodalContact: '9668740177', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 25, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'SUNARI SIKUAN', wasteGeneratedKg: 22.5, gpNodalPerson: 'DINGER HARIJAN', gpNodalContact: '9178954405', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 26, block: 'Khariar', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'DABRI', wasteGeneratedKg: 21.3, gpNodalPerson: 'SASMITA BEHERA', gpNodalContact: '7325870507', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },

  // Sinapali Block - Khariar NAC (Route 3, 4, 5)
  { id: 27, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'BARGAON', wasteGeneratedKg: 42.8, gpNodalPerson: 'SUSHANTA KU. BEHERA', gpNodalContact: '9777747187', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 28, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'BHARUAMUNDA', wasteGeneratedKg: 51.6, gpNodalPerson: 'BAIRAGI CHARAN BAG', gpNodalContact: '8658554141', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 29, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'CHATIAGUDA', wasteGeneratedKg: 31.3, gpNodalPerson: 'KALPALATA SAGAR', gpNodalContact: '7848907928', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 30, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'GANDABAHALI', wasteGeneratedKg: 45.5, gpNodalPerson: 'KHEMSAGAR SAHU', gpNodalContact: '9178186703', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 31, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'HATIBANDHA', wasteGeneratedKg: 64.7, gpNodalPerson: 'JAYANAND MEHER', gpNodalContact: '9668289332', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 32, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'LITIGUDA', wasteGeneratedKg: 24.5, gpNodalPerson: 'DHAKANLAL CHALAN', gpNodalContact: '9556205076', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 33, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'MAKHAPADAR', wasteGeneratedKg: 48.2, gpNodalPerson: 'KHEMSAGAR SAHU', gpNodalContact: '9178186703', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 34, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'GODAL', wasteGeneratedKg: 48.7, gpNodalPerson: 'JAYANAND MEHER', gpNodalContact: '9668289332', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 35, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'SINAPALI', wasteGeneratedKg: 85.2, gpNodalPerson: 'SUSHANTA KU. BEHERA', gpNodalContact: '9777747187', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },

  { id: 36, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KUSUMJORE', wasteGeneratedKg: 34.21, gpNodalPerson: 'BISAMBAR MAJHI', gpNodalContact: '9777468008', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 37, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'JHARBANDH', wasteGeneratedKg: 21.8, gpNodalPerson: 'ROHIT NAYAK', gpNodalContact: '6371687459', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 38, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KAINTPADAR', wasteGeneratedKg: 20.6, gpNodalPerson: 'OM PRAKASH JAGAT', gpNodalContact: '9178579532', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 39, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KARANBAHALI', wasteGeneratedKg: 20.4, gpNodalPerson: 'MANOJ KU SA', gpNodalContact: '7894396166', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 40, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KENDUMUNDA', wasteGeneratedKg: 46.3, gpNodalPerson: 'LABA BARIK', gpNodalContact: '9668753856', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 41, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KHAIRABHADI', wasteGeneratedKg: 22.6, gpNodalPerson: 'DHAKANLAL CHALAN', gpNodalContact: '9556205076', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 42, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KHARSEL', wasteGeneratedKg: 24.5, gpNodalPerson: 'MOHANDAS SATANAMI', gpNodalContact: '7749020553', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 43, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'SINGJHAR', wasteGeneratedKg: 31.2, gpNodalPerson: 'PRADEEP KU TANDI', gpNodalContact: '8260446083', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 44, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'GHUCHAGUDA', wasteGeneratedKg: 14.1, gpNodalPerson: 'SANGITA JAGAT', gpNodalContact: '7205668845', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },

  { id: 45, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'WED, SAT', gpName: 'GORLA', wasteGeneratedKg: 28.8, gpNodalPerson: 'DHAKANLAL CHALAN', gpNodalContact: '9556205076', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 46, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'WED, SAT', gpName: 'NANGALBOD', wasteGeneratedKg: 19.6, gpNodalPerson: 'BHOJRAJ PRADHANI', gpNodalContact: '9938226458', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 47, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'WED, SAT', gpName: 'NILJEE', wasteGeneratedKg: 22.2, gpNodalPerson: 'MOHANDAS SATANAMI', gpNodalContact: '7749020553', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 48, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'WED, SAT', gpName: 'NUAMALPADA', wasteGeneratedKg: 15.6, gpNodalPerson: 'MANOJ KU SA', gpNodalContact: '7894396166', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 49, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'WED, SAT', gpName: 'NUAPADA', wasteGeneratedKg: 18.5, gpNodalPerson: 'BAIRAGI CHARAN BAG', gpNodalContact: '8658554141', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 50, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'WED, SAT', gpName: 'RANIMUNDA', wasteGeneratedKg: 25.3, gpNodalPerson: 'BISAMBAR MAJHI', gpNodalContact: '9777468008', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 51, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'WED, SAT', gpName: 'GHANTIGUDA', wasteGeneratedKg: 22.8, gpNodalPerson: 'PRADEEP KU TANDI', gpNodalContact: '8260446083', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 52, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'WED, SAT', gpName: 'GHATMAL', wasteGeneratedKg: 15.2, gpNodalPerson: 'BHOJRAJ PRADHANI', gpNodalContact: '9938226458', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 53, block: 'Sinapali', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'WED, SAT', gpName: 'TIMANPUR', wasteGeneratedKg: 21.9, gpNodalPerson: 'DAYA JAGAT', gpNodalContact: '6370900121', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },

  // Block Boden - Khariar NAC (Routes 6 & 7)
  { id: 54, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'BABEBIR', wasteGeneratedKg: 38.528, gpNodalPerson: 'SANJAYA MEHER', gpNodalContact: '9556073391', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 55, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'DAMJHAR', wasteGeneratedKg: 34.400, gpNodalPerson: 'SATISH RANJAN ROUT', gpNodalContact: '8018331199', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 56, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'FARSARA', wasteGeneratedKg: 48.742, gpNodalPerson: 'KISHOR CHANDRA ROUT', gpNodalContact: '7681836239', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 57, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'PALSAPADA', wasteGeneratedKg: 33.84, gpNodalPerson: 'HIRANYAMAYEE CHALAN', gpNodalContact: '9937612437', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 58, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'LITISARGI', wasteGeneratedKg: 48.585, gpNodalPerson: 'NAMITA SAHU', gpNodalContact: '7750056798', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 59, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'ROKAL', wasteGeneratedKg: 32.200, gpNodalPerson: 'NIJAYALAXMI MAHANTY', gpNodalContact: '7606952767', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 60, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'LARKA', wasteGeneratedKg: 35.575, gpNodalPerson: 'JAGNYABHARATI MAJHI', gpNodalContact: '7609067606', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 61, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'KARANGAMAL', wasteGeneratedKg: 41.100, gpNodalPerson: 'TAPAS KUMAR AGASTI', gpNodalContact: '6370171605', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },

  { id: 62, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'BODEN', wasteGeneratedKg: 82.255, gpNodalPerson: 'KSHYASAGAR SUNANI', gpNodalContact: '9938567829', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 63, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'BHAISADANI', wasteGeneratedKg: 28.200, gpNodalPerson: 'TAPAS KUMAR AGASTI', gpNodalContact: '6370171605', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 64, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KARLAKOT', wasteGeneratedKg: 42.440, gpNodalPerson: 'SASWATI BHOI', gpNodalContact: '9348116834', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 65, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'SUNAPUR', wasteGeneratedKg: 31.000, gpNodalPerson: 'HRUSIKESH BAITHARU', gpNodalContact: '8114876968', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 66, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KHAIRA', wasteGeneratedKg: 35.696, gpNodalPerson: 'GURJU HANS', gpNodalContact: '9437679567', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 67, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'NAGAPADA', wasteGeneratedKg: 32.200, gpNodalPerson: 'GURJU HANS', gpNodalContact: '9437679567', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 68, block: 'Boden', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'BOIRGAON', wasteGeneratedKg: 34.100, gpNodalPerson: 'KSHYASAGAR SUNANI', gpNodalContact: '9938567829', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },

  // Block Komna - Khariar NAC (Routes 8 & 9)
  { id: 69, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'AGREN', wasteGeneratedKg: 32, gpNodalPerson: 'HIRALAL SAHU', gpNodalContact: '8458018837', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 70, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KONABIRA', wasteGeneratedKg: 54, gpNodalPerson: 'RANJIT KU. RANA', gpNodalContact: '7894648477', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 71, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'RAJNA', wasteGeneratedKg: 49, gpNodalPerson: 'HIRALAL SAHU', gpNodalContact: '8458018837', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 72, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'DHORLAMUNDA', wasteGeneratedKg: 39, gpNodalPerson: 'AMLAN MISHRA', gpNodalContact: '8457894300', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 73, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'PENDRAWAN', wasteGeneratedKg: 95, gpNodalPerson: 'BENUDHARA MAJHI', gpNodalContact: '9938735214', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 74, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'JHAGRAHI', wasteGeneratedKg: 48, gpNodalPerson: 'AMLAN MISHRA', gpNodalContact: '8457894300', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 75, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'DEODHARA', wasteGeneratedKg: 25, gpNodalPerson: 'PRUTHIRAJ NAIK', gpNodalContact: '93374669041', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 76, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'KOMNA', wasteGeneratedKg: 65, gpNodalPerson: 'SURASMITA PANDA', gpNodalContact: '8917688981', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 77, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'BUHIKOMNA', wasteGeneratedKg: 65, gpNodalPerson: 'GIRIDHARI HARIJAN', gpNodalContact: '91780004490', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 78, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'TIKRAPADA', wasteGeneratedKg: 32, gpNodalPerson: 'SUBHASMITA NAIK', gpNodalContact: '7684013511', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 79, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'POINR', wasteGeneratedKg: 36, gpNodalPerson: 'BENUDHARA MAJHI', gpNodalContact: '9938735214', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },

  { id: 80, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON', gpName: 'SOSENG', wasteGeneratedKg: 17, gpNodalPerson: 'PARAMANANDA MAJHI', gpNodalContact: '9777196824', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 81, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON', gpName: 'SUNABEDA', wasteGeneratedKg: 35, gpNodalPerson: 'JAYAPRAKASH MAJHI', gpNodalContact: '9938410783', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },
  { id: 82, block: 'Komna', ulb: 'Khariar NAC', mrf: 'KHARIAR MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON', gpName: 'MICHHAPALI', wasteGeneratedKg: 45, gpNodalPerson: 'NANDAKISHOR PADHI', gpNodalContact: '9937995363', ulbNodalPerson: 'AMIT KU SAMAL', ulbNodalContact: '9438661350' },

  // Block Nuapada - Nuapada NAC (Routes 1 & 2)
  { id: 83, block: 'Nuapada', ulb: 'NUAPADANAC', mrf: 'NUAPADA MRF', vehicleType: 'TATA Ace', vehicleNo: '-', vehicleCapacity: '1025', driverName: '-', driverContact: '-', collectionSchedule: 'MON,THU', gpName: 'AMANARA', wasteGeneratedKg: 94, gpNodalPerson: 'DIKENDRA MAJHI', gpNodalContact: '9668227567', ulbNodalPerson: 'RAJEEV LOCHAN SWAIN', ulbNodalContact: '9668867619' },
];
