export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
  routeId?: string;
  routeName?: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // BHABANIPATNA Block - Near LIC Office
  { id: 1, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '11th and 26th of every month', gpName: 'DADPUR', wasteGeneratedKg: 1539.252, gpNodalPerson: 'Subhasmita Mishra', gpNodalContact: '9437685600', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DDUGMLS-06' },
  { id: 2, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '11th and 26th of every month', gpName: 'DEYPORE', wasteGeneratedKg: 1145.82, gpNodalPerson: 'Gouranga Majhi', gpNodalContact: '7978832693', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DDUGMLS-06' },
  { id: 3, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '11th and 26th of every month', gpName: 'GUDIALIPADAR', wasteGeneratedKg: 1384.11, gpNodalPerson: 'Gouranga Majhi', gpNodalContact: '7978832693', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DDUGMLS-06' },
  { id: 4, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '11th and 26th of every month', gpName: 'LAXMIPUR', wasteGeneratedKg: 393.432, gpNodalPerson: 'Parameswar Senapati', gpNodalContact: '9937576685', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DDUGMLS-06' },
  { id: 5, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '11th and 26th of every month', gpName: 'MEDINIPUR', wasteGeneratedKg: 1656.876, gpNodalPerson: 'Padmanava Singh', gpNodalContact: '9337928151', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DDUGMLS-06' },
  { id: 6, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '11th and 26th of every month', gpName: 'SRIPUR', wasteGeneratedKg: 641.862, gpNodalPerson: 'Pradeep Ku Mishra', gpNodalContact: '9777302269', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DDUGMLS-06' },
  { id: 7, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '11th and 26th of every month', gpName: 'UDEPUR', wasteGeneratedKg: 689.52, gpNodalPerson: 'Ganapati Naik', gpNodalContact: '8847848954', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DDUGMLS-06' },

  // BHABANIPATNA Block - Bhangabari
  { id: 8, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'ARTAL', wasteGeneratedKg: 1442.922, gpNodalPerson: 'Sushanta Ku Bania', gpNodalContact: '9337195284', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAB', routeName: 'BSDAPGK-01' },
  { id: 9, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'DUMURIA', wasteGeneratedKg: 777.738, gpNodalPerson: 'Siddheswar Dev', gpNodalContact: '9348407734', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAB', routeName: 'BSDAPGK-01' },
  { id: 10, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'GURJUNG', wasteGeneratedKg: 592.176, gpNodalPerson: 'Abhimanyu Nayak', gpNodalContact: '8249964389', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAB', routeName: 'BSDAPGK-01' },
  { id: 11, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'KENDUPATI', wasteGeneratedKg: 542.49, gpNodalPerson: 'Sushanta Ku Bania', gpNodalContact: '9337195284', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAB', routeName: 'BSDAPGK-01' },
  { id: 12, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'PALNA', wasteGeneratedKg: 1104.246, gpNodalPerson: 'Anup Ku Biswal', gpNodalContact: '7978257895', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAB', routeName: 'BSDAPGK-01' },
  { id: 13, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'BORDA', wasteGeneratedKg: 975.468, gpNodalPerson: 'Dheuraj Jyotish', gpNodalContact: '7008860326', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAB', routeName: 'BSDAPGK-01' },
  { id: 14, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'SIKUAN', wasteGeneratedKg: 576.966, gpNodalPerson: 'Abhimanyu Nayak', gpNodalContact: '8249964389', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAB', routeName: 'BSDAPGK-01' },
  { id: 15, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'BORBHATA', wasteGeneratedKg: 573, gpNodalPerson: 'Sushanta Ku Bania', gpNodalContact: '9337195284', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAS', routeName: 'SBMMCKC-02' },
  { id: 16, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'CHAHAGAON', wasteGeneratedKg: 776, gpNodalPerson: 'Samir Mishra', gpNodalContact: '8908431412', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAS', routeName: 'SBMMCKC-02' },
  { id: 17, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'CHHELIAMAL', wasteGeneratedKg: 1150, gpNodalPerson: 'Arabinda Meher', gpNodalContact: '7978631088', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAS', routeName: 'SBMMCKC-02' },
  { id: 18, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'KARLAPADA', wasteGeneratedKg: 683, gpNodalPerson: 'Arabinda Meher', gpNodalContact: '7978631088', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAS', routeName: 'SBMMCKC-02' },
  { id: 19, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'MADIGUDA', wasteGeneratedKg: 773, gpNodalPerson: 'Jogendra Sahu', gpNodalContact: '6372879237', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAS', routeName: 'SBMMCKC-02' },
  { id: 20, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'MATIA', wasteGeneratedKg: 687, gpNodalPerson: 'Sai Prasad Panda', gpNodalContact: '9310422971', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAS', routeName: 'SBMMCKC-02' },
  { id: 21, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'SEINPUR', wasteGeneratedKg: 919, gpNodalPerson: 'Abhimanyu Nayak', gpNodalContact: '8249964389', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAS', routeName: 'SBMMCKC-02' },
  { id: 22, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20th of every month', gpName: 'KALAM', wasteGeneratedKg: 1253, gpNodalPerson: 'Nilakantha Rout', gpNodalContact: '7894499055', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAK', routeName: 'KPKKT-03' },
  { id: 23, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20th of every month', gpName: 'KAMTHANA', wasteGeneratedKg: 1917, gpNodalPerson: 'Pradeep Ku Mishra', gpNodalContact: '9777302269', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAK', routeName: 'KPKKT-03' },
  { id: 24, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20th of every month', gpName: 'KARLAGUDA', wasteGeneratedKg: 1306, gpNodalPerson: 'Suvankar Dash', gpNodalContact: '8847839190', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAK', routeName: 'KPKKT-03' },
  { id: 25, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20th of every month', gpName: 'PALSIJHARAN', wasteGeneratedKg: 784, gpNodalPerson: 'Arabinda Meher', gpNodalContact: '7978631088', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAK', routeName: 'KPKKT-03' },
  { id: 26, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Bhangabari)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20th of every month', gpName: 'THUAPADAR', wasteGeneratedKg: 1814, gpNodalPerson: 'Pradeep Ku Sahu', gpNodalContact: '9777698144', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAK', routeName: 'KPKKT-03' },

  // BHABANIPATNA Block - Sirliguda
  { id: 27, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Sirliguda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'CHANCHER', wasteGeneratedKg: 537.42, gpNodalPerson: 'Anup Ku Biswal', gpNodalContact: '7978257895', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DCTJS-04' },
  { id: 28, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Sirliguda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'DUARSUNI', wasteGeneratedKg: 1175, gpNodalPerson: 'Pradeep Ku Sahu', gpNodalContact: '9777698144', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DCTJS-04' },
  { id: 29, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Sirliguda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'JUGSAIPATNA', wasteGeneratedKg: 567.84, gpNodalPerson: 'Nitin Behera', gpNodalContact: '6371895751', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DCTJS-04' },
  { id: 30, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Sirliguda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'SAGADA', wasteGeneratedKg: 1222.884, gpNodalPerson: 'Pradeep Ku Sahu', gpNodalContact: '9777698144', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DCTJS-04' },
  { id: 31, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Sirliguda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'TALBELGAON', wasteGeneratedKg: 655.044, gpNodalPerson: 'Mayuri Dash', gpNodalContact: '6371806302', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAD', routeName: 'DCTJS-04' },

  // BHABANIPATNA Block - Near LIC Office (Additional)
  { id: 32, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'GANDBARAJHOLA', wasteGeneratedKg: 867.984, gpNodalPerson: 'Anup Ku Biswal', gpNodalContact: '7978257895', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAR', routeName: 'RMKGK-O5' },
  { id: 33, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'KULIAMAL', wasteGeneratedKg: 735.15, gpNodalPerson: 'Sarat Ch. Sahu', gpNodalContact: '9937626312', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAR', routeName: 'RMKGK-O5' },
  { id: 34, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'KUTRUKHAMAR', wasteGeneratedKg: 865.956, gpNodalPerson: 'Risant Sahu', gpNodalContact: '8598812152', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAR', routeName: 'RMKGK-O5' },
  { id: 35, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'MALGAON', wasteGeneratedKg: 1263.444, gpNodalPerson: 'Gouranga Majhi', gpNodalContact: '7978832693', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAR', routeName: 'RMKGK-O5' },
  { id: 36, block: 'BHABANIPATNA', ulb: 'BHABANIPATNA Municipality', mrf: 'Bhawanipata(Near Lic Office)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'RISGAON', wasteGeneratedKg: 1117.428, gpNodalPerson: 'Risant Sahu', gpNodalContact: '8598812152', ulbNodalPerson: 'Tapan kumar Nayak', ulbNodalContact: '7077485530', routeId: 'KBHAR', routeName: 'RMKGK-O5' },

  // DHARAMGARH Block
  { id: 37, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'BADFURLA', wasteGeneratedKg: 1215.786, gpNodalPerson: 'LINGARAJ BAG', gpNodalContact: '9437413092', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBBBNBB-01' },
  { id: 38, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'BADGHUMAR', wasteGeneratedKg: 716.898, gpNodalPerson: 'SANJAYA KUMAR SA', gpNodalContact: '9937912320', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBBBNBB-01' },
  { id: 39, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'BAGAD', wasteGeneratedKg: 684.45, gpNodalPerson: 'REENA SATNAMI', gpNodalContact: '7681844506', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBBBNBB-01' },
  { id: 40, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'BODEN', wasteGeneratedKg: 1175.226, gpNodalPerson: 'SUCHISMITA SAHU', gpNodalContact: '8249861966', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBBBNBB-01' },
  { id: 41, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'NANDAGAON', wasteGeneratedKg: 673.296, gpNodalPerson: 'TIRHARAJ MAJHI', gpNodalContact: '7978210744', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBBBNBB-01' },
  { id: 42, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of each month', gpName: 'TARAPUR', wasteGeneratedKg: 1801.878, gpNodalPerson: 'GOLAK BIHARI PUJHARI', gpNodalContact: '7894955950', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBBBNBB-01' },
  { id: 43, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'BEHERA', wasteGeneratedKg: 1165.086, gpNodalPerson: 'GOURANGA NAG', gpNodalContact: '8018976527', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBDCJPKG-02' },
  { id: 44, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'CHANCHANBAHALI', wasteGeneratedKg: 1066.728, gpNodalPerson: 'DUSMANTA NAIK', gpNodalContact: '7735842500', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBDCJPKG-02' },
  { id: 45, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'DHANARPUR', wasteGeneratedKg: 845.676, gpNodalPerson: 'JAGANNATH DANDASENA', gpNodalContact: '9178470499', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBDCJPKG-02' },
  { id: 46, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'GADIAJORE', wasteGeneratedKg: 1469.286, gpNodalPerson: 'SAMPADA KUMARI BISHI', gpNodalContact: '7873440931', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBDCJPKG-02' },
  { id: 47, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'JAYANTPUR', wasteGeneratedKg: 738.192, gpNodalPerson: 'JAGANNATH DANDASENA', gpNodalContact: '9178470499', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBDCJPKG-02' },
  { id: 48, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'KADALIMUNDA', wasteGeneratedKg: 373.152, gpNodalPerson: 'RUPESH KUMAR MEHER', gpNodalContact: '8249544717', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBDCJPKG-02' },
  { id: 49, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'PARLA', wasteGeneratedKg: 1412.502, gpNodalPerson: 'KHETRAMOHAN BIHAR', gpNodalContact: '9937678401', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBDCJPKG-02' },
  { id: 50, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'TENDAPALI', wasteGeneratedKg: 1332.396, gpNodalPerson: 'NETRANAND SAHU', gpNodalContact: '9937982745', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TBDCJPKG-02' },
  { id: 51, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20th of every month', gpName: 'CHILLIPA', wasteGeneratedKg: 1831.284, gpNodalPerson: 'KEDAR NATH NAIK', gpNodalContact: '9178144416', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAK', routeName: 'KSC-03' },
  { id: 52, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20th of every month', gpName: 'KANKERI', wasteGeneratedKg: 581.022, gpNodalPerson: 'KSHIROD KUMAR NAG', gpNodalContact: '6372672826', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAK', routeName: 'KSC-03' },
  { id: 53, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20th of every month', gpName: 'SANDIKULIHARI', wasteGeneratedKg: 308.256, gpNodalPerson: 'KEDAR NATH NAIK', gpNodalContact: '9178144416', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAK', routeName: 'KSC-03' },
  { id: 54, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'BRAHAMANCHHENDIA', wasteGeneratedKg: 891.306, gpNodalPerson: 'HUMRAJ NAIK', gpNodalContact: '9178761371', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TDKB-04' },
  { id: 55, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'DUMERGUDA', wasteGeneratedKg: 1404.39, gpNodalPerson: 'SARAT CHANDRA SABAR', gpNodalContact: '7894131326', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TDKB-04' },
  { id: 56, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'KANAGAON', wasteGeneratedKg: 675.324, gpNodalPerson: 'PARTHABA MAJHI', gpNodalContact: '9853694522', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TDKB-04' },
  { id: 57, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'TIPIGUDA', wasteGeneratedKg: 1795.794, gpNodalPerson: 'GOURANGA NAG', gpNodalContact: '8018976527', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TDKB-04' },
  { id: 58, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'BADBASUL', wasteGeneratedKg: 344.76, gpNodalPerson: 'BATAKRISHNA BARIK', gpNodalContact: '6371479234', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TKB-O5' },
  { id: 59, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'KHAIRAPADAR', wasteGeneratedKg: 890.292, gpNodalPerson: 'HUMRAJ NAIK', gpNodalContact: '9178761371', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TKB-O5' },
  { id: 60, block: 'DHARAMGARH', ulb: 'DHARAMGARH NAC', mrf: 'Dharamgarh (Near Paradeswar Mandir Pada)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'TAMBACHHADA', wasteGeneratedKg: 1190.436, gpNodalPerson: 'BYOMAKESH BAGARTI', gpNodalContact: '9937982745', ulbNodalPerson: 'Abhinandan Prdhan', ulbNodalContact: '7978234239', routeId: 'KDHAT', routeName: 'TKB-O5' },

  // JUNAGARH Block
  { id: 61, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'ATIGAON', wasteGeneratedKg: 1110.33, gpNodalPerson: 'SMITA PADHAN', gpNodalContact: '8144975447', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TAKPCNCPB-01' },
  { id: 62, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'BALDIAMAL', wasteGeneratedKg: 1435.824, gpNodalPerson: 'DIBYA BHARATI LAHAJAL', gpNodalContact: '7991032436', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TAKPCNCPB-01' },
  { id: 63, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'CHHORIAGARH', wasteGeneratedKg: 1118.442, gpNodalPerson: 'BABITA GURU', gpNodalContact: '9668538762', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TAKPCNCPB-01' },
  { id: 64, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'CHICHEIGUDA', wasteGeneratedKg: 1119.456, gpNodalPerson: 'PRAMESHWAR MEHER', gpNodalContact: '9583583935', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TAKPCNCPB-01' },
  { id: 65, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'KALIAKUNDAL', wasteGeneratedKg: 702.702, gpNodalPerson: 'PARBATI BISHI', gpNodalContact: '7683853354', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TAKPCNCPB-01' },
  { id: 66, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'NAKTIGUDA', wasteGeneratedKg: 864.942, gpNodalPerson: 'HAKIM KUMAR TAHALIA', gpNodalContact: '8249246488', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TAKPCNCPB-01' },
  { id: 67, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'PALAS', wasteGeneratedKg: 1030.224, gpNodalPerson: 'PRABHAKAR SETHI', gpNodalContact: '9556391200', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TAKPCNCPB-01' },
  { id: 68, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'PILKIA', wasteGeneratedKg: 640.848, gpNodalPerson: 'SABHYARANI SUNANI', gpNodalContact: '8917348568', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TAKPCNCPB-01' },
  { id: 69, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'TALMALA', wasteGeneratedKg: 826.41, gpNodalPerson: 'PUJA MANAHIRA', gpNodalContact: '6371234204', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TAKPCNCPB-01' },
  { id: 70, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'CHARBAHAL', wasteGeneratedKg: 1324.284, gpNodalPerson: 'SATYABHAMA PANDA', gpNodalContact: '7077379383', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNC', routeName: 'CKMSMHG-02' },
  { id: 71, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'GOUDCHHENDIA', wasteGeneratedKg: 1203.618, gpNodalPerson: 'SIBA HATI', gpNodalContact: '9337900424', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNC', routeName: 'CKMSMHG-02' },
  { id: 72, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'HABASPUR', wasteGeneratedKg: 1240.122, gpNodalPerson: 'BIKASH RANJAN PANDA', gpNodalContact: '6370068785', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNC', routeName: 'CKMSMHG-02' },
  { id: 73, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'KALOPALA', wasteGeneratedKg: 643.89, gpNodalPerson: 'JANMAJAYA SAHU', gpNodalContact: '6371529117', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNC', routeName: 'CKMSMHG-02' },
  { id: 74, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'MAHICHALA', wasteGeneratedKg: 763.542, gpNodalPerson: 'SHRADHANJALI BEHERA', gpNodalContact: '7008498229', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNC', routeName: 'CKMSMHG-02' },
  { id: 75, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'MALIGUDA', wasteGeneratedKg: 1435.824, gpNodalPerson: 'SANTOSHINI SINGH', gpNodalContact: '8249912699', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNC', routeName: 'CKMSMHG-02' },
  { id: 76, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'S.KUNDAMAL', wasteGeneratedKg: 731.094, gpNodalPerson: 'RASMITA NAIK', gpNodalContact: '7735252938', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNC', routeName: 'CKMSMHG-02' },
  { id: 77, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20nd of every month', gpName: 'BANIJARA', wasteGeneratedKg: 353.886, gpNodalPerson: 'SANJUKTA MAJHI', gpNodalContact: '9437293572', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUND', routeName: 'DMRBM-03' },
  { id: 78, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20nd of every month', gpName: 'DASIGAON', wasteGeneratedKg: 1045.434, gpNodalPerson: 'PRAMODINI PRAHARAJ', gpNodalContact: '6372463083', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUND', routeName: 'DMRBM-03' },
  { id: 79, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20nd of every month', gpName: 'MATIGAON', wasteGeneratedKg: 1082.952, gpNodalPerson: 'NILAGAGAN MEHER', gpNodalContact: '9337832806', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUND', routeName: 'DMRBM-03' },
  { id: 80, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20nd of every month', gpName: 'MUNDRAGUDA', wasteGeneratedKg: 965.328, gpNodalPerson: 'TARA SHANKAR RAIGURU', gpNodalContact: '7978105365', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUND', routeName: 'DMRBM-03' },
  { id: 81, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20nd of every month', gpName: 'RAJPUR', wasteGeneratedKg: 787.878, gpNodalPerson: 'GAJINDRA MAJHI', gpNodalContact: '9827499698', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUND', routeName: 'DMRBM-03' },
  { id: 82, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'B. TULSIPALI', wasteGeneratedKg: 802.074, gpNodalPerson: 'ARCHANA MEHER', gpNodalContact: '8018390630', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TNKCBMB-04' },
  { id: 83, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'BHAINRIGUDA', wasteGeneratedKg: 645.918, gpNodalPerson: 'BINAPANI KANDAPAN', gpNodalContact: '9937621793', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TNKCBMB-04' },
  { id: 84, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'CHINGUDISAR', wasteGeneratedKg: 539.448, gpNodalPerson: 'LOPAMUDRA BAG', gpNodalContact: '9692499148', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TNKCBMB-04' },
  { id: 85, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'KENDUPATI', wasteGeneratedKg: 898.404, gpNodalPerson: 'CHINMAYEE SETHI', gpNodalContact: '7978662914', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TNKCBMB-04' },
  { id: 86, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'MERIABANDHLI', wasteGeneratedKg: 553.644, gpNodalPerson: 'GEETANJALI CHANDAN', gpNodalContact: '9938596585', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TNKCBMB-04' },
  { id: 87, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'NANDOL', wasteGeneratedKg: 791.934, gpNodalPerson: 'NIRANJAN MAJHI', gpNodalContact: '7848951317', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TNKCBMB-04' },
  { id: 88, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'TALJARING', wasteGeneratedKg: 553.644, gpNodalPerson: 'K. SUNIL KUMAR', gpNodalContact: '9937722562', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUNT', routeName: 'TNKCBMB-04' },
  { id: 89, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'BANKAPALAS', wasteGeneratedKg: 875.082, gpNodalPerson: 'DIBYA SHANKAR DEEP', gpNodalContact: '9040607802', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUND', routeName: 'DDKCBB-05' },
  { id: 90, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'BUDHIDARA', wasteGeneratedKg: 1088.022, gpNodalPerson: 'JAGYANSENI PANDA', gpNodalContact: '8596005480', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUND', routeName: 'DDKCBB-05' },
  { id: 91, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'CHARBHATI', wasteGeneratedKg: 895.362, gpNodalPerson: 'SHIBA SANKAR NAIK', gpNodalContact: '9348474825', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUND', routeName: 'DDKCBB-05' },
  { id: 92, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'DEDARA', wasteGeneratedKg: 765.57, gpNodalPerson: 'SUBHAGINI SAHU', gpNodalContact: '8328963416', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUND', routeName: 'DDKCBB-05' },
  { id: 93, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'DUNDEIMAL', wasteGeneratedKg: 589.134, gpNodalPerson: 'JYOTI BEMAL', gpNodalContact: '8327745775', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUND', routeName: 'DDKCBB-05' },
  { id: 94, block: 'JUNAGARH', ulb: 'JUNAGARH NAC', mrf: 'Junagarh (Near Eye Hospital)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'KALEIGAON', wasteGeneratedKg: 570.882, gpNodalPerson: 'MALAYA RANJAN ACHARYA', gpNodalContact: '8328934828', ulbNodalPerson: 'Balkrushna Banjara', ulbNodalContact: '8328848584', routeId: 'KJUND', routeName: 'DDKCBB-05' },

  // KESINGA Block
  { id: 95, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '11th and 26th of every month', gpName: 'KANTESIR', wasteGeneratedKg: 1777.542, gpNodalPerson: 'Krutanjali Majhi', gpNodalContact: '7991070077', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESN', routeName: 'NKK-06' },
  { id: 96, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '11th and 26th of every month', gpName: 'KASRUPADA', wasteGeneratedKg: 837.564, gpNodalPerson: 'Ritumbara Purohit', gpNodalContact: '7326864394', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESN', routeName: 'NKK-06' },
  { id: 97, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '11th and 26th of every month', gpName: 'NUNMATH', wasteGeneratedKg: 1772.472, gpNodalPerson: 'Jhasketan Sahu', gpNodalContact: '9777114651', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESN', routeName: 'NKK-06' },
  { id: 98, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '13th and 28th of every month', gpName: 'BELKHANDI', wasteGeneratedKg: 638.82, gpNodalPerson: 'Partha Rana', gpNodalContact: '9668844550', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESB', routeName: 'BHSTT-07' },
  { id: 99, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '13th and 28th of every month', gpName: 'HATIKHOJ', wasteGeneratedKg: 1736.982, gpNodalPerson: 'Chinmayee Naik', gpNodalContact: '9861579184', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESB', routeName: 'BHSTT-07' },
  { id: 100, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '13th and 28th of every month', gpName: 'SIRJAPALI', wasteGeneratedKg: 852.774, gpNodalPerson: 'Prahallad Suna ', gpNodalContact: '9178596140', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESB', routeName: 'BHSTT-07' },
  { id: 101, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '13th and 28th of every month', gpName: 'TUNDLA', wasteGeneratedKg: 873.054, gpNodalPerson: 'Partha Rana', gpNodalContact: '9668844550', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESB', routeName: 'BHSTT-07' },
  { id: 102, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '13th and 28th of every month', gpName: 'TURLAKHAMAN', wasteGeneratedKg: 664.17, gpNodalPerson: 'Jhasketan Bhoi', gpNodalContact: '7077522521', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESB', routeName: 'BHSTT-07' },
  { id: 103, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'ADHAMUNDA', wasteGeneratedKg: 627.666, gpNodalPerson: 'Papu Ram Sahu', gpNodalContact: '9937984043', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESN', routeName: 'NPFA-01' },
  { id: 104, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'FATKAMAL', wasteGeneratedKg: 1289.808, gpNodalPerson: 'Manoj Kumar Sabar', gpNodalContact: '8249101297', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESN', routeName: 'NPFA-01' },
  { id: 105, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'NASIGAON', wasteGeneratedKg: 688.506, gpNodalPerson: 'Jhasketan Bhoi', gpNodalContact: '7077522521', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESN', routeName: 'NPFA-01' },
  { id: 106, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '1st and 16th of Every month', gpName: 'PASTKUDI', wasteGeneratedKg: 1069.77, gpNodalPerson: 'Surya mani Durga', gpNodalContact: '7008046431', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESN', routeName: 'NPFA-01' },
  { id: 107, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'DEOGAON', wasteGeneratedKg: 1563.588, gpNodalPerson: 'Prasanna Kumar Das', gpNodalContact: '9348821109', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESG', routeName: 'GGD-02' },
  { id: 108, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'GAIGAON', wasteGeneratedKg: 855.816, gpNodalPerson: 'Madhusmita Putel', gpNodalContact: '7008248663', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESG', routeName: 'GGD-02' },
  { id: 109, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '3rd and 18th of every month', gpName: 'GOKULESWAR', wasteGeneratedKg: 1176.24, gpNodalPerson: 'Prahallad Suna', gpNodalContact: '9178596140', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESG', routeName: 'GGD-02' },
  { id: 110, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20nd of every month', gpName: 'CHANCHER', wasteGeneratedKg: 1337.466, gpNodalPerson: 'Suryamani Durga', gpNodalContact: '7008046431', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESC', routeName: 'CUKK-03' },
  { id: 111, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20nd of every month', gpName: 'KIKIA', wasteGeneratedKg: 961.272, gpNodalPerson: 'Benudhar Kandhapani', gpNodalContact: '9937190193', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESC', routeName: 'CUKK-03' },
  { id: 112, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20nd of every month', gpName: 'KUNDABANDH', wasteGeneratedKg: 1294.878, gpNodalPerson: 'Shankar Padhan', gpNodalContact: '7605983988', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESC', routeName: 'CUKK-03' },
  { id: 113, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '5th and 20nd of every month', gpName: 'UTKELA', wasteGeneratedKg: 1888.068, gpNodalPerson: 'Manoj Kumar Sabar', gpNodalContact: '8249101297', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESC', routeName: 'CUKK-03' },
  { id: 114, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'BORIA', wasteGeneratedKg: 1059.63, gpNodalPerson: 'Shankar Padhan', gpNodalContact: '7605983988', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESP', routeName: 'PBLK-04' },
  { id: 115, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'KANDEL', wasteGeneratedKg: 1740.024, gpNodalPerson: 'Akash Kumar Bhoi', gpNodalContact: '9556471631', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESP', routeName: 'PBLK-04' },
  { id: 116, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'LAITARA', wasteGeneratedKg: 870.012, gpNodalPerson: 'Shivaprasad Sahu', gpNodalContact: '9438062601', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESP', routeName: 'PBLK-04' },
  { id: 117, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '7th and 22nd of every month', gpName: 'PATHARLA', wasteGeneratedKg: 1075.854, gpNodalPerson: 'Shivaprasad Sahu', gpNodalContact: '9438062601', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESP', routeName: 'PBLK-04' },
  { id: 118, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'BALSI', wasteGeneratedKg: 1682.226, gpNodalPerson: 'Prem chand Rana', gpNodalContact: '9938827875', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESB', routeName: 'BPS-05' },
  { id: 119, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'PARALSINGHA', wasteGeneratedKg: 1118.442, gpNodalPerson: 'Khyama prasad Duria', gpNodalContact: '8018328921', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESB', routeName: 'BPS-05' },
  { id: 120, block: 'KESINGA', ulb: 'KESINGA NAC', mrf: 'kesinga(Dumermunda)', vehicleType: 'TATA Ace (temporary)', vehicleNo: '-', vehicleCapacity: '500', driverName: '-', driverContact: '-', collectionSchedule: '9th and 24th of every month', gpName: 'SIROL', wasteGeneratedKg: 871.026, gpNodalPerson: 'Jhasketan Sahu', gpNodalContact: '9777114651', ulbNodalPerson: 'Nrusingha Behera', ulbNodalContact: '9583603809', routeId: 'KKESB', routeName: 'BPS-05' }
];