export interface GpMappingData {
  id: number;
  block: string;
  gpName: string;
  taggedUlb: string;
  taggedMrf: string;
}

export const gpMappingData: GpMappingData[] = [
  // Bhabanipatna Block (1-36)
  { id: 1, block: 'Bhabanipatna', gpName: 'ARTAL', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 2, block: 'Bhabanipatna', gpName: 'BORABHATA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 3, block: 'Bhabanipatna', gpName: 'BORDA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 4, block: 'Bhabanipatna', gpName: 'CHAHAGAON', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 5, block: 'Bhabanipatna', gpName: 'CHANCHER', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 6, block: 'Bhabanipatna', gpName: 'CHHELIAMAL', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 7, block: 'Bhabanipatna', gpName: 'DADPUR', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 8, block: 'Bhabanipatna', gpName: 'DEYPUR', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 9, block: 'Bhabanipatna', gpName: 'DUARSUNI', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 10, block: 'Bhabanipatna', gpName: 'DUMURIA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 11, block: 'Bhabanipatna', gpName: 'GAND-BARAJHOLA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 12, block: 'Bhabanipatna', gpName: 'GUDIALIPADAR', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 13, block: 'Bhabanipatna', gpName: 'GURJUNG', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 14, block: 'Bhabanipatna', gpName: 'JUGSAIPATNA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 15, block: 'Bhabanipatna', gpName: 'KALAM', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 16, block: 'Bhabanipatna', gpName: 'KAMATHANA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 17, block: 'Bhabanipatna', gpName: 'KARALAPADA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 18, block: 'Bhabanipatna', gpName: 'KARLAGUDA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 19, block: 'Bhabanipatna', gpName: 'KENDUPATI', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 20, block: 'Bhabanipatna', gpName: 'KULIAMAL', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 21, block: 'Bhabanipatna', gpName: 'KUTRUKHAMAR', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 22, block: 'Bhabanipatna', gpName: 'LAXMIPUR', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 23, block: 'Bhabanipatna', gpName: 'MADIGUDA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 24, block: 'Bhabanipatna', gpName: 'MALGAON', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 25, block: 'Bhabanipatna', gpName: 'MATIA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 26, block: 'Bhabanipatna', gpName: 'MEDINIPUR', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 27, block: 'Bhabanipatna', gpName: 'PALNA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 28, block: 'Bhabanipatna', gpName: 'PALSIJHARAN', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 29, block: 'Bhabanipatna', gpName: 'RISIGAON', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 30, block: 'Bhabanipatna', gpName: 'SAGADA', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 31, block: 'Bhabanipatna', gpName: 'SEINPUR', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 32, block: 'Bhabanipatna', gpName: 'SIKUAN', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 33, block: 'Bhabanipatna', gpName: 'SRIPUR', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 34, block: 'Bhabanipatna', gpName: 'TAL-BELGAON', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 35, block: 'Bhabanipatna', gpName: 'THUAPADAR', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },
  { id: 36, block: 'Bhabanipatna', gpName: 'UDEPUR', taggedUlb: 'Bhabanipatna Municipality', taggedMrf: 'Bhabanipatna' },

  // Dharamgarh Block (37-60)
  { id: 37, block: 'Dharamgarh', gpName: 'BADBASUL', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 38, block: 'Dharamgarh', gpName: 'BAGAD', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 39, block: 'Dharamgarh', gpName: 'BADFURLA', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 40, block: 'Dharamgarh', gpName: 'BADGHUMER', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 41, block: 'Dharamgarh', gpName: 'BEHERA', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 42, block: 'Dharamgarh', gpName: 'BODEN', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 43, block: 'Dharamgarh', gpName: 'BRAHAMANCHHENDIA', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 44, block: 'Dharamgarh', gpName: 'CHANCHANBAHALI', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 45, block: 'Dharamgarh', gpName: 'CHILLIPA', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 46, block: 'Dharamgarh', gpName: 'DHANARPUR', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 47, block: 'Dharamgarh', gpName: 'DUMERGUDA', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 48, block: 'Dharamgarh', gpName: 'GADIAJORE', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 49, block: 'Dharamgarh', gpName: 'JAYANTPUR', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 50, block: 'Dharamgarh', gpName: 'KADALIMUNDA', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 51, block: 'Dharamgarh', gpName: 'KANAGAON', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 52, block: 'Dharamgarh', gpName: 'KANKERI(Starting Point)', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 53, block: 'Dharamgarh', gpName: 'KHAIRAPADAR', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 54, block: 'Dharamgarh', gpName: 'NANDAGAON', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 55, block: 'Dharamgarh', gpName: 'PARLA', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 56, block: 'Dharamgarh', gpName: 'SANDIKULIHARI', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 57, block: 'Dharamgarh', gpName: 'TAMBACHHADA', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 58, block: 'Dharamgarh', gpName: 'TARAPUR', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 59, block: 'Dharamgarh', gpName: 'TENDAPALI', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },
  { id: 60, block: 'Dharamgarh', gpName: 'TIPIGUDA', taggedUlb: 'Dharamgarh NAC', taggedMrf: 'Dharamgarh' },

  // Junagarh Block (61-94)
  { id: 61, block: 'Junagarh', gpName: 'ATIGAON', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 62, block: 'Junagarh', gpName: 'BALDIAMAL', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 63, block: 'Junagarh', gpName: 'BANIJARA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 64, block: 'Junagarh', gpName: 'BANKPALASH', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 65, block: 'Junagarh', gpName: 'B-TULSIPALI', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 66, block: 'Junagarh', gpName: 'BHAINRIGUDA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 67, block: 'Junagarh', gpName: 'BUDHIDARA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 68, block: 'Junagarh', gpName: 'CHARBAHAL', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 69, block: 'Junagarh', gpName: 'CHARBHATI', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 70, block: 'Junagarh', gpName: 'CHHORIAGARH', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 71, block: 'Junagarh', gpName: 'CHICHAIGUDA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 72, block: 'Junagarh', gpName: 'CHINGUDISAR', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 73, block: 'Junagarh', gpName: 'DASIGAON', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 74, block: 'Junagarh', gpName: 'DEYDARA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 75, block: 'Junagarh', gpName: 'DUNDELMAL', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 76, block: 'Junagarh', gpName: 'G.CHHENDIA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 77, block: 'Junagarh', gpName: 'HABASPUR', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 78, block: 'Junagarh', gpName: 'KALEIGAON', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 79, block: 'Junagarh', gpName: 'KALIAKUNDAL', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 80, block: 'Junagarh', gpName: 'KALOPALA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 81, block: 'Junagarh', gpName: 'KENDUPATI', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 82, block: 'Junagarh', gpName: 'MAHICHALA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 83, block: 'Junagarh', gpName: 'MALIGUDA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 84, block: 'Junagarh', gpName: 'MATIGAON', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 85, block: 'Junagarh', gpName: 'MERIABANDHLI', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 86, block: 'Junagarh', gpName: 'MUNDRAGUDA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 87, block: 'Junagarh', gpName: 'NAKTIGUDA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 88, block: 'Junagarh', gpName: 'NANDOL', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 89, block: 'Junagarh', gpName: 'PALASH', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 90, block: 'Junagarh', gpName: 'PILIKIA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 91, block: 'Junagarh', gpName: 'RAJPUR', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 92, block: 'Junagarh', gpName: 'S.KUNDAMAL', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 93, block: 'Junagarh', gpName: 'TALJARING', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },
  { id: 94, block: 'Junagarh', gpName: 'TALMALA', taggedUlb: 'Junagarh NAC', taggedMrf: 'Junagarh' },

  // Kesinga Block (95-120)
  { id: 95, block: 'Kesinga', gpName: 'ADHAMUNDA', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 96, block: 'Kesinga', gpName: 'BALSI', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 97, block: 'Kesinga', gpName: 'BELKHANDI', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 98, block: 'Kesinga', gpName: 'BORIA', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 102, block: 'Kesinga', gpName: 'CHANCHER', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 103, block: 'Kesinga', gpName: 'DEOGAON', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 104, block: 'Kesinga', gpName: 'GAIGAON   (KEROKUDA)', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 105, block: 'Kesinga', gpName: 'GOKULESWAR', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 106, block: 'Kesinga', gpName: 'HATIKHOJ', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 107, block: 'Kesinga', gpName: 'KANDEL', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 108, block: 'Kesinga', gpName: 'KANTESIR', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 109, block: 'Kesinga', gpName: 'KASRUPADA', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 110, block: 'Kesinga', gpName: 'KIKIA', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 111, block: 'Kesinga', gpName: 'KUNDABANDHA', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 112, block: 'Kesinga', gpName: 'LAITARA', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 113, block: 'Kesinga', gpName: 'NASIGAON', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 114, block: 'Kesinga', gpName: 'NUNMATH', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 115, block: 'Kesinga', gpName: 'PARALSINGA', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 116, block: 'Kesinga', gpName: 'PASTIKUDI', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 117, block: 'Kesinga', gpName: 'PATHARLA', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 118, block: 'Kesinga', gpName: 'PHATKAMAL', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 119, block: 'Kesinga', gpName: 'SIRJAPALI', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 120, block: 'Kesinga', gpName: 'SIROL', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 121, block: 'Kesinga', gpName: 'TUNDLA', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 122, block: 'Kesinga', gpName: 'TURLAKHAMAN', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
  { id: 123, block: 'Kesinga', gpName: 'UTKELA', taggedUlb: 'Kesinga NAC', taggedMrf: 'Kesinga' },
];
