export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // Block Umerkote - Umerkote ULB
  { id: 1, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'ANCHALA', wasteGeneratedKg: 166.42, gpNodalPerson: 'DEBASISH DASH', gpNodalContact: '9178037919', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 2, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BADABHARANDI', wasteGeneratedKg: 466.77, gpNodalPerson: 'SWAPAN SARKAR', gpNodalContact: '6370654257', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 3, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BADAKUMARI', wasteGeneratedKg: 357.79, gpNodalPerson: 'HANU NAYAK', gpNodalContact: '9178659284', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 4, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BAKODA', wasteGeneratedKg: 447.14, gpNodalPerson: 'HANU NAYAK', gpNodalContact: '9178659284', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 5, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BEHEDA', wasteGeneratedKg: 348.98, gpNodalPerson: 'SWAPAN SARKAR', gpNodalContact: '6370654257', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 6, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BENORA', wasteGeneratedKg: 358.15, gpNodalPerson: 'PRASANT KUMAR SAMAL', gpNodalContact: '7894802678', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 7, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BHAMINI', wasteGeneratedKg: 511.54, gpNodalPerson: 'DEBASISH DASH', gpNodalContact: '9178037919', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 8, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BHANDARIGUDA', wasteGeneratedKg: 345.13, gpNodalPerson: 'JOGENDRA BAIRAGI', gpNodalContact: '9668280079', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 9, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BURJA', wasteGeneratedKg: 464.75, gpNodalPerson: 'DEBASISH DASH', gpNodalContact: '9178037919', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 10, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'CHIKALAPADAR', wasteGeneratedKg: 290.82, gpNodalPerson: 'SUNITA BISSOYI', gpNodalContact: '8114628029', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 11, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'HIRAPUR', wasteGeneratedKg: 365.13, gpNodalPerson: 'PRASANT KUMAR SAMAL', gpNodalContact: '7894802678', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 12, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'JAMRONDA', wasteGeneratedKg: 346.78, gpNodalPerson: 'DEBASISH DASH', gpNodalContact: '9178037919', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 13, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'KARAGAM', wasteGeneratedKg: 422.74, gpNodalPerson: 'HANU NAYAK', gpNodalContact: '9178659284', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 14, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'KHANDA', wasteGeneratedKg: 316.87, gpNodalPerson: 'HIRA MAJHI', gpNodalContact: '9938639330', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 15, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'KOPENA', wasteGeneratedKg: 362.19, gpNodalPerson: 'SWAPAN SARKAR', gpNodalContact: '6370654257', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 16, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'KURSHI', wasteGeneratedKg: 237.42, gpNodalPerson: 'HIRA MAJHI', gpNodalContact: '9938639330', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 17, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'MUNDIGUDA', wasteGeneratedKg: 178.53, gpNodalPerson: 'JOGENDRA BAIRAGI', gpNodalContact: '9668280079', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 18, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'MURTUMMA', wasteGeneratedKg: 347.14, gpNodalPerson: 'DEBASISH DASH', gpNodalContact: '9178037919', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 19, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'NEHURA', wasteGeneratedKg: 286.96, gpNodalPerson: 'PRASANT KUMAR SAMAL', gpNodalContact: '7894802678', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 20, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'RAJPUR', wasteGeneratedKg: 382.92, gpNodalPerson: 'JOGENDRA BAIRAGI', gpNodalContact: '9668280079', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 21, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'SEMALA', wasteGeneratedKg: 366.04, gpNodalPerson: 'SUNITA BISSOYI', gpNodalContact: '8114628029', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 22, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'SINGISARI', wasteGeneratedKg: 351, gpNodalPerson: 'DIBAKAR MAJHI', gpNodalContact: '6372430325', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 23, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'SUKHIGAM A/C', wasteGeneratedKg: 143.85, gpNodalPerson: 'HANU NAYAK', gpNodalContact: '9178659284', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 24, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'SUNABEDA', wasteGeneratedKg: 297.97, gpNodalPerson: 'DEBASISH DASH', gpNodalContact: '9178037919', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 25, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'TOHARA', wasteGeneratedKg: 401.82, gpNodalPerson: 'SWAPAN SARKAR', gpNodalContact: '6370654257', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },
  { id: 26, block: 'Umerkote', ulb: 'UMERKOTE ULB', mrf: 'Umerkote', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'TORENGA', wasteGeneratedKg: 247.33, gpNodalPerson: 'DIBAKAR MAJHI', gpNodalContact: '6372430325', ulbNodalPerson: 'NILAMBARA BHATRA', ulbNodalContact: '7608899281' },

  // Block Nabarangpur - Nabarangpur ULB
  { id: 27, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'AGNIPUR', wasteGeneratedKg: 328.06, gpNodalPerson: 'GOURAV PRADHAN', gpNodalContact: '7894990648', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 28, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BADAMASIGAM', wasteGeneratedKg: 228.98, gpNodalPerson: 'GAYATRI BHANDARI', gpNodalContact: '7978703229', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 29, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BAGHASIUNI', wasteGeneratedKg: 458.15, gpNodalPerson: 'GOURAV PRADHAN', gpNodalContact: '7894990648', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 30, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BASINI', wasteGeneratedKg: 283.29, gpNodalPerson: 'H.K BIOSOI', gpNodalContact: '9937780104', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 31, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BHATRASIUNI', wasteGeneratedKg: 206.42, gpNodalPerson: 'GAYATRI BHANDARI', gpNodalContact: '7978703229', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 32, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BIKRAMPUR', wasteGeneratedKg: 193.20, gpNodalPerson: 'GOURAV PRADHAN', gpNodalContact: '7894990648', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 33, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'BADAKUMULI', wasteGeneratedKg: 341.46, gpNodalPerson: 'SASANKA SEKHAR MAJHI', gpNodalContact: '7788899334', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 34, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'CHATAHANDI', wasteGeneratedKg: 439.25, gpNodalPerson: 'H.K BIOSOI', gpNodalContact: '9937780104', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 35, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'MANTRIGUA', wasteGeneratedKg: 242.38, gpNodalPerson: 'SASANKA SEKHAR MAJHI', gpNodalContact: '7788899334', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 36, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'PUJARIGUDA', wasteGeneratedKg: 282.19, gpNodalPerson: 'GAYATRI BHANDARI', gpNodalContact: '7978703229', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 37, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'SANAMASIGAM', wasteGeneratedKg: 260.73, gpNodalPerson: 'A.K KHURA', gpNodalContact: '9556431795', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 38, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'SINDHIGAM', wasteGeneratedKg: 242.01, gpNodalPerson: 'A.K KHURA', gpNodalContact: '9556431795', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' },
  { id: 39, block: 'Nabarangpur', ulb: 'NABARANGAPUR ULB', mrf: 'Nabarangapur', vehicleType: 'Single Chamber Vehicle', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'Weekly Scheduled', gpName: 'TARAGAM', wasteGeneratedKg: 288.98, gpNodalPerson: 'SASANKA SEKHAR MAJHI', gpNodalContact: '7788899334', ulbNodalPerson: 'SUBHASMITA DHALA', ulbNodalContact: '8249255900' }
];
