
export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
  routeId?: string;
  routeName?: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // BALLIGUDA Block
  { id: 1, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Kailash Pradhan', driverContact: '9438243009', collectionSchedule: '10/25 th of Every Month', gpName: 'BARAKHAMA', wasteGeneratedKg: 795, gpNodalPerson: 'Kartikeswar Behera', gpNodalContact: '8144939544', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBALRBPD1', routeName: 'RBPD-01' },
  { id: 2, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Kailash Pradhan', driverContact: '9438243009', collectionSchedule: '10/25 th of Every Month', gpName: 'BATAGUDA', wasteGeneratedKg: 819, gpNodalPerson: 'Susanta Pradhan', gpNodalContact: '7852941236', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBALRBPD1', routeName: 'RBPD-01' },
  { id: 3, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Niranjan Mallick', driverContact: '7847993685', collectionSchedule: '10/25 th of Every Month', gpName: 'BUDRUKIA', wasteGeneratedKg: 625, gpNodalPerson: 'Chinmayee Sasmal', gpNodalContact: '7789929224', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBALSBK2', routeName: 'SBK-02' },
  { id: 4, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Niranjan Mallick', driverContact: '7847993685', collectionSchedule: '10/25 th of Every Month', gpName: 'DADAKANGIA', wasteGeneratedKg: 459, gpNodalPerson: 'Banambar Desinayak', gpNodalContact: '7008071653', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBALRBPD1', routeName: 'RBPD-01' },
  { id: 5, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Kusha Mallick', driverContact: '7848885726', collectionSchedule: '10/25 th of Every Month', gpName: 'KHAMANKHOL', wasteGeneratedKg: 811, gpNodalPerson: 'Lilsan Nayak', gpNodalContact: '8847879362', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBASKL4', routeName: 'SKL-04' },
  { id: 6, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Niranjan Mallick', driverContact: '7847993685', collectionSchedule: '10/25 th of Every Month', gpName: 'KUTIKIA', wasteGeneratedKg: 607, gpNodalPerson: 'Sujit kuamar Sahu', gpNodalContact: '7008155972', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBALSBK2', routeName: 'SBK-02' },
  { id: 7, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Kusha Mallick', driverContact: '7848885726', collectionSchedule: '10/25 th of Every Month', gpName: 'LANDAGAON', wasteGeneratedKg: 606, gpNodalPerson: 'Bipin Kanhar', gpNodalContact: '8260517315', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBASKL4', routeName: 'SKL-04' },
  { id: 8, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Simanchal Mallick', driverContact: '7978466283', collectionSchedule: '10/25 th of Every Month', gpName: 'MEDIAKIA', wasteGeneratedKg: 384, gpNodalPerson: 'Aditya Ranjan Bishoy', gpNodalContact: '8249612781', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBALMRBS3', routeName: 'MRBS-03' },
  { id: 9, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Kailash Pradhan', driverContact: '9438243009', collectionSchedule: '10/25 th of Every Month', gpName: 'PARAMPANGA', wasteGeneratedKg: 532, gpNodalPerson: 'Banambar Desinayak', gpNodalContact: '7008071653', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBALRBPD1', routeName: 'RBPD-01' },
  { id: 10, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Simanchal Mallick', driverContact: '7978466283', collectionSchedule: '10/25 th of Every Month', gpName: 'REBINGIA', wasteGeneratedKg: 594, gpNodalPerson: 'Kartikeswar Behera', gpNodalContact: '8144939544', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBALMRBS3', routeName: 'MRBS-03' },
  { id: 11, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Kailash Pradhan', driverContact: '9438243009', collectionSchedule: '10/25 th of Every Month', gpName: 'RUTUNGIA', wasteGeneratedKg: 768, gpNodalPerson: 'Sujit kuamar Sahu', gpNodalContact: '7008155972', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBALRBPD1', routeName: 'RBPD-01' },
  { id: 12, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Niranjan Mallick', driverContact: '7847993685', collectionSchedule: '10/25 th of Every Month', gpName: 'SINDRIGAON', wasteGeneratedKg: 750, gpNodalPerson: 'Priyabrata Sahu', gpNodalContact: '7008587094', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBALSBK2', routeName: 'SBK-02' },
  { id: 13, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Simanchal Mallick', driverContact: '7978466283', collectionSchedule: '10/25 th of Every Month', gpName: 'SALAGUDA', wasteGeneratedKg: 693, gpNodalPerson: 'Akshya Kumar Nayak', gpNodalContact: '8249994708', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBALMRBS3', routeName: 'MRBS-03' },
  { id: 14, block: 'Balliguda', ulb: 'BALLIGUDA ULB', mrf: 'BALLIGUDA ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Kusha Mallick', driverContact: '7848885726', collectionSchedule: '10/25 th of Every Month', gpName: 'SUDRA', wasteGeneratedKg: 792, gpNodalPerson: 'Priyabrata Sahu', gpNodalContact: '7008587094', ulbNodalPerson: 'Hitesh', ulbNodalContact: '8249398759', routeId: 'KBASKL4', routeName: 'SKL-04' },

  // Phulbani Block
  { id: 15, block: 'Phulbani', ulb: 'Phulbani ULB', mrf: 'Phulbani ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Swapna Kanhar', driverContact: '8763588727', collectionSchedule: '15/25th every month', gpName: 'Alami', wasteGeneratedKg: 1127, gpNodalPerson: 'Anurag Patanaik', gpNodalContact: '8763479784', ulbNodalPerson: 'Jayapal Baliarsingh', ulbNodalContact: '7978776263', routeId: 'KPHUAGM3', routeName: 'AGM-03' },
  { id: 16, block: 'Phulbani', ulb: 'Phulbani ULB', mrf: 'Phulbani ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Swapna Kanhar', driverContact: '8763588727', collectionSchedule: '15/25th every month', gpName: 'Bisipada', wasteGeneratedKg: 1502, gpNodalPerson: 'Anurag Patanaik', gpNodalContact: '8763479784', ulbNodalPerson: 'Jayapal Baliarsingh', ulbNodalContact: '7978776263', routeId: 'KPHUDDB2', routeName: 'DDB-02' },
  { id: 17, block: 'Phulbani', ulb: 'Phulbani ULB', mrf: 'Phulbani ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Bhagabat Sahu', driverContact: '7853033290', collectionSchedule: '15/25th every month', gpName: 'Dadaki', wasteGeneratedKg: 1083, gpNodalPerson: 'Amitanshu Nayak', gpNodalContact: '6370563842', ulbNodalPerson: 'Jayapal Baliarsingh', ulbNodalContact: '7978776263', routeId: 'KPHUDDB2', routeName: 'DDB-02' },
  { id: 18, block: 'Phulbani', ulb: 'Phulbani ULB', mrf: 'Phulbani ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Bhagabat Sahu', driverContact: '7853033290', collectionSchedule: '15/25th every month', gpName: 'Duduki', wasteGeneratedKg: 959, gpNodalPerson: 'Amitanshu Nayak', gpNodalContact: '6370563842', ulbNodalPerson: 'Jayapal Baliarsingh', ulbNodalContact: '7978776263', routeId: 'KPHUDDB2', routeName: 'DDB-02' },
  { id: 19, block: 'Phulbani', ulb: 'Phulbani ULB', mrf: 'Phulbani ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Pradip Ch Mallick', driverContact: '7016310215', collectionSchedule: '15/25th every month', gpName: 'Ganjuguda', wasteGeneratedKg: 1181, gpNodalPerson: 'Sibani Sahu', gpNodalContact: '6372894692', ulbNodalPerson: 'Jayapal Baliarsingh', ulbNodalContact: '7978776263', routeId: 'KPHUAGM3', routeName: 'AGM-03' },
  { id: 20, block: 'Phulbani', ulb: 'Phulbani ULB', mrf: 'Phulbani ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Akash Mukhi', driverContact: '8763885622', collectionSchedule: '15/25th every month', gpName: 'Gumagarh', wasteGeneratedKg: 1176, gpNodalPerson: 'Ranjeet Kanhar', gpNodalContact: '8144509917', ulbNodalPerson: 'Jayapal Baliarsingh', ulbNodalContact: '7978776263', routeId: 'KPHUKG4', routeName: 'KG-04' },
  { id: 21, block: 'Phulbani', ulb: 'Phulbani ULB', mrf: 'Phulbani ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Swapna Kanhar', driverContact: '8763588727', collectionSchedule: '15/25th every month', gpName: 'Jamjhari', wasteGeneratedKg: 893, gpNodalPerson: 'Alentrevarini Sahu', gpNodalContact: '8249836354', ulbNodalPerson: 'Jayapal Baliarsingh', ulbNodalContact: '7978776263', routeId: 'KPHUTJK1', routeName: 'TJK-01' },
  { id: 22, block: 'Phulbani', ulb: 'Phulbani ULB', mrf: 'Phulbani ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Swapna Kanhar', driverContact: '8763588727', collectionSchedule: '15/25th every month', gpName: 'Katringia', wasteGeneratedKg: 1590, gpNodalPerson: 'Nandirath Digal', gpNodalContact: '8249710587', ulbNodalPerson: 'Jayapal Baliarsingh', ulbNodalContact: '7978776263', routeId: 'KPHUTJK1', routeName: 'TJK-01' },
  { id: 23, block: 'Phulbani', ulb: 'Phulbani ULB', mrf: 'Phulbani ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Pradip Ch Mallick', driverContact: '7016310215', collectionSchedule: '15/25th every month', gpName: 'Keredi', wasteGeneratedKg: 1281, gpNodalPerson: 'Sibani Sahu', gpNodalContact: '6372894692', ulbNodalPerson: 'Jayapal Baliarsingh', ulbNodalContact: '7978776263', routeId: 'KPHUAGM3', routeName: 'AGM-03' },
  { id: 24, block: 'Phulbani', ulb: 'Phulbani ULB', mrf: 'Phulbani ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Akash Mukhi', driverContact: '8763885622', collectionSchedule: '15/25th every month', gpName: 'Minia', wasteGeneratedKg: 966, gpNodalPerson: 'Ranjeet Kanhar', gpNodalContact: '8144509917', ulbNodalPerson: 'Jayapal Baliarsingh', ulbNodalContact: '7978776263', routeId: 'KPHUAGM3', routeName: 'AGM-03' },
  { id: 25, block: 'Phulbani', ulb: 'Phulbani ULB', mrf: 'Phulbani ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'Swapna Kanhar', driverContact: '8763588727', collectionSchedule: '15/25th every month', gpName: 'Tudipaju', wasteGeneratedKg: 1182, gpNodalPerson: 'Deepali Bastia', gpNodalContact: '9439433323', ulbNodalPerson: 'Jayapal Baliarsingh', ulbNodalContact: '7978776263', routeId: 'KPHUTJK1', routeName: 'TJK-01' },

  // G.UDAYAGIRI Block
  { id: 26, block: 'G.UDAYAGIRI', ulb: 'G.UDAYAGIRI ULB', mrf: 'G.UDAYAGIRI ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'MIKHAEL PRADHAN', driverContact: '8763471012', collectionSchedule: '15/25th of Every Month', gpName: 'MALIKAPADI', wasteGeneratedKg: 2340, gpNodalPerson: 'SAPTASIRA BALIARSINGH', gpNodalContact: '8249560918', ulbNodalPerson: 'JHALAK DASH', ulbNodalContact: '9438450233', routeId: 'KGUDKTM-1', routeName: 'KTM--01' },
  { id: 27, block: 'G.UDAYAGIRI', ulb: 'G.UDAYAGIRI ULB', mrf: 'G.UDAYAGIRI ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'MIKHAEL PRADHAN', driverContact: '8763471012', collectionSchedule: '15/25th of Every Month', gpName: 'TALARIMAHA', wasteGeneratedKg: 826, gpNodalPerson: 'SAPTASIRA BALIARSINGH', gpNodalContact: '8249560918', ulbNodalPerson: 'JHALAK DASH', ulbNodalContact: '9438450233', routeId: 'KGUDKTM-1', routeName: 'KTM--01' },
  { id: 28, block: 'G.UDAYAGIRI', ulb: 'G.UDAYAGIRI ULB', mrf: 'G.UDAYAGIRI ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'MIKHAEL PRADHAN', driverContact: '8763471012', collectionSchedule: '15/25th of Every Month', gpName: 'KALINGA', wasteGeneratedKg: 2383, gpNodalPerson: 'SAPTASIRA BALIARSINGH', gpNodalContact: '8249560918', ulbNodalPerson: 'JHALAK DASH', ulbNodalContact: '9438450233', routeId: 'KGUDKTM-1', routeName: 'KTM--01' },
  { id: 29, block: 'G.UDAYAGIRI', ulb: 'G.UDAYAGIRI ULB', mrf: 'G.UDAYAGIRI ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'CHINMAYA PRADHAN', driverContact: '8637217780', collectionSchedule: '15/25th of Every Month', gpName: 'GRESSINGIA', wasteGeneratedKg: 1260, gpNodalPerson: 'SAPTASIRA BALIARSINGH', gpNodalContact: '8249560918', ulbNodalPerson: 'JHALAK DASH', ulbNodalContact: '9438450233', routeId: 'KGUDRG-3', routeName: 'RG-3' },
  { id: 30, block: 'G.UDAYAGIRI', ulb: 'G.UDAYAGIRI ULB', mrf: 'G.UDAYAGIRI ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'CHINMAYA PRADHAN', driverContact: '8637217780', collectionSchedule: '15/25th of Every Month', gpName: 'RATINGIA', wasteGeneratedKg: 1033, gpNodalPerson: 'SAPTASIRA BALIARSINGH', gpNodalContact: '8249560918', ulbNodalPerson: 'JHALAK DASH', ulbNodalContact: '9438450233', routeId: 'KGUDRG-3', routeName: 'RG-3' },
  { id: 31, block: 'G.UDAYAGIRI', ulb: 'G.UDAYAGIRI ULB', mrf: 'G.UDAYAGIRI ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'BIRUPAKSHYA PRADHAN', driverContact: '8144722967', collectionSchedule: '15/25th of Every Month', gpName: 'LINGAGADA', wasteGeneratedKg: 1297, gpNodalPerson: 'SAPTASIRA BALIARSINGH', gpNodalContact: '8249560918', ulbNodalPerson: 'JHALAK DASH', ulbNodalContact: '9438450233', routeId: 'KGUDKLR-2', routeName: 'KLR-2' },
  { id: 32, block: 'G.UDAYAGIRI', ulb: 'G.UDAYAGIRI ULB', mrf: 'G.UDAYAGIRI ULB', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400 Kg', driverName: 'BIRUPAKSHYA PRADHAN', driverContact: '8144722967', collectionSchedule: '15/25th of Every Month', gpName: 'RAIKALA', wasteGeneratedKg: 1093, gpNodalPerson: 'SAPTASIRA BALIARSINGH', gpNodalContact: '8249560918', ulbNodalPerson: 'JHALAK DASH', ulbNodalContact: '9438450233', routeId: 'KGUDKLR-2', routeName: 'KLR-2' },
];
