
export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  {
    id: 1,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '1st and 16th of each month',
    gpName: 'Badchhapal',
    wasteGeneratedKg: 1835,
    gpNodalPerson: 'Rajesh Pradhan',
    gpNodalContact: '9938349645',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 2,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '1st and 16th of each month',
    gpName: 'Cheplipalli',
    wasteGeneratedKg: 2342,
    gpNodalPerson: 'Sushreesmita Dehury',
    gpNodalContact: '6372972096',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 3,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '1st and 16th of each month',
    gpName: 'Suguda',
    wasteGeneratedKg: 1419,
    gpNodalPerson: 'Nilakanta Pradhan',
    gpNodalContact: '9556733292',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 4,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '1st and 16th of each month',
    gpName: 'Baniakilinda',
    wasteGeneratedKg: 1820,
    gpNodalPerson: 'Nilakanta Pradhan',
    gpNodalContact: '9556733292',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 5,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '4th and 19th of each month',
    gpName: 'Tileibani',
    wasteGeneratedKg: 2714,
    gpNodalPerson: 'Lili Mahananda',
    gpNodalContact: '8457082977',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 6,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '4th and 19th of each month',
    gpName: 'Tainsar',
    wasteGeneratedKg: 2161,
    gpNodalPerson: 'Mantu Kisan',
    gpNodalContact: '6371001148',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 7,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '4th and 19th of each month',
    gpName: 'Kalanda',
    wasteGeneratedKg: 1383,
    gpNodalPerson: 'Harapriya Sahu',
    gpNodalContact: '8455050205',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 8,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '7th and 22nd of each month',
    gpName: 'Dholpada',
    wasteGeneratedKg: 1747,
    gpNodalPerson: 'Basanta Dehury',
    gpNodalContact: '9178890134',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 9,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '7th and 22nd of each month',
    gpName: 'Dudhianalli',
    wasteGeneratedKg: 1761,
    gpNodalPerson: 'Tuhinkanta Pradhan',
    gpNodalContact: '9178164540',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 10,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '7th and 22nd of each month',
    gpName: 'Talkundi',
    wasteGeneratedKg: 1763,
    gpNodalPerson: 'Rashmi Pradhan',
    gpNodalContact: '7077966021',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 11,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '10th and 25th of each month',
    gpName: 'Sodo',
    wasteGeneratedKg: 1333,
    gpNodalPerson: 'Sourav Behera',
    gpNodalContact: '9556115814',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 12,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '10th and 25th of each month',
    gpName: 'Kansar',
    wasteGeneratedKg: 2171,
    gpNodalPerson: 'Chinmaya Pradhan',
    gpNodalContact: '7749849676',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 13,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '10th and 25th of each month',
    gpName: 'Palkudar',
    wasteGeneratedKg: 751,
    gpNodalPerson: 'Subhasini Majhi',
    gpNodalContact: '8984629610',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 14,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '10th and 25th of each month',
    gpName: 'Kendeijhuri',
    wasteGeneratedKg: 1661,
    gpNodalPerson: 'Hemanta Sahu',
    gpNodalContact: '9437456069',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 15,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '9th, 18th and 28th of each month',
    gpName: 'Laimura',
    wasteGeneratedKg: 1591,
    gpNodalPerson: 'Bipin Bihari Pradhan',
    gpNodalContact: '9668179907',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 16,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '9th, 18th and 28th of each month',
    gpName: 'Jharmunda',
    wasteGeneratedKg: 688,
    gpNodalPerson: 'Tapaban Dehury',
    gpNodalContact: '9668899639',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 17,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '9th, 18th and 28th of each month',
    gpName: 'Parposi',
    wasteGeneratedKg: 758,
    gpNodalPerson: 'Cherudhar Dehury',
    gpNodalContact: '7077017971',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 18,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '9th, 18th and 28th of each month',
    gpName: 'Dimirikuda',
    wasteGeneratedKg: 830,
    gpNodalPerson: 'Tapaban Dehury',
    gpNodalContact: '9668899639',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 19,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '9th, 18th and 28th of each month',
    gpName: 'Gandam',
    wasteGeneratedKg: 804,
    gpNodalPerson: 'Sipun Kumar Naik',
    gpNodalContact: '7606096090',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  },
  {
    id: 20,
    block: 'Tileibani',
    ulb: 'Deogarh Municipality',
    mrf: 'Deogarh (Benjatinali)',
    vehicleType: 'TATA Ace (temporary)',
    vehicleNo: '-',
    vehicleCapacity: '500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: '9th, 18th and 28th of each month',
    gpName: 'Jharagogua',
    wasteGeneratedKg: 970,
    gpNodalPerson: 'Cherudhar Dehury',
    gpNodalContact: '7077017971',
    ulbNodalPerson: 'Anil',
    ulbNodalContact: '8456991015'
  }
];
