export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
  routeId?: string;
  routeName?: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // Jharsuguda Block (Jharsuguda ULB)
  { id: 1, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'Jamera', wasteGeneratedKg: 82.077, gpNodalPerson: 'Nisikanta Chand', gpNodalContact: '8455052530', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473575', routeId: 'JJHAJMBH', routeName: 'JMBH-01' },
  { id: 2, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'Marakuta', wasteGeneratedKg: 81.194, gpNodalPerson: 'Bedabyash Jagadal', gpNodalContact: '9777605186', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473576', routeId: 'JJHAJMBH', routeName: 'JMBH-01' },
  { id: 3, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'Badamal', wasteGeneratedKg: 121.658, gpNodalPerson: 'Laxhmikanta Kansrali', gpNodalContact: '7077527555', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473577', routeId: 'JJHAJMBH', routeName: 'JMBH-01' },
  { id: 4, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'H. Katapali', wasteGeneratedKg: 177.053, gpNodalPerson: 'Bansidhar Maharana', gpNodalContact: '7077964707', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473578', routeId: 'JJHAJMBH', routeName: 'JMBH-01' },
  { id: 5, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'Hirma', wasteGeneratedKg: 147.456, gpNodalPerson: 'Sabyasachi Nayak', gpNodalContact: '8658499570', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473579', routeId: 'JJHAHSPM', routeName: 'HSPM-02' },
  { id: 6, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'Sripura', wasteGeneratedKg: 66.793, gpNodalPerson: 'Sabyasachi Nayak', gpNodalContact: '8658499571', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473580', routeId: 'JJHAHSPM', routeName: 'HSPM-02' },
  { id: 7, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'Patrapali', wasteGeneratedKg: 57.251, gpNodalPerson: 'Subrat Naik', gpNodalContact: '8658133043', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473581', routeId: 'JJHAHSPM', routeName: 'HSPM-02' },
  { id: 8, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'Malda', wasteGeneratedKg: 52.215, gpNodalPerson: 'Subrat Naik', gpNodalContact: '8658133044', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473582', routeId: 'JJHAHSPM', routeName: 'HSPM-02' },
  { id: 9, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'Durlaga', wasteGeneratedKg: 89.499, gpNodalPerson: 'Nimai Neti', gpNodalContact: '7846809532', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473583', routeId: 'JJHADTDK', routeName: 'DTDK-03' },
  { id: 10, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'Talpatia', wasteGeneratedKg: 80.487, gpNodalPerson: 'Jasoda Kisan', gpNodalContact: '7978371442', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473584', routeId: 'JJHADTDK', routeName: 'DTDK-03' },
  { id: 11, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'Dalki', wasteGeneratedKg: 78.543, gpNodalPerson: 'Dinesh Sunani', gpNodalContact: '7008472965', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473585', routeId: 'JJHADTDK', routeName: 'DTDK-03' },
  { id: 12, block: 'Jharsuguda', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4446', vehicleCapacity: '400KG', driverName: 'Subrat Panday', driverContact: '8457959345', collectionSchedule: 'As and when required by GP', gpName: 'Katikela', wasteGeneratedKg: 63.789, gpNodalPerson: 'Nimei Neti', gpNodalContact: '7846809532', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JJHADTDK', routeName: 'DTDK-03' },

  // Kirmira Block (Jharsuguda ULB)
  { id: 13, block: 'Kirmira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4404', vehicleCapacity: '400KG', driverName: 'Pramod Rohidas', driverContact: '7978050194', collectionSchedule: 'As and when required by GP', gpName: 'Arda', wasteGeneratedKg: 189.069, gpNodalPerson: 'Kedar Patel', gpNodalContact: '381318878', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKIRASBJ', routeName: 'ASBJ-01' },
  { id: 14, block: 'Kirmira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4404', vehicleCapacity: '400KG', driverName: 'Pramod Rohidas', driverContact: '7978050194', collectionSchedule: 'As and when required by GP', gpName: 'Sulehi', wasteGeneratedKg: 150.902, gpNodalPerson: 'Tapaswini Kunar', gpNodalContact: '700859311', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKIRASBJ', routeName: 'ASBJ-01' },
  { id: 15, block: 'Kirmira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4404', vehicleCapacity: '400KG', driverName: 'Pramod Rohidas', driverContact: '7978050194', collectionSchedule: 'As and when required by GP', gpName: 'Bhimjore', wasteGeneratedKg: 72.800, gpNodalPerson: 'Pradeep Naik', gpNodalContact: '9692238393', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKIRASBJ', routeName: 'ASBJ-01' },
  { id: 16, block: 'Kirmira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4404', vehicleCapacity: '400KG', driverName: 'Pramod Rohidas', driverContact: '7978050194', collectionSchedule: 'As and when required by GP', gpName: 'Jharmunda', wasteGeneratedKg: 132.172, gpNodalPerson: 'Kalpana Kumbar', gpNodalContact: '7978992902', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKIRASBJ', routeName: 'ASBJ-01' },
  { id: 17, block: 'Kirmira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4404', vehicleCapacity: '400KG', driverName: 'Pramod Rohidas', driverContact: '7978050194', collectionSchedule: 'As and when required by GP', gpName: 'Bandhpali', wasteGeneratedKg: 107.080, gpNodalPerson: 'Jagabandhu Duan', gpNodalContact: '7327985098', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKIRBKNG', routeName: 'BKNG-02' },
  { id: 18, block: 'Kirmira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4404', vehicleCapacity: '400KG', driverName: 'Pramod Rohidas', driverContact: '7978050194', collectionSchedule: 'As and when required by GP', gpName: 'Kirmira', wasteGeneratedKg: 139.416, gpNodalPerson: 'Salini Sathua', gpNodalContact: '7205929942', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKIRBKNG', routeName: 'BKNG-02' },
  { id: 19, block: 'Kirmira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4404', vehicleCapacity: '400KG', driverName: 'Pramod Rohidas', driverContact: '7978050194', collectionSchedule: 'As and when required by GP', gpName: 'Naxapali', wasteGeneratedKg: 132.260, gpNodalPerson: 'Jagabandhu Duan', gpNodalContact: '7327985098', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKIRBKNG', routeName: 'BKNG-02' },
  { id: 20, block: 'Kirmira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4404', vehicleCapacity: '400KG', driverName: 'Pramod Rohidas', driverContact: '7978050194', collectionSchedule: 'As and when required by GP', gpName: 'G.panpali', wasteGeneratedKg: 91.619, gpNodalPerson: 'Kedar Patel', gpNodalContact: '381318878', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKIRBKNG', routeName: 'BKNG-02' },

  // Kolabira Block (Jharsuguda ULB)
  { id: 21, block: 'Kolabira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4468', vehicleCapacity: '400KG', driverName: 'Visal Behera', driverContact: '9692472882', collectionSchedule: 'As and when required by GP', gpName: 'Jhirlapali', wasteGeneratedKg: 111.674, gpNodalPerson: 'Satyajit Meher', gpNodalContact: '8328898996', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKOLJPKSS', routeName: 'JPKSS-01' },
  { id: 22, block: 'Kolabira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4468', vehicleCapacity: '400KG', driverName: 'Visal Behera', driverContact: '9692472882', collectionSchedule: 'As and when required by GP', gpName: 'Pokharisale', wasteGeneratedKg: 204.619, gpNodalPerson: 'Satyajit Meher', gpNodalContact: '8328898997', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKOLJPKSS', routeName: 'JPKSS-01' },
  { id: 23, block: 'Kolabira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4468', vehicleCapacity: '400KG', driverName: 'Visal Behera', driverContact: '9692472882', collectionSchedule: 'As and when required by GP', gpName: 'Kulihamal', wasteGeneratedKg: 81.989, gpNodalPerson: 'Rajesh Padhy', gpNodalContact: '7008901639', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKOLJPKSS', routeName: 'JPKSS-01' },
  { id: 24, block: 'Kolabira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4468', vehicleCapacity: '400KG', driverName: 'Visal Behera', driverContact: '9692472882', collectionSchedule: 'As and when required by GP', gpName: 'Samasingha', wasteGeneratedKg: 125.280, gpNodalPerson: 'Tarani Pradhan', gpNodalContact: '8249651617', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKOLJPKSS', routeName: 'JPKSS-01' },
  { id: 25, block: 'Kolabira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4468', vehicleCapacity: '400KG', driverName: 'Visal Behera', driverContact: '9692472882', collectionSchedule: 'As and when required by GP', gpName: 'Sodamal', wasteGeneratedKg: 128.549, gpNodalPerson: 'Tarani Pradhan', gpNodalContact: '8249651618', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKOLJPKSS', routeName: 'JPKSS-01' },
  { id: 26, block: 'Kolabira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4468', vehicleCapacity: '400KG', driverName: 'Visal Behera', driverContact: '9692472882', collectionSchedule: 'As and when required by GP', gpName: 'Kolabira', wasteGeneratedKg: 130.758, gpNodalPerson: 'Santosh Majhi', gpNodalContact: '7855914841', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKOLKRKP', routeName: 'KRKP-02' },
  { id: 27, block: 'Kolabira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4468', vehicleCapacity: '400KG', driverName: 'Visal Behera', driverContact: '9692472882', collectionSchedule: 'As and when required by GP', gpName: 'Raghunathpali', wasteGeneratedKg: 125.899, gpNodalPerson: 'Okila Pradhan', gpNodalContact: '7008718374', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKOLKRKP', routeName: 'KRKP-02' },
  { id: 28, block: 'Kolabira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4468', vehicleCapacity: '400KG', driverName: 'Visal Behera', driverContact: '9692472882', collectionSchedule: 'As and when required by GP', gpName: 'Keldamal', wasteGeneratedKg: 141.448, gpNodalPerson: 'Rajesh Padhy', gpNodalContact: '7008901639', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKOLKRKP', routeName: 'KRKP-02' },
  { id: 29, block: 'Kolabira', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P4468', vehicleCapacity: '400KG', driverName: 'Visal Behera', driverContact: '9692472882', collectionSchedule: 'As and when required by GP', gpName: 'Paramanpur', wasteGeneratedKg: 130.228, gpNodalPerson: 'Okila Pradhan', gpNodalContact: '7008718374', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JKOLKRKP', routeName: 'KRKP-02' },

  // Laikera Block (Jharsuguda ULB)
  { id: 30, block: 'Laikera', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P5975', vehicleCapacity: '400KG', driverName: 'Ajit Patel', driverContact: '732999324', collectionSchedule: 'As and when required by GP', gpName: 'Bhatlaida', wasteGeneratedKg: 140.211, gpNodalPerson: 'Dusmanta Pujahari', gpNodalContact: '9668510250', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JLAIBLSK', routeName: 'BLSK-01' },
  { id: 31, block: 'Laikera', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P5975', vehicleCapacity: '400KG', driverName: 'Ajit Patel', driverContact: '732999324', collectionSchedule: 'As and when required by GP', gpName: 'Laikera', wasteGeneratedKg: 71.564, gpNodalPerson: 'Dusmanta Pujahari', gpNodalContact: '9668510251', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JLAIBLSK', routeName: 'BLSK-01' },
  { id: 32, block: 'Laikera', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P5975', vehicleCapacity: '400KG', driverName: 'Ajit Patel', driverContact: '732999324', collectionSchedule: 'As and when required by GP', gpName: 'Saranglai', wasteGeneratedKg: 119.361, gpNodalPerson: 'Jamuna Bag', gpNodalContact: '6371129681', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JLAIBLSK', routeName: 'BLSK-01' },
  { id: 33, block: 'Laikera', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P5975', vehicleCapacity: '400KG', driverName: 'Ajit Patel', driverContact: '732999324', collectionSchedule: 'As and when required by GP', gpName: 'Kulemura', wasteGeneratedKg: 128.108, gpNodalPerson: 'Sudam Tripathy', gpNodalContact: '9937386224', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JLAIBLSK', routeName: 'BLSK-01' },
  { id: 34, block: 'Laikera', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P5975', vehicleCapacity: '400KG', driverName: 'Ajit Patel', driverContact: '732999324', collectionSchedule: 'As and when required by GP', gpName: 'Babuchipidhi', wasteGeneratedKg: 108.405, gpNodalPerson: 'Jagdish Naik', gpNodalContact: '9937934520', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JLAIBJTP', routeName: 'BJTP-02' },
  { id: 35, block: 'Laikera', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P5975', vehicleCapacity: '400KG', driverName: 'Ajit Patel', driverContact: '732999324', collectionSchedule: 'As and when required by GP', gpName: 'Jammal', wasteGeneratedKg: 94.093, gpNodalPerson: 'Laxhmi Sahoo', gpNodalContact: '9861259166', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JLAIBJTP', routeName: 'BJTP-02' },
  { id: 36, block: 'Laikera', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P5975', vehicleCapacity: '400KG', driverName: 'Ajit Patel', driverContact: '732999324', collectionSchedule: 'As and when required by GP', gpName: 'Teleimal', wasteGeneratedKg: 125.015, gpNodalPerson: 'Hrudananda Patel', gpNodalContact: '7978818282', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JLAIBJTP', routeName: 'BJTP-02' },
  { id: 37, block: 'Laikera', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P5975', vehicleCapacity: '400KG', driverName: 'Ajit Patel', driverContact: '732999324', collectionSchedule: 'As and when required by GP', gpName: 'Pakelpada', wasteGeneratedKg: 116.269, gpNodalPerson: 'Sudam Tripathy', gpNodalContact: '9937386224', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JLAIBJTP', routeName: 'BJTP-02' },
  { id: 38, block: 'Laikera', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P5975', vehicleCapacity: '400KG', driverName: 'Ajit Patel', driverContact: '732999324', collectionSchedule: 'As and when required by GP', gpName: 'Sahaspur', wasteGeneratedKg: 97.627, gpNodalPerson: 'Hrudananda Patel', gpNodalContact: '7978818282', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JLAISKN', routeName: 'SKN-03' },
  { id: 39, block: 'Laikera', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P5975', vehicleCapacity: '400KG', driverName: 'Ajit Patel', driverContact: '732999324', collectionSchedule: 'As and when required by GP', gpName: 'Khuntamal', wasteGeneratedKg: 92.237, gpNodalPerson: 'Bijay Bag', gpNodalContact: '7008532955', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JLAISKN', routeName: 'SKN-03' },
  { id: 40, block: 'Laikera', ulb: 'Jharsuguda', mrf: 'Jharsuguda MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD23P5975', vehicleCapacity: '400KG', driverName: 'Ajit Patel', driverContact: '732999324', collectionSchedule: 'As and when required by GP', gpName: 'Niktimal', wasteGeneratedKg: 100.542, gpNodalPerson: 'Khetraranjan Adha', gpNodalContact: '7008524588', ulbNodalPerson: 'Nabadipti Sahu', ulbNodalContact: '9348473586', routeId: 'JLAISKN', routeName: 'SKN-03' },

  // Jharsuguda Block (Brajarajnagar ULB)
  { id: 41, block: 'Jharsuguda', ulb: 'Brajarajnagar', mrf: 'Brajarajnagar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD05CB8268', vehicleCapacity: '400KG', driverName: 'Manoj Dilla', driverContact: '7752096410', collectionSchedule: 'As and when required by GP', gpName: 'Gourmal', wasteGeneratedKg: 59.106, gpNodalPerson: 'Anil Duan', gpNodalContact: '9337589405', ulbNodalPerson: 'Pradeep Behera', ulbNodalContact: '9437174514', routeId: 'JJHAGRLKC', routeName: 'GRLKC-01' },
  { id: 42, block: 'Jharsuguda', ulb: 'Brajarajnagar', mrf: 'Brajarajnagar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD05CB8268', vehicleCapacity: '400KG', driverName: 'Manoj Dilla', driverContact: '7752096410', collectionSchedule: 'As and when required by GP', gpName: 'Rajpur', wasteGeneratedKg: 123.778, gpNodalPerson: 'Anil Duan', gpNodalContact: '9337589406', ulbNodalPerson: 'Pradeep Behera', ulbNodalContact: '9437174514', routeId: 'JJHAGRLKC', routeName: 'GRLKC-01' },
  { id: 43, block: 'Jharsuguda', ulb: 'Brajarajnagar', mrf: 'Brajarajnagar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD05CB8268', vehicleCapacity: '400KG', driverName: 'Manoj Dilla', driverContact: '7752096410', collectionSchedule: 'As and when required by GP', gpName: 'Lohising', wasteGeneratedKg: 166.363, gpNodalPerson: 'Chidananda Naik', gpNodalContact: '7978512407', ulbNodalPerson: 'Pradeep Behera', ulbNodalContact: '9437174514', routeId: 'JJHAGRLKC', routeName: 'GRLKC-01' },
  { id: 44, block: 'Jharsuguda', ulb: 'Brajarajnagar', mrf: 'Brajarajnagar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD05CB8268', vehicleCapacity: '400KG', driverName: 'Manoj Dilla', driverContact: '7752096410', collectionSchedule: 'As and when required by GP', gpName: 'Kudapali', wasteGeneratedKg: 114.767, gpNodalPerson: 'Dinesh Sunani', gpNodalContact: '7008472965', ulbNodalPerson: 'Pradeep Behera', ulbNodalContact: '9437174514', routeId: 'JJHAGRLKC', routeName: 'GRLKC-01' },
  { id: 45, block: 'Jharsuguda', ulb: 'Brajarajnagar', mrf: 'Brajarajnagar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD05CB8268', vehicleCapacity: '400KG', driverName: 'Manoj Dilla', driverContact: '7752096410', collectionSchedule: 'As and when required by GP', gpName: 'Chandinimal', wasteGeneratedKg: 75.009, gpNodalPerson: 'Bedabyash Jagadal', gpNodalContact: '9777605186', ulbNodalPerson: 'Pradeep Behera', ulbNodalContact: '9437174514', routeId: 'JJHAGRLKC', routeName: 'GRLKC-01' },

  // Lakhanpur Block (Brajarajnagar ULB)
  { id: 46, block: 'Lakhanpur', ulb: 'Brajarajnagar', mrf: 'Brajarajnagar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD05CC4274', vehicleCapacity: '400KG', driverName: 'Rajkumar Behera', driverContact: '8438622713', collectionSchedule: 'As and when required by GP', gpName: 'Banjari', wasteGeneratedKg: 88.527, gpNodalPerson: 'Tikeswar Urma', gpNodalContact: '7978331289', ulbNodalPerson: 'Pradeep Behera', ulbNodalContact: '9437174514', routeId: 'JLAKBPKLB', routeName: 'BPKLB-01' },
  { id: 47, block: 'Lakhanpur', ulb: 'Brajarajnagar', mrf: 'Brajarajnagar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD05CC4274', vehicleCapacity: '400KG', driverName: 'Rajkumar Behera', driverContact: '8438622713', collectionSchedule: 'As and when required by GP', gpName: 'Pipilimal', wasteGeneratedKg: 82.254, gpNodalPerson: 'Tikeswar Urma', gpNodalContact: '7978331289', ulbNodalPerson: 'Pradeep Behera', ulbNodalContact: '9437174514', routeId: 'JLAKBPKLB', routeName: 'BPKLB-01' },
  { id: 48, block: 'Lakhanpur', ulb: 'Brajarajnagar', mrf: 'Brajarajnagar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD05CC4274', vehicleCapacity: '400KG', driverName: 'Rajkumar Behera', driverContact: '8438622713', collectionSchedule: 'As and when required by GP', gpName: 'Kudaloi', wasteGeneratedKg: 93.209, gpNodalPerson: 'Bismaya Sahu', gpNodalContact: '6372613664', ulbNodalPerson: 'Pradeep Behera', ulbNodalContact: '9437174514', routeId: 'JLAKBPKLB', routeName: 'BPKLB-01' },
  { id: 49, block: 'Lakhanpur', ulb: 'Brajarajnagar', mrf: 'Brajarajnagar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD05CC4274', vehicleCapacity: '400KG', driverName: 'Rajkumar Behera', driverContact: '8438622713', collectionSchedule: 'As and when required by GP', gpName: 'Lakhanpur', wasteGeneratedKg: 116.445, gpNodalPerson: 'Jogeswar Mjhi', gpNodalContact: '9777516339', ulbNodalPerson: 'Pradeep Behera', ulbNodalContact: '9437174514', routeId: 'JLAKBPKLB', routeName: 'BPKLB-01' },
  { id: 50, block: 'Lakhanpur', ulb: 'Brajarajnagar', mrf: 'Brajarajnagar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD05CC4274', vehicleCapacity: '400KG', driverName: 'Rajkumar Behera', driverContact: '8438622713', collectionSchedule: 'As and when required by GP', gpName: 'Baghamunda', wasteGeneratedKg: 74.921, gpNodalPerson: 'Jogeswar Mjhi', gpNodalContact: '9777516340', ulbNodalPerson: 'Pradeep Behera', ulbNodalContact: '9437174514', routeId: 'JLAKBPKLB', routeName: 'BPKLB-01' },

  // Lakhanpur Block (Belpahar ULB)
  { id: 51, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Tilia', wasteGeneratedKg: 98.069, gpNodalPerson: 'Joshna Barik', gpNodalContact: '8658659741', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKTRKDP', routeName: 'TRKDP-01' },
  { id: 52, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Rampela', wasteGeneratedKg: 93.563, gpNodalPerson: 'Rashmita Patel', gpNodalContact: '9337510015', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKTRKDP', routeName: 'TRKDP-01' },
  { id: 53, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Kumarbandha', wasteGeneratedKg: 91.089, gpNodalPerson: 'Rashmita Patel', gpNodalContact: '9337510016', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKTRKDP', routeName: 'TRKDP-01' },
  { id: 54, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Dalagaon', wasteGeneratedKg: 90.559, gpNodalPerson: 'Amrita Sahu', gpNodalContact: '9777261821', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKTRKDP', routeName: 'TRKDP-01' },
  { id: 55, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Pipilikani', wasteGeneratedKg: 86.848, gpNodalPerson: 'Anil Pradhan', gpNodalContact: '9668183149', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKTRKDP', routeName: 'TRKDP-01' },
  { id: 56, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Kusharloi', wasteGeneratedKg: 76.688, gpNodalPerson: 'Bismaya Sahu', gpNodalContact: '6372613664', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKKBTSR', routeName: 'KBTSR-02' },
  { id: 57, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Bandhabahal', wasteGeneratedKg: 52.922, gpNodalPerson: 'Ajit Patel', gpNodalContact: '9938236464', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKKBTSR', routeName: 'KBTSR-02' },
  { id: 58, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Telenpali', wasteGeneratedKg: 70.415, gpNodalPerson: 'Pradhan Kishan', gpNodalContact: '8658549233', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKKBTSR', routeName: 'KBTSR-02' },
  { id: 59, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Sarandamal', wasteGeneratedKg: 93.121, gpNodalPerson: 'Anil Pradhan', gpNodalContact: '9668183149', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKKBTSR', routeName: 'KBTSR-02' },
  { id: 60, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Remenda', wasteGeneratedKg: 82.342, gpNodalPerson: 'Jayapratap Loha', gpNodalContact: '9777352600', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKKBTSR', routeName: 'KBTSR-02' },
  { id: 61, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Sunari', wasteGeneratedKg: 93.916, gpNodalPerson: 'Puja Pradhan', gpNodalContact: '9556642795', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKSPBKS', routeName: 'SPBKS-03' },
  { id: 62, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Pandri', wasteGeneratedKg: 74.921, gpNodalPerson: 'Jayapratap Loha', gpNodalContact: '9777352600', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKSPBKS', routeName: 'SPBKS-03' },
  { id: 63, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Bhournkhol', wasteGeneratedKg: 105.932, gpNodalPerson: 'Diptimaye Biswal', gpNodalContact: '7752083834', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKSPBKS', routeName: 'SPBKS-03' },
  { id: 64, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Kadamdihi', wasteGeneratedKg: 88.438, gpNodalPerson: 'Suresh Sahu', gpNodalContact: '7077874771', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKSPBKS', routeName: 'SPBKS-03' },
  { id: 65, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Samarbaga', wasteGeneratedKg: 62.022, gpNodalPerson: 'Suresh Sahu', gpNodalContact: '7077874772', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKSPBKS', routeName: 'SPBKS-03' },
  { id: 66, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Jamagaon', wasteGeneratedKg: 65.997, gpNodalPerson: 'Saroj Naik', gpNodalContact: '9439211604', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKJKMPP', routeName: 'JKMPP-04' },
  { id: 67, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Katarbaga', wasteGeneratedKg: 62.375, gpNodalPerson: 'Saroj Naik', gpNodalContact: '9439211605', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKJKMPP', routeName: 'JKMPP-04' },
  { id: 68, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Machhida', wasteGeneratedKg: 72.005, gpNodalPerson: 'Dilip Barik', gpNodalContact: '9937137534', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKJKMPP', routeName: 'JKMPP-04' },
  { id: 69, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Palsda', wasteGeneratedKg: 100.896, gpNodalPerson: 'Sumanta Dash', gpNodalContact: '9938533272', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKJKMPP', routeName: 'JKMPP-04' },
  { id: 70, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Panchagaon', wasteGeneratedKg: 64.496, gpNodalPerson: 'Ajay Pradhan', gpNodalContact: '7846908310', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKJKMPP', routeName: 'JKMPP-04' },
  { id: 71, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Vikampali', wasteGeneratedKg: 84.904, gpNodalPerson: 'Sumanta Dash', gpNodalContact: '9938533272', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKVABK', routeName: 'VABK-05' },
  { id: 72, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Attabira', wasteGeneratedKg: 109.642, gpNodalPerson: 'Biren Pradhan', gpNodalContact: '7328001500', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKVABK', routeName: 'VABK-05' },
  { id: 73, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Badimal', wasteGeneratedKg: 67.588, gpNodalPerson: 'Biren Pradhan', gpNodalContact: '7328001501', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKVABK', routeName: 'VABK-05' },
  { id: 74, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Kanaktora', wasteGeneratedKg: 91.884, gpNodalPerson: 'Ajit Patel', gpNodalContact: '9938236464', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKVABK', routeName: 'VABK-05' },
  { id: 75, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Pithinda', wasteGeneratedKg: 103.458, gpNodalPerson: 'Rabi Meher', gpNodalContact: '8249921904', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKPCRK', routeName: 'PCRK-06' },
  { id: 76, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Charpali', wasteGeneratedKg: 115.562, gpNodalPerson: 'Bhusia Sahu', gpNodalContact: '6361723664', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKPCRK', routeName: 'PCRK-06' },
  { id: 77, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Remeta', wasteGeneratedKg: 93.386, gpNodalPerson: 'Tikeswar Urma', gpNodalContact: '7978331128', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKPCRK', routeName: 'PCRK-06' },
  { id: 78, block: 'Lakhanpur', ulb: 'Belpahar', mrf: 'Belpahar MRF', vehicleType: 'TATA-ACE', vehicleNo: 'OD5BW5191', vehicleCapacity: '400KG', driverName: 'Dilip Kelet', driverContact: '7077502755', collectionSchedule: 'As and when required by GP', gpName: 'Kandheikela', wasteGeneratedKg: 86.583, gpNodalPerson: 'Rashmita Patel', gpNodalContact: '9337510015', ulbNodalPerson: 'Santanu Behera', ulbNodalContact: '9776794653', routeId: 'JLAKPCRK', routeName: 'PCRK-06' },
];
