export interface SanitationWorkerData {
  id: number;
  block: string;
  name: string;
  contact: string;
  activity: string;
}

export interface DriverData {
  id: number;
  block: string;
  name: string;
  contact: string;
  vehicleType: string;
}

// Sanitation Workers Data
export const sanitationWorkerData: SanitationWorkerData[] = [
  // Jharsuguda Block Sanitation Workers
  { id: 1, block: 'Jharsuguda', name: 'RITIK MAHANANDA', contact: '9692972027', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 2, block: 'Jharsuguda', name: 'BANBASI JAYAPURIA', contact: '9668366769', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 3, block: 'Jharsuguda', name: 'TULESWARI NETI', contact: '7077332343', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 4, block: 'Jharsuguda', name: 'BABITA PRADHAN', contact: '8327780696', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 5, block: 'Jharsuguda', name: 'ISWAR KANDARA', contact: '8658197073', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 6, block: 'Jharsuguda', name: 'RINKI PAULE', contact: '9692863945', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 7, block: 'Jharsuguda', name: 'RANJAN NAIK', contact: '7847914297', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 8, block: 'Jharsuguda', name: 'CHARITRA MAREI', contact: '8060382904', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 9, block: 'Jharsuguda', name: 'BUDMBARI KHADIA', contact: '9124323855', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 10, block: 'Jharsuguda', name: 'SUMITRA KHADIA', contact: '7077374452', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 11, block: 'Jharsuguda', name: 'SAUBHAGYA MAREI', contact: '9124076050', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 12, block: 'Jharsuguda', name: 'SAROJINI PANIA', contact: '7328002086', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 13, block: 'Jharsuguda', name: 'TARULATA NETI', contact: '8114703862', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 14, block: 'Jharsuguda', name: 'TANMYA BHOI', contact: '8658048534', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 15, block: 'Jharsuguda', name: 'SAIRENDRI SAHU', contact: '8144675810', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 16, block: 'Jharsuguda', name: 'JITENDRRI NETI', contact: '9827029776', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 17, block: 'Jharsuguda', name: 'MAUNABATI BAG', contact: '9937365312', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 18, block: 'Jharsuguda', name: 'SUMITRA MAJHI', contact: '8455084807', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 19, block: 'Jharsuguda', name: 'SUNITA ORAM', contact: '8658452235', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 20, block: 'Jharsuguda', name: 'BASANTI ORAM', contact: '6370409659', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 21, block: 'Jharsuguda', name: 'KUMUDINI GHASI', contact: '6372060129', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 22, block: 'Jharsuguda', name: 'HEENA GHASI', contact: '9348090306', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 23, block: 'Jharsuguda', name: 'UMA MAJHI', contact: '6372613421', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 24, block: 'Jharsuguda', name: 'ANUPAMA SETH', contact: '7087077701', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 25, block: 'Jharsuguda', name: 'BABY TANTI', contact: '8456850370', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 26, block: 'Jharsuguda', name: 'ANJANA SINGH', contact: '9692463848', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 27, block: 'Jharsuguda', name: 'SANTOSH CHAND', contact: '7735422582', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 28, block: 'Jharsuguda', name: 'BINDU MUNDA', contact: '7684092408', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 29, block: 'Jharsuguda', name: 'BHARAT CHASI', contact: '7008785480', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 30, block: 'Jharsuguda', name: 'BAIDEHI DANSENA', contact: '8018879861', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 31, block: 'Jharsuguda', name: 'SUSANTA CHHATRA', contact: '6372599540', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 32, block: 'Jharsuguda', name: 'GITANJALI BHAINSA', contact: '6371367731', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 33, block: 'Jharsuguda', name: 'PREMLATA GURU', contact: '6372117368', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 34, block: 'Jharsuguda', name: 'MITHILA GADTIA', contact: '9078217471', activity: 'Door to Door collection and Segregation at GP level' },

  // Kirimira Block Sanitation Workers
  { id: 35, block: 'Kirimira', name: 'PINKU PODHA', contact: '9438072756', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 36, block: 'Kirimira', name: 'SANDHYARANI PODHA', contact: '8926186447', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 37, block: 'Kirimira', name: 'DHANESWAR KISAN', contact: '6370496952', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 38, block: 'Kirimira', name: 'PREMLATA NETI', contact: '7008803452', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 39, block: 'Kirimira', name: 'RATNAKAR DUMDUM', contact: '8018783160', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 40, block: 'Kirimira', name: 'PREMADINI KHARSEL', contact: '9178287720', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 41, block: 'Kirimira', name: 'JAYANTI SA', contact: '7008690169', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 42, block: 'Kirimira', name: 'GAYATRI SA', contact: '9776752412', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 43, block: 'Kirimira', name: 'RANJANA KUSUM', contact: '8637207700', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 44, block: 'Kirimira', name: 'SABITA SETH', contact: '8637207700', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 45, block: 'Kirimira', name: 'BIRANCHI JAYAPURIA', contact: '9337238603', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 46, block: 'Kirimira', name: 'SANTOSHINI PATEL', contact: '7978173369', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 47, block: 'Kirimira', name: 'KISHORE BEHERA', contact: '8926246861', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 48, block: 'Kirimira', name: 'PREM KUMAR JAYAPURIA', contact: '7751911630', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 49, block: 'Kirimira', name: 'HIRABATI NAIK', contact: '9348630496', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 50, block: 'Kirimira', name: 'SOUBAHGYA PAEL', contact: '9777324250', activity: 'Door to Door collection and Segregation at GP level' },

  // Kolabira Block Sanitation Workers
  { id: 51, block: 'Kolabira', name: 'SAMBHU SAHU', contact: '8260915040', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 52, block: 'Kolabira', name: 'TIKESWARI BAG', contact: '7077024189', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 53, block: 'Kolabira', name: 'BISHNUPRIYA RANA', contact: '7682950504', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 54, block: 'Kolabira', name: 'ANANDA BHANJA', contact: '9861687285', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 55, block: 'Kolabira', name: 'KHUSIRAM BUDA', contact: '7852982566', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 56, block: 'Kolabira', name: 'KAMALA MAJHI', contact: '9861258120', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 57, block: 'Kolabira', name: 'SARITA MAHAKULA', contact: '7205427045', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 58, block: 'Kolabira', name: 'SABITA KISAN', contact: '8249329429', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 59, block: 'Kolabira', name: 'URBASI BHOI', contact: '6370721186', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 60, block: 'Kolabira', name: 'SARAOJ DHURUA', contact: '7853851824', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 61, block: 'Kolabira', name: 'MANJULATA MAJHI', contact: '8572550457', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 62, block: 'Kolabira', name: 'JOSNA KISAN', contact: '7853940980', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 63, block: 'Kolabira', name: 'SUSANTA KARANI', contact: '6167128427', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 64, block: 'Kolabira', name: 'PUSAP RAKSA', contact: '9112032049', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 65, block: 'Kolabira', name: 'HARIHAR SUNANI', contact: '9692969097', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 66, block: 'Kolabira', name: 'JAYAKANTI BHOI', contact: '7715172775', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 67, block: 'Kolabira', name: 'DASAMI SAHU', contact: '9861825692', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 68, block: 'Kolabira', name: 'SANJIB DILA', contact: '8847832219', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 69, block: 'Kolabira', name: 'PANKAJINI ROUT', contact: '6371822983', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 70, block: 'Kolabira', name: 'JAGYANSENI BAG', contact: '7735910670', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 71, block: 'Kolabira', name: 'BIKASAN KISAN', contact: '9124556905', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 72, block: 'Kolabira', name: 'UMESH KISAN', contact: '7764885622', activity: 'Door to Door collection and Segregation at GP level' },

  // Laikera Block Sanitation Workers
  { id: 73, block: 'Laikera', name: 'BAPI ROHIDAS', contact: '8658994308', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 74, block: 'Laikera', name: 'GUNTHU ROHIDAS', contact: '7846859956', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 75, block: 'Laikera', name: 'KANTI KISAN', contact: '7978165353', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 76, block: 'Laikera', name: 'RAJU KISAN', contact: '9178931519', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 77, block: 'Laikera', name: 'SUDARSAN MANI', contact: '9327696161', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 78, block: 'Laikera', name: 'LOKANTH HANSA', contact: '7606820881', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 79, block: 'Laikera', name: 'SIBA BEHERA', contact: '7978867701', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 80, block: 'Laikera', name: 'AJIT SUNANI', contact: '7852954452', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 81, block: 'Laikera', name: 'LILIMA KANTA', contact: '8144565799', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 82, block: 'Laikera', name: 'LAXHMI KARALI', contact: '9861893583', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 83, block: 'Laikera', name: 'DULUMA BEHERA', contact: '9938224780', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 84, block: 'Laikera', name: 'DROUPADI MEHER', contact: '9556136277', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 85, block: 'Laikera', name: 'SANDHYA MISHRA', contact: '7847907074', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 86, block: 'Laikera', name: 'BANITA DANSENA', contact: '8144638349', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 87, block: 'Laikera', name: 'PUSPANJALI MAREI', contact: '9937794655', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 88, block: 'Laikera', name: 'BISHNUPRIYA MAREI', contact: '9556898985', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 89, block: 'Laikera', name: 'DILA SAHU', contact: '8448989062', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 90, block: 'Laikera', name: 'GOLAPI CHOUDHURY', contact: '7008317959', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 91, block: 'Laikera', name: 'MANJLTA NAJIK', contact: '6372845632', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 92, block: 'Laikera', name: 'RAJKUMAR THAKUR', contact: '9692025649', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 93, block: 'Laikera', name: 'PRAVASINI KANTA', contact: '8658697842', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 94, block: 'Laikera', name: 'SUJATA KANTA', contact: '8280929873', activity: 'Door to Door collection and Segregation at GP level' },

  // Lakhanpur Block Sanitation Workers
  { id: 95, block: 'Lakhanpur', name: 'PUSPANJALI MEHER', contact: '9777850200', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 96, block: 'Lakhanpur', name: 'AMBIKA KHADIA', contact: '7077521457', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 97, block: 'Lakhanpur', name: 'MAMINA KHAMARI', contact: '9938530914', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 98, block: 'Lakhanpur', name: 'PADMINI BHOI', contact: '8658290672', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 99, block: 'Lakhanpur', name: 'KARISHMA PADHAN', contact: '8093442844', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 100, block: 'Lakhanpur', name: 'MANJULATA SETH', contact: '9668796787', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 101, block: 'Lakhanpur', name: 'SONALI PRIYADARSHANI Das', contact: '7326058419', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 102, block: 'Lakhanpur', name: 'PADMABATI SAHU', contact: '8260814575', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 103, block: 'Lakhanpur', name: 'RUKMATI KHADIA', contact: '6371900163', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 104, block: 'Lakhanpur', name: 'SANJUKTA GIRI', contact: '8260657739', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 105, block: 'Lakhanpur', name: 'BIKI YADAB', contact: '6372600423', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 106, block: 'Lakhanpur', name: 'LOKESWAR DHURUA', contact: '9630140987', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 107, block: 'Lakhanpur', name: 'SATYABATI SA', contact: '9692419453', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 108, block: 'Lakhanpur', name: 'SABITRI RAUT', contact: '9556299571', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 109, block: 'Lakhanpur', name: 'GEETANJALI MALLICK', contact: '9556625110', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 110, block: 'Lakhanpur', name: 'PUSPALATA PERE', contact: '7205421933', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 111, block: 'Lakhanpur', name: 'RUSHA CHANDRA SA', contact: '8117918289', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 112, block: 'Lakhanpur', name: 'SANTOSH ROHIDAS', contact: '7008544841', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 113, block: 'Lakhanpur', name: 'ANOJ KALET', contact: '8117833580', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 114, block: 'Lakhanpur', name: 'KALPANA KALET', contact: '9124270863', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 115, block: 'Lakhanpur', name: 'RAKHYAPAL GARDIA', contact: '7751033458', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 116, block: 'Lakhanpur', name: 'RATNAKARA PRADHAN', contact: '9337603967', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 117, block: 'Lakhanpur', name: 'SUSHANTA DAS', contact: '9668021243', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 118, block: 'Lakhanpur', name: 'SHYAMASUNDAR PADHAN', contact: '6372150373', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 119, block: 'Lakhanpur', name: 'SARADA KHADIA', contact: '7848966859', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 120, block: 'Lakhanpur', name: 'KETAKI PADHAN', contact: '9777468684', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 121, block: 'Lakhanpur', name: 'LALITA MAJHI', contact: '7077227461', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 122, block: 'Lakhanpur', name: 'SAROJINI PRADHAN', contact: '7608888472', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 123, block: 'Lakhanpur', name: 'JASODA PODH', contact: '7735086603', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 124, block: 'Lakhanpur', name: 'PUSPA BARUI', contact: '7873281136', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 125, block: 'Lakhanpur', name: 'SATYABHAMA NAIK', contact: '9556393755', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 126, block: 'Lakhanpur', name: 'RAJENDRA KUMRA', contact: '9668499038', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 127, block: 'Lakhanpur', name: 'GUNANIDHI BISI', contact: '9668449030', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 128, block: 'Lakhanpur', name: 'BIRA MUNDA', contact: '7853001056', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 129, block: 'Lakhanpur', name: 'BIDYADHAR SUNA', contact: '7894256502', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 130, block: 'Lakhanpur', name: 'PRABHASINI SET', contact: '8455040538', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 131, block: 'Lakhanpur', name: 'RUDRA DHURUA', contact: '8260413212', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 132, block: 'Lakhanpur', name: 'SUSANTA BHOI', contact: '9692926365', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 133, block: 'Lakhanpur', name: 'MARKANDA KUSUM', contact: '7326928210', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 134, block: 'Lakhanpur', name: 'NABINA MEHER', contact: '7008808311', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 135, block: 'Lakhanpur', name: 'NALINI BEHERA', contact: '9938670030', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 136, block: 'Lakhanpur', name: 'BILASINI SAHU', contact: '7875071818', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 137, block: 'Lakhanpur', name: 'BILASINI NAIK', contact: '7846899934', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 138, block: 'Lakhanpur', name: 'BHUMISUTA GANIK', contact: '9668328423', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 139, block: 'Lakhanpur', name: 'CHHABIRANI BARIK', contact: '9668446132', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 140, block: 'Lakhanpur', name: 'NARENDRA PRADHAN', contact: '6370022381', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 141, block: 'Lakhanpur', name: 'JEMA KHARA SEL', contact: '7683821066', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 142, block: 'Lakhanpur', name: 'SATYABHAMA LENKA', contact: '9334946448', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 143, block: 'Lakhanpur', name: 'INDRA DEHERI', contact: '8280439413', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 144, block: 'Lakhanpur', name: 'PREMSWARI DEHERAN', contact: '9409030256', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 145, block: 'Lakhanpur', name: 'BRUNDABATI SAHU', contact: '8658828631', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 146, block: 'Lakhanpur', name: 'SANTARA BEGAM', contact: '7683956545', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 147, block: 'Lakhanpur', name: 'JAMUNA PADHAN', contact: '8144366271', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 148, block: 'Lakhanpur', name: 'MEHEJBIN NISHA', contact: '9668529333', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 149, block: 'Lakhanpur', name: 'MOHITKUMAR PABIYA', contact: '9938591937', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 150, block: 'Lakhanpur', name: 'KRUSHNA BISWAL', contact: '9348809146', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 151, block: 'Lakhanpur', name: 'BANITA PADHAN', contact: '7008089720', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 152, block: 'Lakhanpur', name: 'BINA PRADHAN', contact: '8260639169', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 153, block: 'Lakhanpur', name: 'MAMATA ORAM', contact: '6372167455', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 154, block: 'Lakhanpur', name: 'SURUBALI DHURUA', contact: '9777577638', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 155, block: 'Lakhanpur', name: 'SABITA RAHIDAS', contact: '7894726980', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 156, block: 'Lakhanpur', name: 'MOUSUMI BHOI', contact: '7077050819', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 157, block: 'Lakhanpur', name: 'KALPANA BISI', contact: '9556470829', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 158, block: 'Lakhanpur', name: 'GITANJALI BHOI', contact: '8984374097', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 159, block: 'Lakhanpur', name: 'GITA BHOI', contact: '9556470829', activity: 'Door to Door collection and Segregation at GP level' },
  { id: 160, block: 'Lakhanpur', name: 'ISWARI SAHU', contact: '8984374097', activity: 'Door to Door collection and Segregation at GP level' }
];

// Driver Data
export const driverData: DriverData[] = [
  // Jharsuguda Block Drivers
  { id: 1, block: 'Jharsuguda', name: 'RITIK MAHANANDA', contact: '9692972027', vehicleType: 'BOV' },
  { id: 2, block: 'Jharsuguda', name: 'TULESWARI NETI', contact: '7077332343', vehicleType: 'BOV' },
  { id: 3, block: 'Jharsuguda', name: 'ISWAR KANDARA', contact: '8658197073', vehicleType: 'BOV' },
  { id: 4, block: 'Jharsuguda', name: 'RANJAN NAIK', contact: '7847914297', vehicleType: 'BOV' },
  { id: 5, block: 'Jharsuguda', name: 'BUDMBARI KHADIA', contact: '9124323855', vehicleType: 'BOV' },
  { id: 6, block: 'Jharsuguda', name: 'SAUBHAGYA MAREI', contact: '9124076050', vehicleType: 'BOV' },
  { id: 7, block: 'Jharsuguda', name: 'TARULATA NETI', contact: '8114703862', vehicleType: 'BOV' },
  { id: 8, block: 'Jharsuguda', name: 'SAIRENDRI SAHU', contact: '8144675810', vehicleType: 'BOV' },
  { id: 9, block: 'Jharsuguda', name: 'MAUNABATI BAG', contact: '9937365312', vehicleType: 'BOV' },
  { id: 10, block: 'Jharsuguda', name: 'SUNITA ORAM', contact: '8658452235', vehicleType: 'BOV' },
  { id: 11, block: 'Jharsuguda', name: 'KUMUDINI GHASI', contact: '6372060129', vehicleType: 'BOV' },
  { id: 12, block: 'Jharsuguda', name: 'UMA MAJHI', contact: '6372613421', vehicleType: 'BOV' },
  { id: 13, block: 'Jharsuguda', name: 'BABY TANTI', contact: '8456850370', vehicleType: 'BOV' },
  { id: 14, block: 'Jharsuguda', name: 'SANTOSH CHAND', contact: '7735422582', vehicleType: 'BOV' },
  { id: 15, block: 'Jharsuguda', name: 'BINDU MUNDA', contact: '7684092408', vehicleType: 'BOV' },
  { id: 16, block: 'Jharsuguda', name: 'BAIDEHI DANSENA', contact: '8018879861', vehicleType: 'BOV' },
  { id: 17, block: 'Jharsuguda', name: 'GITANJALI BHAINSA', contact: '6371367731', vehicleType: 'BOV' },

  // Kirimira Block Drivers
  { id: 18, block: 'Kirimira', name: 'PINKU PODHA', contact: '9438072756', vehicleType: 'BOV' },
  { id: 19, block: 'Kirimira', name: 'DHANESWAR KISAN', contact: '6370496952', vehicleType: 'BOV' },
  { id: 20, block: 'Kirimira', name: 'RATNAKAR DUMDUM', contact: '8018783160', vehicleType: 'BOV' },
  { id: 21, block: 'Kirimira', name: 'JAYANTI SA', contact: '7008690169', vehicleType: 'BOV' },
  { id: 22, block: 'Kirimira', name: 'RANJANA KUSUM', contact: '8637207700', vehicleType: 'BOV' },
  { id: 23, block: 'Kirimira', name: 'BIRANCHI JAYAPURIA', contact: '9337238603', vehicleType: 'BOV' },
  { id: 24, block: 'Kirimira', name: 'KISHORE BEHERA', contact: '8926246861', vehicleType: 'BOV' },
  { id: 25, block: 'Kirimira', name: 'SOUBAHGYA PAEL', contact: '9777324250', vehicleType: 'BOV' },

  // Kolabira Block Drivers
  { id: 26, block: 'Kolabira', name: 'SAMBHU SAHU', contact: '8260915040', vehicleType: 'BOV' },
  { id: 27, block: 'Kolabira', name: 'ANANDA BHANJA', contact: '9861687285', vehicleType: 'BOV' },
  { id: 28, block: 'Kolabira', name: 'KHUSIRAM BUDA', contact: '7852982566', vehicleType: 'BOV' },
  { id: 29, block: 'Kolabira', name: 'SARAOJ DHURUA', contact: '7853851824', vehicleType: 'BOV' },
  { id: 30, block: 'Kolabira', name: 'SUSANTA KARANI', contact: '6167128427', vehicleType: 'BOV' },
  { id: 31, block: 'Kolabira', name: 'HARIHAR SUNANI', contact: '9692969097', vehicleType: 'BOV' },
  { id: 32, block: 'Kolabira', name: 'SANJIB DILA', contact: '8847832219', vehicleType: 'BOV' },
  { id: 33, block: 'Kolabira', name: 'PANKAJINI ROUT', contact: '6371822983', vehicleType: 'BOV' },
  { id: 34, block: 'Kolabira', name: 'UMESH KISAN', contact: '7764885622', vehicleType: 'BOV' },

  // Laikera Block Drivers
  { id: 35, block: 'Laikera', name: 'BAPI ROHIDAS', contact: '8658994308', vehicleType: 'BOV' },
  { id: 36, block: 'Laikera', name: 'KANTI KISAN', contact: '7978165353', vehicleType: 'BOV' },
  { id: 37, block: 'Laikera', name: 'SUDARSAN MANI', contact: '9327696161', vehicleType: 'BOV' },
  { id: 38, block: 'Laikera', name: 'AJIT SUNANI', contact: '7852954452', vehicleType: 'BOV' },
  { id: 39, block: 'Laikera', name: 'LAXHMI KARALI', contact: '9861893583', vehicleType: 'BOV' },
  { id: 40, block: 'Laikera', name: 'DULUMA BEHERA', contact: '9938224780', vehicleType: 'BOV' },
  { id: 41, block: 'Laikera', name: 'SANDHYA MISHRA', contact: '7847907074', vehicleType: 'BOV' },
  { id: 42, block: 'Laikera', name: 'BISHNUPRIYA MAREI', contact: '9556898985', vehicleType: 'BOV' },
  { id: 43, block: 'Laikera', name: 'DILA SAHU', contact: '8448989062', vehicleType: 'BOV' },
  { id: 44, block: 'Laikera', name: 'RAJKUMAR THAKUR', contact: '9692025649', vehicleType: 'BOV' },
  { id: 45, block: 'Laikera', name: 'PRAVASINI KANTA', contact: '8658697842', vehicleType: 'BOV' },

  // Lakhanpur Block Drivers
  { id: 46, block: 'Lakhanpur', name: 'PUSPANJALI MEHER', contact: '9777850200', vehicleType: 'BOV' },
  { id: 47, block: 'Lakhanpur', name: 'MAMINA KHAMARI', contact: '9938530914', vehicleType: 'BOV' },
  { id: 48, block: 'Lakhanpur', name: 'KARISHMA PADHAN', contact: '8093442844', vehicleType: 'BOV' },
  { id: 49, block: 'Lakhanpur', name: 'SONALI PRIYADARSHANI Das', contact: '7326058419', vehicleType: 'BOV' },
  { id: 50, block: 'Lakhanpur', name: 'RUKMATI KHADIA', contact: '6371900163', vehicleType: 'BOV' },
  { id: 51, block: 'Lakhanpur', name: 'BIKI YADAB', contact: '6372600423', vehicleType: 'BOV' },
  { id: 52, block: 'Lakhanpur', name: 'SATYABATI SA', contact: '9692419453', vehicleType: 'BOV' },
  { id: 53, block: 'Lakhanpur', name: 'GEETANJALI MALLICK', contact: '9556625110', vehicleType: 'BOV' },
  { id: 54, block: 'Lakhanpur', name: 'SANTOSH ROHIDAS', contact: '7008544841', vehicleType: 'BOV' },
  { id: 55, block: 'Lakhanpur', name: 'ANOJ KALET', contact: '8117833580', vehicleType: 'BOV' },
  { id: 56, block: 'Lakhanpur', name: 'RAKHYAPAL GARDIA', contact: '7751033458', vehicleType: 'BOV' },
  { id: 57, block: 'Lakhanpur', name: 'SUSHANTA DAS', contact: '9668021243', vehicleType: 'BOV' },
  { id: 58, block: 'Lakhanpur', name: 'SARADA KHADIA', contact: '7848966859', vehicleType: 'BOV' },
  { id: 59, block: 'Lakhanpur', name: 'LALITA MAJHI', contact: '7077227461', vehicleType: 'BOV' },
  { id: 60, block: 'Lakhanpur', name: 'JASODA PODH', contact: '7735086603', vehicleType: 'BOV' },
  { id: 61, block: 'Lakhanpur', name: 'RAJENDRA KUMRA', contact: '9668499038', vehicleType: 'BOV' },
  { id: 62, block: 'Lakhanpur', name: 'GUNANIDHI BISI', contact: '9668449030', vehicleType: 'BOV' },
  { id: 63, block: 'Lakhanpur', name: 'BIDYADHAR SUNA', contact: '7894256502', vehicleType: 'BOV' },
  { id: 64, block: 'Lakhanpur', name: 'RUDRA DHURUA', contact: '8260413212', vehicleType: 'BOV' },
  { id: 65, block: 'Lakhanpur', name: 'MARKANDA KUSUM', contact: '7326928210', vehicleType: 'BOV' },
  { id: 66, block: 'Lakhanpur', name: 'NALINI BEHERA', contact: '9938670030', vehicleType: 'BOV' },
  { id: 67, block: 'Lakhanpur', name: 'BILASINI NAIK', contact: '7846899934', vehicleType: 'BOV' },
  { id: 68, block: 'Lakhanpur', name: 'NARENDRA PRADHAN', contact: '6370022381', vehicleType: 'BOV' },
  { id: 69, block: 'Lakhanpur', name: 'JEMA KHARA SEL', contact: '7683821066', vehicleType: 'BOV' },
  { id: 70, block: 'Lakhanpur', name: 'INDRA DEHERI', contact: '8280439413', vehicleType: 'BOV' },
  { id: 71, block: 'Lakhanpur', name: 'BRUNDABATI SAHU', contact: '8658828631', vehicleType: 'BOV' },
  { id: 72, block: 'Lakhanpur', name: 'JAMUNA PADHAN', contact: '8144366271', vehicleType: 'BOV' },
  { id: 73, block: 'Lakhanpur', name: 'MOHITKUMAR PABIYA', contact: '9938591937', vehicleType: 'BOV' },
  { id: 74, block: 'Lakhanpur', name: 'BANITA PADHAN', contact: '7008089720', vehicleType: 'BOV' },
  { id: 75, block: 'Lakhanpur', name: 'MAMATA ORAM', contact: '6372167455', vehicleType: 'BOV' },
  { id: 76, block: 'Lakhanpur', name: 'SABITA RAHIDAS', contact: '7894726980', vehicleType: 'BOV' },
  { id: 77, block: 'Lakhanpur', name: 'KALPANA BISI', contact: '9556470829', vehicleType: 'BOV' },
  { id: 78, block: 'Lakhanpur', name: 'GITANJALI BHOI', contact: '8984374097', vehicleType: 'BOV' }
];