export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // Aska Block (MRF 1)
  { id: 1, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 1', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'Chadhiapalli', wasteGeneratedKg: 412, gpNodalPerson: 'Lilami Pradhan', gpNodalContact: '7077046513', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 2, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 1', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'Kalasandhapur', wasteGeneratedKg: 323, gpNodalPerson: 'K Jogindra Reddy', gpNodalContact: '9937356364', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 3, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 1', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'Nalabanta', wasteGeneratedKg: 468, gpNodalPerson: 'Deepanjali Pradhan', gpNodalContact: '7894224387', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 4, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 1', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'Debabhumi', wasteGeneratedKg: 135, gpNodalPerson: 'G Appanna', gpNodalContact: '9668794316', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 5, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 1', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'Mangalpur', wasteGeneratedKg: 165, gpNodalPerson: 'E Tejaswini Dora', gpNodalContact: '8249954521', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 6, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 1', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'Balichhai', wasteGeneratedKg: 198, gpNodalPerson: 'Pradip Kumar Patra', gpNodalContact: '9938618956', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 7, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 1', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'Haridapadar', wasteGeneratedKg: 297, gpNodalPerson: 'Prasad Kumar Nayak', gpNodalContact: '7656863196', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 8, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 1', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'Jaypur', wasteGeneratedKg: 264, gpNodalPerson: 'Susanta Kumar Bhuyan', gpNodalContact: '9937640373', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 9, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 1', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'Gangapur', wasteGeneratedKg: 264, gpNodalPerson: 'Rinku Patro', gpNodalContact: '8895717181', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 10, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 1', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'Khandadeuli', wasteGeneratedKg: 198, gpNodalPerson: 'Sidhiranjan Nayak', gpNodalContact: '8984286143', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  // Aska Block (MRF 2)
  { id: 11, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 2', vehicleType: 'TATA ACE', vehicleNo: '2', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'Babanapur', wasteGeneratedKg: 390, gpNodalPerson: 'Nilambar Sethi', gpNodalContact: '9658342452', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 12, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 2', vehicleType: 'TATA ACE', vehicleNo: '2', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'Bhetanai', wasteGeneratedKg: 297, gpNodalPerson: 'Susanta Kumar Gouda', gpNodalContact: '9861114175', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 13, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 2', vehicleType: 'TATA ACE', vehicleNo: '2', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'Badakholi', wasteGeneratedKg: 264, gpNodalPerson: 'Susanta Kumar Gouda', gpNodalContact: '9861114175', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 14, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 2', vehicleType: 'TATA ACE', vehicleNo: '2', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'Gahangu', wasteGeneratedKg: 495, gpNodalPerson: 'A. Bhikari Pradhan', gpNodalContact: '9658278905', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 15, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 2', vehicleType: 'TATA ACE', vehicleNo: '2', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'Balisira', wasteGeneratedKg: 330, gpNodalPerson: 'Sukanta Kumar Nayak', gpNodalContact: '9692617038', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 16, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 2', vehicleType: 'TATA ACE', vehicleNo: '2', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'Gunthapada', wasteGeneratedKg: 363, gpNodalPerson: 'Pradip Kumar Patra', gpNodalContact: '9938618956', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 17, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 2', vehicleType: 'TATA ACE', vehicleNo: '2', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'Benapata', wasteGeneratedKg: 462, gpNodalPerson: 'Sailendra Kumar Padhy', gpNodalContact: '8249926393', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 18, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 2', vehicleType: 'TATA ACE', vehicleNo: '2', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'Bangarada', wasteGeneratedKg: 495, gpNodalPerson: 'Soumyaranjan Mallik', gpNodalContact: '6372258766', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },
  { id: 19, block: 'Aska', ulb: 'Aska NAC', mrf: 'Aska NAC MRF 2', vehicleType: 'TATA ACE', vehicleNo: '2', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'TUE, FRI', gpName: 'Allipur', wasteGeneratedKg: 165, gpNodalPerson: 'Kulamani Sahu', gpNodalContact: '8658310911', ulbNodalPerson: 'Deepa', ulbNodalContact: '6372289722' },

  // Belaguntha Block
  { id: 20, block: 'Belaguntha', ulb: 'Belaguntha NAC', mrf: 'Belaguntha MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'Monday, Friday', gpName: 'AMBAPUA', wasteGeneratedKg: 132, gpNodalPerson: 'SURYA NARAYAN SAHU', gpNodalContact: '9668612818', ulbNodalPerson: 'Prabin', ulbNodalContact: '8895775454' },
  { id: 21, block: 'Belaguntha', ulb: 'Belaguntha NAC', mrf: 'Belaguntha MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'Monday, Friday', gpName: 'BANKA', wasteGeneratedKg: 99, gpNodalPerson: 'SURYA NARAYAN SAHU', gpNodalContact: '9668612818', ulbNodalPerson: 'Prabin', ulbNodalContact: '8895775454' },
  { id: 22, block: 'Belaguntha', ulb: 'Belaguntha NAC', mrf: 'Belaguntha MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'Monday, Friday', gpName: 'BENIPALLI', wasteGeneratedKg: 198, gpNodalPerson: 'BRAJABASI SETHY', gpNodalContact: '9777704659', ulbNodalPerson: 'Prabin', ulbNodalContact: '8895775454' },
  { id: 23, block: 'Belaguntha', ulb: 'Belaguntha NAC', mrf: 'Belaguntha MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'Monday, Friday', gpName: 'DHUMUCHAI', wasteGeneratedKg: 165, gpNodalPerson: 'SUCHILAGNA SWAIN', gpNodalContact: '9827732228', ulbNodalPerson: 'Prabin', ulbNodalContact: '8895775454' },
  { id: 24, block: 'Belaguntha', ulb: 'Belaguntha NAC', mrf: 'Belaguntha MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'Monday, Friday', gpName: 'G.NUAGAM', wasteGeneratedKg: 231, gpNodalPerson: 'RAJANI PRADHAN', gpNodalContact: '9178880996', ulbNodalPerson: 'Prabin', ulbNodalContact: '8895775454' },
  { id: 25, block: 'Belaguntha', ulb: 'Belaguntha NAC', mrf: 'Belaguntha MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'Monday, Friday', gpName: 'MANGALPUR', wasteGeneratedKg: 132, gpNodalPerson: 'SUGYANI PADHI', gpNodalContact: '8763828998', ulbNodalPerson: 'Prabin', ulbNodalContact: '8895775454' },
  { id: 26, block: 'Belaguntha', ulb: 'Belaguntha NAC', mrf: 'Belaguntha MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'Monday, Friday', gpName: 'TANARADA', wasteGeneratedKg: 99, gpNodalPerson: 'D TRIPATI PRADHAN', gpNodalContact: '7606038443', ulbNodalPerson: 'Prabin', ulbNodalContact: '8895775454' },
  { id: 27, block: 'Belaguntha', ulb: 'Belaguntha NAC', mrf: 'Belaguntha MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'Monday, Friday', gpName: 'UDHURA', wasteGeneratedKg: 132, gpNodalPerson: 'SANGITA BISOYI', gpNodalContact: '7326046165', ulbNodalPerson: 'Prabin', ulbNodalContact: '8895775454' },

  // Bhanjanagar Block
  { id: 28, block: 'Bhanjanagar', ulb: 'Bhanjanagar NAC', mrf: 'Bhanjanagar MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'BADAKODANDA', wasteGeneratedKg: 99, gpNodalPerson: 'SARMILA JENA', gpNodalContact: '9438137742', ulbNodalPerson: 'Amrita Nayak', ulbNodalContact: '8249919496' },
  { id: 29, block: 'Bhanjanagar', ulb: 'Bhanjanagar NAC', mrf: 'Bhanjanagar MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'BARUDA', wasteGeneratedKg: 396, gpNodalPerson: 'JAYANTI BEHERA', gpNodalContact: '7978443899', ulbNodalPerson: 'Amrita Nayak', ulbNodalContact: '8249919496' },
  { id: 30, block: 'Bhanjanagar', ulb: 'Bhanjanagar NAC', mrf: 'Bhanjanagar MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'BAUNSALUNDI', wasteGeneratedKg: 231, gpNodalPerson: 'JAMUNA JANI', gpNodalContact: '6371856959', ulbNodalPerson: 'Amrita Nayak', ulbNodalContact: '8249919496' },
  { id: 31, block: 'Bhanjanagar', ulb: 'Bhanjanagar NAC', mrf: 'Bhanjanagar MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'DIHAPADHALA', wasteGeneratedKg: 66, gpNodalPerson: 'GNYANESWAR BEHERA', gpNodalContact: '9938736111', ulbNodalPerson: 'Amrita Nayak', ulbNodalContact: '8249919496' },
  { id: 32, block: 'Bhanjanagar', ulb: 'Bhanjanagar NAC', mrf: 'Bhanjanagar MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'GOLAPADA', wasteGeneratedKg: 132, gpNodalPerson: 'MONALISA PATRA', gpNodalContact: '6371900673', ulbNodalPerson: 'Amrita Nayak', ulbNodalContact: '8249919496' },
  { id: 33, block: 'Bhanjanagar', ulb: 'Bhanjanagar NAC', mrf: 'Bhanjanagar MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'JILLUNDI', wasteGeneratedKg: 198, gpNodalPerson: 'JITENDRA PRADHAN', gpNodalContact: '7853892190', ulbNodalPerson: 'Amrita Nayak', ulbNodalContact: '8249919496' },
  { id: 34, block: 'Bhanjanagar', ulb: 'Bhanjanagar NAC', mrf: 'Bhanjanagar MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'KULLADA', wasteGeneratedKg: 99, gpNodalPerson: 'GNYANESWAR BEHERA', gpNodalContact: '9938736111', ulbNodalPerson: 'Amrita Nayak', ulbNodalContact: '8249919496' },
  { id: 35, block: 'Bhanjanagar', ulb: 'Bhanjanagar NAC', mrf: 'Bhanjanagar MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'LALSINGI', wasteGeneratedKg: 264, gpNodalPerson: 'PRIYANKA SAMAL', gpNodalContact: '6372486411', ulbNodalPerson: 'Amrita Nayak', ulbNodalContact: '8249919496' },
  { id: 36, block: 'Bhanjanagar', ulb: 'Bhanjanagar NAC', mrf: 'Bhanjanagar MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'MUDULIPALLI', wasteGeneratedKg: 165, gpNodalPerson: 'PRIYANKA SAMAL', gpNodalContact: '6372486411', ulbNodalPerson: 'Amrita Nayak', ulbNodalContact: '8249919496' },
  { id: 37, block: 'Bhanjanagar', ulb: 'Bhanjanagar NAC', mrf: 'Bhanjanagar MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'MUJAGADA', wasteGeneratedKg: 132, gpNodalPerson: 'ARUNA KUMAR BISOYI', gpNodalContact: '9937545388', ulbNodalPerson: 'Amrita Nayak', ulbNodalContact: '8249919496' },
  { id: 38, block: 'Bhanjanagar', ulb: 'Bhanjanagar NAC', mrf: 'Bhanjanagar MRF', vehicleType: 'TATA ACE', vehicleNo: '1', vehicleCapacity: '300-400 Kg', driverName: '-', driverContact: '-', collectionSchedule: 'MON, THU', gpName: 'SANAKODANDA', wasteGeneratedKg: 297, gpNodalPerson: 'SATYANARAYAN NAYAK', gpNodalContact: '8917352691', ulbNodalPerson: 'Amrita Nayak', ulbNodalContact: '8249919496' }
];