export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // ATTABIRA BLOCK
  {
    id: 1,
    block: 'ATTABIRA',
    ulb: 'Attabira NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'KULUNDA-BUGBUGA-CHKULI (KBC-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Buddadev Behera, Sananda Mallick, Sudhansu Dash',
    gpNodalContact: '8917453949, 6371826799, 7077953660',
    ulbNodalPerson: 'Aswini Kumar Sabar, SE',
    ulbNodalContact: '7077795474'
  },
  {
    id: 2,
    block: 'ATTABIRA',
    ulb: 'Attabira NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'MANAPADA-KHARMUMUNDA-HIRLIAPALI (MKH-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Sushanta Bag, Upendra Pradhan',
    gpNodalContact: '9090590300, 9938902710',
    ulbNodalPerson: 'Aswini Kumar Sabar, SE',
    ulbNodalContact: '7077795474'
  },
  {
    id: 3,
    block: 'ATTABIRA',
    ulb: 'Attabira NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'PAHARSRIGIDA-JANHAPADA-JHILIMINDA (PJJ-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Deepak Kumar Pradhan, Asit Das, Buddadev Behera',
    gpNodalContact: '9777075858, 6372556570, 8917453949',
    ulbNodalPerson: 'Aswini Kumar Sabar, SE',
    ulbNodalContact: '7077795474'
  },
  {
    id: 4,
    block: 'ATTABIRA',
    ulb: 'Attabira NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'LACHIDA-TANGARAPALLI-GODBHAGA (LTG-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Trilochan Sahu, Suraj Kumbhar, Babli Biswal',
    gpNodalContact: '8249203071, 7894250745, 8456965825',
    ulbNodalPerson: 'Aswini Kumar Sabar, SE',
    ulbNodalContact: '7077795474'
  },
  {
    id: 5,
    block: 'ATTABIRA',
    ulb: 'Attabira NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'KADABAHAL-KULTATUKRA-KUMALSINMGHA (KKK-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Saroj Kumar Nanda, Preeti Bhue, Suprabha Panda',
    gpNodalContact: '7008523619, 9937339164, 9853864413',
    ulbNodalPerson: 'Aswini Kumar Sabar, SE',
    ulbNodalContact: '7077795474'
  },
  {
    id: 6,
    block: 'ATTABIRA',
    ulb: 'Attabira NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'LAHANDA-LARAMBHA-SILOT (LLS-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Bhupesh Gupta, Swaraj Mahapatra, Debananda Dhusar',
    gpNodalContact: '9937767773, 9178018738, 9178197611',
    ulbNodalPerson: 'Aswini Kumar Sabar, SE',
    ulbNodalContact: '7077795474'
  },
  {
    id: 7,
    block: 'ATTABIRA',
    ulb: 'Attabira NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'TAMPARSARA-DULAMPUR-AMLIPALI (TDA-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Swaraj Mahapatra, Sudhansu Dash, Ashok Kumar Sahu',
    gpNodalContact: '9178018738, 7077953660, 7894170870',
    ulbNodalPerson: 'Aswini Kumar Sabar, SE',
    ulbNodalContact: '7077795474'
  },
  {
    id: 8,
    block: 'ATTABIRA',
    ulb: 'Attabira NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'LARASARA-TOPE-JANGAD (LTJ-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Sujata Biswal, Ashok Kumar Sahu, Akshya Kumar Sahu',
    gpNodalContact: '9777377120, 7894170870, 8249304676',
    ulbNodalPerson: 'Aswini Kumar Sabar, SE',
    ulbNodalContact: '7077795474'
  },

  // BARGARH BLOCK
  {
    id: 9,
    block: 'Bargarh',
    ulb: 'Bargarh Municipality',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Nileswar-Birmal-S.Dumerpali (NBS-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Madhusmita Sahu, Minaketan Kharsel, Kshetrapal Dash',
    gpNodalContact: '9090810420, 9937980513, 9937186068',
    ulbNodalPerson: 'Dushmanta Kumar Behera, SE',
    ulbNodalContact: '9778855785'
  },
  {
    id: 10,
    block: 'Bargarh',
    ulb: 'Bargarh Municipality',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Chakarkend-Patharla-Gobindpur (CPG-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Dushyanta kara, Sangita Debta, Buddhadeb Jhant',
    gpNodalContact: '9658070886, 8260008655, 9777793595',
    ulbNodalPerson: 'Dushmanta Kumar Behera, SE',
    ulbNodalContact: '9778855785'
  },
  {
    id: 11,
    block: 'Bargarh',
    ulb: 'Bargarh Municipality',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Gudesira-Deogaon-Bardol (GDB-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Monika Munda, Kshetrapal Dash, Jemabati Majhi',
    gpNodalContact: '7750812933, 9937186068, 6371607614',
    ulbNodalPerson: 'Dushmanta Kumar Behera, SE',
    ulbNodalContact: '9778855785'
  },
  {
    id: 12,
    block: 'Bargarh',
    ulb: 'Bargarh Municipality',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Khaliapali-Katapali-Bargaon (KKB-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Sapna Padhan, Chitrasen Meher, Nandalal Dash',
    gpNodalContact: '9668005527, 7008922142, 9937929994',
    ulbNodalPerson: 'Dushmanta Kumar Behera, SE',
    ulbNodalContact: '9778855785'
  },
  {
    id: 13,
    block: 'Bargarh',
    ulb: 'Bargarh Municipality',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Tumgaon-Khuntpali-Sarsara (TKS-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Nabin Kumar sahu, Maninimayee Padhan, Santoshini Sahu',
    gpNodalContact: '8328829836, 6371769331, 8249790803',
    ulbNodalPerson: 'Dushmanta Kumar Behera, SE',
    ulbNodalContact: '9778855785'
  },
  {
    id: 14,
    block: 'Bargarh',
    ulb: 'Bargarh Municipality',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Gaisima-Dhanger (GD-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Milu Bhoi, Milu Bhoi',
    gpNodalContact: '7077453789, 7077453789',
    ulbNodalPerson: 'Dushmanta Kumar Behera, SE',
    ulbNodalContact: '9778855785'
  },
  {
    id: 15,
    block: 'Bargarh',
    ulb: 'Bargarh Municipality',
    mrf: 'MRF-3',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Bonda-N.Jampali-Jamurda (BNJJ-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Jayashree Biswal, Jagruti Dash, Nandalal Dash',
    gpNodalContact: '9556366051, 6370288318, 9937929994',
    ulbNodalPerson: 'Dushmanta Kumar Behera, SE',
    ulbNodalContact: '9778855785'
  },
  {
    id: 16,
    block: 'Bargarh',
    ulb: 'Bargarh Municipality',
    mrf: 'MRF-3',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Talsrigida-Kalapani-Barhagoda (TKB-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Gurekha Suna, Swagatika Biswal, Santoshini Sahu',
    gpNodalContact: '9348433936, 9853471126, 8249790803',
    ulbNodalPerson: 'Dushmanta Kumar Behera, SE',
    ulbNodalContact: '9778855785'
  },
  {
    id: 17,
    block: 'Bargarh',
    ulb: 'Bargarh Municipality',
    mrf: 'MRF-3',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Kuruan-Khandahata-Adgaon (KKA-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Minaketan Kharsel, Ramesh Ch. Behera, Ramesh Ch. Behera',
    gpNodalContact: '9937980513, 9668864040, 9668864040',
    ulbNodalPerson: 'Dushmanta Kumar Behera, SE',
    ulbNodalContact: '9778855785'
  },
  {
    id: 18,
    block: 'Bargarh',
    ulb: 'Bargarh Municipality',
    mrf: 'MRF-3',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Tora Circuit (T-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Sanjeeb Naik',
    gpNodalContact: '7894101497',
    ulbNodalPerson: 'Dushmanta Kumar Behera, SE',
    ulbNodalContact: '9778855785'
  },

  // BARPALI BLOCK
  {
    id: 19,
    block: 'BARPALI',
    ulb: 'Barpali NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Gopaepali-Bandhpali-Katapali (GBK-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Ketaki Meher, Manoj Behera, Taranisen Padhan',
    gpNodalContact: '9556390059, 9438293096, 9668218492',
    ulbNodalPerson: 'Sujit Purohit, SE',
    ulbNodalContact: '8018537101'
  },
  {
    id: 20,
    block: 'BARPALI',
    ulb: 'Barpali NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Barguda-Bhatigaon-Satalma (BBS-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Gopala Sahu, Rabikanta sahu, Saheba pande',
    gpNodalContact: '8249806514, 7326851494, 9337069708',
    ulbNodalPerson: 'Sujit Purohit, SE',
    ulbNodalContact: '8018537101'
  },
  {
    id: 21,
    block: 'BARPALI',
    ulb: 'Barpali NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Kainsir-Tulandi-Patkulunda (KTP-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Himansu Bhue, Nilanchala Padhan, Shikhal hota',
    gpNodalContact: '7750981359, 8249191296, 7684944244',
    ulbNodalPerson: 'Sujit Purohit, SE',
    ulbNodalContact: '8018537101'
  },
  {
    id: 22,
    block: 'BARPALI',
    ulb: 'Barpali NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Tinkani-Tilaemal-Roxa (TTR-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Mahendra sahu, Manoj Adabar, Upendra padhan',
    gpNodalContact: '9337216752, 8018144497, 9937531044',
    ulbNodalPerson: 'Sujit Purohit, SE',
    ulbNodalContact: '8018537101'
  },
  {
    id: 23,
    block: 'BARPALI',
    ulb: 'Barpali NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Khemesara-Mahada-Agalpur (KMA-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Rakesh purohit, Pramod padhan, Mahendra sahu',
    gpNodalContact: '9583782397, 8847889426, 9337216752',
    ulbNodalPerson: 'Sujit Purohit, SE',
    ulbNodalContact: '8018537101'
  },
  {
    id: 24,
    block: 'BARPALI',
    ulb: 'Barpali NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Lenda-Mahulpali-Kusanpuri (LMK-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Pramod padhan, Manoj Behera, Taranisen Padhan',
    gpNodalContact: '8847889426, 9438293096, 9668218492',
    ulbNodalPerson: 'Sujit Purohit, SE',
    ulbNodalContact: '8018537101'
  },
  {
    id: 25,
    block: 'BARPALI',
    ulb: 'Barpali NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Kanbar-Bagbadi (KB-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Brahmananda sahu, Sibanarayana sahu',
    gpNodalContact: '7978366340, 7978371599',
    ulbNodalPerson: 'Sujit Purohit, SE',
    ulbNodalContact: '8018537101'
  },
  {
    id: 26,
    block: 'BARPALI',
    ulb: 'Barpali NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'Remta-Kumbhari-Baramkela (RKB-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Nilanchala Padhan, Sushanta Dash, Pramod Bag',
    gpNodalContact: '8249191296, 9439104034, 9668699347',
    ulbNodalPerson: 'Sujit Purohit, SE',
    ulbNodalContact: '8018537101'
  },

  // BIJEPUR BLOCK
  {
    id: 27,
    block: 'BIJEPUR',
    ulb: 'BIJEPUR NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'CHARPALI-BUDAPALI-BAIRAKHPALI (CBB-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'CHUDAMANI NAIK, SABITRI LUHA, RAMBHA RANA',
    gpNodalContact: '8328912189, -, -',
    ulbNodalPerson: 'Prabhat Kumar Barik, SE',
    ulbNodalContact: '9668822700'
  },
  {
    id: 28,
    block: 'BIJEPUR',
    ulb: 'BIJEPUR NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'T.GANDAPALI-KHARMUNDA-SURUBALI (TKS-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'UMAKANTA BAG, MOUSAM PADHAN',
    gpNodalContact: '7978070599, 8763588393',
    ulbNodalPerson: 'Prabhat Kumar Barik, SE',
    ulbNodalContact: '9668822700'
  },
  {
    id: 29,
    block: 'BIJEPUR',
    ulb: 'BIJEPUR NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'SANBAUSEN-TALPADAR-M.SRIGIDA (STM-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'GOLAPA NAIK, PRAMOD PADHAN, SURAJ BISHI',
    gpNodalContact: '8327725472, 9937432653, 8594829007',
    ulbNodalPerson: 'Prabhat Kumar Barik, SE',
    ulbNodalContact: '9668822700'
  },
  {
    id: 30,
    block: 'BIJEPUR',
    ulb: 'BIJEPUR NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'JOKHIPALI-LAUMUNDA-PATHARLA (JLP-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'GOLAPA NIAK, NIRANJAN SAHU, ASWINI SAHU',
    gpNodalContact: '8327725472, 9937787831, 8328875150',
    ulbNodalPerson: 'Prabhat Kumar Barik, SE',
    ulbNodalContact: '9668822700'
  },
  {
    id: 31,
    block: 'BIJEPUR',
    ulb: 'BIJEPUR NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'BADBRAHAMNI-SAIPALI-BENIACHAL (BSB-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'SASHANK SEKHAR BEHERA, PANDAV NANDA, ABHILASH DISHRI',
    gpNodalContact: '7205579697, 9937787899, 7008083731',
    ulbNodalPerson: 'Prabhat Kumar Barik, SE',
    ulbNodalContact: '9668822700'
  },
  {
    id: 32,
    block: 'BIJEPUR',
    ulb: 'BIJEPUR NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'BARMUNDA-PADA-BHATIGAON (BPB-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'SURAJ BISHI, AMULYA BUDEK, GOLAPA NAIK',
    gpNodalContact: '8594829007, 7855017646, 8327725472',
    ulbNodalPerson: 'Prabhat Kumar Barik, SE',
    ulbNodalContact: '9668822700'
  },
  {
    id: 33,
    block: 'BIJEPUR',
    ulb: 'BIJEPUR NAC',
    mrf: 'MRF-1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'SAMALEIPADAR-JARING-BADBAUSEN (SJB-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'PANDAV NANDA, JAMINIKANTA DASH, RABI MEHER',
    gpNodalContact: '9937787899, 9938385959, 9937479353',
    ulbNodalPerson: 'Prabhat Kumar Barik, SE',
    ulbNodalContact: '9668822700'
  },
  {
    id: 34,
    block: 'BIJEPUR',
    ulb: 'BIJEPUR NAC',
    mrf: 'MRF-2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'PAHANDI-GANTHIAPALI (PG-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'RANJIT SINGH BARIHA, ASWINI SAHU',
    gpNodalContact: '9178643023, 8328875150',
    ulbNodalPerson: 'Prabhat Kumar Barik, SE',
    ulbNodalContact: '9668822700'
  },

  // PADAMPUR BLOCK
  {
    id: 35,
    block: 'PADAMPUR',
    ulb: 'PADAMPUR NAC',
    mrf: 'MRF1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'MAHULPALI-BHEUNRIA-BARIKEL (MBB-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Pusparanjan Uti, kunu seth',
    gpNodalContact: '7894433542, 9439623710',
    ulbNodalPerson: 'Dinabandhu Sahu, SE',
    ulbNodalContact: '9346051621'
  },
  {
    id: 36,
    block: 'PADAMPUR',
    ulb: 'PADAMPUR NAC',
    mrf: 'MRF1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'PURENA-LOHARPALI-KHALIAPALI (PLK-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Dolamani Padhan, Pusparanjan Uti',
    gpNodalContact: '9937930628, 7894433542',
    ulbNodalPerson: 'Dinabandhu Sahu, SE',
    ulbNodalContact: '9346051621'
  },
  {
    id: 37,
    block: 'PADAMPUR',
    ulb: 'PADAMPUR NAC',
    mrf: 'MRF1',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'DAHITA-BUDEN-DAHIGAON (DBD-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Gajanan Sidar, Rahasa seth',
    gpNodalContact: '7894566402, 7077374792',
    ulbNodalPerson: 'Dinabandhu Sahu, SE',
    ulbNodalContact: '9346051621'
  },
  {
    id: 38,
    block: 'PADAMPUR',
    ulb: 'PADAMPUR NAC',
    mrf: 'MRF2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'JAMARTALA-BUDAMAL-KANSAR (JBK-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Chamulal Luhar, Ramdas mahananda, Durga prasad Seth',
    gpNodalContact: '6371792715, 9348846480, 9937162529',
    ulbNodalPerson: 'Dinabandhu Sahu, SE',
    ulbNodalContact: '9346051621'
  },
  {
    id: 39,
    block: 'PADAMPUR',
    ulb: 'PADAMPUR NAC',
    mrf: 'MRF2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'JAMALA-DANGAGHAT-PALSAPALI (JDP-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Khirasagar Sahu, Lalit mohan sahu, Ghanashyam Tatang',
    gpNodalContact: '9937913002, 7682927338, 8249790803',
    ulbNodalPerson: 'Dinabandhu Sahu, SE',
    ulbNodalContact: '9346051621'
  },
  {
    id: 40,
    block: 'PADAMPUR',
    ulb: 'PADAMPUR NAC',
    mrf: 'MRF2',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'GYAN-TAL-MELCHHAMUNDA (GTM-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Ghanashyam Tatang, Priyambada Priyadashani luha, Durga prasa seth',
    gpNodalContact: '7894790638, 7683904423, 9937162529',
    ulbNodalPerson: 'Dinabandhu Sahu, SE',
    ulbNodalContact: '9346051621'
  },
  {
    id: 41,
    block: 'PADAMPUR',
    ulb: 'PADAMPUR NAC',
    mrf: 'MRF3',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'SARGIBAHAL-BARIHAPALI-KANSINGHA (SBK-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Khirasagar Sahu, Sarita Barik',
    gpNodalContact: '9937913002, 7326076338',
    ulbNodalPerson: 'Dinabandhu Sahu, SE',
    ulbNodalContact: '9346051621'
  },
  {
    id: 42,
    block: 'PADAMPUR',
    ulb: 'PADAMPUR NAC',
    mrf: 'MRF3',
    vehicleType: 'TATA S',
    vehicleNo: '-',
    vehicleCapacity: '6500 Kg',
    driverName: '-',
    driverContact: '-',
    collectionSchedule: 'Scheduled',
    gpName: 'CHARPALI Circuit (C-01)',
    wasteGeneratedKg: 0,
    gpNodalPerson: 'Lalit Mohan Sahu',
    gpNodalContact: '7682927338',
    ulbNodalPerson: 'Dinabandhu Sahu, SE',
    ulbNodalContact: '9346051621'
  }
];
