export interface GpMappingData {
  id: number;
  block: string;
  gpName: string;
  taggedUlb: string;
  taggedMrf: string;
}

export const gpMappingData: GpMappingData[] = [
  // Attabira Block
  { id: 1, block: 'Attabira', gpName: 'AMLIPALI', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 2, block: 'Attabira', gpName: 'BUGBUGA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 1' },
  { id: 3, block: 'Attabira', gpName: 'CHKULI', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 1' },
  { id: 4, block: 'Attabira', gpName: 'DULAMPUR', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 5, block: 'Attabira', gpName: 'GODBHAGA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 6, block: 'Attabira', gpName: 'HIRLIAPALI', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 1' },
  { id: 7, block: 'Attabira', gpName: 'JANGAD', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 8, block: 'Attabira', gpName: 'JANHAPADA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 1' },
  { id: 9, block: 'Attabira', gpName: 'JHILIMINDA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 1' },
  { id: 10, block: 'Attabira', gpName: 'KADABAHAL', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 11, block: 'Attabira', gpName: 'KHARMUMUNDA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 1' },
  { id: 12, block: 'Attabira', gpName: 'KULTATUKRA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 13, block: 'Attabira', gpName: 'KULUNDA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 1' },
  { id: 14, block: 'Attabira', gpName: 'KUMALSINMGHA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 15, block: 'Attabira', gpName: 'LACHIDA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 1' },
  { id: 16, block: 'Attabira', gpName: 'LAHANDA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 17, block: 'Attabira', gpName: 'LARAMBHA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 18, block: 'Attabira', gpName: 'LARASARA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 19, block: 'Attabira', gpName: 'MANAPADA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 1' },
  { id: 20, block: 'Attabira', gpName: 'PAHARSRIGIDA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 1' },
  { id: 21, block: 'Attabira', gpName: 'SILOT', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 22, block: 'Attabira', gpName: 'TAMPARSARA', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },
  { id: 23, block: 'Attabira', gpName: 'TANGARAPALLI', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 1' },
  { id: 24, block: 'Attabira', gpName: 'TOPE', taggedUlb: 'Attabira NAC', taggedMrf: 'MRF 2' },

  // Bargarh Block
  { id: 25, block: 'Bargarh', gpName: 'ADGAON', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 3' },
  { id: 26, block: 'Bargarh', gpName: 'BARDOL', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 27, block: 'Bargarh', gpName: 'BARGAON', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 28, block: 'Bargarh', gpName: 'BARHAGODA', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 3' },
  { id: 29, block: 'Bargarh', gpName: 'BIRMAL', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 30, block: 'Bargarh', gpName: 'BONDA', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 3' },
  { id: 31, block: 'Bargarh', gpName: 'CHAKARKEND', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 32, block: 'Bargarh', gpName: 'DEOGAON', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 33, block: 'Bargarh', gpName: 'DHANGER', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 2' },
  { id: 34, block: 'Bargarh', gpName: 'GAISIMA', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 2' },
  { id: 35, block: 'Bargarh', gpName: 'GOBINDPUR', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 36, block: 'Bargarh', gpName: 'GUDESIRA', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 37, block: 'Bargarh', gpName: 'JAMURDA', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 3' },
  { id: 38, block: 'Bargarh', gpName: 'KALAPANI', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 3' },
  { id: 39, block: 'Bargarh', gpName: 'KATAPALI', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 40, block: 'Bargarh', gpName: 'KHALIAPALI', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 41, block: 'Bargarh', gpName: 'KHANDAHATA', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 3' },
  { id: 42, block: 'Bargarh', gpName: 'KHUNTPALI', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 2' },
  { id: 43, block: 'Bargarh', gpName: 'KURUAN', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 3' },
  { id: 44, block: 'Bargarh', gpName: 'N. JAMPALI', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 3' },
  { id: 45, block: 'Bargarh', gpName: 'NILESWAR', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 46, block: 'Bargarh', gpName: 'PATHARLA', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 47, block: 'Bargarh', gpName: 'S. DUMERPALI', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 1' },
  { id: 48, block: 'Bargarh', gpName: 'SARSARA', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 2' },
  { id: 49, block: 'Bargarh', gpName: 'TALSRIGIDA', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 3' },
  { id: 50, block: 'Bargarh', gpName: 'TORA', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 3' },
  { id: 51, block: 'Bargarh', gpName: 'TUMGAON', taggedUlb: 'Bargarh Municipality', taggedMrf: 'MRF 2' },

  // Barpali Block
  { id: 52, block: 'Barpali', gpName: 'Agalpur', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 53, block: 'Barpali', gpName: 'Bagbadi', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 1' },
  { id: 54, block: 'Barpali', gpName: 'Bandhpali', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 55, block: 'Barpali', gpName: 'Baramkela', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 1' },
  { id: 56, block: 'Barpali', gpName: 'Barguda', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 57, block: 'Barpali', gpName: 'Bhatigon', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 58, block: 'Barpali', gpName: 'Gopaepali', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 1' },
  { id: 59, block: 'Barpali', gpName: 'Kainsir', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 60, block: 'Barpali', gpName: 'Kanbar', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 1' },
  { id: 61, block: 'Barpali', gpName: 'Katapali', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 1' },
  { id: 62, block: 'Barpali', gpName: 'Khemesara', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 63, block: 'Barpali', gpName: 'Kumbhari', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 1' },
  { id: 64, block: 'Barpali', gpName: 'Kushanpuri', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 1' },
  { id: 65, block: 'Barpali', gpName: 'Lenda', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 1' },
  { id: 66, block: 'Barpali', gpName: 'Mahada', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 67, block: 'Barpali', gpName: 'Mahulpali', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 68, block: 'Barpali', gpName: 'Patkulunda', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 69, block: 'Barpali', gpName: 'Remta', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 1' },
  { id: 70, block: 'Barpali', gpName: 'Roxa', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 71, block: 'Barpali', gpName: 'Satalma', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 72, block: 'Barpali', gpName: 'Tilaemal', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 73, block: 'Barpali', gpName: 'Tinkani', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },
  { id: 74, block: 'Barpali', gpName: 'Tulandi', taggedUlb: 'Barpali NAC', taggedMrf: 'MRF 2' },

  // Bijepur Block
  { id: 75, block: 'Bijepur', gpName: 'BADBAUSEN', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 76, block: 'Bijepur', gpName: 'BADBRAHMANI', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 77, block: 'Bijepur', gpName: 'BAIRAKHPALI', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 78, block: 'Bijepur', gpName: 'BARMUNDA', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 89, block: 'Bijepur', gpName: 'BENIACHAL', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 80, block: 'Bijepur', gpName: 'BHATIGAON', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 81, block: 'Bijepur', gpName: 'BUDAPALI', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 82, block: 'Bijepur', gpName: 'CHARPALI', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 83, block: 'Bijepur', gpName: 'GANTHIAPALI', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 2' },
  { id: 84, block: 'Bijepur', gpName: 'JARIG', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 85, block: 'Bijepur', gpName: 'JOKHIPALI', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 2' },
  { id: 86, block: 'Bijepur', gpName: 'KHARMUNDA', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 2' },
  { id: 87, block: 'Bijepur', gpName: 'LAUMUNDA', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 2' },
  { id: 88, block: 'Bijepur', gpName: 'M.SRIGIDA', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 89, block: 'Bijepur', gpName: 'PADA', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 90, block: 'Bijepur', gpName: 'PAHANDI', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 91, block: 'Bijepur', gpName: 'PATHARLA', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 2' },
  { id: 92, block: 'Bijepur', gpName: 'SAIPALI', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 2' },
  { id: 93, block: 'Bijepur', gpName: 'SAMALEIPADAR', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 94, block: 'Bijepur', gpName: 'SANBAUSEN', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },
  { id: 95, block: 'Bijepur', gpName: 'SURUBALI', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 2' },
  { id: 96, block: 'Bijepur', gpName: 'T.GANDAPALI', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 2' },
  { id: 97, block: 'Bijepur', gpName: 'TALPADAR', taggedUlb: 'Bijepur NAC', taggedMrf: 'MRF 1' },

  // Padampur Block
  { id: 98, block: 'Padampur', gpName: 'Barihapali', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
  { id: 99, block: 'Padampur', gpName: 'Charpali', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 1' },
  { id: 100, block: 'Padampur', gpName: 'Dahigaon', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 1' },
  { id: 101, block: 'Padampur', gpName: 'Dahita', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 2' },
  { id: 102, block: 'Padampur', gpName: 'Dangaghat', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
  { id: 103, block: 'Padampur', gpName: 'Jamala', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
  { id: 104, block: 'Padampur', gpName: 'Kansingh', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 2' },
  { id: 105, block: 'Padampur', gpName: 'Mahulpali', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 2' },
  { id: 106, block: 'Padampur', gpName: 'Melchhamunda', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
  { id: 107, block: 'Padampur', gpName: 'Bheunria', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
  { id: 108, block: 'Padampur', gpName: 'Barikel', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
  { id: 109, block: 'Padampur', gpName: 'Budamal', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
  { id: 110, block: 'Padampur', gpName: 'Buden', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 1' },
  { id: 111, block: 'Padampur', gpName: 'Gyan', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
  { id: 112, block: 'Padampur', gpName: 'Jamartala', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 1' },
  { id: 113, block: 'Padampur', gpName: 'Kansar', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 2' },
  { id: 114, block: 'Padampur', gpName: 'Khaliapali', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 1' },
  { id: 115, block: 'Padampur', gpName: 'Phalsapali', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
  { id: 116, block: 'Padampur', gpName: 'Purena', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
  { id: 117, block: 'Padampur', gpName: 'Tal', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 2' },
  { id: 118, block: 'Padampur', gpName: 'Loharpali', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
  { id: 119, block: 'Padampur', gpName: 'Sargibhal', taggedUlb: 'Padampur NAC', taggedMrf: 'MRF 3' },
];
