export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // Titlagarh Block (Rows 1-24)
  { id: 1, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'ADABAHAL', wasteGeneratedKg: 2315, gpNodalPerson: 'PEO', gpNodalContact: '8917408652', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 2, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BANDUPALA', wasteGeneratedKg: 2212, gpNodalPerson: 'PEO', gpNodalContact: '9438040437', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 3, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BANJIPADAR', wasteGeneratedKg: 1705, gpNodalPerson: 'PEO', gpNodalContact: '7881883802', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 4, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BHALEGAON', wasteGeneratedKg: 1882, gpNodalPerson: 'PEO', gpNodalContact: '9438040437', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 5, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BIJEPUR', wasteGeneratedKg: 3331, gpNodalPerson: 'PEO', gpNodalContact: '8917395122', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 6, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BINEKELA', wasteGeneratedKg: 2098, gpNodalPerson: 'PEO', gpNodalContact: '8260704230', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 7, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'DIGSIRA', wasteGeneratedKg: 1979, gpNodalPerson: 'PEO', gpNodalContact: '8249377839', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 8, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GHANTABAHAL', wasteGeneratedKg: 1384, gpNodalPerson: 'PEO', gpNodalContact: '9938574811', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8227421601' },
  { id: 9, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GHODAR', wasteGeneratedKg: 1876, gpNodalPerson: 'PEO', gpNodalContact: '9437224167', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 10, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'JAGUA', wasteGeneratedKg: 2380, gpNodalPerson: 'PEO', gpNodalContact: '9437224167', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 11, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KATARKELA', wasteGeneratedKg: 1799, gpNodalPerson: 'PEO', gpNodalContact: '9937986161', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 12, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KHOLAN', wasteGeneratedKg: 2795, gpNodalPerson: 'PEO', gpNodalContact: '9938574811', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 13, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KURSUD', wasteGeneratedKg: 2487, gpNodalPerson: 'PEO', gpNodalContact: '8114880891', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 14, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KUSKELA', wasteGeneratedKg: 1287, gpNodalPerson: 'PEO', gpNodalContact: '9777224742', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 15, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'LUTHURBANDH', wasteGeneratedKg: 1976, gpNodalPerson: 'PEO', gpNodalContact: '9337725519', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 16, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MAHULPADA', wasteGeneratedKg: 2318, gpNodalPerson: 'PEO', gpNodalContact: '9937908761', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 17, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MANIGAON', wasteGeneratedKg: 2155, gpNodalPerson: 'PEO', gpNodalContact: '9937535865', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 18, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MARLAD', wasteGeneratedKg: 1344, gpNodalPerson: 'PEO', gpNodalContact: '9938440907', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 19, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'NAREN', wasteGeneratedKg: 1992, gpNodalPerson: 'PEO', gpNodalContact: '8658800077', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8227421601' },
  { id: 20, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'PARASARA', wasteGeneratedKg: 2309, gpNodalPerson: 'PEO', gpNodalContact: '7854048548', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 21, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SAGADGHAT', wasteGeneratedKg: 2020, gpNodalPerson: 'PEO', gpNodalContact: '7978035963', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 22, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SIHINI', wasteGeneratedKg: 2991, gpNodalPerson: 'PEO', gpNodalContact: '8249674773', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 23, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SIJUAN', wasteGeneratedKg: 1590, gpNodalPerson: 'PEO', gpNodalContact: '8917828561', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },
  { id: 24, block: 'Titlagarh', ulb: 'Titlagarh', mrf: 'Titlagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SURDA', wasteGeneratedKg: 1565, gpNodalPerson: 'PEO', gpNodalContact: '7539838477', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9337421601' },

  // Tureikela Block (Rows 25-43)
  { id: 25, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BADBANKI', wasteGeneratedKg: 3303, gpNodalPerson: 'PEO', gpNodalContact: '8370457352', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 26, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BADDHAKLA', wasteGeneratedKg: 1740, gpNodalPerson: 'PEO', gpNodalContact: '7894013121', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 27, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BUROMAL', wasteGeneratedKg: 2670, gpNodalPerson: 'PEO', gpNodalContact: '9938737857', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 28, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'CHATUANKA', wasteGeneratedKg: 1885, gpNodalPerson: 'PEO', gpNodalContact: '9938588241', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 29, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'CHHAUSUKHA', wasteGeneratedKg: 1450, gpNodalPerson: 'PEO', gpNodalContact: '7978109490', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 30, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'DHAMANDANGA', wasteGeneratedKg: 2894, gpNodalPerson: 'PEO', gpNodalContact: '9938588241', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 31, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'DHOLMANDAL', wasteGeneratedKg: 1475, gpNodalPerson: 'PEO', gpNodalContact: '7894013121', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 32, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GHUNESH', wasteGeneratedKg: 2355, gpNodalPerson: 'PEO', gpNodalContact: '9938477848', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 33, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'HALANBHATA', wasteGeneratedKg: 2042, gpNodalPerson: 'PEO', gpNodalContact: '8260135946', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 34, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'HIAL', wasteGeneratedKg: 3976, gpNodalPerson: 'PEO', gpNodalContact: '9937803660', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 35, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'JHARANI', wasteGeneratedKg: 2424, gpNodalPerson: 'PEO', gpNodalContact: '7608040948', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 36, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KAMBIMUNDA', wasteGeneratedKg: 1522, gpNodalPerson: 'PEO', gpNodalContact: '9337265372', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 37, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KANDEI', wasteGeneratedKg: 1389, gpNodalPerson: 'PEO', gpNodalContact: '7077322058', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 38, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KARUANMUNDA', wasteGeneratedKg: 1691, gpNodalPerson: 'PEO', gpNodalContact: '9937408606', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 39, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KHAGSA', wasteGeneratedKg: 1748, gpNodalPerson: 'PEO', gpNodalContact: '9338241132', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 40, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KUILBAHAL', wasteGeneratedKg: 2066, gpNodalPerson: 'PEO', gpNodalContact: '7894943370', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 41, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MAHAKHAND', wasteGeneratedKg: 1387, gpNodalPerson: 'PEO', gpNodalContact: '8371848879', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 42, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MAHULPATI', wasteGeneratedKg: 1445, gpNodalPerson: 'PEO', gpNodalContact: '9938477848', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },
  { id: 43, block: 'Tureikela', ulb: 'Kantabanji', mrf: 'Kantabanji MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'TUREIKELA', wasteGeneratedKg: 3374, gpNodalPerson: 'PEO', gpNodalContact: '9938167329', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8249991154' },

  // Balangir Block (Rows 44-68)
  { id: 44, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BAIDIPALI', wasteGeneratedKg: 1607, gpNodalPerson: 'PEO', gpNodalContact: '9556065129', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 45, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BARAPUDGIA', wasteGeneratedKg: 2137, gpNodalPerson: 'PEO', gpNodalContact: '9938618275', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 46, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BARKANI', wasteGeneratedKg: 1020, gpNodalPerson: 'PEO', gpNodalContact: '9938618275', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 47, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BHUNDIMUHAN', wasteGeneratedKg: 1087, gpNodalPerson: 'PEO', gpNodalContact: '8114463831', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 48, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BHUTIARBAHAL', wasteGeneratedKg: 1705, gpNodalPerson: 'PEO', gpNodalContact: '7008044064', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 49, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BIDIKHAT', wasteGeneratedKg: 1175, gpNodalPerson: 'PEO', gpNodalContact: '9938312215', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 50, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'CHANDANBHATI', wasteGeneratedKg: 2752, gpNodalPerson: 'PEO', gpNodalContact: '9938312215', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 51, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'CHIKALBAHAL', wasteGeneratedKg: 1493, gpNodalPerson: 'PEO', gpNodalContact: '9861253657', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 52, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'CHUDAPALI', wasteGeneratedKg: 1071, gpNodalPerson: 'PEO', gpNodalContact: '9861253657', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 53, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'JHANKARPALI', wasteGeneratedKg: 1604, gpNodalPerson: 'PEO', gpNodalContact: '7008044064', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 54, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KHALIAPALI', wasteGeneratedKg: 1040, gpNodalPerson: 'PEO', gpNodalContact: '9556065129', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 55, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KHULENPALI', wasteGeneratedKg: 1472, gpNodalPerson: 'PEO', gpNodalContact: '9938312215', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 56, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KHUNTPALI', wasteGeneratedKg: 1279, gpNodalPerson: 'PEO', gpNodalContact: '9938312215', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 57, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KUDASINGHA', wasteGeneratedKg: 1627, gpNodalPerson: 'PEO', gpNodalContact: '8114463831', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 58, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KUTUMDOLA', wasteGeneratedKg: 1625, gpNodalPerson: 'PEO', gpNodalContact: '9437572049', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 59, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MADHIAPALI', wasteGeneratedKg: 1608, gpNodalPerson: 'PEO', gpNodalContact: '9437801942', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 60, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MANHIRA', wasteGeneratedKg: 2174, gpNodalPerson: 'PEO', gpNodalContact: '9938618275', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 61, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MAYABARHA', wasteGeneratedKg: 1726, gpNodalPerson: 'PEO', gpNodalContact: '7978075671', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 62, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MIRDHPALI', wasteGeneratedKg: 2161, gpNodalPerson: 'PEO', gpNodalContact: '7978075671', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 63, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SADEIPALI', wasteGeneratedKg: 2240, gpNodalPerson: 'PEO', gpNodalContact: '9437572049', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 64, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SAHABAHAL', wasteGeneratedKg: 1109, gpNodalPerson: 'PEO', gpNodalContact: '9437801942', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 65, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SAKMA', wasteGeneratedKg: 2397, gpNodalPerson: 'PEO', gpNodalContact: '7008044064', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 66, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SIBTALA', wasteGeneratedKg: 2378, gpNodalPerson: 'PEO', gpNodalContact: '9437801942', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 67, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SIKACHHIDA', wasteGeneratedKg: 1681, gpNodalPerson: 'PEO', gpNodalContact: '9556065129', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },
  { id: 68, block: 'Balangir', ulb: 'Balangir', mrf: 'Balangir MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'TUSURABAHAL', wasteGeneratedKg: 1074, gpNodalPerson: 'PEO', gpNodalContact: '9437572049', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '9439146997' },

  // Patnagarh Block (Rows 69-98)
  { id: 69, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BALIPATA', wasteGeneratedKg: 2106, gpNodalPerson: 'PEO', gpNodalContact: '6372735351', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 70, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BANEIMUNDA', wasteGeneratedKg: 2318, gpNodalPerson: 'PEO', gpNodalContact: '7749075734', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 71, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BARPADAR', wasteGeneratedKg: 1705, gpNodalPerson: 'PEO', gpNodalContact: '9437707876', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 72, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BATHARLA', wasteGeneratedKg: 1484, gpNodalPerson: 'PEO', gpNodalContact: '9777986265', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 73, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BHAINSA', wasteGeneratedKg: 2741, gpNodalPerson: 'PEO', gpNodalContact: '9938353566', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 74, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BHARATBAHAL', wasteGeneratedKg: 1253, gpNodalPerson: 'PEO', gpNodalContact: '9556144199', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 75, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'DANGBAHAL', wasteGeneratedKg: 2675, gpNodalPerson: 'PEO', gpNodalContact: '7894636848', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 76, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'DEULGAON', wasteGeneratedKg: 1863, gpNodalPerson: 'PEO', gpNodalContact: '9937521514', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 77, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'DHATUK', wasteGeneratedKg: 1866, gpNodalPerson: 'PEO', gpNodalContact: '7894636848', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 78, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'DUBHALAPAD', wasteGeneratedKg: 1845, gpNodalPerson: 'PEO', gpNodalContact: '9937680730', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 79, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'FATAMUNDA', wasteGeneratedKg: 1100, gpNodalPerson: 'PEO', gpNodalContact: '7608085222', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 80, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GANGASAGAR', wasteGeneratedKg: 1813, gpNodalPerson: 'PEO', gpNodalContact: '7978202965', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 81, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GERDA', wasteGeneratedKg: 1720, gpNodalPerson: 'PEO', gpNodalContact: '9937521514', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 82, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GHASIAN', wasteGeneratedKg: 1528, gpNodalPerson: 'PEO', gpNodalContact: '9938353566', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 83, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GHUCHE PALI', wasteGeneratedKg: 1342, gpNodalPerson: 'PEO', gpNodalContact: '9938304121', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 84, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'JOGIMUNDA', wasteGeneratedKg: 2489, gpNodalPerson: 'PEO', gpNodalContact: '6371786433', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 85, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KENDUMUNDI', wasteGeneratedKg: 2931, gpNodalPerson: 'PEO', gpNodalContact: '8358024093', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 86, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KERBEDA', wasteGeneratedKg: 1737, gpNodalPerson: 'PEO', gpNodalContact: '9938304121', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 87, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KHUNTSAMAL', wasteGeneratedKg: 2304, gpNodalPerson: 'PEO', gpNodalContact: '7077610462', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 88, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'KHURSEL', wasteGeneratedKg: 1352, gpNodalPerson: 'PEO', gpNodalContact: '9556144199', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 89, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'LARAMBHA', wasteGeneratedKg: 2268, gpNodalPerson: 'PEO', gpNodalContact: '8637255181', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 90, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MARUAN', wasteGeneratedKg: 2641, gpNodalPerson: 'PEO', gpNodalContact: '7894636848', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 91, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MUNDOMAHUL', wasteGeneratedKg: 1810, gpNodalPerson: 'PEO', gpNodalContact: '9437707876', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 92, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'PANDAMUNDA', wasteGeneratedKg: 2280, gpNodalPerson: 'PEO', gpNodalContact: '9556468562', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 93, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SALEPALI', wasteGeneratedKg: 2059, gpNodalPerson: 'PEO', gpNodalContact: '9556468562', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 94, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SOLEBANDH', wasteGeneratedKg: 1299, gpNodalPerson: 'PEO', gpNodalContact: '9938387340', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 95, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SUNAMUDI', wasteGeneratedKg: 2068, gpNodalPerson: 'PEO', gpNodalContact: '9938387340', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 96, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'TAMIAN', wasteGeneratedKg: 2513, gpNodalPerson: 'PEO', gpNodalContact: '8895119241', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 97, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'TENDAPADAR', wasteGeneratedKg: 2106, gpNodalPerson: 'PEO', gpNodalContact: '9337049747', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },
  { id: 98, block: 'Patnagarh', ulb: 'Patnagarh', mrf: 'Patnagarh MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'ULBA', wasteGeneratedKg: 2217, gpNodalPerson: 'PEO', gpNodalContact: '6371804050', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '8384032675' },

  // Gudvella Block (Rows 99-111)
  { id: 99, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BADAMOUNDA', wasteGeneratedKg: 1215, gpNodalPerson: 'PEO', gpNodalContact: '9337790050', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 100, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'BIRAMUNDA', wasteGeneratedKg: 1461, gpNodalPerson: 'PEO', gpNodalContact: '8328822040', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 101, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'CHINCHED', wasteGeneratedKg: 958, gpNodalPerson: 'PEO', gpNodalContact: '9556172569', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 102, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'DEULGUDI', wasteGeneratedKg: 1992, gpNodalPerson: 'PEO', gpNodalContact: '8328822040', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 103, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GAMBHARIGUDA', wasteGeneratedKg: 1047, gpNodalPerson: 'PEO', gpNodalContact: '9556172569', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 104, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GHUNA', wasteGeneratedKg: 2229, gpNodalPerson: 'PEO', gpNodalContact: '8637211991', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 105, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'GUDVELA', wasteGeneratedKg: 1933, gpNodalPerson: 'PEO', gpNodalContact: '8637211991', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 106, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'JAMUT', wasteGeneratedKg: 1209, gpNodalPerson: 'PEO', gpNodalContact: '7978830470', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 107, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'MADHEKELA', wasteGeneratedKg: 2042, gpNodalPerson: 'PEO', gpNodalContact: '8310078186', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 108, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'NUAPADA', wasteGeneratedKg: 1865, gpNodalPerson: 'PEO', gpNodalContact: '8249977917', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 109, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'RUSUDA', wasteGeneratedKg: 2532, gpNodalPerson: 'PEO', gpNodalContact: '9556464582', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 110, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'SAMARA', wasteGeneratedKg: 1200, gpNodalPerson: 'PEO', gpNodalContact: '9938000596', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' },
  { id: 111, block: 'Gudvella', ulb: 'Tusura', mrf: 'Tusura MRF', vehicleType: 'Tractor', vehicleNo: '-', vehicleCapacity: '-', driverName: '-', driverContact: '-', collectionSchedule: 'Scheduled', gpName: 'TENTULIKHUNTI', wasteGeneratedKg: 2291, gpNodalPerson: 'PEO', gpNodalContact: '8249977917', ulbNodalPerson: 'Sanitaiton Expert', ulbNodalContact: '7978330685' }
];
