export interface GpMappingData {
  id: number;
  block: string;
  gpName: string;
  taggedUlb: string;
  taggedMrf: string;
}

export const gpMappingData: GpMappingData[] = [
  // Block Balangir
  { id: 1, block: 'Balangir', gpName: 'BAIDIPALI', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 2, block: 'Balangir', gpName: 'BARAPUDGIA', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 3, block: 'Balangir', gpName: 'BARKANI', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 4, block: 'Balangir', gpName: 'BHUNDIMUHAN', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 5, block: 'Balangir', gpName: 'BHUTIARBAHAL', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 6, block: 'Balangir', gpName: 'BIDIKHAT', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 7, block: 'Balangir', gpName: 'CHANDANBHATI', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 8, block: 'Balangir', gpName: 'CHIKALBAHAL', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 9, block: 'Balangir', gpName: 'CHUDAPALI', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 10, block: 'Balangir', gpName: 'JHANKARPALI', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 11, block: 'Balangir', gpName: 'KHALIAPALI', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 12, block: 'Balangir', gpName: 'KHULENPALI', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 13, block: 'Balangir', gpName: 'KHUNTPALI', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 14, block: 'Balangir', gpName: 'KUDASINGHA', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 15, block: 'Balangir', gpName: 'KUTUMDOLA', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 16, block: 'Balangir', gpName: 'MADHIAPALI', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 17, block: 'Balangir', gpName: 'MANHIRA', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 18, block: 'Balangir', gpName: 'MAYABARHA', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 19, block: 'Balangir', gpName: 'MIRDHPALI', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 20, block: 'Balangir', gpName: 'SADEIPALI', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 21, block: 'Balangir', gpName: 'SAHABAHAL', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 22, block: 'Balangir', gpName: 'SAKMA', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 23, block: 'Balangir', gpName: 'SIBTALA', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 24, block: 'Balangir', gpName: 'SIKACHHIDA', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },
  { id: 25, block: 'Balangir', gpName: 'TUSURABAHAL', taggedUlb: 'Balangir', taggedMrf: 'Balangir' },

  // Block Gudvella
  { id: 26, block: 'Gudvella', gpName: 'BADAMOUNDA', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 27, block: 'Gudvella', gpName: 'BIRAMUNDA', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 28, block: 'Gudvella', gpName: 'CHINCHED', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 29, block: 'Gudvella', gpName: 'DEULGUDI', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 30, block: 'Gudvella', gpName: 'GAMBHARIGUDA', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 31, block: 'Gudvella', gpName: 'GHUNA', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 32, block: 'Gudvella', gpName: 'GUDVELA', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 33, block: 'Gudvella', gpName: 'JAMUT', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 34, block: 'Gudvella', gpName: 'MADHEKELA', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 35, block: 'Gudvella', gpName: 'NUAPADA', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 36, block: 'Gudvella', gpName: 'RUSUDA', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 37, block: 'Gudvella', gpName: 'SAMARA', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },
  { id: 38, block: 'Gudvella', gpName: 'TENTULIKHUNTI', taggedUlb: 'Tusura', taggedMrf: 'Tusura' },

  // Block Patnagarh
  { id: 39, block: 'Patnagarh', gpName: 'BALIPATA', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 40, block: 'Patnagarh', gpName: 'BANEIMUNDA', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 41, block: 'Patnagarh', gpName: 'BARPADAR', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 42, block: 'Patnagarh', gpName: 'BATHARLA', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 43, block: 'Patnagarh', gpName: 'BHAINSA', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 44, block: 'Patnagarh', gpName: 'BHARATBAHAL', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 45, block: 'Patnagarh', gpName: 'DANGBAHAL', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 46, block: 'Patnagarh', gpName: 'DEULGAON', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 47, block: 'Patnagarh', gpName: 'DHATUK', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 48, block: 'Patnagarh', gpName: 'DUBHALAPAD', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 49, block: 'Patnagarh', gpName: 'FATAMUNDA', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 50, block: 'Patnagarh', gpName: 'GANGASAGAR', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 51, block: 'Patnagarh', gpName: 'GERDA', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 52, block: 'Patnagarh', gpName: 'GHASIAN', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 53, block: 'Patnagarh', gpName: 'GHUCHE PALI', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 54, block: 'Patnagarh', gpName: 'JOGIMUNDA', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 55, block: 'Patnagarh', gpName: 'KENDUMUNDI', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 56, block: 'Patnagarh', gpName: 'KERBEDA', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 57, block: 'Patnagarh', gpName: 'KHUNTSAMAL', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 58, block: 'Patnagarh', gpName: 'KHURSEL', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 59, block: 'Patnagarh', gpName: 'LARAMBHA', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 60, block: 'Patnagarh', gpName: 'MARUAN', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 61, block: 'Patnagarh', gpName: 'MUNDOMAHUL', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 62, block: 'Patnagarh', gpName: 'PANDAMUNDA', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 63, block: 'Patnagarh', gpName: 'SALEPALI', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 64, block: 'Patnagarh', gpName: 'SOLEBANDH', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 65, block: 'Patnagarh', gpName: 'SUNAMUDI', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 66, block: 'Patnagarh', gpName: 'TAMIAN', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 67, block: 'Patnagarh', gpName: 'TENDAPADAR', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },
  { id: 68, block: 'Patnagarh', gpName: 'ULBA', taggedUlb: 'Patnagarh', taggedMrf: 'Patnagarh' },

  // Block Titlagarh
  { id: 69, block: 'Titlagarh', gpName: 'ADABAHAL', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 70, block: 'Titlagarh', gpName: 'BANDUPALA', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 71, block: 'Titlagarh', gpName: 'BANJIPADAR', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 72, block: 'Titlagarh', gpName: 'BHALEGAON', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 73, block: 'Titlagarh', gpName: 'BIJEPUR', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 74, block: 'Titlagarh', gpName: 'BINEKELA', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 75, block: 'Titlagarh', gpName: 'DIGSIRA', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 76, block: 'Titlagarh', gpName: 'GHANTABAHAL', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 77, block: 'Titlagarh', gpName: 'GHODAR', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 78, block: 'Titlagarh', gpName: 'JAGUA', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 79, block: 'Titlagarh', gpName: 'KATARKELA', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 80, block: 'Titlagarh', gpName: 'KHOLAN', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 81, block: 'Titlagarh', gpName: 'KURSUD', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 82, block: 'Titlagarh', gpName: 'KUSKELA', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 83, block: 'Titlagarh', gpName: 'LUTHURBANDH', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 84, block: 'Titlagarh', gpName: 'MAHULPADA', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 85, block: 'Titlagarh', gpName: 'MANIGAON', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 86, block: 'Titlagarh', gpName: 'MARLAD', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 87, block: 'Titlagarh', gpName: 'NAREN', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 88, block: 'Titlagarh', gpName: 'PARASARA', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 89, block: 'Titlagarh', gpName: 'SAGADGHAT', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 90, block: 'Titlagarh', gpName: 'SIHINI', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 91, block: 'Titlagarh', gpName: 'SIJUAN', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },
  { id: 92, block: 'Titlagarh', gpName: 'SURDA', taggedUlb: 'Titlagarh', taggedMrf: 'Titlagarh' },

  // Block Tureikela
  { id: 93, block: 'Tureikela', gpName: 'BADBANKI', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 94, block: 'Tureikela', gpName: 'BADDHAKLA', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 95, block: 'Tureikela', gpName: 'BUROMAL', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 96, block: 'Tureikela', gpName: 'CHATUANKA', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 97, block: 'Tureikela', gpName: 'CHHAUSUKHA', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 98, block: 'Tureikela', gpName: 'DHAMANDANGA', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 99, block: 'Tureikela', gpName: 'DHOLMANDAL', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 100, block: 'Tureikela', gpName: 'GHUNESH', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 101, block: 'Tureikela', gpName: 'HALANBHATA', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 102, block: 'Tureikela', gpName: 'HIAL', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 103, block: 'Tureikela', gpName: 'JHARANI', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 104, block: 'Tureikela', gpName: 'KAMBIMUNDA', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 105, block: 'Tureikela', gpName: 'KANDEI', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 106, block: 'Tureikela', gpName: 'KARUANMUNDA', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 107, block: 'Tureikela', gpName: 'KHAGSA', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 108, block: 'Tureikela', gpName: 'KUILBAHAL', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 109, block: 'Tureikela', gpName: 'MAHAKHAND', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 110, block: 'Tureikela', gpName: 'MAHULPATI', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
  { id: 111, block: 'Tureikela', gpName: 'TUREIKELA', taggedUlb: 'Tureikela', taggedMrf: 'Tureikela' },
];
