export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
  routeId?: string;
  routeName?: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // BARIPADA Block
  {
    id: 1,
    block: 'BARIPADA',
    ulb: 'BARIPADA MUNICIPALITY',
    mrf: 'RAGHUNATHPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'MONDAY, FRIDAY',
    gpName: 'BETNA',
    wasteGeneratedKg: 163.9,
    gpNodalPerson: 'Kartik Chandra Mohanta',
    gpNodalContact: '9861213832',
    ulbNodalPerson: 'SARTHAK',
    ulbNodalContact: '7978829303'
  },
  {
    id: 2,
    block: 'BARIPADA',
    ulb: 'BARIPADA MUNICIPALITY',
    mrf: 'RAGHUNATHPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'MONDAY, FRIDAY',
    gpName: 'BANKISOLE',
    wasteGeneratedKg: 112.1,
    gpNodalPerson: 'Kartik Chandra Mohanta',
    gpNodalContact: '9861213832',
    ulbNodalPerson: 'SARTHAK',
    ulbNodalContact: '7978829303'
  },
  {
    id: 3,
    block: 'BARIPADA',
    ulb: 'BARIPADA MUNICIPALITY',
    mrf: 'RAGHUNATHPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'MONDAY, FRIDAY',
    gpName: 'CHANDANPUR',
    wasteGeneratedKg: 178.2,
    gpNodalPerson: 'Kanhuram Soren',
    gpNodalContact: '9980908409',
    ulbNodalPerson: 'SARTHAK',
    ulbNodalContact: '7978829303'
  },
  {
    id: 4,
    block: 'BARIPADA',
    ulb: 'BARIPADA MUNICIPALITY',
    mrf: 'RAGHUNATHPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'TUESDAY, SATURDAY',
    gpName: 'LAXMIPOSI',
    wasteGeneratedKg: 92.6,
    gpNodalPerson: 'Ananta Kishore Maharana',
    gpNodalContact: '9861363677',
    ulbNodalPerson: 'SARTHAK',
    ulbNodalContact: '7978829303'
  },
  {
    id: 5,
    block: 'BARIPADA',
    ulb: 'BARIPADA MUNICIPALITY',
    mrf: 'RAGHUNATHPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'TUESDAY, SATURDAY',
    gpName: 'RAJABASA',
    wasteGeneratedKg: 217.0,
    gpNodalPerson: 'Subasish Behera',
    gpNodalContact: '8984189369',
    ulbNodalPerson: 'SARTHAK',
    ulbNodalContact: '7978829303'
  },
  {
    id: 6,
    block: 'BARIPADA',
    ulb: 'BARIPADA MUNICIPALITY',
    mrf: 'RAGHUNATHPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'TUESDAY, SATURDAY',
    gpName: 'SANKHABHANGA',
    wasteGeneratedKg: 173.1,
    gpNodalPerson: 'Rajabati Sing',
    gpNodalContact: '7735285694',
    ulbNodalPerson: 'SARTHAK',
    ulbNodalContact: '7978829303'
  },

  // UDALA Block
  {
    id: 12,
    block: 'UDALA',
    ulb: 'UDALA NAC',
    mrf: 'MRF1 (MENDHAKHAI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'MONDAY',
    gpName: 'RADHO, KOCHILADIHA',
    wasteGeneratedKg: 393.8,
    gpNodalPerson: 'Prafulla Kumar sial, Daka Singh',
    gpNodalContact: '9853988109, 8018980295',
    ulbNodalPerson: 'PRITISH',
    ulbNodalContact: '9040370732',
    routeId: 'KMAYUDAR-1',
    routeName: 'RK-01'
  },
  {
    id: 13,
    block: 'UDALA',
    ulb: 'UDALA NAC',
    mrf: 'MRF1 (MENDHAKHAI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'TUESDAY',
    gpName: 'BAHUBANDH, BADKHAMAN',
    wasteGeneratedKg: 327.5,
    gpNodalPerson: 'Gangadhara Sahu, Prafulla Kumar sial',
    gpNodalContact: '9439450171, 9853988110',
    ulbNodalPerson: 'PRITISH',
    ulbNodalContact: '9040370732',
    routeId: 'KMAYUDAB-2',
    routeName: 'BB-02'
  },
  {
    id: 14,
    block: 'UDALA',
    ulb: 'UDALA NAC',
    mrf: 'MRF1 (MENDHAKHAI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'WEDNESDAY',
    gpName: 'BADSINGARIA, DUGUDHA',
    wasteGeneratedKg: 255.2,
    gpNodalPerson: 'Banita Patra, Rasmita Kumari Sahu',
    gpNodalContact: '9439714047, 9937501333',
    ulbNodalPerson: 'PRITISH',
    ulbNodalContact: '9040370732',
    routeId: 'KMAYUDAB-3',
    routeName: 'BD-03'
  },
  {
    id: 15,
    block: 'UDALA',
    ulb: 'UDALA NAC',
    mrf: 'MRF1 (MENDHAKHAI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'THRUSDAY',
    gpName: 'KHALADI, BHIMTALI',
    wasteGeneratedKg: 391.4,
    gpNodalPerson: 'Biswanath Sail, Surat Kumar Pradhan',
    gpNodalContact: '9853454896, 9778346109',
    ulbNodalPerson: 'PRITISH',
    ulbNodalContact: '9040370732',
    routeId: 'KMAYUDAK-4',
    routeName: 'KB-04'
  },
  {
    id: 16,
    block: 'UDALA',
    ulb: 'UDALA NAC',
    mrf: 'MRF1 (MENDHAKHAI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'FRIDAY',
    gpName: 'KUNDABAI, NUAGAN',
    wasteGeneratedKg: 224.2,
    gpNodalPerson: 'Prasanta Kumar Pattanayak, Anita Behera',
    gpNodalContact: '9439216480, 7381626128',
    ulbNodalPerson: 'PRITISH',
    ulbNodalContact: '9040370732',
    routeId: 'KMAYUDAK-5',
    routeName: 'KN-05'
  },
  {
    id: 17,
    block: 'UDALA',
    ulb: 'UDALA NAC',
    mrf: 'MRF1 (MENDHAKHAI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'SATURDAY',
    gpName: 'PATSANIPUR, SRIRAMCHANDRAPUR',
    wasteGeneratedKg: 362.3,
    gpNodalPerson: 'Harish Chandra Sahu, Bijan Kumar Mohapatra',
    gpNodalContact: '9337985204, 9853269370',
    ulbNodalPerson: 'PRITISH',
    ulbNodalContact: '9040370732',
    routeId: 'KMAYUDAP-6',
    routeName: 'PS-06'
  },

  // RAIRANGPUR Block
  {
    id: 18,
    block: 'RAIRANGPUR',
    ulb: 'RAIRANGPUR MUNICIPALITY',
    mrf: 'MRF 2 (BAIDAPOSI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'MONDAY (EVERY MONDAY IN A MONTH)',
    gpName: 'BHALUBASA, HALDA',
    wasteGeneratedKg: 336.4,
    gpNodalPerson: 'Anil Kumar Mohanta(Jamda), Ghasiram Marndi',
    gpNodalContact: '9438116732, 8249077677',
    ulbNodalPerson: 'SWADHIN',
    ulbNodalContact: '9778588533',
    routeId: 'KMAYRAIBH-1',
    routeName: 'BH-01'
  },
  {
    id: 19,
    block: 'RAIRANGPUR',
    ulb: 'RAIRANGPUR MUNICIPALITY',
    mrf: 'MRF 2 (BAIDAPOSI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'TUESDAY (EVERY TUESDAY IN A MONTH)',
    gpName: 'SANPAKHANA, BADMOUDA',
    wasteGeneratedKg: 359.5,
    gpNodalPerson: 'Jharana Naik, Sasmita Kisku',
    gpNodalContact: '9348704583, 8917271296',
    ulbNodalPerson: 'SWADHIN',
    ulbNodalContact: '9778588533',
    routeId: 'KMAYRAISB-2',
    routeName: 'SB-02'
  },
  {
    id: 20,
    block: 'RAIRANGPUR',
    ulb: 'RAIRANGPUR MUNICIPALITY',
    mrf: 'MRF 2 (BAIDAPOSI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'WEDNESDAY (EVERY WEDNESDAY IN A MONTH)',
    gpName: 'KULEISILA',
    wasteGeneratedKg: 126.8,
    gpNodalPerson: 'Pradeep Kumar Behera',
    gpNodalContact: '9437615050',
    ulbNodalPerson: 'SWADHIN',
    ulbNodalContact: '9778588533',
    routeId: 'KMAYRAIK-3',
    routeName: 'K-03'
  },
  {
    id: 21,
    block: 'RAIRANGPUR',
    ulb: 'RAIRANGPUR MUNICIPALITY',
    mrf: 'MRF 2 (BAIDAPOSI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'WEDNESDAY (EVERY WEDNESDAY IN A MONTH)',
    gpName: 'SUDARSANPUR',
    wasteGeneratedKg: 156.6,
    gpNodalPerson: 'Mohan Patra',
    gpNodalContact: '9348010793',
    ulbNodalPerson: 'SWADHIN',
    ulbNodalContact: '9778588533',
    routeId: 'KMAYRAIS-4',
    routeName: 'S-04'
  },
  {
    id: 22,
    block: 'RAIRANGPUR',
    ulb: 'RAIRANGPUR MUNICIPALITY',
    mrf: 'MRF 2 (BAIDAPOSI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'THRUSDAY (EVERY THRUSDAY IN A MONTH)',
    gpName: 'GUHALDANGRI, HATIA',
    wasteGeneratedKg: 290.4,
    gpNodalPerson: 'Mohan Patra, Budai Majhi',
    gpNodalContact: '9348010793, 8917222481',
    ulbNodalPerson: 'SWADHIN',
    ulbNodalContact: '9778588533',
    routeId: 'KMAYRAIGH-5',
    routeName: 'GH-05'
  },
  {
    id: 23,
    block: 'RAIRANGPUR',
    ulb: 'RAIRANGPUR MUNICIPALITY',
    mrf: 'MRF 2 (BAIDAPOSI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'FRIDAY (EVERY FRIDAY IN A MONTH)',
    gpName: 'PURUNAPANI',
    wasteGeneratedKg: 241.0,
    gpNodalPerson: 'Hemanta Kumar Patra',
    gpNodalContact: '8847836161',
    ulbNodalPerson: 'SWADHIN',
    ulbNodalContact: '9778588533',
    routeId: 'KMAYRAIP-6',
    routeName: 'P-06'
  },

  // KARANJIA Block
  {
    id: 24,
    block: 'KARANJIA',
    ulb: 'KARANJIA NAC',
    mrf: 'MRF1 (NUASAHI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'MONDAY (EVERY MONDAY IN A MONTH)',
    gpName: 'BADADEULI, CHITRAPOSI, GHOSADA',
    wasteGeneratedKg: 560.5,
    gpNodalPerson: 'Nibedita Sethy, Swadhin Kumar Mahanty',
    gpNodalContact: '9337424183, 9658466655',
    ulbNodalPerson: 'SANITATION EXPERT',
    ulbNodalContact: '-',
    routeId: 'KMAYKARA-1',
    routeName: 'BCG-01'
  },
  {
    id: 25,
    block: 'KARANJIA',
    ulb: 'KARANJIA NAC',
    mrf: 'MRF1 (NUASAHI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'TUESDAY (EVERY TUESDAY IN A MONTH)',
    gpName: 'KERKERA, SARANGAGADA, DORI',
    wasteGeneratedKg: 445.3,
    gpNodalPerson: 'Manoranjan Sethy, Kajal Prusty, Preetiranjan Mohanta',
    gpNodalContact: '9777013411, 8984044908, 7008865037',
    ulbNodalPerson: 'SANITATION EXPERT',
    ulbNodalContact: '-',
    routeId: 'KMAYKARA-2',
    routeName: 'KSD-02'
  },
  {
    id: 26,
    block: 'KARANJIA',
    ulb: 'KARANJIA NAC',
    mrf: 'MRF1 (NUASAHI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'WEDNESDAY (EVERY WEDNESDAY IN A MONTH)',
    gpName: 'BALA, TATO',
    wasteGeneratedKg: 309.1,
    gpNodalPerson: 'Manoranjan Sethy, Malay Ranjan Mohanta',
    gpNodalContact: '9777013411, 8260105699',
    ulbNodalPerson: 'SANITATION EXPERT',
    ulbNodalContact: '-',
    routeId: 'KMAYKARA-3',
    routeName: 'BT-03'
  },
  {
    id: 27,
    block: 'KARANJIA',
    ulb: 'KARANJIA NAC',
    mrf: 'MRF1 (NUASAHI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'THRUSDAY (EVERY THRUSDAY IN A MONTH)',
    gpName: 'BADAGAON, BATPALASA, MIRIGINENDI',
    wasteGeneratedKg: 479.5,
    gpNodalPerson: 'Malay Ranjan Mohanta, Smita Soren, Parshuram Nayak',
    gpNodalContact: '8260105699, 6371555871, 6372824641',
    ulbNodalPerson: 'SANITATION EXPERT',
    ulbNodalContact: '-',
    routeId: 'KMAYKARA-4',
    routeName: 'BBM-04'
  },
  {
    id: 28,
    block: 'KARANJIA',
    ulb: 'KARANJIA NAC',
    mrf: 'MRF1 (NUASAHI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'FRIDAY (EVERY FRIDAY IN A MONTH)',
    gpName: 'RASAMTALA, DUDHIANI',
    wasteGeneratedKg: 261.0,
    gpNodalPerson: 'Kajal Prusty, Soraj Kumar Barik',
    gpNodalContact: '8984044908, 7008089506',
    ulbNodalPerson: 'SANITATION EXPERT',
    ulbNodalContact: '-',
    routeId: 'KMAYKARA-5',
    routeName: 'RD-05'
  },
  {
    id: 29,
    block: 'KARANJIA',
    ulb: 'KARANJIA NAC',
    mrf: 'MRF1 (NUASAHI)',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Verified Personnel',
    driverContact: '-',
    collectionSchedule: 'SATURDAY (EVERY SATURDAY IN A MONTH)',
    gpName: 'KOLIPOSI, PATBIL',
    wasteGeneratedKg: 438.8,
    gpNodalPerson: 'Soraj Kumar Barik, Parshuram Nayak',
    gpNodalContact: '7008089506, 6372824641',
    ulbNodalPerson: 'SANITATION EXPERT',
    ulbNodalContact: '-',
    routeId: 'KMAYKARA-6',
    routeName: 'KP-06'
  }
];
