export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // Block BALIANTA
  { id: 1, block: 'BALIANTA', ulb: 'BMC', mrf: 'NAHARAKANTA', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'BALIANTA', wasteGeneratedKg: 9724.06, gpNodalPerson: '-', gpNodalContact: '-', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 2, block: 'BALIANTA', ulb: 'BMC', mrf: 'NAHARAKANTA', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'BENTAPUR', wasteGeneratedKg: 4157.43, gpNodalPerson: 'KAMALAKANTA DAS', gpNodalContact: '8908490085', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 3, block: 'BALIANTA', ulb: 'BMC', mrf: 'NAHARAKANTA', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'BHINGARPUR', wasteGeneratedKg: 10624.54, gpNodalPerson: 'AJAYA SUNDARAY', gpNodalContact: '8327748150', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 4, block: 'BALIANTA', ulb: 'BMC', mrf: 'NAHARAKANTA', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'JAGANNATHPUR', wasteGeneratedKg: 8671.54, gpNodalPerson: 'KAILASH ROUT', gpNodalContact: '9337674698', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 5, block: 'BALIANTA', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'BAINCHUA', wasteGeneratedKg: 7005.06, gpNodalPerson: 'PRIYANKA KULU', gpNodalContact: '9853503324', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 6, block: 'BALIANTA', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'PRATAPSASAN', wasteGeneratedKg: 11244.35, gpNodalPerson: 'JITISH ROUTRAY', gpNodalContact: '97778374698', ulbNodalPerson: 'Abinash Dash', ulbNodalContact: '9938782453' },
  { id: 7, block: 'BALIANTA', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'PURANPRADHAN', wasteGeneratedKg: 10378.95, gpNodalPerson: '-', gpNodalContact: '-', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 8, block: 'BALIANTA', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'SARAKANA', wasteGeneratedKg: 8531.21, gpNodalPerson: 'BASANTA SAHOO', gpNodalContact: '9937004525', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 9, block: 'BALIANTA', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'SATYABHAMAPUR', wasteGeneratedKg: 4315.30, gpNodalPerson: 'SABITA MUNI', gpNodalContact: '8249540383', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 10, block: 'BALIANTA', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'UMADEIBERHAMPUR', wasteGeneratedKg: 4052.17, gpNodalPerson: 'AJIT SATAPATHY', gpNodalContact: '8658220128', ulbNodalPerson: '-', ulbNodalContact: '-' },

  // Block BALIPATNA
  { id: 11, block: 'BALIPATNA', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'BHAPUR', wasteGeneratedKg: 6408.64, gpNodalPerson: 'ABHINAS DAS', gpNodalContact: '8327783647', ulbNodalPerson: '-', ulbNodalContact: '-' },

  // Block BANPUR
  { id: 12, block: 'BANPUR', ulb: 'BANPUR', mrf: 'BANPUR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'GAMBHARIMUNDA', wasteGeneratedKg: 8788.49, gpNodalPerson: 'BISWAJIT NAYAK', gpNodalContact: '8457953260', ulbNodalPerson: 'MANOJ KUMAR NADA', ulbNodalContact: '9861798616' },
  { id: 13, block: 'BANPUR', ulb: 'BALUGAON', mrf: 'BALUGAON', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'NACHUNI', wasteGeneratedKg: 9957.95, gpNodalPerson: 'BIKRAM SABAR', gpNodalContact: '7653922474', ulbNodalPerson: 'SUSHREE RANJAN BEHERA', ulbNodalContact: '81449733400' },

  // Block BEGUNIA
  { id: 14, block: 'BEGUNIA', ulb: 'KHORDHA MUNICIPALITY', mrf: 'KHORDHA MUNICIPALITY', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'SARUA', wasteGeneratedKg: 5554.93, gpNodalPerson: 'PRIYATAMA NAYAK', gpNodalContact: '9938141766', ulbNodalPerson: 'DEBASISH BARAL', ulbNodalContact: '8763434865' },
  { id: 15, block: 'BEGUNIA', ulb: 'KHORDHA MUNICIPALITY', mrf: 'KHORDHA MUNICIPALITY', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'BAGHAMARI', wasteGeneratedKg: 8209.60, gpNodalPerson: 'DUKHABANDHU TUDU', gpNodalContact: '7978136991', ulbNodalPerson: 'DEBASISH BARAL', ulbNodalContact: '8763434866' },

  // Block Bhubaneswar
  { id: 16, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'BASUAGHAI', wasteGeneratedKg: 6490.50, gpNodalPerson: 'GAOUTAM SAHOO', gpNodalContact: '8249789182', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 17, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'SISUPALGARH', wasteGeneratedKg: 5847.30, gpNodalPerson: 'GAOUTAM SAHOO', gpNodalContact: '8249789183', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 18, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'DHAULI', wasteGeneratedKg: 5443.83, gpNodalPerson: 'PRIYABRATA SAMANTARAY', gpNodalContact: '8249284882', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 19, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'ITIPUR', wasteGeneratedKg: 5812.21, gpNodalPerson: 'SUSANTA SEHTI', gpNodalContact: '7894391628', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 20, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'LINGIPUR', wasteGeneratedKg: 7151.24, gpNodalPerson: 'PRIYABRATA SAMANTARAY', gpNodalContact: '8249284882', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 21, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BASUAGHAI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'TIKARAPADA', wasteGeneratedKg: 4642.75, gpNodalPerson: 'RAJANANDINI MANGAL', gpNodalContact: '7978684754', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 22, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'PANDRA', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'BARIMUNDA', wasteGeneratedKg: 6215.67, gpNodalPerson: 'JOGENDRA BEHERA', gpNodalContact: '9348815423', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 23, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'PANDRA', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'KALYANPUR', wasteGeneratedKg: 9402.45, gpNodalPerson: 'SADASIBA RATH', gpNodalContact: '8249034060', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 24, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'PANDRA', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'DADHA', wasteGeneratedKg: 9075.00, gpNodalPerson: 'JAGANATH GHADEI', gpNodalContact: '9668983348', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 25, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'NILADRIBIHAR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'INJANA', wasteGeneratedKg: 3561.00, gpNodalPerson: 'SADASIBA RATH', gpNodalContact: '8249034060', ulbNodalPerson: 'Rajesh Dutta', ulbNodalContact: '8296689126' },
  { id: 26, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'NILADRIBIHAR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'RAGHUNATHPUR', wasteGeneratedKg: 8630.61, gpNodalPerson: 'PRIYANKA KANUNGO', gpNodalContact: '8249769664', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 27, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BHARATPUR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'ANDHARUA', wasteGeneratedKg: 8665.69, gpNodalPerson: 'NARAYAN JENA', gpNodalContact: '9937861159', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 28, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BHARATPUR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'MALIPADA', wasteGeneratedKg: 7911.39, gpNodalPerson: 'CHINMAYA CHIRANJIB', gpNodalContact: '7205161750', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 29, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BHARATPUR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'CHANDAKA', wasteGeneratedKg: 10308.78, gpNodalPerson: 'NANDINI MISHRA', gpNodalContact: '8018440602', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 30, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BHARATPUR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'KANTABADA', wasteGeneratedKg: 6081.19, gpNodalPerson: 'DIPTIPRIYA NAYAK', gpNodalContact: '7894358680', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 31, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BHARATPUR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'DARUTHENGA', wasteGeneratedKg: 8905.43, gpNodalPerson: 'CHINMAYA CHIRANJIB', gpNodalContact: '7205161750', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 32, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BHAGABANPUR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'RANSINGHPUR', wasteGeneratedKg: 8507.82, gpNodalPerson: 'MAMATA NAYAK', gpNodalContact: '7735105713', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 33, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BHAGABANPUR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'TAMANDO', wasteGeneratedKg: 6508.04, gpNodalPerson: 'ANITA MAHANTY', gpNodalContact: '9040175947', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 34, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BHAGABANPUR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'NANPUT', wasteGeneratedKg: 3338.80, gpNodalPerson: 'GAYATRI BEHERA', gpNodalContact: '8114714734', ulbNodalPerson: '-', ulbNodalContact: '-' },
  { id: 35, block: 'Bhubaneswar', ulb: 'BMC', mrf: 'BHAGABANPUR', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'MENDHASAL', wasteGeneratedKg: 7829.53, gpNodalPerson: 'DIPTIPRIYA NAYAK', gpNodalContact: '7894358680', ulbNodalPerson: '-', ulbNodalContact: '-' },

  // Block CHILIKA
  { id: 36, block: 'CHILIKA', ulb: 'BALUGAON', mrf: 'BALUGAON', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'DUNGAMAL', wasteGeneratedKg: 5414.59, gpNodalPerson: 'SIDDHARTH SANKAR PRADHAN', gpNodalContact: '7077355754', ulbNodalPerson: 'SUSHREE RANJAN BEHERA', ulbNodalContact: '81449733400' },
  { id: 37, block: 'CHILIKA', ulb: 'BALUGAON', mrf: 'BALUGAON', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'BADAKUL', wasteGeneratedKg: 9273.81, gpNodalPerson: 'SUBASH SAMANTARAY', gpNodalContact: '7978649177', ulbNodalPerson: 'SUSHREE RANJAN BEHERA', ulbNodalContact: '81449733401' },

  // Block JATNI
  { id: 38, block: 'JATNI', ulb: 'JATNI MUNICIPALITY', mrf: 'JATNI MUNICIPALITY', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'JANLA', wasteGeneratedKg: 8396.72, gpNodalPerson: 'MANGARAJ ROUT', gpNodalContact: '7008082206', ulbNodalPerson: 'RAJESH KUMAR SAHOO', ulbNodalContact: '9692488763' },
  { id: 39, block: 'JATNI', ulb: 'JATNI MUNICIPALITY', mrf: 'JATNI MUNICIPALITY', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'BENAPANJARI', wasteGeneratedKg: 5753.74, gpNodalPerson: 'SWETA NAYAK', gpNodalContact: '8144285488', ulbNodalPerson: 'CHINMAYA KUMAR SAHOO', ulbNodalContact: '7008755925' },

  // Block KHORDHA
  { id: 40, block: 'KHORDHA', ulb: 'KHORDHA MUNICIPALITY', mrf: 'KHORDHA MUNICIPALITY', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'NALIPADAARJUNPUR', wasteGeneratedKg: 9899.47, gpNodalPerson: 'BIBHUPRASAD SUBUDHI', gpNodalContact: '9668728513', ulbNodalPerson: 'DEBASISH BARAL', ulbNodalContact: '8763434865' },
  { id: 41, block: 'KHORDHA', ulb: 'KHORDHA MUNICIPALITY', mrf: 'KHORDHA MUNICIPALITY', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'GADAHALADIA', wasteGeneratedKg: 10297.10, gpNodalPerson: 'MANORANJAN JENA', gpNodalContact: '8984122482', ulbNodalPerson: 'DEBASISH BARAL', ulbNodalContact: '8763434865' },

  // Block TANGI
  { id: 42, block: 'TANGI', ulb: 'TANGI', mrf: 'TANGI', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '400', driverName: '-', driverContact: '-', collectionSchedule: 'To be notified', gpName: 'BADAPARI', wasteGeneratedKg: 10501.75, gpNodalPerson: 'SUBRAT KUMAR BISWAL', gpNodalContact: '9178530674', ulbNodalPerson: '-', ulbNodalContact: '-' }
];
