export interface GpMappingData {
  id: number;
  block: string;
  gpName: string;
  taggedUlb: string;
  taggedMrf: string;
}

export const gpMappingData: GpMappingData[] = [
  // Baleswar Block - Balasore Municipality (Rows 1-37)
  { id: 1, block: 'Baleswar', gpName: 'ALUMEDA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 2, block: 'Baleswar', gpName: 'ANKO', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 3, block: 'Baleswar', gpName: 'BAHABALPUR', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF Purna Baleswar' },
  { id: 4, block: 'Baleswar', gpName: 'BAINCHA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF Purna Baleswar' },
  { id: 5, block: 'Baleswar', gpName: 'BARDHANPUR', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 4 (Sunhat)' },
  { id: 6, block: 'Baleswar', gpName: 'BUANL', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 7, block: 'Baleswar', gpName: 'CHANDIPUR', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF Purna Baleswar' },
  { id: 8, block: 'Baleswar', gpName: 'CHHANUA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF Purna Baleswar' },
  { id: 9, block: 'Baleswar', gpName: 'DUBALGADI', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF Purna Baleswar' },
  { id: 10, block: 'Baleswar', gpName: 'GENGUTI', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 4 (Sunhat)' },
  { id: 11, block: 'Baleswar', gpName: 'GOPINATHPUR', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF Purna Baleswar' },
  { id: 12, block: 'Baleswar', gpName: 'GUDU', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 4 (Sunhat)' },
  { id: 13, block: 'Baleswar', gpName: 'HALADIPADA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 14, block: 'Baleswar', gpName: 'HIDIGAN', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF Purna Baleswar' },
  { id: 15, block: 'Baleswar', gpName: 'JAYDEVKASABA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 4 (Sunhat)' },
  { id: 16, block: 'Baleswar', gpName: 'KASAFAL', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 17, block: 'Baleswar', gpName: 'KASIPADA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 18, block: 'Baleswar', gpName: 'KHANNAGAR', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 4 (Sunhat)' },
  { id: 19, block: 'Baleswar', gpName: 'KURADIHA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 20, block: 'Baleswar', gpName: 'NAGRAM', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 21, block: 'Baleswar', gpName: 'ODANGI', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 22, block: 'Baleswar', gpName: 'OLANDASARGAN', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 23, block: 'Baleswar', gpName: 'PADMAPUR', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 4 (Sunhat)' },
  { id: 24, block: 'Baleswar', gpName: 'PANCHUPADA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 25, block: 'Baleswar', gpName: 'PARIKHI', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF Purna Baleswar' },
  { id: 26, block: 'Baleswar', gpName: 'PATRAPADA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF Purna Baleswar' },
  { id: 27, block: 'Baleswar', gpName: 'RAISUAN', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 28, block: 'Baleswar', gpName: 'RANASAHI', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 4 (Sunhat)' },
  { id: 29, block: 'Baleswar', gpName: 'RASALPUR', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 4 (Sunhat)' },
  { id: 30, block: 'Baleswar', gpName: 'RASULPUR', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 31, block: 'Baleswar', gpName: 'RUPSA SAMIL HASANPUR', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 32, block: 'Baleswar', gpName: 'SARAGAN', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 4 (Sunhat)' },
  { id: 33, block: 'Baleswar', gpName: 'SARTHA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },
  { id: 34, block: 'Baleswar', gpName: 'SASANG', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 4 (Sunhat)' },
  { id: 35, block: 'Baleswar', gpName: 'SINDHIA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF Purna Baleswar' },
  { id: 36, block: 'Baleswar', gpName: 'SRIKONA', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF Purna Baleswar' },
  { id: 37, block: 'Baleswar', gpName: 'SRIRAMAPUR', taggedUlb: 'Balasore Municipality', taggedMrf: 'MRF 2 ( Sahadevkhunta, Chandmari padia)' },

  // Jaleswar Block (Rows 38-72)
  { id: 38, block: 'Jaleswar', gpName: 'ARUHA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 39, block: 'Jaleswar', gpName: 'BAIGANBADIA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 40, block: 'Jaleswar', gpName: 'BARADIHA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 41, block: 'Jaleswar', gpName: 'BARTANA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 42, block: 'Jaleswar', gpName: 'CHAMARGAN', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 43, block: 'Jaleswar', gpName: 'D.P. PUR', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 44, block: 'Jaleswar', gpName: 'GADASAHI BALIAPAL', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 45, block: 'Jaleswar', gpName: 'GOBARGHATA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 46, block: 'Jaleswar', gpName: 'GOPIMOHANPUR', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 47, block: 'Jaleswar', gpName: 'JHADPIPAL', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 48, block: 'Jaleswar', gpName: 'K.M. SAHI', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 49, block: 'Jaleswar', gpName: 'KALAMA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 50, block: 'Jaleswar', gpName: 'KALIKO', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 51, block: 'Jaleswar', gpName: 'KHALINA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 52, block: 'Jaleswar', gpName: 'KHUARD', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 53, block: 'Jaleswar', gpName: 'KHULUDA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 54, block: 'Jaleswar', gpName: 'KOTSAHI', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 55, block: 'Jaleswar', gpName: 'LAKSHMANNATH', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 56, block: 'Jaleswar', gpName: 'M.N. PATANA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 57, block: 'Jaleswar', gpName: 'MANKIDIA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 58, block: 'Jaleswar', gpName: 'NACHHIMPUR', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 59, block: 'Jaleswar', gpName: 'NAMPO', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 60, block: 'Jaleswar', gpName: 'NETUA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 61, block: 'Jaleswar', gpName: 'OLMARA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 62, block: 'Jaleswar', gpName: 'PAIKASIDA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 63, block: 'Jaleswar', gpName: 'PASCHIMBAD', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 64, block: 'Jaleswar', gpName: 'R.R.PUR', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 65, block: 'Jaleswar', gpName: 'RAIBANIA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 66, block: 'Jaleswar', gpName: 'RAJPUR', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 67, block: 'Jaleswar', gpName: 'SAMPATIA', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 68, block: 'Jaleswar', gpName: 'SARADARBANDH', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 69, block: 'Jaleswar', gpName: 'SHYAMNAGAR', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 70, block: 'Jaleswar', gpName: 'SIKHARPUR', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 71, block: 'Jaleswar', gpName: 'SRIRAMPUR', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },
  { id: 72, block: 'Jaleswar', gpName: 'SUGO', taggedUlb: 'Jaleswar Municipality', taggedMrf: 'Jaleswar-MRF' },

  // Soro Block (Rows 73-96)
  { id: 73, block: 'Soro', gpName: 'ANANTAPUR', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 74, block: 'Soro', gpName: 'ATTAPUR', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 75, block: 'Soro', gpName: 'BALANGA', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 76, block: 'Soro', gpName: 'DAHISADA', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 77, block: 'Soro', gpName: 'GOPINATHPUR', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 78, block: 'Soro', gpName: 'GUD', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 79, block: 'Soro', gpName: 'JADIDA', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 80, block: 'Soro', gpName: 'KEDARPUR', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 81, block: 'Soro', gpName: 'KESHARIPUR', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 82, block: 'Soro', gpName: 'MADHUSUIDANPUR', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 83, block: 'Soro', gpName: 'MAHUMUHAN', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 84, block: 'Soro', gpName: 'MANATRI', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 85, block: 'Soro', gpName: 'MANIPUR', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 86, block: 'Soro', gpName: 'MULISING', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 87, block: 'Soro', gpName: 'NADIGAN', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 88, block: 'Soro', gpName: 'NATAPADA', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 89, block: 'Soro', gpName: 'NISCHINTAPUR', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 90, block: 'Soro', gpName: 'PAKHARA', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 91, block: 'Soro', gpName: 'SABIRA', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 92, block: 'Soro', gpName: 'SAJANPUR', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 93, block: 'Soro', gpName: 'SARASAKHA', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 94, block: 'Soro', gpName: 'SINGAKHUNTA', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 95, block: 'Soro', gpName: 'TALANAGAR', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },
  { id: 96, block: 'Soro', gpName: 'TENTEI', taggedUlb: 'Soro Municipality', taggedMrf: 'Soro-MRF' },

  // Nilgiri Block (Rows 97-121)
  { id: 97, block: 'Nilgiri', gpName: 'AJODHYA', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 98, block: 'Nilgiri', gpName: 'ARBANDH', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 99, block: 'Nilgiri', gpName: 'BEGUNIA', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 100, block: 'Nilgiri', gpName: 'BERHAMPUR', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 101, block: 'Nilgiri', gpName: 'BHAUNRIABAD', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 102, block: 'Nilgiri', gpName: 'CHHATRAPUR', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 103, block: 'Nilgiri', gpName: 'DHARAMPUR', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 104, block: 'Nilgiri', gpName: 'DHOBASILA', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 105, block: 'Nilgiri', gpName: 'GARADIHI', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 106, block: 'Nilgiri', gpName: 'JADIDA', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 107, block: 'Nilgiri', gpName: 'JAMUDIHA', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 108, block: 'Nilgiri', gpName: 'K,C.PUR', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 109, block: 'Nilgiri', gpName: 'K.P. LAKHARAJ', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 110, block: 'Nilgiri', gpName: 'KANSA', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 111, block: 'Nilgiri', gpName: 'MACHHUA', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 112, block: 'Nilgiri', gpName: 'MAHISAPATA', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 113, block: 'Nilgiri', gpName: 'MATIALI', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 114, block: 'Nilgiri', gpName: 'NARANPUR', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 115, block: 'Nilgiri', gpName: 'NARASINGHPUR', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 116, block: 'Nilgiri', gpName: 'PITHAHATA', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 117, block: 'Nilgiri', gpName: 'RADHAKISHOREPUR', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 118, block: 'Nilgiri', gpName: 'SAJANAGARH', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 119, block: 'Nilgiri', gpName: 'SIADIMAL', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 120, block: 'Nilgiri', gpName: 'TELIPAL', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },
  { id: 121, block: 'Nilgiri', gpName: 'TENTULIA', taggedUlb: 'Nilagiri NAC', taggedMrf: 'Nilgiri-MRF' },

  // Remuna Block (Rows 122-153)
  { id: 122, block: 'Remuna', gpName: 'BADAPAL', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 123, block: 'Remuna', gpName: 'BALIA', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 124, block: 'Remuna', gpName: 'BARUNASING', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 125, block: 'Remuna', gpName: 'BHIMPURA', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 126, block: 'Remuna', gpName: 'BIRUAN', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 127, block: 'Remuna', gpName: 'CHASAKHAND', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 128, block: 'Remuna', gpName: 'DAHAPADA', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 129, block: 'Remuna', gpName: 'DURGADEVI', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 130, block: 'Remuna', gpName: 'GANDARDA', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 131, block: 'Remuna', gpName: 'GUDUDA', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 132, block: 'Remuna', gpName: 'HARIPUR', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 133, block: 'Remuna', gpName: 'INCHUDI', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 134, block: 'Remuna', gpName: 'KALYAPUR', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 135, block: 'Remuna', gpName: 'KARANJIA', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 136, block: 'Remuna', gpName: 'KHARID MUKHURA', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 137, block: 'Remuna', gpName: 'KULIGAN', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 138, block: 'Remuna', gpName: 'KURUDA', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 139, block: 'Remuna', gpName: 'MAHARAJPUR', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 140, block: 'Remuna', gpName: 'MANDARPUR', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 141, block: 'Remuna', gpName: 'MANGALPUR', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 142, block: 'Remuna', gpName: 'NARAHARIPUR', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 143, block: 'Remuna', gpName: 'NIZAMPUR', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 144, block: 'Remuna', gpName: 'NUAGAN', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 145, block: 'Remuna', gpName: 'NUAPADHI', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 146, block: 'Remuna', gpName: 'PATRIPAL', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 147, block: 'Remuna', gpName: 'SARASWATIPUR', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 148, block: 'Remuna', gpName: 'SERGARH', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 149, block: 'Remuna', gpName: 'SRIJANG', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 150, block: 'Remuna', gpName: 'SUTEI', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 151, block: 'Remuna', gpName: 'TALAPADA', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 152, block: 'Remuna', gpName: 'TENTULIDA', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
  { id: 153, block: 'Remuna', gpName: 'TUNDRA', taggedUlb: 'Remuna NAC', taggedMrf: 'Remuna-NAC-MRF' },
];
