export interface GpMappingData {
  id: number;
  block: string;
  gpName: string;
  taggedUlb: string;
  taggedMrf: string;
}

export const gpMappingData: GpMappingData[] = [
  // Block NAYAGARH
  { id: 1, block: 'NAYAGARH', gpName: 'Badapandusara', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 2, block: 'NAYAGARH', gpName: 'Balugaon', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 3, block: 'NAYAGARH', gpName: 'Baunsiapada', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 4, block: 'NAYAGARH', gpName: 'Bhatasahi', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 5, block: 'NAYAGARH', gpName: 'Biruda', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 6, block: 'NAYAGARH', gpName: 'Champatipur', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 7, block: 'NAYAGARH', gpName: 'Chandibasta', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 8, block: 'NAYAGARH', gpName: 'Gadadhara-prasad', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 9, block: 'NAYAGARH', gpName: 'Gambharidihi', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 10, block: 'NAYAGARH', gpName: 'Ghaduala', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 11, block: 'NAYAGARH', gpName: 'Ikiri', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 12, block: 'NAYAGARH', gpName: 'Itamati', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 13, block: 'NAYAGARH', gpName: 'Jemadeipurpatana', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 14, block: 'NAYAGARH', gpName: 'Kalikaprasad', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 15, block: 'NAYAGARH', gpName: 'Kendudhipi', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 16, block: 'NAYAGARH', gpName: 'Khuntubandha', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 17, block: 'NAYAGARH', gpName: 'Kridaspur', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 18, block: 'NAYAGARH', gpName: 'Lathipada', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 19, block: 'NAYAGARH', gpName: 'Laxmiprasad', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 20, block: 'NAYAGARH', gpName: 'Lenkudipada', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 21, block: 'NAYAGARH', gpName: 'Machhipada', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 22, block: 'NAYAGARH', gpName: 'Muthagadia', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 23, block: 'NAYAGARH', gpName: 'Nabaghanpur', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 24, block: 'NAYAGARH', gpName: 'Nadiali', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 25, block: 'NAYAGARH', gpName: 'Natugaon', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 26, block: 'NAYAGARH', gpName: 'Notara', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 27, block: 'NAYAGARH', gpName: 'Saradhapur', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 28, block: 'NAYAGARH', gpName: 'Sarankul (Janhipada)', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },
  { id: 29, block: 'NAYAGARH', gpName: 'Sinduria', taggedUlb: 'NAYAGARH Municipality', taggedMrf: 'NAYAGARH' },

  // Block Daspalla
  { id: 30, block: 'Daspalla', gpName: 'Banigochha', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 31, block: 'Daspalla', gpName: 'Bhogabadi', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 32, block: 'Daspalla', gpName: 'Chadeyapalli', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 33, block: 'Daspalla', gpName: 'Dihagaon', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 34, block: 'Daspalla', gpName: 'Duda', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 35, block: 'Daspalla', gpName: 'Gholahandi', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 36, block: 'Daspalla', gpName: 'Ghugudipada', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 37, block: 'Daspalla', gpName: 'Kalasakhamana', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 38, block: 'Daspalla', gpName: 'Khamarasahi', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 39, block: 'Daspalla', gpName: 'Kujamendhi', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 40, block: 'Daspalla', gpName: 'Kulurukumpa', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 41, block: 'Daspalla', gpName: 'Madhyakhanda', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 42, block: 'Daspalla', gpName: 'Nachhipur', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 43, block: 'Daspalla', gpName: 'Nuagaon', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 44, block: 'Daspalla', gpName: 'Pokharigochha', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 45, block: 'Daspalla', gpName: 'Sariganda', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 46, block: 'Daspalla', gpName: 'Similisahi', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 47, block: 'Daspalla', gpName: 'Takera', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 48, block: 'Daspalla', gpName: 'Tendabadi', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },
  { id: 49, block: 'Daspalla', gpName: 'Tumandi', taggedUlb: 'Daspalla NAC', taggedMrf: 'Daspalla' },

  // Block Ranpur
  { id: 50, block: 'Ranpur', gpName: 'Bajrakot', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 51, block: 'Ranpur', gpName: 'Balabhadrapur', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 52, block: 'Ranpur', gpName: 'Bandhamunda', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 53, block: 'Ranpur', gpName: 'Baunsagarh', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 54, block: 'Ranpur', gpName: 'Brajarajpur', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 55, block: 'Ranpur', gpName: 'Brundabanpur', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 56, block: 'Ranpur', gpName: 'Champagarh', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 57, block: 'Ranpur', gpName: 'Champapedi', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 58, block: 'Ranpur', gpName: 'Chandapur', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 59, block: 'Ranpur', gpName: 'Damasahi', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 60, block: 'Ranpur', gpName: 'Darpanarayanpur', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 61, block: 'Ranpur', gpName: 'Gopalpur', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 62, block: 'Ranpur', gpName: 'Gourangpur', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 63, block: 'Ranpur', gpName: 'Gadabanikilo', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 64, block: 'Ranpur', gpName: 'Hansara', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 65, block: 'Ranpur', gpName: 'Jhadapada', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 66, block: 'Ranpur', gpName: 'Kandapada', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 67, block: 'Ranpur', gpName: 'Kandhanayagarh', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 68, block: 'Ranpur', gpName: 'Kasanda', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 69, block: 'Ranpur', gpName: 'Kerendatangi', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 70, block: 'Ranpur', gpName: 'Khairapalli', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 71, block: 'Ranpur', gpName: 'Khatia', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 72, block: 'Ranpur', gpName: 'Kulasar', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 73, block: 'Ranpur', gpName: 'Lodhachua', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 74, block: 'Ranpur', gpName: 'Mahatpalla', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 75, block: 'Ranpur', gpName: 'Majhiakhanda', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 76, block: 'Ranpur', gpName: 'Mayurjhalia', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 77, block: 'Ranpur', gpName: 'Narasinghpur', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 78, block: 'Ranpur', gpName: 'Narendrapur', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 79, block: 'Ranpur', gpName: 'Patia', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 80, block: 'Ranpur', gpName: 'Pimpal', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 81, block: 'Ranpur', gpName: 'Raipada', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 82, block: 'Ranpur', gpName: 'Raj-sunakhala', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 83, block: 'Ranpur', gpName: 'Raj-jankia', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 84, block: 'Ranpur', gpName: 'Rankadeuli', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 85, block: 'Ranpur', gpName: 'Surkabadi', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },
  { id: 86, block: 'Ranpur', gpName: 'Talakani', taggedUlb: 'Ranpur NAC', taggedMrf: 'Ranpur' },

  // Block Khandapada
  { id: 87, block: 'Khandapada', gpName: 'KHALISAHI', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 88, block: 'Khandapada', gpName: 'MARDARAJPUR', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 89, block: 'Khandapada', gpName: 'BENAGADIA', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 90, block: 'Khandapada', gpName: 'KANTILO', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 91, block: 'Khandapada', gpName: 'BADABANAPUR', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 92, block: 'Khandapada', gpName: 'SIDHAMULA', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 93, block: 'Khandapada', gpName: 'GADIASAHI', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 94, block: 'Khandapada', gpName: 'SINGHAPADA', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 95, block: 'Khandapada', gpName: 'KIAJHAR', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 96, block: 'Khandapada', gpName: 'KUMBARAPADA', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 97, block: 'Khandapada', gpName: 'BALABHADRAPRASAD', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 98, block: 'Khandapada', gpName: 'KOSKA', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 99, block: 'Khandapada', gpName: 'R.DHOLAMARA', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 100, block: 'Khandapada', gpName: 'BODASA', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 101, block: 'Khandapada', gpName: 'BANAMALIPUR', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 102, block: 'Khandapada', gpName: 'RANICHHELI', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 103, block: 'Khandapada', gpName: 'GUNTHUNI', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 104, block: 'Khandapada', gpName: 'SALAJHARIA', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 105, block: 'Khandapada', gpName: 'SIKHARPUR', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 106, block: 'Khandapada', gpName: 'JOGIAPALLI', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 107, block: 'Khandapada', gpName: 'RANIPADA', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },
  { id: 108, block: 'Khandapada', gpName: 'J.N.PRASAD', taggedUlb: 'Khandapada NAC', taggedMrf: 'Khandapada' },

  // Block Odagaon
  { id: 109, block: 'Odagaon', gpName: 'Angisingi', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 110, block: 'Odagaon', gpName: 'Aarada', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 111, block: 'Odagaon', gpName: 'Badagorada', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 112, block: 'Odagaon', gpName: 'Banthapur', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 113, block: 'Odagaon', gpName: 'Barasahi', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 114, block: 'Odagaon', gpName: 'Bhadikila', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 115, block: 'Odagaon', gpName: 'Bhaliadihi', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 116, block: 'Odagaon', gpName: 'Dimisar', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 117, block: 'Odagaon', gpName: 'Giridipalli', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 118, block: 'Odagaon', gpName: 'Godipada', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 119, block: 'Odagaon', gpName: 'Godipalli', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 120, block: 'Odagaon', gpName: 'Golagaon', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 121, block: 'Odagaon', gpName: 'Gotisahi', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 122, block: 'Odagaon', gpName: 'Gaudaput', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 123, block: 'Odagaon', gpName: 'Haridabandha', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 124, block: 'Odagaon', gpName: 'Hariharpur', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 125, block: 'Odagaon', gpName: 'Kajalaipalli', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 126, block: 'Odagaon', gpName: 'Komanda', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 127, block: 'Odagaon', gpName: 'Korapitha', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 128, block: 'Odagaon', gpName: 'Kural', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 129, block: 'Odagaon', gpName: 'Magarbandha', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 130, block: 'Odagaon', gpName: 'Nandighore', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 131, block: 'Odagaon', gpName: 'P.Manapur', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 132, block: 'Odagaon', gpName: 'Panchamu', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 133, block: 'Odagaon', gpName: 'Panderipada', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 134, block: 'Odagaon', gpName: 'Pantikhari', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 135, block: 'Odagaon', gpName: 'Rabara', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 136, block: 'Odagaon', gpName: 'Rabigadia', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 137, block: 'Odagaon', gpName: 'Ranganipatana', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 138, block: 'Odagaon', gpName: 'Rohibanka', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 139, block: 'Odagaon', gpName: 'Sakeri', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 140, block: 'Odagaon', gpName: 'Saradhapur', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 141, block: 'Odagaon', gpName: 'Sarankul', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 142, block: 'Odagaon', gpName: 'Sikharpur', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 143, block: 'Odagaon', gpName: 'Solapata', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
  { id: 144, block: 'Odagaon', gpName: 'Sunamuhin', taggedUlb: 'Odagaon NAC', taggedMrf: 'Odagaon' },
];
