
export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // ATHAGAD Block (1-34)
  { id: 1, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'ANANTAPUR', wasteGeneratedKg: 30.7314, gpNodalPerson: 'Manoj Munda', gpNodalContact: '9078827471', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 2, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'BADABHUIN', wasteGeneratedKg: 35.91, gpNodalPerson: 'Santosh Kumar Choudhury', gpNodalContact: '9937561055', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 3, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'BENTAPADA', wasteGeneratedKg: 46.0026, gpNodalPerson: 'Siddhanta Shahid Samantaray', gpNodalContact: '9438223276', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 4, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'BHOGARA', wasteGeneratedKg: 17.1234, gpNodalPerson: 'Sitakanta Dash', gpNodalContact: '8249424266', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 5, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'CHHAGAON', wasteGeneratedKg: 27.216, gpNodalPerson: 'Santosh Kumar Choudhury', gpNodalContact: '9937561055', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 6, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'DALABHAGA', wasteGeneratedKg: 15.6492, gpNodalPerson: 'Sitakanta Dash', gpNodalContact: '8249424266', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 7, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'DHAIPUR', wasteGeneratedKg: 19.5426, gpNodalPerson: 'Bijayram Swain', gpNodalContact: '9668675898', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 8, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'DHURUSIA', wasteGeneratedKg: 54.4698, gpNodalPerson: 'Priyabrata Dehury', gpNodalContact: '9348660884', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 9, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'DORADA', wasteGeneratedKg: 39.2742, gpNodalPerson: 'Rajesh Kumar Sahoo', gpNodalContact: '9778651481', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 10, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'GHANTIKHAL', wasteGeneratedKg: 25.3638, gpNodalPerson: 'Suraksha Mohanty', gpNodalContact: '9178199221', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 11, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'GOBARA', wasteGeneratedKg: 46.5696, gpNodalPerson: 'Alok Ratha', gpNodalContact: '7978387650', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 12, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'GURUDIJHATIA', wasteGeneratedKg: 40.635, gpNodalPerson: 'Sangram Panda', gpNodalContact: '7327823677', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 13, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'ICHHapur', wasteGeneratedKg: 48.006, gpNodalPerson: 'Manjushree Barik', gpNodalContact: '9777336134', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 14, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Jenapada Desh', wasteGeneratedKg: 54.8856, gpNodalPerson: 'Subhashree Tapas Kumar Sahoo', gpNodalContact: '8895482920', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 15, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'JORANDA', wasteGeneratedKg: 28.0476, gpNodalPerson: 'Manjushree Barik', gpNodalContact: '9777336134', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 16, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KANDAREI', wasteGeneratedKg: 29.6352, gpNodalPerson: 'Sitakanta Dash', gpNodalContact: '8249424266', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 17, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KANDARPUR', wasteGeneratedKg: 19.089, gpNodalPerson: 'Dejina Priyadarsini', gpNodalContact: '7978052900', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 18, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KATIKIASAHI', wasteGeneratedKg: 15.8004, gpNodalPerson: 'Rajesh Kumar Sahoo', gpNodalContact: '9778651481', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 19, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KHUNTAKATA', wasteGeneratedKg: 66.2634, gpNodalPerson: 'Santosh Kumar Choudhury', gpNodalContact: '9937561055', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 20, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KHUNTUNI', wasteGeneratedKg: 46.116, gpNodalPerson: 'Dibyanu Ranjan Behera', gpNodalContact: '9861657533', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 21, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KULAILO', wasteGeneratedKg: 35.1162, gpNodalPerson: 'Rajesh Kumar Sahoo', gpNodalContact: '9778651481', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 22, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KUMARPUR', wasteGeneratedKg: 55.7928, gpNodalPerson: 'Jitendra Kumar Das', gpNodalContact: '9556541297', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 23, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KUSPANGI', wasteGeneratedKg: 18.522, gpNodalPerson: 'Aniketa Mishra', gpNodalContact: '9827523599', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 24, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'MAHAKALBASTA', wasteGeneratedKg: 39.2742, gpNodalPerson: 'Kiran Kumar Mallick', gpNodalContact: '9040698436', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 25, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'MANCHESWAR', wasteGeneratedKg: 47.7036, gpNodalPerson: 'Jitendra Kumar Das', gpNodalContact: '9556541297', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 26, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'MEGHA', wasteGeneratedKg: 35.91, gpNodalPerson: 'Alok Ratha', gpNodalContact: '7978387650', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 27, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'ORANDA', wasteGeneratedKg: 26.3466, gpNodalPerson: 'Jitendra Kumar Das', gpNodalContact: '9556541297', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 28, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Radhagobindapur', wasteGeneratedKg: 29.862, gpNodalPerson: 'Dejina Priyadarsini', gpNodalContact: '7978052900', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 29, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'RADHAKISHOREPUR', wasteGeneratedKg: 41.8068, gpNodalPerson: 'Manoj Kumar Pradhan', gpNodalContact: '9937431241', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 30, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'RADHAKRUSHNAPUR', wasteGeneratedKg: 8.0514, gpNodalPerson: 'Manoj Kumar Pradhan', gpNodalContact: '9937431241', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 31, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'RAJANAGAR', wasteGeneratedKg: 33.1506, gpNodalPerson: 'Uliyam Jonson Kumar Gamanga', gpNodalContact: '9078928773', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 32, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'SAMSARPUR', wasteGeneratedKg: 48.0816, gpNodalPerson: 'Pradeepta Kumar swain', gpNodalContact: '9583077146', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 33, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'SATHILO', wasteGeneratedKg: 46.2672, gpNodalPerson: 'Bijayram Swain', gpNodalContact: '9668675898', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },
  { id: 34, block: 'ATHAGAD', ulb: 'ATHAGARH NAC', mrf: 'CTC/ATH/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'TARDING', wasteGeneratedKg: 19.5048, gpNodalPerson: 'Rajesh Kumar Sahoo', gpNodalContact: '9778651481', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7978077247' },

  // Banki Block (35-54)
  { id: 35, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'kiapala', wasteGeneratedKg: 46.2672, gpNodalPerson: 'ASHOK KUMAR MISHRA', gpNodalContact: '9937378234', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 36, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Golaganda', wasteGeneratedKg: 33.8688, gpNodalPerson: 'ASHOK KUMAR MISHRA', gpNodalContact: '9937378234', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 37, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Kendupali', wasteGeneratedKg: 34.2846, gpNodalPerson: 'AKSHAYA KUMAR SAMAL', gpNodalContact: '9658309070', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 38, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Anuary', wasteGeneratedKg: 46.116, gpNodalPerson: 'AKSHAYA KUMAR SAMAL', gpNodalContact: '9658309070', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 39, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Balabhadrapur', wasteGeneratedKg: 27.6696, gpNodalPerson: 'DINABANDHU SWAIN', gpNodalContact: '9937330626', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 40, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Kalapathar', wasteGeneratedKg: 67.9644, gpNodalPerson: 'DINABANDHU SWAIN', gpNodalContact: '9937330626', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 41, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Ostia', wasteGeneratedKg: 22.6044, gpNodalPerson: 'SABITA DEHURY', gpNodalContact: '7008898096', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 42, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Baideswar', wasteGeneratedKg: 61.7274, gpNodalPerson: 'KALANDI BEHERA', gpNodalContact: '6370007001', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 43, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Jagannathpur', wasteGeneratedKg: 42.4494, gpNodalPerson: 'KALANDI BEHERA', gpNodalContact: '6370007001', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 44, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Kantapanhra', wasteGeneratedKg: 47.5524, gpNodalPerson: 'SARASWATI NAIK', gpNodalContact: '7008127462', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 45, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Ratagarh', wasteGeneratedKg: 19.9584, gpNodalPerson: 'SARASWATI NAIK', gpNodalContact: '7008127462', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 46, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Bandalo', wasteGeneratedKg: 33.264, gpNodalPerson: 'JYOTIRMAYEE BEHERA', gpNodalContact: '6370225270', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 47, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Brahmapura', wasteGeneratedKg: 68.3802, gpNodalPerson: 'BIRENDRA KUMAR SAHU', gpNodalContact: '6370201969', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 48, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Kalipoi', wasteGeneratedKg: 55.755, gpNodalPerson: 'BIRENDRA KUMAR SAHU', gpNodalContact: '6370201969', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 49, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Baunsput', wasteGeneratedKg: 48.7242, gpNodalPerson: 'MAUSAM KUMAR BISOYI', gpNodalContact: '9861745165', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 50, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Subarnapur', wasteGeneratedKg: 34.7382, gpNodalPerson: 'MAUSAM KUMAR BISOYI', gpNodalContact: '9861745165', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 51, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Baraput', wasteGeneratedKg: 72.5382, gpNodalPerson: 'MANORANJAN MALLICK', gpNodalContact: '8093916146', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 52, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Kadaliadi', wasteGeneratedKg: 21.2436, gpNodalPerson: 'SUTRITHA DALEI', gpNodalContact: '9938897923', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 53, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Puincha', wasteGeneratedKg: 58.023, gpNodalPerson: 'BIKANT NAIK', gpNodalContact: '6370225270', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 54, block: 'Banki', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Nuagaon', wasteGeneratedKg: 23.6628, gpNodalPerson: 'BIKANT NAIK', gpNodalContact: '6370225270', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },

  // Banki-Dampada Block (55-71)
  { id: 55, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Banara', wasteGeneratedKg: 36.477, gpNodalPerson: 'SRUTIDHAR BEHERA', gpNodalContact: '7008959413', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 56, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Bhagipur', wasteGeneratedKg: 35.3808, gpNodalPerson: 'SRUTIDHAR BEHERA', gpNodalContact: '7008959413', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 57, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Bilipada', wasteGeneratedKg: 35.3808, gpNodalPerson: 'PRAGYANMITA SAHOO', gpNodalContact: '9439950270', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 58, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Dampada', wasteGeneratedKg: 48.8376, gpNodalPerson: 'MINATI SOREN', gpNodalContact: '7978507871', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 59, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Dhansar', wasteGeneratedKg: 46.7208, gpNodalPerson: 'SUJATA PRADHAN', gpNodalContact: '7326967297', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 60, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Dulanapur', wasteGeneratedKg: 68.985, gpNodalPerson: 'SADANANDA BARAL', gpNodalContact: '6371501410', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 61, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Durgapur', wasteGeneratedKg: 25.7418, gpNodalPerson: 'LAXMIDHAR PAL', gpNodalContact: '8917227821', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 62, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Gobingapur', wasteGeneratedKg: 97.1082, gpNodalPerson: 'SADANANDA BARAL', gpNodalContact: '6371501410', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 63, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Gopalpur', wasteGeneratedKg: 39.8412, gpNodalPerson: 'MINATI SOREN', gpNodalContact: '7978507871', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 64, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Harirajpur', wasteGeneratedKg: 33.2262, gpNodalPerson: 'MINATI SOREN', gpNodalContact: '7978507871', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 65, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Kuspangi', wasteGeneratedKg: 71.253, gpNodalPerson: 'TRINATH PARIDA', gpNodalContact: '9178733096', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 66, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Naraganga', wasteGeneratedKg: 42.4116, gpNodalPerson: 'PRABHUPADA BHANJA', gpNodalContact: '9040439131', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 67, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Pathapur', wasteGeneratedKg: 60.5556, gpNodalPerson: 'SUSHREE SEPHALI SETHY', gpNodalContact: '7609838013', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 68, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Ragadi', wasteGeneratedKg: 32.319, gpNodalPerson: 'SADANANDA BARAL', gpNodalContact: '6371501410', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 69, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Similipur', wasteGeneratedKg: 47.4768, gpNodalPerson: 'PRAGYANMITA SAHOO', gpNodalContact: '9439950270', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 70, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Talabast', wasteGeneratedKg: 112.5684, gpNodalPerson: 'LAXMIDHAR PAL', gpNodalContact: '8917227821', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },
  { id: 71, block: 'Banki-Dampada', ulb: 'BANKI NAC', mrf: 'CTC/BAN/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Tulasipur', wasteGeneratedKg: 39.879, gpNodalPerson: 'SASWAT SINGH', gpNodalContact: '8327703233', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008672151' },

  // CUTTACKSADAR Block (72-94)
  { id: 72, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'AMANA', wasteGeneratedKg: 41.58, gpNodalPerson: 'HEMANTA DASH', gpNodalContact: '9861163104', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 73, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'ARILO', wasteGeneratedKg: 31.3362, gpNodalPerson: 'GOBINDA CHANDRA SAHOO', gpNodalContact: '9348526092', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 74, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'AYATPUR', wasteGeneratedKg: 54.8856, gpNodalPerson: 'SHIBA PRASAD DAS', gpNodalContact: '9778045166', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 75, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'BARADA', wasteGeneratedKg: 11.718, gpNodalPerson: 'DILLIP KUMAR MAHANTA', gpNodalContact: '9438833160', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 76, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'BENTAKAR', wasteGeneratedKg: 29.862, gpNodalPerson: 'AMIYA RANJAN BARIK', gpNodalContact: '8144447507', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 77, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'BODHAPUR', wasteGeneratedKg: 32.319, gpNodalPerson: 'SAGAR SAHANI', gpNodalContact: '7377356927', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 78, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Brahmapur', wasteGeneratedKg: 51.7482, gpNodalPerson: 'SUDHANSHU SHEKHAR MOHAPATRA', gpNodalContact: '7978955076', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 79, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'DADHIBAMANPUR', wasteGeneratedKg: 62.937, gpNodalPerson: 'DURGA PRASAD MOHAPATRA', gpNodalContact: '8637225130', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 80, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'DHARINA', wasteGeneratedKg: 47.5146, gpNodalPerson: 'NIBEDITTA PANDA', gpNodalContact: '8658999937', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 81, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'FAKIRAPADA', wasteGeneratedKg: 22.2264, gpNodalPerson: 'SARASWATI MAHALI', gpNodalContact: '8908112336', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 82, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'GATIROUTPATNA', wasteGeneratedKg: 36.288, gpNodalPerson: 'SUKADEV BEHERA', gpNodalContact: '8637216343', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 83, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'JASAPADA', wasteGeneratedKg: 31.9788, gpNodalPerson: 'AMIYA RANJAN BARIK', gpNodalContact: '8144447507', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 84, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'JHARKATA', wasteGeneratedKg: 32.6214, gpNodalPerson: 'AJAY SETHI', gpNodalContact: '9438082190', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 85, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KALAPADA', wasteGeneratedKg: 72.765, gpNodalPerson: 'DURGA PRASAD MOHAPATRA', gpNodalContact: '8637225130', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 86, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KANDARPUR', wasteGeneratedKg: 66.8304, gpNodalPerson: 'DILLIP KUMAR MAHANTA', gpNodalContact: '9438833160', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 87, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KHANDEITA', wasteGeneratedKg: 40.7106, gpNodalPerson: 'ARCHANA BEHERA', gpNodalContact: '9555999128', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 88, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KISHORENAGAR', wasteGeneratedKg: 63.9576, gpNodalPerson: 'DEBRAJ DASH', gpNodalContact: '8210266363', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 89, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KULASARICHUAN', wasteGeneratedKg: 80.6274, gpNodalPerson: 'DURGA PRASAD MOHAPATRA', gpNodalContact: '8637225130', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 90, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'NIMEISAPUR', wasteGeneratedKg: 44.1126, gpNodalPerson: 'SUKADEV BEHERA', gpNodalContact: '8637216343', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 91, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'PARAMAHANSA', wasteGeneratedKg: 74.088, gpNodalPerson: 'JAYANTA DAS', gpNodalContact: '9937678159', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 92, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'PRAHARAJPUR', wasteGeneratedKg: 56.0952, gpNodalPerson: 'DEEPIKA ROUT', gpNodalContact: '6370052057', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 93, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'SOMPUR', wasteGeneratedKg: 53.9028, gpNodalPerson: 'DEBASIS NAYAK', gpNodalContact: '8249540256', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },
  { id: 94, block: 'CUTTACKSADAR', ulb: 'CMC CUTTACK', mrf: 'CTC/CUT/MRF/001', vehicleType: 'TATA ACE', vehicleNo: '-', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'URALI', wasteGeneratedKg: 64.5246, gpNodalPerson: 'HEMANTA DASH', gpNodalContact: '9861163104', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '9658123120' },

  // TANGI CHOUDWAR Block (95-118)
  { id: 95, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05CB2167', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'AGRAHAT', wasteGeneratedKg: 56.9268, gpNodalPerson: 'DEEPSHIKHA DAS', gpNodalContact: '9861135992', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 96, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2549', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'BADASAMANTARAPUR', wasteGeneratedKg: 32.2434, gpNodalPerson: 'KEDARESWAR BEHERA', gpNodalContact: '6370069841', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 97, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2549', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'BANIPADA', wasteGeneratedKg: 63.0882, gpNodalPerson: 'LAXMIDHAR PATRI', gpNodalContact: '789421514', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 98, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2593', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'BHATIMUNDA', wasteGeneratedKg: 46.5318, gpNodalPerson: 'CH. SATYAM PRAHRAJ', gpNodalContact: '7008512687', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 99, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2549', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Bramhapur', wasteGeneratedKg: 27.1404, gpNodalPerson: 'RAHUL KUMAR ORAM', gpNodalContact: '9439599499', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 100, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05CB2167', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'GARUDAGAON', wasteGeneratedKg: 48.0438, gpNodalPerson: 'ARAKHITA SAHOO', gpNodalContact: '6372891338', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 101, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2593', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'GOVINDPUR', wasteGeneratedKg: 34.8894, gpNodalPerson: 'SUDAM CHARAN PATRA', gpNodalContact: '9437577426', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 102, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2593', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'HARIANTA', wasteGeneratedKg: 52.0506, gpNodalPerson: 'PARTH SARATHI DAS', gpNodalContact: '9937438100', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 103, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2549', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'INDRANIPATNA', wasteGeneratedKg: 15.8382, gpNodalPerson: 'OM PRAKASH SAHOO', gpNodalContact: '9937204848', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 104, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2593', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'JARIPADA', wasteGeneratedKg: 67.2084, gpNodalPerson: 'DEBENDRANATH DASH', gpNodalContact: '7978257697', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 105, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2549', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KAKHADI', wasteGeneratedKg: 44.3394, gpNodalPerson: 'ARATI MURMU', gpNodalContact: '9348042631', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 106, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2593', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Kanheipur', wasteGeneratedKg: 67.3596, gpNodalPerson: 'RAHUL KUMAR ORAM', gpNodalContact: '9439599499', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 107, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05CB2167', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KARANJI', wasteGeneratedKg: 52.9956, gpNodalPerson: 'SALKHAN HANSDA', gpNodalContact: '9937692600', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 108, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2549', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KAYALPADA', wasteGeneratedKg: 48.8376, gpNodalPerson: 'LAXMIDHAR PATRI', gpNodalContact: '7894921514', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 109, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2593', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'KOTASAHI', wasteGeneratedKg: 67.7754, gpNodalPerson: 'CH. SATYAM PRAHRAJ', gpNodalContact: '7008512687', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 110, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2593', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Magura Dhanmandal', wasteGeneratedKg: 55.566, gpNodalPerson: 'SUDAM CHARAN PATRA', gpNodalContact: '9437577426', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 111, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05CB2167', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'MAHISALANDA', wasteGeneratedKg: 26.5734, gpNodalPerson: 'KEDARESWAR BEHERA', gpNodalContact: '6370069841', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 112, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05CB2167', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'MANGARAJPUR', wasteGeneratedKg: 40.0302, gpNodalPerson: 'BIBHUTI KUDADA', gpNodalContact: '7894945923', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 113, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2593', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'NAKHARA', wasteGeneratedKg: 34.02, gpNodalPerson: 'PARTH SARATHI DAS', gpNodalContact: '9937438100', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 114, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2593', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'NAPANGA', wasteGeneratedKg: 57.4938, gpNodalPerson: 'DEBENDRANATH DASH', gpNodalContact: '7978257697', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 115, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05CB2167', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'SAFA', wasteGeneratedKg: 41.8068, gpNodalPerson: 'SALKHAN HANSDA', gpNodalContact: '9937692600', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 116, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2593', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'SALAGAON', wasteGeneratedKg: 82.2906, gpNodalPerson: 'LAXMIDHAR PATRI', gpNodalContact: '7894921514', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 117, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2549', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'SANKARPUR', wasteGeneratedKg: 31.8654, gpNodalPerson: 'BIBHUTI KUDADA', gpNodalContact: '7894945923', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' },
  { id: 118, block: 'TANGI CHOUDWAR', ulb: 'Choudwar Municipality', mrf: 'CTC/CHO/MRF/001', vehicleType: 'TATA ACE', vehicleNo: 'OD05BG2593', vehicleCapacity: '300-400', driverName: '-', driverContact: '-', collectionSchedule: '1st & 15th of each Month', gpName: 'Uchapada', wasteGeneratedKg: 61.6518, gpNodalPerson: 'CH. SATYAM PRAHRAJ', gpNodalContact: '7008512687', ulbNodalPerson: 'Sanitation Expert', ulbNodalContact: '7008953569' }
];
