
export interface GpMappingData {
  id: number;
  block: string;
  gpName: string;
  taggedUlb: string;
  taggedMrf: string;
}

export const gpMappingData: GpMappingData[] = [
  // ATHAGAD Block
  { id: 1, block: 'ATHAGAD', gpName: 'Anantapur', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 2, block: 'ATHAGAD', gpName: 'Badabhuin', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 3, block: 'ATHAGAD', gpName: 'Bentapada', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 4, block: 'ATHAGAD', gpName: 'Bhogara', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 5, block: 'ATHAGAD', gpName: 'Chhagaon', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 6, block: 'ATHAGAD', gpName: 'Dalabhaga', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 7, block: 'ATHAGAD', gpName: 'Dhaipur', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 8, block: 'ATHAGAD', gpName: 'Dhurusia', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 9, block: 'ATHAGAD', gpName: 'Dorada', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 10, block: 'ATHAGAD', gpName: 'Ghantikhal', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 11, block: 'ATHAGAD', gpName: 'Gobara', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 12, block: 'ATHAGAD', gpName: 'Gurudijhatia', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 13, block: 'ATHAGAD', gpName: 'Ichhapur', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 14, block: 'ATHAGAD', gpName: 'Jenapada Desh', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 15, block: 'ATHAGAD', gpName: 'Joranda', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 16, block: 'ATHAGAD', gpName: 'Kandarei', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 17, block: 'ATHAGAD', gpName: 'Kandarpur', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 18, block: 'ATHAGAD', gpName: 'Katikiasahi', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 19, block: 'ATHAGAD', gpName: 'Khuntakata', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 20, block: 'ATHAGAD', gpName: 'Khuntuni', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 21, block: 'ATHAGAD', gpName: 'Kulailo', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 22, block: 'ATHAGAD', gpName: 'Kumarpur', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 23, block: 'ATHAGAD', gpName: 'Kuspangi', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 24, block: 'ATHAGAD', gpName: 'Mahakalbasta', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 25, block: 'ATHAGAD', gpName: 'Mancheswar', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 26, block: 'ATHAGAD', gpName: 'Megha', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 27, block: 'ATHAGAD', gpName: 'Oranda', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 28, block: 'ATHAGAD', gpName: 'Radhagobindapur', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 29, block: 'ATHAGAD', gpName: 'Radhakishorepur', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 30, block: 'ATHAGAD', gpName: 'Radhakrushnapur', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 31, block: 'ATHAGAD', gpName: 'Rajanagar', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 32, block: 'ATHAGAD', gpName: 'Samsarpur', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 33, block: 'ATHAGAD', gpName: 'Sathilo', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },
  { id: 34, block: 'ATHAGAD', gpName: 'Tarding', taggedUlb: 'ATHAGARH NAC', taggedMrf: 'CTC/ATH/MRF/001' },

  // Banki Block
  { id: 35, block: 'Banki', gpName: 'kiapala', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 36, block: 'Banki', gpName: 'Golaganda', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 37, block: 'Banki', gpName: 'Kendupali', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 38, block: 'Banki', gpName: 'Anuary', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 39, block: 'Banki', gpName: 'Balabhadrapur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 40, block: 'Banki', gpName: 'Kalapathar', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 41, block: 'Banki', gpName: 'Ostia', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 42, block: 'Banki', gpName: 'Baideswar', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 43, block: 'Banki', gpName: 'Jagannathpur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 44, block: 'Banki', gpName: 'Kantapanhra', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 45, block: 'Banki', gpName: 'Ratagarh', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 46, block: 'Banki', gpName: 'Bandalo', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 47, block: 'Banki', gpName: 'Brahmapura', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 48, block: 'Banki', gpName: 'Kalipoi', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 49, block: 'Banki', gpName: 'Baunsput', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 50, block: 'Banki', gpName: 'Subarnapur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 51, block: 'Banki', gpName: 'Baraput', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 52, block: 'Banki', gpName: 'Kadaliadi', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 53, block: 'Banki', gpName: 'Puincha', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 54, block: 'Banki', gpName: 'Nuagaon', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },

  // Banki-Dampada Block
  { id: 55, block: 'Banki-Dampada', gpName: 'Banara', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 56, block: 'Banki-Dampada', gpName: 'Bhagipur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 57, block: 'Banki-Dampada', gpName: 'Bilipada', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 58, block: 'Banki-Dampada', gpName: 'Dhansa', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 59, block: 'Banki-Dampada', gpName: 'Dompara', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 60, block: 'Banki-Dampada', gpName: 'Dulanapur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 61, block: 'Banki-Dampada', gpName: 'Durgapur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 62, block: 'Banki-Dampada', gpName: 'Gopalpur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 63, block: 'Banki-Dampada', gpName: 'Govindpur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 64, block: 'Banki-Dampada', gpName: 'Harirajpur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 65, block: 'Banki-Dampada', gpName: 'Kuspangi', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 66, block: 'Banki-Dampada', gpName: 'Naraganga', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 67, block: 'Banki-Dampada', gpName: 'Pathapur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 68, block: 'Banki-Dampada', gpName: 'Ragadi', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 69, block: 'Banki-Dampada', gpName: 'Similipur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 70, block: 'Banki-Dampada', gpName: 'Talabasta', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },
  { id: 71, block: 'Banki-Dampada', gpName: 'Tulasipur', taggedUlb: 'BANKI NAC', taggedMrf: 'CTC/BAN/MRF/001' },

  // CUTTACKSADAR Block
  { id: 72, block: 'CUTTACKSADAR', gpName: 'AMANA', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 73, block: 'CUTTACKSADAR', gpName: 'ARILO', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 74, block: 'CUTTACKSADAR', gpName: 'AYATPUR', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 75, block: 'CUTTACKSADAR', gpName: 'BARADA', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 76, block: 'CUTTACKSADAR', gpName: 'BENTAKAR', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 77, block: 'CUTTACKSADAR', gpName: 'BODHAPUR', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 78, block: 'CUTTACKSADAR', gpName: 'Brahmapur', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 79, block: 'CUTTACKSADAR', gpName: 'DADHIBAMANPUR', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 80, block: 'CUTTACKSADAR', gpName: 'DHARINA', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 81, block: 'CUTTACKSADAR', gpName: 'FAKIRAPADA', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 82, block: 'CUTTACKSADAR', gpName: 'GATIROUTPATNA', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 83, block: 'CUTTACKSADAR', gpName: 'JASAPADA', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 84, block: 'CUTTACKSADAR', gpName: 'JHARKATA', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 85, block: 'CUTTACKSADAR', gpName: 'KALAPADA', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 86, block: 'CUTTACKSADAR', gpName: 'KANDARPUR', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 87, block: 'CUTTACKSADAR', gpName: 'KHANDEITA', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 88, block: 'CUTTACKSADAR', gpName: 'KISHORENAGAR', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 89, block: 'CUTTACKSADAR', gpName: 'KULASARICHUAN', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 90, block: 'CUTTACKSADAR', gpName: 'NIMEISAPUR', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 91, block: 'CUTTACKSADAR', gpName: 'PARAMAHANSA', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 92, block: 'CUTTACKSADAR', gpName: 'PRAHARAJPUR', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 93, block: 'CUTTACKSADAR', gpName: 'SOMPUR', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },
  { id: 94, block: 'CUTTACKSADAR', gpName: 'URALI', taggedUlb: 'CMC CUTTACK', taggedMrf: 'CTC/CUT/MRF/001' },

  // TANGI CHOUDWAR Block
  { id: 95, block: 'TANGI CHOUDWAR', gpName: 'AGRAHAT', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/003' },
  { id: 96, block: 'TANGI CHOUDWAR', gpName: 'BADASAMANTARAPUR', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/001' },
  { id: 97, block: 'TANGI CHOUDWAR', gpName: 'BANIPADA', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/001' },
  { id: 98, block: 'TANGI CHOUDWAR', gpName: 'BHATIMUNDA', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/002' },
  { id: 99, block: 'TANGI CHOUDWAR', gpName: 'Bramhapur', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/001' },
  { id: 100, block: 'TANGI CHOUDWAR', gpName: 'GARUDAGAON', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/003' },
  { id: 101, block: 'TANGI CHOUDWAR', gpName: 'GOVINDPUR', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/002' },
  { id: 102, block: 'TANGI CHOUDWAR', gpName: 'HARIANTA', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/002' },
  { id: 103, block: 'TANGI CHOUDWAR', gpName: 'INDRANIPATNA', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/001' },
  { id: 104, block: 'TANGI CHOUDWAR', gpName: 'JARIPADA', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/002' },
  { id: 105, block: 'TANGI CHOUDWAR', gpName: 'KAKHADI', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/001' },
  { id: 106, block: 'TANGI CHOUDWAR', gpName: 'Kanheipur', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/002' },
  { id: 107, block: 'TANGI CHOUDWAR', gpName: 'KARANJI', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/003' },
  { id: 108, block: 'TANGI CHOUDWAR', gpName: 'KAYALPADA', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/001' },
  { id: 109, block: 'TANGI CHOUDWAR', gpName: 'KOTASAHI', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/002' },
  { id: 110, block: 'TANGI CHOUDWAR', gpName: 'Magura Dhanmandal', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/002' },
  { id: 111, block: 'TANGI CHOUDWAR', gpName: 'MAHISALANDA', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/003' },
  { id: 112, block: 'TANGI CHOUDWAR', gpName: 'MANGARAJPUR', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/003' },
  { id: 113, block: 'TANGI CHOUDWAR', gpName: 'NAKHARA', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/002' },
  { id: 114, block: 'TANGI CHOUDWAR', gpName: 'NAPANGA', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/002' },
  { id: 115, block: 'TANGI CHOUDWAR', gpName: 'SAFA', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/003' },
  { id: 116, block: 'TANGI CHOUDWAR', gpName: 'SALAGAON', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/002' },
  { id: 117, block: 'TANGI CHOUDWAR', gpName: 'SANKARPUR', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/001' },
  { id: 118, block: 'TANGI CHOUDWAR', gpName: 'Uchapada', taggedUlb: 'Choudwar Municipality', taggedMrf: 'CTC/CHO/MRF/002' },
];
