export interface CollectionScheduleItem {
  id: number;
  block: string;
  ulb: string;
  mrf: string;
  vehicleType: string;
  vehicleNo: string;
  vehicleCapacity: string;
  driverName: string;
  driverContact: string;
  collectionSchedule: string;
  gpName: string;
  wasteGeneratedKg: number;
  gpNodalPerson: string;
  gpNodalContact: string;
  ulbNodalPerson: string;
  ulbNodalContact: string;
}

export const collectionScheduleData: CollectionScheduleItem[] = [
  // Block: BINIKA (ULB: Binika NAC)
  {
    id: 1,
    block: 'Binika',
    ulb: 'Binika NAC',
    mrf: 'Binika MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'MUKTA BHUE',
    driverContact: '8260494420',
    collectionSchedule: '1ST Monday',
    gpName: 'SINGHIJUBA, BHANDAR',
    wasteGeneratedKg: 143.5,
    gpNodalPerson: 'Nimain Charan Naik',
    gpNodalContact: '9178798090',
    ulbNodalPerson: 'Sagarika Patra',
    ulbNodalContact: '8249789191'
  },
  {
    id: 2,
    block: 'Binika',
    ulb: 'Binika NAC',
    mrf: 'Binika MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'SUSHMA SAHU',
    driverContact: '7684056101',
    collectionSchedule: '1ST TUESDAY',
    gpName: 'SILATI, MEGHALA',
    wasteGeneratedKg: 86.2,
    gpNodalPerson: 'Bidesi Karmi, Biram Kishor Sahu',
    gpNodalContact: '8249754977, 9437346557',
    ulbNodalPerson: 'Sagarika Patra',
    ulbNodalContact: '8249789191'
  },
  {
    id: 3,
    block: 'Binika',
    ulb: 'Binika NAC',
    mrf: 'Binika MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'NURABATI BARIK',
    driverContact: '7978778001',
    collectionSchedule: '1ST WEDNESDAY',
    gpName: 'CHARDA, SANKARA',
    wasteGeneratedKg: 88.9,
    gpNodalPerson: 'Sibram Mishra, Babita Bhoi',
    gpNodalContact: '7008388490, 7735853746',
    ulbNodalPerson: 'Sagarika Patra',
    ulbNodalContact: '8249789191'
  },
  {
    id: 4,
    block: 'Binika',
    ulb: 'Binika NAC',
    mrf: 'Binika MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'KISHORI MAHALA',
    driverContact: '8658077990',
    collectionSchedule: '1ST THURS DAY',
    gpName: 'BAUNSUNI, KAINTARA',
    wasteGeneratedKg: 100,
    gpNodalPerson: 'Saroj Dharua, Banbihari Mahakur',
    gpNodalContact: '8458039789, 8917418662',
    ulbNodalPerson: 'Sagarika Patra',
    ulbNodalContact: '8249789191'
  },
  {
    id: 5,
    block: 'Binika',
    ulb: 'Binika NAC',
    mrf: 'Binika MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'PUSPANJALI BAGH',
    driverContact: '9556565044',
    collectionSchedule: '1ST Friday',
    gpName: 'JULLUNDA, KUHIBAHAL, MAHADA',
    wasteGeneratedKg: 150,
    gpNodalPerson: 'Bidesi Karmi, Sachikanta Mahakur',
    gpNodalContact: '8249754977, 7008814308',
    ulbNodalPerson: 'Sagarika Patra',
    ulbNodalContact: '8249789191'
  },
  {
    id: 6,
    block: 'Binika',
    ulb: 'Binika NAC',
    mrf: 'Binika MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'PUNI CHHATRI',
    driverContact: '9078117028',
    collectionSchedule: '1STSaturday',
    gpName: 'SELEDI, MAHADEVPALI',
    wasteGeneratedKg: 120,
    gpNodalPerson: 'Siba Barik, Sibram Mishra',
    gpNodalContact: '6371179021, 7008388490',
    ulbNodalPerson: 'Sagarika Patra',
    ulbNodalContact: '8249789191'
  },
  {
    id: 7,
    block: 'Binika',
    ulb: 'Binika NAC',
    mrf: 'Binika MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'BASANTI BAGH',
    driverContact: '7077313583',
    collectionSchedule: '2ND Monday',
    gpName: 'BABUPALI, BANKIGHIRDI',
    wasteGeneratedKg: 110,
    gpNodalPerson: 'Duryodhan Meher, Sibram Mishra',
    gpNodalContact: '7749045679, 7008388490',
    ulbNodalPerson: 'Sagarika Patra',
    ulbNodalContact: '8249789191'
  },
  {
    id: 8,
    block: 'Binika',
    ulb: 'Binika NAC',
    mrf: 'Binika MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'MADHUSMITA PANDA',
    driverContact: '6372592055',
    collectionSchedule: '2ND TUESDAY',
    gpName: 'SINDURPUR',
    wasteGeneratedKg: 90,
    gpNodalPerson: 'Ramesh Meher',
    gpNodalContact: '9556804078',
    ulbNodalPerson: 'Sagarika Patra',
    ulbNodalContact: '8249789191'
  },

  // Block: SONEPUR (ULB: Sonepur M)
  {
    id: 9,
    block: 'Sonepur',
    ulb: 'Sonepur-M',
    mrf: 'SONEPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Rajani Kathar',
    driverContact: '9556581880',
    collectionSchedule: '1ST Monday',
    gpName: 'Kalapathar, Janmura',
    wasteGeneratedKg: 97.5,
    gpNodalPerson: 'Ritanjali Panigrahi',
    gpNodalContact: '8763395726',
    ulbNodalPerson: 'Ajay Kumar Swain',
    ulbNodalContact: '7978132931'
  },
  {
    id: 10,
    block: 'Sonepur',
    ulb: 'Sonepur-M',
    mrf: 'SONEPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Bindusara Sethi',
    driverContact: '9777285403',
    collectionSchedule: '1ST TUESDAY',
    gpName: 'Mayurudan, Haradakhol',
    wasteGeneratedKg: 86.2,
    gpNodalPerson: 'Kshyanaprabha Panda, Susil Kumar Mohapatra',
    gpNodalContact: '8658535124, 8917535561',
    ulbNodalPerson: 'Ajay Kumar Swain',
    ulbNodalContact: '7978132931'
  },
  {
    id: 11,
    block: 'Sonepur',
    ulb: 'Sonepur-M',
    mrf: 'SONEPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Kishori Mahananda',
    driverContact: '8018677393',
    collectionSchedule: '1ST WEDNESDAY',
    gpName: 'Mallikmunda, Bishimunda',
    wasteGeneratedKg: 34,
    gpNodalPerson: 'Dillip Kumar Pandia, Susanta Kamalia',
    gpNodalContact: '9583742552, 6372067930',
    ulbNodalPerson: 'Ajay Kumar Swain',
    ulbNodalContact: '7978132931'
  },
  {
    id: 12,
    block: 'Sonepur',
    ulb: 'Sonepur-M',
    mrf: 'SONEPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Puspanjali Matari',
    driverContact: '7855895504',
    collectionSchedule: '1ST THURS DAY',
    gpName: 'Kharjhura, Khari',
    wasteGeneratedKg: 49,
    gpNodalPerson: 'Nilima Bhoi, Seshadev Dharua',
    gpNodalContact: '7894543263, 9078605804',
    ulbNodalPerson: 'Ajay Kumar Swain',
    ulbNodalContact: '7978132931'
  },
  {
    id: 13,
    block: 'Sonepur',
    ulb: 'Sonepur-M',
    mrf: 'SONEPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Priyata Mahakur',
    driverContact: '9337544240',
    collectionSchedule: '1ST Friday',
    gpName: 'Baladi, Narayapur',
    wasteGeneratedKg: 60,
    gpNodalPerson: 'Seshadev Dharua, Sanjaya Panigrahi',
    gpNodalContact: '9078605804, 7978705578',
    ulbNodalPerson: 'Ajay Kumar Swain',
    ulbNodalContact: '7978132931'
  },
  {
    id: 14,
    block: 'Sonepur',
    ulb: 'Sonepur-M',
    mrf: 'SONEPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Rajani Kathar',
    driverContact: '9556581880',
    collectionSchedule: '1STSaturday',
    gpName: 'Khaliapali, Rengali',
    wasteGeneratedKg: 44,
    gpNodalPerson: 'Anjali Panigrahi, Padmanabha Panda',
    gpNodalContact: '8249203609, 9938771825',
    ulbNodalPerson: 'Ajay Kumar Swain',
    ulbNodalContact: '7978132931'
  },
  {
    id: 15,
    block: 'Sonepur',
    ulb: 'Sonepur-M',
    mrf: 'SONEPUR MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Mita Tandia',
    driverContact: '6371358886',
    collectionSchedule: '2ND Monday',
    gpName: 'Lachhipur, Chhakormal',
    wasteGeneratedKg: 70,
    gpNodalPerson: 'Saroj Dharua, Sanjaya Panigrahi',
    gpNodalContact: '9337756743, 7978705578',
    ulbNodalPerson: 'Ajay Kumar Swain',
    ulbNodalContact: '7978132931'
  },

  // Block: TARBHA (ULB: Tarbha NAC)
  {
    id: 16,
    block: 'Tarbha',
    ulb: 'TARBHA NAC',
    mrf: 'TARBHA MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Basudha Karan',
    driverContact: '6370871675',
    collectionSchedule: '1ST Monday',
    gpName: 'Jartarbha, Katapali',
    wasteGeneratedKg: 66.3,
    gpNodalPerson: 'Shankar Badhia, Jasobanta Dalbehera',
    gpNodalContact: '8260575359, 8249170044',
    ulbNodalPerson: 'Harihar Bhoi',
    ulbNodalContact: '9438459839'
  },
  {
    id: 17,
    block: 'Tarbha',
    ulb: 'TARBHA NAC',
    mrf: 'TARBHA MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Belmati Meher',
    driverContact: '6371889287',
    collectionSchedule: '1ST TUESDAY',
    gpName: 'Badbhairo, Maraduguchha',
    wasteGeneratedKg: 86.2,
    gpNodalPerson: 'Chumki Jhankar, Mayadhara Dash',
    gpNodalContact: '8260286981, 9938771975',
    ulbNodalPerson: 'Harihar Bhoi',
    ulbNodalContact: '9438459839'
  },
  {
    id: 18,
    block: 'Tarbha',
    ulb: 'TARBHA NAC',
    mrf: 'TARBHA MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Malliphula Barik',
    driverContact: '7978161132',
    collectionSchedule: '1ST WEDNESDAY',
    gpName: 'Sibtula, Jarajaring',
    wasteGeneratedKg: 88.9,
    gpNodalPerson: 'Biswamitra Singh, Sudhir Kuanr',
    gpNodalContact: '9938771975, 7008721797',
    ulbNodalPerson: 'Harihar Bhoi',
    ulbNodalContact: '9438459839'
  },
  {
    id: 19,
    block: 'Tarbha',
    ulb: 'TARBHA NAC',
    mrf: 'TARBHA MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Rukuni Kuanr',
    driverContact: '9124146191',
    collectionSchedule: '1ST THURS DAY',
    gpName: 'Pua, Deulpadar',
    wasteGeneratedKg: 100,
    gpNodalPerson: 'Sujan Deep, Himachal Thanapati',
    gpNodalContact: '7684058355, 9938382175',
    ulbNodalPerson: 'Harihar Bhoi',
    ulbNodalContact: '9438459839'
  },
  {
    id: 20,
    block: 'Tarbha',
    ulb: 'TARBHA NAC',
    mrf: 'TARBHA MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Duleswari Nanda',
    driverContact: '9337831655',
    collectionSchedule: '1ST Friday',
    gpName: 'Paikbahal, Menda, Ranisarda',
    wasteGeneratedKg: 150,
    gpNodalPerson: 'Himachal Thanapati, Sujan Deep',
    gpNodalContact: '9938382175, 7684058355',
    ulbNodalPerson: 'Harihar Bhoi',
    ulbNodalContact: '9438459839'
  },
  {
    id: 21,
    block: 'Tarbha',
    ulb: 'TARBHA NAC',
    mrf: 'TARBHA MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Jhili Bibhar',
    driverContact: '8018387361',
    collectionSchedule: '1STSaturday',
    gpName: 'Sargaj, Brahmani',
    wasteGeneratedKg: 120,
    gpNodalPerson: 'Sudesna Patra, Biseswar Dash',
    gpNodalContact: '8249872198, 9938729422',
    ulbNodalPerson: 'Harihar Bhoi',
    ulbNodalContact: '9438459839'
  },
  {
    id: 22,
    block: 'Tarbha',
    ulb: 'TARBHA NAC',
    mrf: 'TARBHA MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Ranjita Rana',
    driverContact: '9668779923',
    collectionSchedule: '2ND Monday',
    gpName: 'Singhari, Baghia',
    wasteGeneratedKg: 110,
    gpNodalPerson: 'Biseswar Dash, Mayadhara Dash',
    gpNodalContact: '9938729422, 9938771975',
    ulbNodalPerson: 'Harihar Bhoi',
    ulbNodalContact: '9438459839'
  },
  {
    id: 23,
    block: 'Tarbha',
    ulb: 'TARBHA NAC',
    mrf: 'TARBHA MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Abanti Suna',
    driverContact: '8926012551',
    collectionSchedule: '2nd TUESDAY',
    gpName: 'Dubula, Tulunda',
    wasteGeneratedKg: 90,
    gpNodalPerson: 'Sushil Pandey, Harekrushna Bhoi',
    gpNodalContact: '9777283348, 9348776957',
    ulbNodalPerson: 'Harihar Bhoi',
    ulbNodalContact: '9438459839'
  },
  {
    id: 24,
    block: 'Tarbha',
    ulb: 'TARBHA NAC',
    mrf: 'TARBHA MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Pinki Rana',
    driverContact: '8144510705',
    collectionSchedule: '2nd WEDNESDAY',
    gpName: 'Charvata, Balikhamar',
    wasteGeneratedKg: 90,
    gpNodalPerson: 'Ramesh Suna',
    gpNodalContact: '7978092835',
    ulbNodalPerson: 'Harihar Bhoi',
    ulbNodalContact: '9438459839'
  },
  {
    id: 25,
    block: 'Tarbha',
    ulb: 'TARBHA NAC',
    mrf: 'TARBHA MRF',
    vehicleType: 'TATA ACE',
    vehicleNo: '-',
    vehicleCapacity: '400 Kg',
    driverName: 'Kuntala Rana',
    driverContact: '9337215145',
    collectionSchedule: '2nd THURS DAY',
    gpName: 'Kamsara, Kumbharmunda',
    wasteGeneratedKg: 100,
    gpNodalPerson: 'Pradeep Panda, Biseswar Dash',
    gpNodalContact: '6370689840, 9938729422',
    ulbNodalPerson: 'Harihar Bhoi',
    ulbNodalContact: '9438459839'
  },
];
